### ISSUE TITLE
Updating plugins throws errors

### ISSUE THREAD

**Issue by yellowled** [s9y/Serendipity#120]
`Fatal error: Uncaught exception 'ErrorException' with message 'Assigning the return value of new by reference is deprecated' in /path/to//include/compat.inc.php:126`

[Full error messages](http://board.s9y.org/viewtopic.php?p=10439009#p10439009)

**Comment by garvinhicking** [comment]
I think this issue is either unclear to me or fixed; please elaborate what the problem is, if there is any reamining, so that we can address it properly. Until then I'll close it. :-)
