### ISSUE TITLE
Backend functionality for additional plugins

### ISSUE THREAD

**Issue by yellowled** [s9y/Serendipity#149]
All plugins in `additonal_plugins` which create their own backend section should

* **at least** be tested with the 2.0 backend
* adapted to the 2.0 backend (markup/styles)

**Comment by yellowled** [comment]
Kind of an intermediate “result” on this:

* **serendipity_event_adminnotes:** I think this should become a dashboard widget, so it doesn't make sense to work on it before that happens
* **serendipity_event_spamblock_bayes:** what it really needs is a UI pattern for the subnavigation that it creates. We don't have that in the backend yet. I think that's a good topic for the next devTalk.
* **serendipity_event_staticpage:** not sure if I should invest any time in prettying this up, depends on the status of the forked dev version by @ophian → devTalk
* **serendipity_plugin_twitter:** this is a complex one, and I'm not even sure if the plugin still works properly since I don't use it myself anymore. → devTalk?

As for the rest, the ones I already addressed work okay-ish in the 2.0 backend. pollbox has a bug, and I haven't looked at guestbook in a while because it's kind of huge. The ones I didn't address yet are kind of “meh” because they're rarely used, it seems, and we haven't had any complaints about plugin backend sections in 2.0 yet.

So for the time being, I'll put this issue on hold at least until the next devTalk and take care of other things.

**Comment by onli** [comment]
Non-blocking, but keep open? Or close this because stale?

**Comment by yellowled** [comment]
I would like to keep it open in order to not forget about it, especially not the details. But it is in no way a release blocker.

Should we add a label for non-blocking issues?

**Comment by onli** [comment]
Yes, please!

**Comment by yellowled** [comment]
Closed due to unreadability, replaced by #426
