### ISSUE TITLE
add theme summary and description info?

### ISSUE THREAD

**Issue by ophian** [s9y/Serendipity#229]
See here: https://github.com/s9y/Serendipity/blob/2.0/templates/2k11/admin/templates.inc.tpl#L43 ff

I would be really nice to have an additional summary and description info in the backends themes info box, eg. adding to the end:
``` smarty
                            ....
                            {if isset($cur_tpl.info.summary)}
                            <dt class="template_summary">Summary:</dt>
                            <dd>{$cur_tpl.info.summary}</dd>
                            {/if}
                            {if isset($cur_tpl.info.description)}
                            <dt class="template_description">Description:</dt>
                            <dd>{$cur_tpl.info.description}</dd>
                            {/if}
```
This would not need anything else by now, since it just reads the info.txt of a theme and the `{$cur_tpl.info}` array already includes this part, if a theme has it set. 
This is only done for the current chosen theme at the moment. To make this available in the backend theme list info boxes for all other themes, this would need some more enhancements.

What do you think?

**Comment by onli** [comment]
Is that something one of you still wants to work on?

**Comment by yellowled** [comment]
I still think it's not feasible and thus kind of pointless. (That's a “no”.)

**Comment by ophian** [comment]
These sort of unilateral and lonely "closing" decisions make me feel not at home! Don't you have any windows to clean up? Four people, not being able to talk and to make joint and friendly decisions make me angry.

**Comment by yellowled** [comment]
Just because an issue is closed does **not** mean this is never ever going to be discussed again. You could open a discussion about this in the forum right now. But there is no reason to keep a GitHub issue open that should have been a forum discussion in the first place an that has not had *any* interaction in **14 months** (prior to the recent issue cleanup).
