### ISSUE TITLE
Umlauts rewrite for image directories

### ISSUE THREAD

**Issue by ophian** [s9y/Serendipity#238]
This is a request to rewrite Umlauts for image directories using either 
* `serendipity_makeFilename()` or 
* `iconv("utf-8","ascii//TRANSLIT",$input);` (see http://php.net/manual/en/function.iconv.php#105507), or 
* Text::Unidecode (http://stackoverflow.com/a/11058319) or
* a simple user function (eg http://stackoverflow.com/a/6856938) or
* whatever else

to convert umlauts to ascii standards. Currently they are just cut off :-( which is an unexplained odd behaviour.

> Could you add it as an issue with milestone "future", then we can take care of it for 2.0.1.

I'll never understand why such knick-knacks have to wait for a future release, but here its is:

**Comment by garvinhicking** [comment]
Committed with 71e41b3
