### ISSUE TITLE
Entry editor: assigned tags

### ISSUE THREAD

**Issue by yellowled** [s9y/Serendipity#239]
Currently, when using modal overlays in the backend, ~~there is no way to see the~~ tags already assigned to an entry are not visible from the entry editor directly (since the original section for that is hidden). They are only visible in the overlay's input field, which is not ideal.

The entry editor should have a way to display these, probably similar to the way assigned categories are displayed.

**Comment by garvinhicking** [comment]
Devtalk discussed: We'll try to create a simple "Tags: XXX" output just like "Categories"

**Comment by garvinhicking** [comment]
(when it gets long, the height simply adapts and people need to suffer their own overassignment)

**Comment by yellowled** [comment]
See, this is what happens if you give me some time and some chocolate on a Saturday afternoon.

![screenshot 2015-01-17 17 44 08](https://cloud.githubusercontent.com/assets/326223/5789546/8a89bb86-9e70-11e4-864a-21282504cfb9.png)

Yes, we could “do more” here. I was thinking about styling the tags like actual tags, but it would be a lot of CSS overhead, and how would we style categories accordingly, and now it fit's the rest of the entry editor and … yeah. No.

Done?

**Comment by yellowled** [comment]
(And yes, it does look kind of odd in the screenshot because those are random category and tag names and an arbitrary number of both assigned. It will look worse if people use more cats/tags, but better if they use less.)

**Comment by yellowled** [comment]
> Done?

Not yet, I broke something.

**Comment by yellowled** [comment]
@garvinhicking Could you please run the addlang thingy and ping me once it's done so I can exchange the lang constants? Thx. :)

**Comment by garvinhicking** [comment]
@yellowled - I just checked the entry editor and saw a minor oddity with the height of the "schedule time" icon: 

https://www.dropbox.com/s/3zoobh0xh1o72lk/Screenshot%202015-01-19%2009.42.11.png?dl=0

can you easily fix that or should I open a new issue?

I really like the new display, however I believe we do need a visual seperator to unclutter taglists. What do you think of adding a small color highlight / border around the taxonomy items like:

´´´´
.taxonomy li {
    background-color: #E8E8E8;
    border-radius: 5px;
    padding: 0 0.5em 0 0.5em;
    margin: 0 1em 0.2em 0;
}
´´´´

?

**Comment by yellowled** [comment]
I (hope I) can easily fix the time icon, and I'll see that I can find something suitable to seprate the taxonomy lists.

**Comment by yellowled** [comment]
The “schedule time” icon is because of the Static Pages dev plugin. Won't fix in core (that's pointless).

@ophian, please revise the Static Pages dev backend CSS to use more specific selectors.

```
.icon-ok:before, .icon-error:before, .icon-attention:before, .icon-clock:before {font-size:131%;}
```
That (as well as some of the styles in the rest of the Static Pages dev backend CSS, I assume) will also affect other instances of said icons in the backend, which is not intended. Please make sure that these are only applied in the Static Pages part of the backend, if necessary, by using a parent class (`.sp_entries_pane .icon-clock:before` etc.).

**Comment by yellowled** [comment]
Visual seperation should be done. I adapted your proposed styles a little to match the overall UI patterns. Please close if this works.

**Comment by yellowled** [comment]
Seems like I “lost” @garvinhicking in our skype call about this. The current state is how I'd want to leave it. Please close if you think the same. :)
