### ISSUE TITLE
de-select (reset) multiselection fields

### ISSUE THREAD

**Issue by ophian** [s9y/Serendipity#242]
Talking about $eventData['properties']['ep_disable_markup_* 

I just discovered being unable to reset an already selected disabled markup plugin via the entryforms entryproperties markup hook. (It is not a javascript issue!)

1. Edit entry with CKEDITOR and disable nl2br via multiselect
2. Save your entry
3. Via sidebar get entries request call this entry again and de-select the multiselect selection ([CTRL]+marked option)
3. Save your entry
4. Via sidebar get entries request, call this entry again and see the multiselect has not changed.

I already have a full working proposel adding a NONE constant reset option field for this, if it has selected options, but maybe this will happen to us on more places too....?!

Anybody for this?

**Comment by yellowled** [comment]
Has been left open for about a month now, should we close it?
