### ISSUE TITLE
automatically disable nl2br parsing when WYSIWYG is active

### ISSUE THREAD

**Issue by ophian** [s9y/Serendipity#243]
First, let me ask two questions:

1. Are you going d'accord with me, that you **have to** disable textformatting when using WYSIWYG, to not run into frontend stairviews?
2. Are you going d'accord with me, that some users do not know all the options we have, to switch this off singulary by entry, as a preset, or in general?

This has been bothering me for some years. Now we have this splendit new editor, it would be nice to make this more dummy proof...

So I looked into the nl2br plugin and did this ~L245:
```php
                    foreach ($this->markup_elements as $temp) {
+                        if ($serendipity['wysiwyg'] && isset($eventData[$temp['element']]) && !$eventData['properties']['ep_no_nl2br']) {
+                            $eventData['properties']['ep_no_nl2br'] = true; // automatically reset element nl2br parsing. when WYSIWYG is active
+                        }
```
which works well for all content being edited by ckeditor. If you disable personal WYSIWYG option, all options regarding textformatting (by entries, nuggets, staticpages etc) are back to take effect.

Shall I ? ;-)

**Comment by garvinhicking** [comment]
@ophian - since the RC is out and we dealt with the double_encode thing in another thread, can this be closed here? If not, please reopen and we can discuss.
