### ISSUE TITLE
Category view needs hierarchy option

### ISSUE THREAD

**Issue by garvinhicking** [s9y/Serendipity#254]
I have hierarchical categories, and only a few:

https://www.dropbox.com/s/csrk0vjvgxoztn6/Screenshot%202014-12-30%2019.14.35.png?dl=0

This looks like this in the editor:

https://www.dropbox.com/s/8zoptktv3ak0875/Screenshot%202014-12-30%2019.14.14.png?dl=0 

and removes all hierarchy.

I would like to propose to add a new "toggle" Button that switches between the current view (optimized for many categories) and a view similar to the "Categories" sidebar plugin (probably with inline styles for padding, as I'm not sure if we can easily have nested ul/li elements there, but I'll look into this).

Ideally, this toggling should be saved within a cookie to show the last used option. We'd have to talk about which of the two views will be the default then. Also I'd leave it up for discussion if we need a new personal preference option for the default behavior (which I think we could live without, when the toggle remembers, we don't need the option).

**Comment by yellowled** [comment]
@garvinhicking Please do the `addlang.txt` run for me, I remember this producing errors on OS X for me.

Personally, I don't think this needs a config option. If you guys agree, this can be closed.

**Comment by ophian** [comment]
well done - ok fo me!

**Comment by ophian** [comment]
@yellowled do we need a default copy of serendipity_editor.js for this?

**Comment by yellowled** [comment]
I literally have no idea. Probably?

**Comment by yellowled** [comment]
Wait, that's the static copy of `serendipity_editor.js` for the “old” default admin theme, right? I'm pretty sure we do not need this in there since it doesn't even use MagnificPopup.

This should be done with 2944725b6925733846fa9f9de33c1a3fca731a84. If anyone still wants to add a config option for it, re-open or make a new issue for it. (I still don't think it's necessary.)

**Comment by ophian** [comment]
> Wait, that's the static copy of serendipity_editor.js for the “old” default admin theme, right? I'm pretty sure we do not need this in there since it doesn't even use MagnificPopup.

Yes, that is what I meant. All the better if we do not need to force a copy on every js.tpl change. I just wanted to make sure, since I am not clear in which specific circumstances this fallback even happens.

**Comment by yellowled** [comment]
>  I am not clear in which specific circumstances this fallback even happens

Me neither. :D
