### ISSUE TITLE
[openid] non-static method serendipity_common_openid::loginform()

### ISSUE THREAD

**Issue by bauigel** [s9y/Serendipity#259]
> Deprecated: Non-static method serendipity_common_openid::loginform() should not be called statically, assuming $this from incompatible context in /.../plugins/serendipity_event_openid/serendipity_event_openid.php on line 150
>
> Deprecated: Non-static method serendipity_common_openid::load_account_selectbox() should not be called statically, assuming $this from incompatible context in /.../plugins/serendipity_event_openid/common.inc.php on line 240

May be, it is a duplicate of https://github.com/s9y/Serendipity/issues/256?

**Comment by bauigel** [comment]
Here is another one...

> Deprecated: Non-static method serendipity_common_openid::authenticate_openid() should not be called statically, assuming $this from incompatible context in /.../plugins/serendipity_event_openid/serendipity_event_openid.php on line 205

**Comment by garvinhicking** [comment]
Fixed in git

**Comment by yellowled** [comment]
@garvinhicking Same thing for pollbox

```
Fatal error: Uncaught exception 'ErrorException' with message 'Notice: Non-static method serendipity_common_pollbox::fetchPoll() should not be called statically, assuming $this from incompatible context' in /var/www/virtual/user/domain.tld/plugins/serendipity_plugin_pollbox/serendipity_event_pollbox.php:260 Stack trace: #0 /var/www/virtual/user/domain.tld/plugins/serendipity_plugin_pollbox/serendipity_event_pollbox.php(260): errorToExceptionHandler(8192, 'Non-static meth...', '/var/www/virtua...', 260, Array) #1 /var/www/virtual/user/domain.tld/plugins/serendipity_plugin_pollbox/serendipity_event_pollbox.php(447): serendipity_event_pollbox->showBackend() #2 /var/www/virtual/user/domain.tld/include/plugin_api.inc.php(1138): serendipity_event_pollbox->event_hook('backend_sidebar...', Object(serendipity_property_bag), Array, NULL) #3 /var/www/virtual/user/domain.tld/serendipity_admin.php(218): serendipity_plugin_api::hook_event('backend_sidebar...', Array) #4 { in /var/www/virtual/user/domain.tld/plugins/serendipity_plugin_pollbox/serendipity_event_pollbox.php on line 260
```

**Comment by yellowled** [comment]
Fixed by https://github.com/s9y/additional_plugins/commit/c6625a64025bca147fef9cd6a5cff167a332ccff
