### ISSUE TITLE
Publish from dashboard doesn't make much sense?

### ISSUE THREAD

**Issue by yellowled** [s9y/Serendipity#262]
One could argue that the *Publish* button in the dashboard currently doesn't make much sense (see #260).

What it does: It publishes a draft article by setting it status from Draft to Publish. Nothing else.

One could expect it to also set the date/time to current (I would expect that) or to take you to the entry editor to revise the draft (which you can do by clicking on the title).

I would propose to change it to set the date/time to current, but since this is kind of a huge decision, I added the discuss label.

**Comment by yellowled** [comment]
(We can easily save that discussion for the dev talk if you guys prefer that.)

**Comment by ddeimeke** [comment]
Pretty good idea!

**Comment by garvinhicking** [comment]
For me this button should not change the actually set time when it was edited; if one wants to change something the entry should be edited...

**Comment by yellowled** [comment]
But why would you not change the date? To publish an article with a past date?

**Comment by bauigel** [comment]
> For me this button should not change the actually set time when it was edited; if one wants to change something the entry should be edited... 

Same for me.=

**Comment by yellowled** [comment]
I guess we could squeeze in 2 icon buttons instead of one text button – one for “Change state from draft to publish” (although I still don't see the purpose in that), one for “Set date to now and publish” …?

**Comment by bauigel** [comment]
> But why would you not change the date? To publish an article with a past date?
> 
Date could be in future too. ;-)=

**Comment by garvinhicking** [comment]
Exactly, usually I make drafts with a date in the future, and when I'm 
fine with it I wouldn't want to publish it now.

Two buttons would be too clunky. Maybe we'd need to check whether the 
saved entry timestamp is > NOW, if so, the date is not touched, if it's 
< NOW then the timestamp gets set to NOW.

On the other hand, some people might appreciate to one-button publish a 
future-draft entry instead of needing to edit it. It's a pickle, I guess.

**Comment by onli** [comment]
I think the first idea, to set the date to current, works best here. In the other cases you wouldn't probably be in the dashboard, multiple buttons there are too clunky for the available space (and the function not that important). It's something that is sound and can be learned. I'd call the button "Publish now" though.

**Comment by yellowled** [comment]
> I think the first idea, to set the date to current, works best here.

I think it's not so much that it works best, but it's what we had in mind when we implemented that button.

Another idea would be to have one *Publish* button which pulls up an overlay with a “how to proceed” dialogue which has the options

* Edit the entry
* Publish or schedule with the date set in the entry
* Publish with the current system date
* Delete

**Comment by bauigel** [comment]
>
> Another idea would be to have one *Publish* button which pulls up an
> overlay with a “how to proceed” dialogue which has the options
>
>    - Edit the entry
>    - Publish or schedule with the date set in the entry
>    - Publish with the current system date
>    - Delete
>
>
​Sounds good, but i don't know if we need "edit" and "delete" here because
the button is still called "publish". Otherwise we should rename it to
"Action..." or something else.

**Comment by yellowled** [comment]
I'd want to go with an icon button (*Edit* icon probably) in that case anyway. However, that would be an extra step in the process, which kind of goes against the idea of a *Quick publish* button. Might be way too many options for the John Doe user anyway.

As Garvin stated, it's a pickle. Hmmm.

**Comment by onli** [comment]
>  Another idea would be to have one *Publish* button which pulls up an overlay with a “how to proceed” dialogue which has the options

That sounds too close like the normal entry editor to me.

**Comment by yellowled** [comment]
We could turn this button into a “dropdown button”, i.e. a button which exposes a dropdown menu, which could include the two publishing options.

However, that would be a new UI pattern in our backend which we don't use anywhere else, and frankly, I'm not a huge fan of dropdown menus in general.

How about this: In #260, Dirk suggested to change the *Draft* badge to a date. I didn't see a point in that. However, with the use cases mentioned here, I could see a use for a date in drafts. We could:

* have a date for Scheduled and Draft in the dashboard
* add an icon to that date (clock and edit) to distinguish Scheduled and Draft
* make that date badge clickable to reset the date to current date/time
* add Publish buttons for Scheduled as well (sort of “forget about the scheduled date, publish now”)

**Comment by yellowled** [comment]
Before I think about this too much – is it actually *possible* to reset the date from the dashboard? In the entry editor, we do that using JS, but there's a save step involved to actually save the date. Does it even make sense to implement that functionality in the dashboard from a technical point of view?

**Comment by onli** [comment]
I got bit by modifying entries not being as I thought before (and that might be why I didn't implement the publish now functionality it in the alpha), but yes, it has to be possible. When clicking on the button we are calling php code on the server, and there we can set the date.

**Comment by garvinhicking** [comment]
We'd need to do that in an AJAX call / wrapper then, and also use form tokens...

Personally I think we should move this thing to a 2.0.1 milestone and address it after the 2.0 release. The possibility to f*ck up things because we do it too quickly at this point and introduce other issues is IMO higher than the benefit. We shouldn't stall because of things like that.

Adding a 2.0.1 branch at this point would complicate things a lot, so IMO we should stop at this point and carry on after the 2.0 release...?!

**Comment by yellowled** [comment]
I was gonna suggest to discuss that in the next dev talk, but I guess moving it to Future is fine as well.

(Mental note to self: We should also discuss future git workflows there.)

**Comment by onli** [comment]
You did test whether the publish button does not do this already, did you? Because the code in https://github.com/s9y/Serendipity/blob/5723673ab3cb039e2991856858c9ad120d63acf6/include/admin/overview.inc.php actually already sets the date to 'now' when that button is clicked. That code does not work?

**Comment by yellowled** [comment]
http://nbe.netzgestaltung.net/archives/42-DraftPublish.html was set to 2014-11-13 before. I hit publish in the dashboard just now, it gets published with just that date.

**Comment by ophian** [comment]
intended behaviour, see #160

**Comment by onli** [comment]
> intended behaviour, see #160

No, not at all. If I call time() I expect it to resovle to the unix-time of just now, and having given that to the timestamp parameter I'd expect the entry timestamp to be set to now as well. That is how I understood given this bugreport that is does *not* work right now. And in fact, it does not. So the bug is exactly there, in that line of code.

**Comment by ophian** [comment]
???
we seem to speak of different issues https://github.com/s9y/Serendipity/commit/3660a2f116f2d03c19aed088980ce9fb101f1098

**Comment by onli** [comment]
Oi. Ok, if the core was patched so the timestamp got ignored that explains the bug. And now I get why you saw that as intended behaviour.

I'd like to modify that patch and restore the original intended behavior, and the one wished for in this bug report. Publish in the dashboard should set the timestamp to now, the bug in #160 covered only disappearing drafts. That shouldn't have been timestamp related, was it?

**Comment by yellowled** [comment]
I think we should discuss this tomorrow given the fact that it's not clear what we actually *want* here. :)

**Comment by ophian** [comment]
I for myself better want it to stick to the date it was created. If I want an entry to take another date, I make it a future right away, or use the edit. So leave the action, if we have to, but do not touch its values.

This dashboard (publish) function makes only sense to me, to remember the user that there are still drafts pending. I have seen people using it like this, setting not ready entries or entry ideas as drafts, and then they often are never finished or even forgotten and could get removed at all. They don't care or know that each remove, or unused ID, or sort scrambling (use early IDs on a different range) slows down their system a tiny trifle.
Actually a publish does not make sense for them and would better be an active edit or remove button. 

Writing a publish ready entry waiting to be published via the dashboard, without having another look into, does not sound like a real life example to me too.

**Comment by yellowled** [comment]
Well, to me it *does* sound like a real life example. Besides, I find it pretty pointless to start an argument with what a single person wants. We're not developing this for ourselves.

If the majority wants this to not publish with the current date, I vote to remove it altogether.

**Comment by yellowled** [comment]
Devtalk decision: Publish-Button bleibt, veröffentlicht per sofort; Button wird in einen grauen Icon-Button umgewandelt, um ihn nicht übermäßig zu betonen; Icon steht noch nicht fest.

Wer den Artikel mit dem zuvor gesetzten Datum veröffentlichen will, kann (muss) das über den Eintragseditor tun.

**Comment by garvinhicking** [comment]
Und unbedingt auf ein guten TITLE-Attribut achten "Diesen Artikel veröffentlichen und das Eintragsdatum auf die jetzige Zeit setzen" ;)

**Comment by onli** [comment]
Please give it a test and close here if it works.

**Comment by yellowled** [comment]
Works for me.
