### ISSUE TITLE
FR for Image upload via Go & enter Properties

### ISSUE THREAD

**Issue by ophian** [s9y/Serendipity#266]
I think it is strongly recommended to show/have a radio option field in the image properties form to disset all or even change the EXIF/IPTC/XMP image values by line.

**Comment by yellowled** [comment]
I might be completely wrong here because I never care about EXIF data et.al., but can't you already basically do that if you click “Go & enter properties”?

**Comment by yellowled** [comment]
Ah, right, you can't edit them, they're just being listed. Hm.

**Comment by onli** [comment]
Don't think that ever was possible there

**Comment by garvinhicking** [comment]
EXIF metadate is metadata in the image file, not in the application data. If someone wants to change/edit that data, he/she would need to use an image editor to change the actual image file. IMO s9y is not aimed at providing an interface for that... 

Only little of the EXIF metadata is put into fields like descrpition/title, if someone wants to clear that, IMO it's quite easy to simply overwrite/remove the fields. A "remove all" button is IMO not something that is needed in reality...

**Comment by yellowled** [comment]
So, um … close?

**Comment by garvinhicking** [comment]
I'd vote for that, but let's wait on feedback from @ophian

**Comment by ophian** [comment]
Ich glaube es wäre ein echter Mehrwert für Serendipity wenn wir soetwas anbieten könnten. Nicht jeder weiß, dass images so eine, manchmal sehr detaillierte Information über Standort/Aufnahme Daten etc mitschleppen. Wenigstens ein reset Knopf wäre hier wirklich Klasse. Ups, wont translate this back!

**Comment by garvinhicking** [comment]
The danger is that writing EXIF metadata can quite possibly garbage the whole file, since the standards are quite wacky. Many image tools write EXIF metadata with extended binary data from specific workflows, and RAW-information which by editing with a PHP tool could easily break the file. Also, we'd need a GetID3-like library. So it would be something we'd quite possibly need to put into a plugin because GetID3 is GPL licensed.

**Comment by yellowled** [comment]
Also, we would be implementing something (I have no idea, how much overhead it would be) which probably a lot of our users don't know or care about.

**Comment by ophian** [comment]
> we would be implementing something ... which probably a lot of our users don't know or care about.

What a funny argument. Serendipity has a whole lot of these options. I still think it is a good idea to have... if possible without being wacky.

**Comment by garvinhicking** [comment]
Realistically, I simply think it is a lot of work and not feasible. If you are interested in that and want to implement it i.e. in the serendipity_event_imageselectorplus, please feel free to do that!

**Comment by mbirth** [comment]
Stripping all metadata using ImageMagick (which is a given on 99% of hosters these days) is a matter of:

    convert inputfile.jpg -strip outputfile.jpg

Or programmatically:

    Imagick::stripImage()

Ideally, this would happen after S9Y extracted all metadata from the files.

**Comment by onli** [comment]
I see that more as a workflow issue, the whole properties page is a bit problematic. But sure. If it's so easy I would not be against adding such a function. One should test that imagemagick is available and that this command does not bloat the file size (quality settings etc).
