### ISSUE TITLE
check access & group perms  for all changed or newly added config options

### ISSUE THREAD

**Issue by ophian** [s9y/Serendipity#267]
We should check all Access level and Group Membership (and ACL) permission levels in configuration. For example Maintenance, Dasdboard, newly added Configs or personal Configs, etc.
I assigned Garvin, since I think he has the best insight to this.

**Comment by garvinhicking** [comment]
config_personal got four new items: simpleFilters, enableBackendPopup, use_autosave, wysiwygToolbar. All of them are personal settings, per-author, so those are okay.

config_local got one new item: archiveSortStable, set as "blogConfiguration", and thus changeable by the chief editor.

So everything should be fine, unless I misunderstand you, in which case please reopen.
