### ISSUE TITLE
smarty bugfix clearCompiledTemplates()

### ISSUE THREAD

**Issue by ophian** [s9y/Serendipity#271]
@garvinhicking Shall we include this bugfix "_clearCompiledTemplates() could try to delete whole drive at wrong path permissions because realpath() fail (forum 25397)_" to our 21 version for 2.0?
https://github.com/smarty-php/smarty/commit/7a1df12afa7e1c83e3529d89c38e97feea6f0bf7

**Comment by garvinhicking** [comment]
Oh, bad one :D Yes, please for both 2.0 and master, great!

**Comment by ophian** [comment]
Done and References 762283c and ef90f8e

**Comment by ophian** [comment]
Extend patch ba7de46 and e483598 with ba7de46 and e483598
