### ISSUE TITLE
Dashboard “Entries” is misleading

### ISSUE THREAD

**Issue by yellowled** [s9y/Serendipity#274]
In the dashboard, the “Entries” section is not ideally labelled since it only shows drafts and scheduled entries. So we should come up with a simple term to differentiate from “All entries”.

“Unpublished entries” comes to mind, but that's probably a tad long. Maybe “Drafts”, because scheduled entries are kind of drafts as well? Or “On hold”?

**Comment by garvinhicking** [comment]
"In Progress"
"Work in Progress"
"Queue"
"Pile of Shame"
"Getting Things Done"
"Next Up"

?

**Comment by yellowled** [comment]
I really want “In limbo”. (No, I don't.)

I'm always thinking about the German translation as well. I like “In Progess”, but how would we translate that? “In Arbeit”?

**Comment by ophian** [comment]
hm, "Entries in task/Anstehende Einträge" 
And what about the comments block? Could be "Last X comments"...

**Comment by yellowled** [comment]
The comments block is not misleading. „Anstehende Einträge“ is **way** too long (and sounds very beamtenlike), and I don't think “Entries in task” would make sense to a native speaker.

**Comment by garvinhicking** [comment]
I think "In Progress" / "in Vorbereitung" fits the task nicely.

**Comment by yellowled** [comment]
@garvinhicking Please

a) run `addlang.sh` and add the German translations

b) remind me that we should have a look at `addlang.sh` together in Essen and figure out why this doesn't work on my Mac. It's ridiculous that I have to ask you every time to run it for me. :)

**Comment by garvinhicking** [comment]
Done. I changed the addlang.sh to a "find" syntax that should work on OSX (it needs "find ." instead of only "find". Maybe that's the main issue, Linux has a different find that is agnostic for this.

I also did my first "cherry-pick" of a commit to 2.0 to backport to master, seems much easier than applying the patches manually like I did before, hope that worked.

@yellowled could you also document the last commits you made in docs/NEWS of both master and 2.0?

**Comment by yellowled** [comment]
> could you also document the last commits you made in docs/NEWS of both master and 2.0?

Will do. I keep forgetting it because back when I was just the frontend dude, you guys used to do that. ;)

**Comment by yellowled** [comment]
Don't know how/if you guys do this, but `git cherry-pick <commit sha in master>` (while in 2.0) will backport changes in `master` to `2.0` automagically. I never did that before. So much easier.

**Comment by yellowled** [comment]
FFS. I had a typo in `addlang.txt`, it says `DASHBAORD_ENTRIES`. Gna.

**Comment by yellowled** [comment]
Note to all: @garvinhicking will take care of this.
