### ISSUE TITLE
Spamblock Bayes confirmation is mispositioned

### ISSUE THREAD

**Issue by yellowled** [s9y/Serendipity#276]
It's supposed to be aligned vertically with the button bar.

![screenshot 2015-01-24 12 29 39](https://cloud.githubusercontent.com/assets/326223/5887240/cec782ac-a3c4-11e4-937f-4530f772eb43.png)

**Comment by yellowled** [comment]
If using both Bayes and Spamblock blocking, these styles do not match. So the `<p>` element from Bayes needs a class.

**Comment by yellowled** [comment]
Hm. So commit hashes don't work across branches of the same repo? Bummer.

**Comment by ophian** [comment]
This is still an issue in 2.0.0.

**Comment by yellowled** [comment]
I believe the fix was committed after 2.0.0 was released.

**Comment by yellowled** [comment]
Definitely working in `master`, the code was backported to `2.0`, so it should be fixed in 2.0.1. I don't think the CSS should be added to the backend CSS for Bayes, though. The margins are very specific to the 2k11 backend. Unfortunately, that means it will have to wait for 2.0.1 to be fixed.
