### ISSUE TITLE
checksums.inc.php not found

### ISSUE THREAD

**Issue by bauigel** [s9y/Serendipity#277]
If i to to german "Wartung" (maintenance or something like this) and push "Installation prüfen" (check installation) i get an error

> Fehler beim Vergleich der Prüfsummen! (Keine Prüfsummendatei checksums.inc.php im Hauptverzeichnis gefunden)

checksums.inc.php is available in main directory, but the maintenance-job seems not to find it.

**Comment by yellowled** [comment]
Did you maybe use a git snapshot to update? In that case, the `checksums.inc.php` would be present, but empty (0 bytes). That's because the `checksums.inc.php` is only generated for actual release files (meaning zip files downloaded from s9y.org via SF).

**Comment by bauigel** [comment]
Your are right, the file is empty because of my git-snapshot. Didn't realize this before.
