### ISSUE TITLE
Moved plugins need version requirements and hack protection

### ISSUE THREAD

**Issue by garvinhicking** [s9y/Serendipity#278]
@ophian wrote:

Another thing I noticed: Since being core plugins before, they only used @serendipity_plugin_api::load_language(dirname(__FILE__)); and no if (IN_serendipity !== true) { die ("Don't hack!"); }. I did not check them alltogether, but it seems, they were not set to require 2.0 or 1.7 only. What shall we do about it?

**Comment by garvinhicking** [comment]
We should add the hack-protection and set version requirement to 1.7, I think most plugins should work on non 2.0? the load_language API should afaik be available in older versions already

**Comment by garvinhicking** [comment]
committed changes to additional_plugins

**Comment by ophian** [comment]
:+1: but you did not set the required version, though... it was added in 2010 AFAIR, introduced with 1.6
