### ISSUE TITLE
Show image toolbar in media db overlay when activated

### ISSUE THREAD

**Issue by onli** [s9y/Serendipity#281]
See http://board.s9y.org/viewtopic.php?f=3&t=20237

Also, the setting should be placed in the normal section of the personal settings.

**Comment by garvinhicking** [comment]
@onli I took the liberty to assign you to this, since I haven't checked out the media integration with 2.0 yet. If it's no task you want to take on, feel free to deassign yourself ;)

**Comment by onli** [comment]
It is actually really quite difficult. I got the toolbar displayed, but the buttons that redirect to new pages after their action - delete and rename - redirect to the normal ML. My solution is to ajaxify those. Rename is done, working on delete. That will affect also the normal ML.

**Comment by onli** [comment]
That commit solves the issue partially, the rescale-function is missing. Has someone an idea how we could modify that function to not use a page, but also a js-dialog? Can we have overlays in overlays (would we want that?)?

**Comment by yellowled** [comment]
> would we want that?

I don't think so, at least not a MagnificPopup within another MagnificPopup. Not sure what you would need there, though. Maybe just a `<div>` that's positioned absolutely within the (relatively positioned) `.mfp-content` and overlays it temporarily?

**Comment by garvinhicking** [comment]
How about having the resize part in a div that is invisible and gets shown (unhidden) by clicking the button? Overlay within overlay sounds wicked. :)

**Comment by yellowled** [comment]
That's what I meant. :)

If that `<div>` is within `.mfp-content` (which has `position: relative;` anyway), it can have `position: absolute;`, so it will be positioned absolutely *within* `.mfp-content` when it's “unhidden”.

**Comment by onli** [comment]
So, basically yes, an overlay… 
I'll think a bit about it, and if no one else implements it, try it. Right now I'm missing how exactly I'd do that. 

I'd prefer an intelligent js-dialogue, two number inputs and the checkbox, prefilled with the current size and keeping the aspect ratio like it works now. But that would probably have to go in such a div, and be handcoded.

**Comment by onli** [comment]
I decided now to instead use the extra-params-helper to transport the needed GET-parameters like. It should behave exactly like in the normal ML. @donchambers, would be nice if you test it.

**Comment by yellowled** [comment]
@onli Works for me (tested in `master`, but that should not make a difference, right?). The option for this should still be moved from entry-specific to personal settings, right? Also, this probaby needs to be documented in `docs/NEWS` since it changes the interface.

**Comment by onli** [comment]
master is fine here, yes. 

> The option for this should still be moved from entry-specific to personal settings, right?

Oh, yes. I forgot about that. Will do that and the docu.

**Comment by yellowled** [comment]
> master is fine here, yes.

Just pointing out that this still needs to be cherry-picked to `2.0` since it's supposed to go into `2.0` according to the issue assignment. :)

**Comment by onli** [comment]
Setting is moved, NEWS is updated, and the commits cherry-picked to 2.0. There was a very small conflict I had to resolve, I hope that went well.
