### ISSUE TITLE
serendipity_event_tooltips not working with PHP 5.5+

### ISSUE THREAD

**Issue by garvinhicking** [s9y/Serendipity#282]
Since "e" is deprected in preg_replace, this plugins throws a bunch of errors (which lead to i.e. the backend JS competely not being loadable).

This plugin needs changing to use preg_replace_callback instead.

**Comment by garvinhicking** [comment]
Committed to the plugin

**Comment by yellowled** [comment]
@garvinhicking You can actually use `References s9y/Serendipity#282` in your commit msg in `additional_plugins` to reference the commit here, by the way. :)
