### ISSUE TITLE
Freetag related entries vs stable archives

### ISSUE THREAD

**Issue by yellowled** [s9y/Serendipity#286]
As mentioned in https://github.com/s9y/Serendipity/issues/269#issuecomment-72449673:

If stable archives are used, the second page following the index page (a.k.a. the first “next page”) emits only one entry. If freetags is installed and set to emit related entries, the related entries are emitted on that (overview) page. This is not supposed to happen, related entries are only supposed to be displayed on single entry view.

**Comment by onli** [comment]
Closed with #269, at least till this pops up again.
