### ISSUE TITLE
Deleting a media db directory does not emit file names

### ISSUE THREAD

**Issue by yellowled** [s9y/Serendipity#287]
Reproduce:

* create a new folder in media db
* upload a few files to said folder
* delete said folder

Result:

* the notification msg is wrapped redundantly (got a fix for that ready, will commit asap)
* `serendipity_killPath` does not emit the actual file names of the files deleted, the `<ul>` only has blank `<li>` elements

**Comment by ophian** [comment]
Strange! You took the JS approach to upload several files at once, didn't you. Have a look to your filesystem. The directory is created, but empty, The uploaded files are in /uploads root. This is why they can't be deleted if you purge the ML directory through the dialog.
It seems the JS mass uploader does not transport the dir name... or likely.

**Comment by yellowled** [comment]
> You took the JS approach to upload several files at once, didn't you.

Yes, I did.

> Have a look to your filesystem. The directory is created, but empty, The uploaded files are in /uploads root.

I ran some tests, and I used a new directory for any of the following tests. All “results” check if the file is in the designated directory in the filesystem.

* **Test A:** uploaded a single file through “Add media”, result: file is in designated directory
* **Test B:** uploaded multiple files that way, result: files are in designated directory
* **Test C:** replicated Test A, but this time selected the designated directory *after* selecting the file to upload, result: file is in designated directory
* **Test D:** replicated Test B, but this time selected the designated directory *after* selecting the files to upload, result: files are in designated directory

After that, I deleted the dirctories created for the tests one by one. All four runs removed the directory and files correctly, all of them reported the correct number of files deleted (which you can see because it emits the empty `<li>` elements, but *none* emitted the names of the files deleted.

> It seems the JS mass uploader does not transport the dir name... or likely.

I don't think so.

**Comment by ophian** [comment]
Yes you are right about the JS-mass uploader. I just forgot to add the right dir, when I did that.
I fixed the non echoed file thing though.
Since you removed the obsolete msg wrapper, where does the starting `<span class="msg_notice"><span class="icon-info-circled"></span>` before `Prüfe Dateien im Verzeichnis 'test/' ...` now come from...?

**Comment by yellowled** [comment]
> I fixed the non echoed file thing though.

Thanks.

> where does the starting <span class="msg_notice"><span class="icon-info-circled"></span> before Prüfe Dateien im Verzeichnis 'test/' ... now come from...?

Been trying to grep that, actually. No idea, but it's there. (I realize this is not actually a good fix, but it was all I had time for this morning …)

I would want to leave this issue open until I get the time to investigate the msg further, but this should not be a blocker for 2.0.x.

**Comment by ophian** [comment]
I have already tested it and would recommend to leave
```php
        echo '<span class="msg_notice"><span class="icon-info-circled"></span> ';
        printf(CHECKING_DIRECTORY, $directory);
        echo "</span>\n";
```
in function_images and to use `{if $ob_serendipity_killPath}{$ob_serendipity_killPath}{/if}` only in https://github.com/s9y/Serendipity/blob/master/templates/2k11/admin/images.inc.tpl#L70
Then it works well.

**Comment by ophian** [comment]
Can you confirm this? Then I can commit it.

**Comment by yellowled** [comment]
I can nether confirm nor commit this right now, but I would suggest you go ahead and commit it to `master`. I can test it later today and `cherry-pick` it to `2.0` if it works for me?

**Comment by yellowled** [comment]
Nevermind, I found some time to test it.

**Comment by yellowled** [comment]
@ophian That's perfect, thanks again.

**Comment by ophian** [comment]
There even are some more minors in there: ` . $n .` or written `"<br />\n"` wrapped by these msg classes used in (s)printf() should get removed, since something like an ending `</span>` followed by `<br /><ul>` etc has no need any more.

**Comment by ophian** [comment]
Did you really test all these in any case?

For this one at least, it semmed necessary (that is why I previously added it) to break inbetween for longer image and preview names. It looked much better with...
```diff
 if (@unlink($dfThumb)) {
- $messages .= "<br />\n" . sprintf(DELETE_THUMBNAIL . ' ', $dfnThumb);
+ $messages .= sprintf('<span class="msg_success"><span class="icon-ok-circled"></span> ' . DELETE_THUMBNAIL . '</span>', $dfnThumb);
}
```

**Comment by yellowled** [comment]
> Did you really test all these in any case?

As far as I understand the cases available and was able to reproduce them, yes.

> For this one at least, it semmed necessary

Since both the image to be deleted as well as the thumbnail to be deleted are now seperate msg items, there is no visual need to have a `<br>` inbetween them (msgs are block level items in CSS).

If we wanted to have these “paired” in *one* msg item, we would need to close the `<span class="msg_*">` later. What I'm not sure about is whether there is a case where the image can **not** be deleted (i.e. `msg_error`), but the thumbnail *can* be deleted. In that case, it would look *really* weird if both were only seperated by a `<br>`. That's why I opted to remove the `<br>` and seperate the msgs.

**Comment by yellowled** [comment]
(For the record, I agree that it looks nicer if both are in the same msg item, I'm just not sure if that would not produce an edge case.)

**Comment by yellowled** [comment]
There is still one bug at large here.

If one or multiple images are deleted from the media db by clicking their “Delete” icon or using multi-select and clicking “Delete” at  the bottom of the media db, `serendipity_deleteImage()` is called from a different context than in `serendipity_killPath()` (meaning it omits the `<ul><li></li></ul>` markup).

If that's the case, the success msgs for the deleted image(s) are still wrapped in a `<span class="msg_notice">`. So far, I have not been able to figure out why/where that happens. :(

**Comment by ophian** [comment]
I am not sure this is good. The simple unstiled messages were IMHO better before. I once did this similar to your approach and remember to be called back by @garvinhicking .. and I think he was right.



> If that's the case, the success msgs for the deleted image(s) are still wrapped in a <span class="msg_notice">. So far, I have not been able to figure out why/where that happens. :(

That must be somthing similar to the images.inc.tpl thing we had before, because a "callback" is started, for the image itself and the thumb, and so on.

**Comment by yellowled** [comment]
These *are* messages. Styling them as messages is consistent with our UI, plus it makes it way easier to spot errors in that “wall of text”.

> That must be somthing similar to the images.inc.tpl thing we had before, because a "callback" is started, for the image itself and the thumb, and so on.

I can't figure it out, especially since the `view:source` for the page emitting those messages gives me a completely different markup than the web inspector, which is very weird. (Kind of as if there was some kind of AJAX happening there or something.)

**Comment by ophian** [comment]
I am pretty sure is the line 2 in images.inc.tpl which is the foreach wrapper for $message(s).

**Comment by ophian** [comment]
> in that “wall of text”

Yeah see the missing spaces between sentences...
`Sie beabsichtigen, die Datei 6009-full-a-very-long-long-image-name.jpg zu löschen.Wenn Sie die Datei in einem Ihrer Einträge verwenden, wird das Löschen Lücken erzeugen.Soll trotzdem fortgefahren werden?`

**Comment by yellowled** [comment]
> the missing spaces between sentences

Crap. I was wondering what those were there for.

**Comment by yellowled** [comment]
I tested *almost* all of these. The one thing I can not test is if the permissions of the file or directory involved do not allow upload or deletion. That's because I would basically screw myself if I removed write permission on files or dirs on my test stage (because I'm not root there).

Can anyone with a local test server test this for me?

**Comment by ophian** [comment]
Yeah, it works:
`red Kann das Bild namens test/6009-full-a-very-long-long-image-name.jpg nicht löschen `
`green Vorschaubilder zu test/6009-full-a-very-long-long-image-name.jpg gelöscht `
`yellow Ruhe in Frieden, # 165 ...`
Actually it makes no sense to follow the routine, if there is a permission prob, since it will delete the thumb and the db entry and immediately create a new one, because there is a (new/unknown) image in ML (the one with the perm prob).

**Comment by yellowled** [comment]
> Actually it makes no sense to follow the routine

I have a feeling we have **a lot** of legacy code that is no longer necessary, and not only in this file. It is just very tedious and time-consuming to find and remove. Just look at #50.

Unless there is a way to automate looking for these things I guess there's now way we can remove stuff like that other than “along the way whenever we stumble upon it”. It's either that or we declare one of the 2.x.0 release “the big purge” and do just that – clean out legacy code. (Yay, that's going to be fun.)
