### ISSUE TITLE
jump behaviour of "non-popup" categories/tags buttons and show fields

### ISSUE THREAD

**Issue by ophian** [s9y/Serendipity#291]
Refering to #234 

I tried the new granular option, entering categories, tags for example. I first thought it to be not working, then I discovered the "toolbar".like top-buttons have to be clicked **2 times** to jump to the fields and the inner-form jump for shown categories and tags to be **disabled** at all. I think that needs improvement to be more intuitive.

**Comment by yellowled** [comment]
Duplicate with #290, which I created at the same time. Sorry. Closing this because I already assigned #290 to me.
