### ISSUE TITLE
Entry save confirmation msg uses 2k11 preview_iframe regardless of selected theme

### ISSUE THREAD

**Issue by donchambers** [s9y/Serendipity#295]
to make it even more interesting, although 2k11's preview_iframe.tpl is being used to output the message "Your entry has been saved", the theme's stylesheet is being used thanks to 

<link rel="stylesheet" href="{$serendipityHTTPPath}{$serendipityRewritePrefix}serendipity.css">

**Comment by yellowled** [comment]
Closed together with #294. This needs discussion in the forums to really formulate and idea how to solve it.
