### ISSUE TITLE
Generic odd/even for dashboard widgets

### ISSUE THREAD

**Issue by yellowled** [s9y/Serendipity#297]
As @ophian mentioned in d584a7febb6dfa6b2f8383854c17b4672243a6d3 and http://board.s9y.org/viewtopic.php?p=10441864#p10441864, it is not very efficient to let every plugin that can emit a widget to the 2.0 dashboard reinvent the wheel in terms of detecting where said widget is in the layout of the dashboard (odd/even element). This should be part of the backend theme, not something the plugin has to solve.

This would actually be possible in CSS only if it weren't for IE 8 support, so CSS with a little JS helper for IE 8 should do the trick.

**Comment by yellowled** [comment]
Also, I just realized we must have **zero** IE8 users, at least in the forums. The whole equal heights script did not work in IE8 since we introduced `var mq_small` in JS, and no one ever reported it. LOL.

**Comment by yellowled** [comment]
For future reference: backend dashboard widgets need an extra class `dashboard_widget` on the `<section>` they create.

**Comment by ophian** [comment]
The bad thing about this is, you are now updating plugins on Spartacus for tomorrow, which need then 2.0.1 to work properly!

**Comment by yellowled** [comment]
Right. I can think of three options for this:

1. revert the version number increment so Spartacus doesn't push out updates
2. implement a more granular version check
3. live with it until 2.0.1 is released

I think 2 would be opening Pandora's box of version checks. I'm not a fan of that. 3 would be an option since these are rarely used plugins (I think). 1 would probably be the best, but then we need to remember to increment these for 2.0.1, and there's the possibility of different changes to these plugins in the meantime.

What do you suggest?

**Comment by ophian** [comment]
hmm, probably the first ... and make an issue note.
What happens when 2.0.1 is out if we did not remember?

**Comment by yellowled** [comment]
> What happens when 2.0.1 is out if we did not remember?

The hardcoded sections in `overview.inc.tpl` will be aligned properly, but those emitted by linktrimmer and admin notes will not. They won't have any positioning styles but will still look like a dashboard widget, meaning they will (I think) take up the full width of the dashboard.

**Comment by yellowled** [comment]
I think that is the best course of action. I will create a seperate issue for updating these.
