### ISSUE TITLE
Backend preview stylesheet

### ISSUE THREAD

**Issue by yellowled** [s9y/Serendipity#302]
Pretty sure the preview in the entry editor is bugged at least for some themes. I did some tests and could not get the backend iframe preview to generate the proper stylesheet.

See http://board.s9y.org/viewtopic.php?p=10441958#p10441958

**Comment by yellowled** [comment]
Seems like the issue here is that some templates now use `{$serendipityHTTPPath}{$serendipityRewritePrefix}serendipity.css`, which does not have a cache busting version string. With these themes, the entry preview needs a hard refresh in the browser for the stylesheet to be loaded properly. However, in these themes (in their `preview_iframe.tpl`), `{$head_link_stylesheet}` does not work properly, either.

**Comment by yellowled** [comment]
I think the best solution here would be a generic function to add the cache busting version string to any CSS or JS asset in Smarty templates. That would also be helpful for frontend theme authors.

**Comment by garvinhicking** [comment]
Sadly that's not easy, it would require all custom getfile calls with a new param; because the cache string needs to be appended with "?" For url-rewritten blogs but "&" for non-rewritten ones...

**Comment by yellowled** [comment]
Well, the option would be to find out how to make `{$head_link_stylesheet}` work in these themes' `preview_iframe.tpl` or to just live with it for the time being and see if we can find a way to implement a better preview (see #218).

**Comment by garvinhicking** [comment]
I've now committed a new tpl var that properly references the frontend, and includes the cache-busting string... please check and reopen if it doesn't work for you guys or I misunderstood

cc @donchambers

**Comment by yellowled** [comment]
Works. Excellent, I had already given up on this. ;-)

Why do we still need the fallback to `serendipity.css`?

**Comment by garvinhicking** [comment]
For users with s9y < 2.0.2

(we could remove that fallback for 2k11 and other themes, but I'm too afraid that users will user that as a copy&paste draft, and then a fallback could help...)

**Comment by yellowled** [comment]
Wouldn't it make more sense to incorporate the version check and fallback into the generation of `{$head_link_stylesheet_frontend}` so that theme authors can only use that variable in `preview_iframe.tpl`? I.e. if version < 2.0.2, $head_link_stylesheet_frontend == serendipity.css …?

**Comment by garvinhicking** [comment]
$head_link_stylesheet_frontend does not exist in < 2.0.2, so no.

**Comment by donchambers** [comment]
It does seem to work..   however, the html being emitted upon save (and perhaps other states, such as error) is coming from 2k11: `<span class="msg_success"><span class="icon-ok-circled"></span> Your entry has been saved</span>`

So, unless a template has those classes, they will not appear as they do in the 2k11 theme.

So, can we get those messages emitted by a theme's specific preview_iframe instead of 2k11?

**Comment by yellowled** [comment]
That is a different issue, though. This should probably be discussed along with #218.
