### ISSUE TITLE
Sidebar loginform does not log out

### ISSUE THREAD

**Issue by yellowled** [s9y/Serendipity#304]
Forum reference: http://board.s9y.org/viewtopic.php?p=10442011

Reproduce:

* Install `serendipity_plugin_loginform` sidebar plugin
* Login through the sidebar login form
* Click logout button

Expected result: User is logged out

Actual result: User is not logged out, logging out is only possble through the backend

**Comment by garvinhicking** [comment]
Is the event plugin maybe not installed, would that be the issue? Or is 
it installed and not "listening" for the logout?

**Comment by yellowled** [comment]
Uh, that does ring a bell. I'm going to have to check, but I think I had the same thing before in 1.7.

**Comment by yellowled** [comment]
Yup, just checked, works just fine with the event plugin installed. Going to check with the user in the forums.
