### ISSUE TITLE
Get number of navlinks when navigatinon is global.

### ISSUE THREAD

**Issue by donchambers** [s9y/Serendipity#305]
Reference: http://board.s9y.org/viewtopic.php?f=5&t=20266.

I want to be able to collapse all navigation options of a theme.

This will work if I can get the number of navlinks from a theme's config:

```
$navlinks_collapse = array();
array_push($navlinks_collapse, 'use_corenav', 'amount');
for ($i = 0; $i < $template_loaded_config['amount']; $i++) {
   array_push($navlinks_collapse, 'navlink' . $i . 'text' ,'navlink' . $i . 'url');
}

$template_config_groups = array(
    THEME_NAVIGATION    => $navlinks_collapse
);
```

The part of this that does not work is $template_loaded_config['amount'].  I should note that this DOES work of I define navigation within the theme itself, and not use global navigation.  Global nav is defined in functions_config.inc.php, approx line 2121.

**Comment by garvinhicking** [comment]
To reproduce I'd need the WHOLE config.inc.php.

To me it seems you are trying to access $template_loaded_config before you actually call serendipity_loadGlobalThemeOptions(). Only after that call the variables are actually accessible...

**Comment by donchambers** [comment]
Thanks Garvin.  I was playing around with this last night, and came to nearly the same conclusion.... except that I had two things in the wrong order.

You are correct, $template_loaded_config cannot be accessed until serendipity_loadGlobalThemeOptions() has been called.  Additionally, serendipity_loadGlobalThemeOptions() must be called AFTER $template_loaded_config.

Ultimately I used this:
```
$navlinks_collapse = array( 'use_corenav', 'amount');
for ($i = 0; $i < $template_loaded_config['amount']; $i++) {
	array_push($navlinks_collapse, 'navlink' . $i . 'text' ,'navlink' . $i . 'url');
}

$template_config_groups = array(
    THEME_NAVIGATION    => $navlinks_collapse
);
```
