### ISSUE TITLE
Check all instances of localStorage in backend JS

### ISSUE THREAD

**Issue by yellowled** [s9y/Serendipity#306]
Forum reference: http://board.s9y.org/viewtopic.php?p=10442025

Apparently, there is at least one instance where localStorage not being available in the browser prevents the JS from being executed. This should not happen since localStorage is only supposed to store the stte of a collapsible element.

**Comment by onli** [comment]
Given the support of that feature, this should not be necessary: http://caniuse.com/#search=localstorage

Of course, if it's only one `if` in three places I don't mind.

**Comment by yellowled** [comment]
Apparently, users can disable localStorage in `about:config`. If that leads to people being unable to toggle expandable items, it should be fixed.

Since this is an "advanced" setting, a fix is not high priority, I guess.

**Comment by onli** [comment]
See, I disagree with that. If user disable manually features needed to operate the site, the site should break. Don't disable essential features if you want to use the web.

The thing is: We are not only using it for collapsible items. We are also using it for showing the correct tab in the plugin page. We use it to save autosave the editor content. We might use it for even more essential things in the future. 

Main point is: I want to be able to rely on this feature in the future, given all browsers support it.

**Comment by yellowled** [comment]
Yes, but we (currently) use it only to *store states*. That means localStorage is used to i.e. remember if a collapsible element was last expanded or collapsed. It is not used to actually expand or collapse it, but *that* is the functionality that it breaks.

**Comment by garvinhicking** [comment]
I think we should gracefully degrade, and an extra "if" to check if 
local storage is available don't hurt us, but make the user actually use 
the software. It's not an essential feature, so breakage should IMO not 
occur.

Having said that, I'm not sure how that IF should look like?! :)

Once that localstorage really gets critical for any feature, we can 
still remodel that IF to create an alert or so. We could even use the 
dashboard to emit things like "Warning: LocalStorage not available" or 
"Warning: Javascript not available"...?!

**Comment by yellowled** [comment]
> Having said that, I'm not sure how that IF should look like?! :)

I don't even have time to look at the code or try to reproduce this at the moment. I really think that this is not high priority, but there might even be extensions for FF which set this config option.

**Comment by onli** [comment]
> Once that localstorage really gets critical for any feature, we can still remodel that IF to create an alert or so.

There is a difference between graceful degradation for stuff that is normal and stuff that is obscure. JS without localstorage is obscure enough to break hard imo. 

Though I have to correct myself, the thing more critical is indexeddb, not localstorage, since that powers an actual important feature I thin is essential. Though that probably gets disabled by the same config setting.

So, was important for me to protest. I'll get quiet now :)

**Comment by yellowled** [comment]
> Though that probably gets disabled by the same config setting.

Well … 

> Obviously, browsers do not want to allow some advertising network or malicious website to pollute your computer, so browsers prompt the user the first time any given web app attempts to open an IndexedDB for storage. The user can choose to allow or deny access. Also, IndexedDB is completely disabled in the privacy modes of browsers (Private Browsing mode for Firefox and Incognito mode for Chrome).

https://developer.mozilla.org/en-US/docs/Web/API/IndexedDB_API/Using_IndexedDB

**Comment by yellowled** [comment]
I do, by the way, agree with the sentiment that we can expect users to have certain (wide-spread, well-supported) browser options available in order to user certain features of the backend.

However, essential functionality should still be accessible.
