### ISSUE TITLE
Canonical links in frontend themes

### ISSUE THREAD

**Issue by yellowled** [s9y/Serendipity#310]
For all core and additional themes that have an `index.tpl`.
```
{if ($view == "entry" || $view == 'start' || $staticpage_pagetitle != '')}
   <meta name="robots" content="index,follow">
{else}
   <meta name="robots" content="noindex,follow">
{/if}
{if ($view == "entry")}
   <link rel="canonical" href="{$entry.rdf_ident}">
{/if}
{if ($view == "start")}
   <link rel="canonical" href="{$serendipityBaseURL}">
{/if}
```

**Comment by yellowled** [comment]
Maybe add a canonical URL for static pages?

**Comment by yellowled** [comment]
Check what happens if `serendipityBaseURL` is set to autodetect.

**Comment by garvinhicking** [comment]
I beliebe the noindex-thing is too strict, it could prevent indexing externalcplugin output or others? Maybe better explicitly check for archives views and make those noindex, and let the default be to index?

**Comment by yellowled** [comment]
I think we're going to need to make a list what should explicitly get indexed and what should explicitly **not** get indexed, including i.e. static pages generated by plugins etc.

**Comment by garvinhicking** [comment]
I change my mind, it's better to use a positive index,follow because it would be too much to blacklist.

Now those views are covered:

noindex:
archives
404
admin
archive
categories
authors
search
css
js
comments

index:
entry
feed
plugin
start

So I propose this code:

```
{if ($view == "entry" || $view == "start" || $view == "feed" || $view = "plugin" || $staticpage_pagetitle != "")}
   <meta name="robots" content="index,follow">
{else}
   <meta name="robots" content="noindex,follow">
{/if}
{if ($view == "entry")}
   <link rel="canonical" href="{$entry.rdf_ident}">
{/if}
{if ($view == "start")}
   <link rel="canonical" href="{$serendipityBaseURL}">
{/if}
```

**Comment by yellowled** [comment]
Do we *have* to do this in Smarty templates? Wouldn't it be smarter to inject this globally through a frontend hook?

**Comment by garvinhicking** [comment]
If we did that from a global frontend hook, it couldn't be 
changed/override in a template file, if template authors want it 
differently. I think this is the best place...

**Comment by yellowled** [comment]
> If we did that from a global frontend hook, it couldn't be changed/override in a template file, if template authors want it differently.

Right. Hm. Don't get me wrong, I don't mind editing all `index.tpl` files, I just thought a central place would be better in case we ever have to change this again.

**Comment by garvinhicking** [comment]
What we could do is to put this code into a variable like {$canonical} with the "final" HTML, like this in genpage.inc.php:

```
if ($serendipity['view'] == '...' || $serendipity['view'] == '...') {
    $canonical = '<link rel blabla';
....
$uri_addData['canonical'] = $canonical;
````

and then simply use {$canonical} in each index.tpl.

This way, someone who wants his own canonicals can remove {$canonical} from the template and put in his own code. And we'd have it at a central place. That means that however spartacus templates need a new s9y version for this feature to work. That'd be fine, I think.

If @onli and @ophian don't disagree I can implement this code?

**Comment by ophian** [comment]
I have no opts. Just a question: Does this (somehow) hit the staticpage metas?

**Comment by onli** [comment]
> If @onli and @ophian don't disagree I can implement this code?

I would prefer to have it in the template. Reason is simply that we spent all that time to separate the html code out of the core into templates (well, in the backend) that it seems wrong to me to do now add html in the core.

If we have to change that alter, I'll try to provide a regex to help with such a change.

**Comment by yellowled** [comment]
> Reason is simply that we spent all that time to separate the html code out of the core into templates (well, in the backend) that it seems wrong to me to do now add html in the core.

We do basically the same for i.e. incuding jQuery in the frontend, don't we?

**Comment by garvinhicking** [comment]
I agree with that, it's really a few lines of "real" HTML that we put in code, and it has overhead (passing along parameters). Codewise it would be a hack to make this a single place. Maintenance-wise it's harder, but then again I hope we don't really need to change it in the future. I suppose more views will be added where noindex is appreciated, I'm not sure if there will be new places in the future that forbid it.

To be sure, we could modify the code to:

```
{if ($view == "entry" || $view == "start" || $view == "feed" || $view = "plugin" || $staticpage_pagetitle != "" || $robots_index == 'index')}
   <meta name="robots" content="index,follow">
{else}
   <meta name="robots" content="noindex,follow">
{/if}
{if ($view == "entry")}
   <link rel="canonical" href="{$entry.rdf_ident}">
{/if}
{if ($view == "start")}
   <link rel="canonical" href="{$serendipityBaseURL}">
{/if}
```

Then in the future we could make parts of the core set this $robots_index variable to "index" to force a site being indexable (defaulting to "noindex")...?

**Comment by donchambers** [comment]
We have a canonical plugin.  Wouldn't this be better suited there?

**Comment by garvinhicking** [comment]
We feel this is something that needs to be covered in our core, because Google is really penalizing pages that don't have this. Should work out-of-the-box.

**Comment by yellowled** [comment]
For the record: I do not want to do that again. Ever.

There are (as the diff shows) quite a lot of themes in `additional_themes` that do not adhere to our coding guideslines (tabs/spaces, indenting, encoding) properly, by the way. But since they're pretty much all outdated, I would not bother to fix that unless someone can come up with a method to automate it.
