### ISSUE TITLE
Move Documentation to Github Pages

### ISSUE THREAD

**Issue by garvinhicking** [s9y/Serendipity#311]
I made an initial draft:

http://s9y.github.io/Serendipity/todo.txt

on what to put where. First step would be to simply mirror the current structure, and move all text from cowiki syntax there to markdown.

Second step would be to rework all actual content, add new images, rewrite text so that it fits.

Third step is to write up new texts for everything that's missing.

**Comment by garvinhicking** [comment]
(Of course I'd love to get some help on that *g*)

**Comment by garvinhicking** [comment]
Moved from: https://github.com/s9y/Serendipity/commit/bdf090b80be08bb3155b53187928c6ddfeaaaba8#commitcomment-10095719

We'll need a seperate repository for this gh-page branch, I'm sorry I messed up.

I propose those new repositories:

* docs (for gh-pages)
* theme_board
* theme_blog

The "one-liner" for the static www.s9y.org page will also be hosted on github.io. I will simply add a rewriteRule to www.s9y.org that will directly forward to github.io (read: docs.s9y.org once we have it), then we never need to store anything else on www.s9y.org apart from the mirror/ process.

If we all agree on the repository names I can create them and move the gh-branch there.

**Comment by yellowled** [comment]
I'll see what I can do after my vacation week. I *might* get to do some things this week even, but that will be totally sporadic and spontaneous.

The docs repo **has** to be called `s9y.github.io` for github pages deployment to work. However, we can start working on it in a docs repository and move/rename that later, I think.

**Comment by donchambers** [comment]
Are you guys sure about having absolutely nothing on s9y.org?  While I am all for the elimination of cowiki, I am having a difficult time imaging everything contained on github.

**Comment by yellowled** [comment]
There will not be nothing. There will be a onepager showcasing the basic things a first-time visitor needs to know. Also, the domain s9y.org will still be used, it will just redirect to GitHub.

**Comment by garvinhicking** [comment]
Maintaining the onepage there is IMO not necessary.

The reason for github pages is that it will updated content immediately. If we hosted it on s9y.org, we wouldn't be able to have real-time updates (due to server access we would need to run cronjobs that could only periodaclly update). If github ever goes away, or github pages, we can go that route.

I really like being able to remove some services...

**Comment by donchambers** [comment]
I have the s9y blog template, forum templates - pretty much all of the templates....  provided they never changed after I created them.  @garvinhicking  - do you need these, or do you also have them?

**Comment by garvinhicking** [comment]
Hey don,

thanks for the offer - I don't think they have changed, but I have 
access to them and will commit them this week to github to serve as a 
point where it will also be pulled back to those two places, allowing 
actual editing for us, so that I don't need to manually copy over files :)

**Comment by yellowled** [comment]
Might even be worth to see if phpBB has some kind of newer default theme to use as a starting point, but I *think* they don't, and it's probably more work than using the one we currently use.

@donchambers Do you remember if adapting it for s9y was CSS only or was there some kind of template editing involved?

**Comment by donchambers** [comment]
@garvinhicking - ok.  Am I understanding this correctly:  pages currently residing at s9y.org will instead be hosted here on github?

@yellowled - if you go to phpbb, you will see they are using pretty much the same basic template.  It is named prosilver.  The "style" is a combination of css (themes) and html (templates).  The html is broken into components.   I THINK (but don't know for sure) the only html mod required was to the header file...  that's where our top nav (homepage, blog, download etc), banner nav and book info all exists.. pretty much everything above the forum posts themselves.

I think Carl Galloway did the original designs, and there is much in there that we would consider sloppy by today's standards.  I remember recreating the header in photoshop, and I think I may have drawn other elements in photoshop.   I have all those files - and the s9y logo.

**Comment by yellowled** [comment]
> Am I understanding this correctly: pages currently residing at s9y.org will instead be hosted here on github?

Yes.

> I have all those files - and the s9y logo.

As far as I'm thinking now, we won't need any of those assets for the future template besides an SVG version of the logo, and we have that in s9y/additional_plugins@9a6df781bb5aa773d58707b7141345de60501440. (Probably still a good idea to keep them as a backup.)

**Comment by garvinhicking** [comment]
Ok I have now created the three repos, deleted the gh-pages branch, and added the current phpbb and s9y templates. They are pulled every 15 minutes to the s9y.org server.

**Comment by yellowled** [comment]
So once we start working on `theme_board` and `theme_blog`, we'll want to do that in a branch so it does not get deployed to s9y.org while we're still working on it.

**Comment by hommelma** [comment]
If I want to provide some help transferring the old pages to the new repository/markdown, I think I first need an account for the wiki to get the old markdown?

**Comment by yellowled** [comment]
I'm not sure we can actually get Markdown from CoWiki … but technically, yes.

**Comment by hommelma** [comment]
With "old markdown" I meant the old wiki syntax/markup. As I understand Garvins `todo.txt` we can take it and "translate" it to markdown. So, if it's ok, I would be happy to get a wiki account.

**Comment by yellowled** [comment]
@garvinhicking, give the man a coWiki account! :)

**Comment by donchambers** [comment]
I have coWiki credentials too, and will help with that when I can.

Those pages are going to be ugly, but probably no more so than some of these themes I've been looking at today!  :)

**Comment by garvinhicking** [comment]
Sure that would be awesome. We'll need to coordinate with @donchambers so that nobody does double work. Maybe check who starts with which section? I'll create a wiki account for you tonorrow. Much much appreciated. This will be quite some work...

**Comment by yellowled** [comment]
In s9y/s9y.github.io – is `index.html` supposed to be the onepager (i.e. s9y.org) or the start page for the docs (i.e. docs.s9y.org/index.html)? If it's supposed to be the onepager, it might be a good idea to move all the docs to a subdirectory.

All this will somehow depend on what we actually use to create HTML out of Markdown. Of course, we can always move files later, depending on what build mechanism we end up using.

**Comment by garvinhicking** [comment]
Not sure yet. Probably the onepager and docs.s9y/index will be one and the same. Shouldnt matter at this point though? First lets get the migrated files together, we can do the moving or renaming later.

**Comment by yellowled** [comment]
> Shouldnt matter at this point though?

Nope. As I said, we can always move the stuff later. Might be worth moving Markdown files to a `src` directory, for example.

**Comment by garvinhicking** [comment]
I created subdirectories for each menu item that I think we'll need...?! 
There we would put "index.markdown", "blabla.markdown" etc. files...?!

**Comment by yellowled** [comment]
Honestly, I have no idea what's smart here in terms of directory structure yet. :)

Let's see what build process we end up using (I'm guessing Jekyll), have a trial run with that, and then we'll probably know what to do here.

**Comment by mariohommel** [comment]
Ok, let's go.
I would take the "faq" section. 
What naming convention will we have?
`11.html` will become `11.markdown` in the faq subdirectory?
Where should internal links point at? Will `http://www.s9y.org/11.html` be  `docs.s9y.org/faq/11.html` in the future?

**Comment by yellowled** [comment]
> What naming convention will we have?

No idea, actually. Jekyll requires a certain directory structure, but I'm not sure what makes sense here. Maybe @mattsches can shed some light on this?

> Where should internal links point at?

Excellent question. I don't think we can avoid having to fix those manually later …

**Comment by garvinhicking** [comment]
I also think we'll need to fix up the internal links later when we figure the jekyll scheme out. For now I'd rather go with "speaking" filenames like "faq.markdown" or so...?

What's the best way to coordinate who works on this? Dropping a note here in this thread, or some titanpad/google spreadsheet?!

**Comment by donchambers** [comment]
> What's the best way to coordinate who works on this? Dropping a note here in this thread, or some titanpad/google spreadsheet?!

I vote here.

**Comment by mariohommel** [comment]
>What's the best way to coordinate who works on this? Dropping a note here in this thread, or some titanpad/google spreadsheet?!

I agree with Don, we can manage it here.

**Comment by mariohommel** [comment]
I just commited a very simple testpage here:
http://mariohommel.github.io [(Source)](https://github.com/mariohommel/mariohommel.github.io)
So the subfolder-thingie will work and wie *could* use the old filenames with ".markdown" which will be ported to ".html". Certanly we also can use brandnew "speaking" filenames as Garvin suggested.

**Comment by garvinhicking** [comment]
Thanks for checking! I'd tend to go for speaking names and make a cut. We'll consilidate most content so I think having clean filenames will be important...

**Comment by yellowled** [comment]
IMHO wensible URLs (i.e. `topic.html` instead of `123.html`) are a must, if only for SE0 reason. Might also be a requirement for Jekyll, I'm not sure yet. However, that probably also means quite a lot of 301 rewrite rules …

**Comment by mattsches** [comment]
I'd also vote for speaking names. Combine that with a brand new file structure, and we will have beautiful paths in our URLs - nice :smile_cat: I think the initial file structure that exists now is fine. It can be changed later, but then we would have to update all the internal links and so on. (Internal linking would have been one of the advantages of reStructuredText btw, but using that is out of the question here).

Should we really set up RewriteRules for each old page? Probably, the new documentation will be much more dynamic, and some of those rules won't be needed anymore after a while.

And can we agree on `.md` as file extension for the Markdown files? I know `.markdown` is also possible, but the shorter version is the more common, I guess.

**Comment by yellowled** [comment]
+1 for `.md`. I would also suggest to encourage people to use Markdown, although technically, Textile and HTML are possible. It's just nicer for people editing and possibly translating things if everything is consistent.

**Comment by mattsches** [comment]
Seems I don't have access to the old wiki (or I lost it). Nevermind. I've just copied the proper HTML from the source (view-source:http://www.s9y.org/3.html) and used [pandoc](https://github.com/jgm/pandoc) to convert it to Markdown - works like a charm :)

Simply paste the HTML into file, e.g. `Features.html`, save it, and run
```
$ pandoc -o Features.md Features.html 
```

**Comment by yellowled** [comment]
By the way

* Features
* Downloads
* Support
* Team

are also supposed to part of the homepage (which I'm working on right now), but I'm not sure if they should have “extended versions” (might make sense for some of them) in the docs.

**Comment by garvinhicking** [comment]
We'll want to only have the body of the page content, and also I believe 
it'll be easer to copy the raw cowiki markup, because it always has the 
proper indents and I think it ensure that we don't lose something 
structural becuase of the HTML transformation...?!

**Comment by garvinhicking** [comment]
Hi!

Yeah; we could shorten the feature for the startpage, but be more 
verbose on a detail page.

For the startpage we only want one download, on the subpage we want past 
versions and instructions on where/how to get prereleases.

For support we want a simple linklist on homepage, but on the detail 
page explain what we use for what.

On the startpage we want a short member list, on the extended page we 
want to list past developers...

**Comment by yellowled** [comment]
I'll make something up out of thin air for the demo of the homepage. We'll probably also want a smaller team (I was thinking only active devs?).

**Comment by donchambers** [comment]
>We'll want to only have the body of the page content, and also I believe it'll be easer to copy the raw cowiki markup, because it always has the proper indents and I think it ensure that we don't lose something structural becuase of the HTML transformation...?!

Is the cowiki markup compatible with markdown, or are we doing a translation cowiki to markdown?

**Comment by garvinhicking** [comment]
@donchambers Check out the todo.txt file, it mentions what differences are of concern; shouldn't be too hard I hope.

**Comment by donchambers** [comment]
Pretty groovy:  https://github.com/s9y/s9y.github.io/blob/master/docs-landing-page.md

I'll do Features and Downloads next

**Comment by mariohommel** [comment]
I'm working on faq.

**Comment by garvinhicking** [comment]
Hm that's strange - http://s9y.github.io/docs-landing-page.md is not parsed as markdown..?!

**Comment by yellowled** [comment]
As far as I know, Jekyll requires a specific directory structure (which I think is configurable). Also, `s9y.github.io` still lacks some components required for Jekyll to convert Markdown to HTML (layouts, includes).

**Comment by donchambers** [comment]
>Hm that's strange - http://s9y.github.io/docs-landing-page.md is not parsed as markdown..?!

How are you coming to that conclusion?  It looks like a web page when I access it.

**Comment by donchambers** [comment]
Actually, this is when it looks like a webpage:
https://github.com/s9y/s9y.github.io/blob/master/features/features.md

**Comment by mariohommel** [comment]
@yellowled GitHub will parse markdown without this when you open the file in GitHub itself. The parsing to html when calling http://s9y.github.io only works, when there is a section with
```
---
title: Test
---
```
or so at the top of the file.
The problem seems to be the strange path wil "/blob/master"?

**Comment by yellowled** [comment]
https://github.com/s9y/s9y.github.io/blob/master/docs-landing-page.md and http://s9y.github.io/docs-landing-page.md are two different views of the same file. The first one is the Markdown file in the GitHub repository, which is indeed rendered as HTML like (I think) any Markdown file in any GitHub repository. You can also click the “Raw” button to get the [raw view](https://raw.githubusercontent.com/s9y/s9y.github.io/master/docs-landing-page.md) there.

The second URL is never supposed to be called in a browser. The proper “rendered” URL for that page would be http://s9y.github.io/docs-landing-page.html, which doesn't exist yet because the Jekyll “frame” (layouts, includes etc.) is still missing in the repository, which is why no HTML file is generated in the first place.

**Comment by yellowled** [comment]
We could, however, try adding the YAML frontend matter (the code snippet that @mariohommel quoted above) to https://github.com/s9y/s9y.github.io/blob/master/docs-landing-page.md – but I doubt that would lead to the HTML file being rendered. I might be wrong. Try it. :)

**Comment by donchambers** [comment]
I modified the top:
```
---
title: # Serendipity -  a PHP Weblog/Blog software
---
```
I get a 404 here: http://s9y.github.io/docs-landing-page.md

**Comment by mariohommel** [comment]
Ah yes, the link with the "/blob/master" is also used when I klick on the file in https://github.com/s9y/s9y.github.io.

**Comment by yellowled** [comment]
Ah, it *did* work that way: http://s9y.github.io/docs-landing-page.html (We committed at the same time.)

So every Markdown file needs at least the following *before* the content

```
---
title: Whatever
---
```

**Comment by garvinhicking** [comment]
I see, thanks. Was under the impression we could directly view MD on the gh-pages. Guess for now the other url (w/ blob/...) is suitable to see how code is rendered.

**Comment by yellowled** [comment]
> Was under the impression we could directly view MD on the gh-pages.

See above – we *can*, but the MD files need the YAML frontend matter.

**Comment by yellowled** [comment]
See https://raw.githubusercontent.com/s9y/s9y.github.io/master/docs-landing-page.md for how to use the YAML frontend matter, see http://s9y.github.io/docs-landing-page.html for the rendered HTML.

(Look at that page's source code to see that it's indeed still missing header/footer as includes, which is why it does not have a `<head>`, for instance. That needs to be defined in an HTML include.)

**Comment by yellowled** [comment]
Also, a little Markdown hint: writint lists this way

```
* first item

* second item
```
will result in 

```
<ul>
    <li><p>first item</p></li>
    <li><p>second item</p></li>
</ul>
```
while
```
* first item
* second item
```
will generate the same without the `<p>` elements (which are not really necessary).

**Comment by mariohommel** [comment]
If you look to the sample page I posted above, you can see a very simple example for how it's working.

**Comment by yellowled** [comment]
Yeah, it uses Liquid templates. Pretty simple. I'm working on a HTML version of the homepage, but it will take me a few more days. We can use that as a layout pretty easily, along with stylesheets, JS and all that jazz.

**Comment by mattsches** [comment]
I just wrote a simple parser and html2md converter, maybe it helps. I didn't verify the results, however, because it's just a quick hack. The results are in the `markdown` directory: https://github.com/mattsches/s9ydocs-html2md

**Comment by mariohommel** [comment]
I think that makes things a little easier. Thanks. :smiley:

**Comment by garvinhicking** [comment]
I love you guys :-)

**Comment by donchambers** [comment]
The next docs I was going to work on were http://www.s9y.org/32.html, (todo list) its subpage of http://www.s9y.org/140.html (summer of code) and http://www.s9y.org/61.html (hosting providers).

Are those really desired going forward?

**Comment by garvinhicking** [comment]
No, many are on the "blacklist" index - check out todo.txt, there are 
quite a few files that we can drop completely.

(hosting providers needs moving though)

**Comment by donchambers** [comment]
> (hosting providers needs moving though)

Will do that one next

**Comment by donchambers** [comment]
Not entirely sure what you guys want to do with the [developer page](http://www.s9y.org/6.html)

* Is this to be stored with features.md (todo.txt makes me think so)?
* The list is both out of date, but also missing people I know to be developers.  Is there a more complete list, perhaps drafted in Essen?
* Many of the links point to wiki pages for a specific author.  Are we porting those to markdown?
* A few of the links point to wordpress sites...  do we really want to be linking to wordpress sites?

**Comment by garvinhicking** [comment]
First a distinct page, later we can see where/if we merge. We need to append/update the list, we have not prepared that. Active developers get links, old ones won't :)

**Comment by mariohommel** [comment]
I'm done with the faq folder. I found six more documents while following the links, which weren't in todo.txt and not in @mattsches markdown folder. Don't know why but I added them to faq. I changed the links to other docs in faq to the new name without a path, so they will work as long as the docs stay in same folder. Links to docs in other subfolders I left unchanged. I documented everything in filenames-old-new.txt so we remember what needs to be done.

**Comment by mariohommel** [comment]
Next I do "Getting Started".

**Comment by garvinhicking** [comment]
Awesome, I didn't dare to wish getting progress so quickly. Guess I'll need to prepare my thumbs to worte up the missing this...

**Comment by yellowled** [comment]
I have a prototype of the homepage about 50% done, will probably finish it at the beginning of next week. Should at least be usable for the docs right away, maybe even for the blog theme.

**Comment by garvinhicking** [comment]
Our subdomain http://docs.s9y.org/ is now working! :-)

**Comment by mariohommel** [comment]
> I have a prototype of the homepage about 50% done, will probably finish it at the beginning of next week.

Don't know how to say "Bin gespannt wie ein Flitzebogen" in English. :smile: 

> Our subdomain http://docs.s9y.org/ is now working! :-)

Great!
I'm working on "Using Serendipity" now.

**Comment by garvinhicking** [comment]
@donchambers @mariohommel Could you maybe mark the pages you guys took care off in the todo.txt file? Then we have a list to easily see whats still missing. I hope to find time next week to get started on this and rework existing text, and add stubs for where I want more content and what exactly...

**Comment by donchambers** [comment]
Sure - I have a few one or two still in progress...  life got in the way the past few days.  :)

**Comment by mariohommel** [comment]
OK, I will do this later this evening. :smiley:

**Comment by donchambers** [comment]
I added the developer page /features/developer-team.md.  There are numerous questions noted in the file.  @garvinhicking I feel you will need to edit this document for the most accurate reflection of the developers and their responsibilities, if so noted.

>First a distinct page, later we can see where/if we merge. We need to append/update the list, we have not prepared that. Active developers get links, old ones won't 

>>On 13.03.2015, at 19:46, donchambers <notifications@github.com> wrote: Not entirely sure what you guys want to do with the developer page Is this to be stored with features.md (todo.txt makes me think so)? The list is both out of date, but also missing people I know to be developers. Is there a more complete list, perhaps drafted in Essen? Many of the links point to wiki pages for a specific author. Are we porting those to markdown? A few of the links point to wordpress sites... do we really want to be linking to wordpress sites? — Reply to this email directly or view it on GitHub.

**Comment by donchambers** [comment]
Working on http://www.s9y.org/20.html next

**Comment by garvinhicking** [comment]
@donchambers Upps, sorry. I implemented this today. Hope it's not too late. Check out my recent commit right now.

**Comment by donchambers** [comment]
No problem.  I had not completed my version.  Great job!

**Comment by mariohommel** [comment]
I'll do `documentation/developing` next.

**Comment by garvinhicking** [comment]
I'm now at a point where I need help to continue:

How can we now view pages (without a layout currently, that's ok) to click/browse through the pages, with navigation and automatic table of contents?

How exactly do we need to build links?

I'd need that to be able to view our current code and try to restructure all text properly. That's quite impossible with a simple editor like I did until now, the structure is now too large to be able to work with it to move around content.

@mattsches @yellowled ?

(No need to hurry, just noting that, that I probably can't continue until this is figured out)

**Comment by yellowled** [comment]
> How can we now view pages (without a layout currently, that's ok) to click/browse through the pages, with navigation and automatic table of contents?

We can't. Both navigation and toc would need to be generated by Jekyll which means we would need corresponding Jekyll templates. (I would, by the way, suggest to only have a toc for navigating the docs. That's basically all there is to it, right? Treat the docs like a book, so navigate it through a toc?)

I'm still working on layout drafts for the homepage and docs. Of course, we could generate a rudimentary Jekyll template which simply combines the pages' content with a toc, if that helps.

> How exactly do we need to build links?

What do you mean, like linking to other sections of the docs from the content?

**Comment by mariohommel** [comment]
> How can we now view pages (without a layout currently, that's ok) to click/browse through the pages, with navigation and automatic table of contents?

If the pages have am YAML-Block, we can view them simply with http://docs.s9y.org/faq/serendipity-faq.html.
To navigate from toc to the topics, I did
```
*  [General information](#A2)
  *  [Where does the name Serendipity originate from?](#A3)
 .
 .
 .
# <a name="A2"></a>General information

## <a name="A3"></a>Where does the name Serendipity originate from?
```
which works but generates a strange html-code. Also it would be difficult to handle all these links manually, when changes are made?

To link to other documents I used the `filename.html` for docs in the same directory and the full path `http://docs.s9y.org/path/doc.html`.

**Comment by garvinhicking** [comment]
Ok Inwas hoping to have a dynamic TOC in each individual file as well as a "full" TOC that spans across all pages. I'd especcially need the latter to have a full overview of all sections... That toc could be the entry point to the "Documentation" link in our future header (where board, blog, spartacus are also linked)...?

**Comment by mariohommel** [comment]
Ah ok, I misunderstood your question, sorry.

> Ok Inwas hoping to have a dynamic TOC in each individual file as well as a "full" TOC that spans across all pages. I'd especcially need the latter to have a full overview of all sections... That toc could be the entry point to the "Documentation" link in our future header (where board, blog, spartacus are also linked)...?

**Comment by yellowled** [comment]
> Inwas hoping to have a dynamic TOC in each individual file as well as a "full" TOC that spans across all pages.

Should not be a problem technically. There's Jekyll plugins for that, I think. Depending on which Markdown engine one uses, it might even work with plain Jekyll.

**Comment by yellowled** [comment]
I'll assume that this can be closed since the issue has been dead for more than 8 months now and a lot has changed in the docs repository since then. Will close and remove the associated milestone.
