### ISSUE TITLE
dbclean: Use cronjob

### ISSUE THREAD

**Issue by garvinhicking** [s9y/Serendipity#315]
Hook into cronjob plugin for performing maintenance.

Also check why dbclean plugin is emptying whole tables (?)

**Comment by garvinhicking** [comment]
@onli You mentioned on our meeting that sometimes whole tables where emptied. Do you remember which ones? Some of them have "weird" dateparsing, so it could be that a comparison of those makes a problem. What strikes me odd is that "referrers" and "exits" differently query the 'day' column, even though the seem to share the same table definition? Looks to me as if both would need to use the date(...) syntax?

**Comment by garvinhicking** [comment]
cronjob functionality has been added to the plugin.
@ddeimeke - please check it out :-)

**Comment by onli** [comment]
> Do you remember which ones?

I'm not sure, sorry. I'm sure it works for spamblocklog. I think it failed or referrers.

**Comment by garvinhicking** [comment]
@onli Yeah I believe we would need to use the same WHERE query for referrers that's used for exits?

**Comment by onli** [comment]
Yes, both tables have the same date-scheme:

    CREATE TABLE {PREFIX}exits (
      entry_id int(11) NOT NULL default '0',
      day date NOT NULL,
      count int(11) NOT NULL default '0',
      scheme varchar(5),
      host varchar(128) NOT NULL,
      port varchar(5),
      path varchar(255),
      query varchar(255),
      PRIMARY KEY  (host,path,day,entry_id)
    ) {UTF_8};

    CREATE TABLE {PREFIX}referrers (
      entry_id int(11) NOT NULL default '0',
      day date NOT NULL,
      count int(11) NOT NULL default '0',
      scheme varchar(5),
      host varchar(128) NOT NULL,
      port varchar(5),
      path varchar(255),
      query varchar(255),
      PRIMARY KEY  (host,day,entry_id)
    ) {UTF_8};

What works for the one should work for the other (and it seems like referrers is the one not working, tough difficult to test, as I don't have exit tracking enabled).

**Comment by onli** [comment]
This fixed, isn't it?

**Comment by onli** [comment]
I'll assume yes and close here
