### ISSUE TITLE
Revise assets for s9y.org

### ISSUE THREAD

**Issue by yellowled** [s9y/Serendipity#319]
- [x] Check [image assets provided](https://github.com/s9y/additional_plugins/commit/9a6df781bb5aa773d58707b7141345de60501440)
- [x] Also check if these assets suffice for HDPI images
- [x] Search for a free webfont (Google Webfonts, preferably) similar to Schneidler Black
- [x] Search for a free webfont for long body copy etc. (Source Sans Pro maybe?) – that font should *not* be associated with other brands (like the Ubuntu font family) or overused (like Open Sans)
- [x] Find a sensible way to display the funny slogan as a banner or something like that

**Comment by yellowled** [comment]
Possible **heading** font options I found while quickly browsing Google Webfonts (always compared to the Bold/700 variant of the font):

* [Neuton](http://www.google.com/fonts/specimen/Neuton)
* [Alegreya](http://www.google.com/fonts/specimen/Alegreya)
* [Vollkorn](http://www.google.com/fonts/specimen/Vollkorn) – @onli mentioned that, and I misunderstood that he meant for body copy; it would probably work for headings, but not for body copy
* [Source Serif Pro](http://www.google.com/fonts/specimen/Source+Serif+Pro) – does not look *that* similar, but would be a nice match with Source Sans Pro for body copy

**Comment by garvinhicking** [comment]
Vollkorn looks good to me

**Comment by donchambers** [comment]
Take a look at Arimo:  http://www.google.com/fonts/specimen/Arimo.  Love the simplicity.  Very clean to me.

**Comment by yellowled** [comment]
Arimo seems a bit small at 1em.

I'd rather check out various body copy fonts together with (probably) Vollkorn for headings once we have actual body copy. :)

**Comment by donchambers** [comment]
Am I missing something here?  doesn't 1 em in font A = 1 em in font B?  :)

**Comment by yellowled** [comment]
Doesn't even have to be 1em, could be 100%, 1rem or 16px - some fonts just “look bigger” than others, even if their `font-size` is technically the same.

**Comment by onli** [comment]
> Vollkorn – @onli mentioned that, and I misunderstood that he meant for body copy; it would probably work for headings, but not for body copy

You understood me correctly - I meant for body text, and still think that Vollkorn would be a valid choice for that. It is not only advertised as such, is also works well in such sizes for my eyes.

There are other good choices of course too, and it would be a valid header font as well.

**Comment by yellowled** [comment]
Vollkorn with 400/700 and italics for both gives us a page load impact of 124, which is in the yellow. Even for example Source Sans Pro combined with just bold Vollkorn for headings has less page load impact than that.

Yes, those are cached, but I don't think that many users will already have Vollkorn in their browser cache. It's not that widely used. Also, a sans-serif font for body copy is usually nicer to read on displays than a serif font.

**Comment by yellowled** [comment]
Found some time for a first assessment:

* The header/logo SVG export is weird (lots of layers), but I think we can get a decent SVG version of the logo out of it, which is basically all we need.
* The header/logo PSD is also technically large enough to generate bitmap versions of the logo even in HDPI if the SVG falls through. It's not layered, so we'd need to crop the logo out of the rest, but that's doable. (I would prefer a SVG version, though.)
* I think Vollkorn Bold is a viable free replacement for Schneidler Black for headings. I don't think it will work well for body copy, though.
* I think we should look for a body copy font once we have actual content and a basic design to work with.

**Comment by donchambers** [comment]
Here is a little font comparison:  http://www.optional-necessity.com/demo/cleanblog/fonttest/index.html

I think the attraction to Vollkorn is that it looks a lot like the serendipity logo.  I don't personally care much for it.  Looks old, dated.  I would much rather convey a new, fresh impression for serendipity.  For headings, my personal preference is Source Serif Pro.  For body, Arimo.  Not only is it not small, it is actually the second largest (behind Source Serif Pro).

**Comment by yellowled** [comment]
> I think the attraction to Vollkorn is that it looks a lot like the serendipity logo.

That is the point of choosing it for headings. It is *supposed* to look like the old logo without having to use text in an image for the logo. I'm not too keen on keeping the old look either, but @garvinhicking was pretty determined to keep it.

None of these would be my first choice for body copy.

**Comment by garvinhicking** [comment]
I'm not really a font guy, so I can't really comment. I'm open to anything regarding copy and headline fonts. I just want the serendipity-logo font to remain a bit like this; all other headlines I don't mind as long as it can be read ;)

I personally think we do not need to use the same font for headlines and the logo; many corporations have a different font in their logo than they use for headings; often the font in a logo is unique.

**Comment by yellowled** [comment]
Well, the question is do we really want to commit to the logo being a combination of that particular font and the flower thingy? If so, we can just have both on transparent background. That way, we would not need a replacement for Schneidler Black (which has a vague license at best) as a web font. However, it *is* less flexible.

**Comment by yellowled** [comment]
I just spent about an hour trying to get a decent SVG version of *just* the flower thingy out of the SVG in additional_plugins/homepage/source – I can't do it. This is still not a “true” SVG, although Illustrator did a pretty good job at exporting it, but for instance the gradients below the actual shapes of the flower are still images embedded in SVG, which is unnecessary since SVG can do native gradients.

I assume that all this is due to the age of the logo. As SVG became a more important and a viable option for image on the web, our standards that we hold SVG images to have evolved. The logo was probably created in an older version of Illustrator, so we probably will not get a “true” SVG file out of the AI source files that we have. I might be wrong, I'm far from being a vector graphics expert. Might as well be that Sketch can't handle Illustrator exports well, but I don't *have* Illustrator because I usually don't need it.

I see three options for the flower logo:

* Go with the PSD version, crop the flower out of it and use it as PNG with a HDPI PNG for retina displays. I think I can create the PNG files from the PSD that we have.
* Contact Martin Jacobsen and see if he would be willing/able to provide us a “true” SVG version of the logo, including native SVG gradients.
* Let someone else have a go at the SVG or AI version that we have, preferably in Illustrator, and see if they can “extract” the logo as “true” SVG.

**Comment by ophian** [comment]
Am 11.03.2015 um 11:44 schrieb Matthias Mees:
> * Go with the PSD version, crop the flower out of it and use it as PNG with a HDPI PNG for retina displays. I think I can create the PNG files from the PSD that we have.

I did that once for the sidebar, thought its probably not a HDPI, maybe 
we can use this a while...
https://github.com/ophian/Sliver/blob/master/sliver/img/s9y_banner_small.png

**Comment by yellowled** [comment]
That's a wee bit small for what I have in mind. :)

I assume we're going to need it at least 600px wide. I got it, though. Already cropped it out of the PSD in additional_plugin, will commit that as PNGs along with a first design draft next week (on vacation now).

**Comment by garvinhicking** [comment]
Just a small note: The .ai file can be opened in the most recent 
Illustrator without problems... all lines, gradients etc. are editable 
and show up properly.

I can thus export the .ai in any PNG resolution you would like.

(The .svg and new .png files were already exported using Illustrator of 
a friend)

**Comment by yellowled** [comment]
I think we're good. The logo extracted from the PSD is about 1000x500, that should be enough. Good to know, though.
