### ISSUE TITLE
entry title not escaped in dashboard

### ISSUE THREAD

**Issue by donchambers** [s9y/Serendipity#322]
I'm having github (windows) issues and cannot commit this myself.

Entry title is not escaped in the backend dashboard.  Interestingly enough, the title is escaped.  I noticed it for a test entry that included "&lt;pre&gt;" in the title

../2k11/admin/overview.inc.tpl, line 79

**Comment by ophian** [comment]
@yellowled Did you check it isn't already escaped in php before getting assined?

**Comment by yellowled** [comment]
I would not even know how to do that, so no.

**Comment by ophian** [comment]
Better always check this up before having a possible double escapement. In this case your commit is alright, since it seems to be a plain entries database fetched array value.
