### ISSUE TITLE
fallback to default - file references cleanup dor 2.0

### ISSUE THREAD

**Issue by ophian** [s9y/Serendipity#323]
When doing this commit 18bdf03623913815902b0d18d23462f006819f5a, I recognized there are references in some default admin files, which not really respond to a current 2.0 install and will possibly error by js or something.
We should take care of them and/or the admin directory in whole.
In which case does it ever fall back to default admin and or default frontend?

I assume this will not stop a 2.0.1, but may be something for 2.0.2.

**Comment by garvinhicking** [comment]
Not sure what you mean. Can you give an example?

**Comment by ophian** [comment]
just as simple as `<script src="{serendipity_getFile file='admin/header_spawn.js'}"></script>` in media_choose, etc. I did check any further and we should check this carefully.
And better know if which case default/admin ist still a valid usecase with 2.0ups.

**Comment by garvinhicking** [comment]
OK, I see. @onli  - do you know if those <script...> things in the media library are still utilized?!

**Comment by onli** [comment]
I don't think so, everything was moved. I wouldn't remove them without testing though.

**Comment by yellowled** [comment]
Xmas issue cleanup – this issue has been open, but without interaction for a while now. Is it still an issue? Has anyone tested or reproduced it? Should/can we close it?

**Comment by onli** [comment]
I think we can close this.

**Comment by ophian** [comment]
Is this a closing by "Putzfimmel" or did you check this carefully?

**Comment by onli** [comment]
More of that:

 1. this is no actual bug report. I want to see something that is broken, so it can be fixed. 
 2. No movement in almost a year -> there is no pressing problem
 3. I prepare the 2.1 release and am going through the issues for that

**Comment by yellowled** [comment]
To be fair, the sheer number of issue comments made by you over the past 24 hours make it seem a bit like a closing-issues frenzy. ;)

> I want to see something that is broken, so it can be fixed

I second going with that as a means of distinguishing GitHub issues from board topics.

> it isa lso no clear feature request

No comprende, señor. (Let's avoid “feature request”, a GitHub issue does not necessarily request a *new* feature, which I feel “feature request” kind of implies.)

**Comment by onli** [comment]
> To be fair, the sheer number of issue comments made by you over the past 24 hours make it seem a bit like a closing-issues frenzy. ;)

I can see that :) I think I'm done now anyway.

> it isa lso no clear feature request

it is also no clear feature request – wanted to say that it is neither a clear (feature) request nor a clear bug report and thus something I felt confident closing.
