### ISSUE TITLE
Dashboard comment entry link does not work

### ISSUE THREAD

**Issue by garvinhicking** [s9y/Serendipity#324]
Refers to {$comment.entrylink} but this array index does not exist; so the link is always an empty href.

We'll need to make the array passed to overview.inc.tpl have said link.

**Comment by ophian** [comment]
What do you mean? John Doe's personal blog in #3? My 2.1-alpha (not currently up to date) has a valid link in #3.
Build here https://github.com/s9y/Serendipity/blob/master/include/admin/overview.inc.php#L60

**Comment by yellowled** [comment]
> What do you mean?

The “Answer to comment” button does not work. (I'm kind of flabbergasted we never noticed that. Then again, I never use that button myself.)

**Comment by ophian** [comment]
It does work.You just need to click twice. :)

**Comment by yellowled** [comment]
Oh. Okay. (But only the first time. Odd.)

Then I have no idea.

**Comment by garvinhicking** [comment]
The problem for the missing entrylink was I only had one comment, and then the mentioned code in PHP did not work (it checks for > 1). I modified that to check for > 0.
