### ISSUE TITLE
Smarty compiler fails for shared installations

### ISSUE THREAD

**Issue by fugue88** [s9y/Serendipity#328]
For shared installations, the installer and upgrader calculate the compile directory "templates_c" according to installation type.  See include/admin/installer.php line 247, concat'ing $basedir and PATH_SMARTY_COMPILE, where $basedir is set at lines 20-27 according to installation type.

However, after the initial installer screen, Smarty is configured according to include/serendipity_smarty_class.inc.php line 149, referencing $serendipity['serendipityPath'] regardless of installation type.

This causes the first installation screen to report that, for example, /var/www/localhost/htdocs/templates_c is writable, but then the very next screen to fail to write a compiled template to (/usr/share/serendipity-2.0.1/s9y/templates_c/99/62/dd/9962dd610dddf45afcd41bd3b167a9743bd4e80e.file.guess_input.tpl.php.

**Comment by fugue88** [comment]
Here's a patch that at least gets me to the second screen of the installer:

```
=== modified file 'include/serendipity_smarty_class.inc.php'
--- old/include/serendipity_smarty_class.inc.php	2015-03-16 15:31:25 +0000
+++ new/include/serendipity_smarty_class.inc.php	2015-03-16 15:41:56 +0000
@@ -146,7 +146,11 @@
 
         $this->setTemplateDir($template_dirs);
 
-        $this->setCompileDir($serendipity['serendipityPath'] . PATH_SMARTY_COMPILE);
+        if (defined('S9Y_DATA_PATH')) {
+                $this->setCompileDir(S9Y_DATA_PATH . PATH_SMARTY_COMPILE);
+        } else {
+                $this->setCompileDir($serendipity['serendipityPath'] . PATH_SMARTY_COMPILE);
+        }
 
         $this->setConfigDir(array(S9Y_TEMPLATE_USERDEFAULT));
 

```

**Comment by garvinhicking** [comment]
Oh thanks for reporting!

The proper path to store templates_c should IMO be in each "deployed" directory, not the central one, readng your patch this should be the case, right?

**Comment by fugue88** [comment]
On Mon, 16 Mar 2015, Garvin Hicking wrote:

> Oh thanks for reporting!
> 
> The proper path to store templates_c should IMO be in each "deployed"
> directory, not the central one, readng your patch this should be the case,
> right?

Yes, that's what I'm trying to achieve with that patch.

Thanks,
David

**Comment by garvinhicking** [comment]
I committed your patch to 2.0.2 and 2.1.0 branches; please let me know if you face further issues, thanks a lot. I've closed it for now, feel free to reopen if you face followup issues
