### ISSUE TITLE
Change themes in additional_themes config array using "title" to "name"

### ISSUE THREAD

**Issue by donchambers** [s9y/Serendipity#329]
Forum reference: http://board.s9y.org/viewtopic.php?f=11&t=20298
Previous issue: https://github.com/s9y/Serendipity/issues/320

I know most, maybe even all, of these themes are old and probably unused.  But something doesn't sit well with me knowing we are offering themes to the end user that will simply not display their template option names correctly on the backend.  I think everything should show the correct syntax, even if never used again.  :)

**Comment by yellowled** [comment]
I can do this, but I'm not a 100% sure what to replace – **every** instance of `'title'` in a `config.inc.php` or just *some*?

**Comment by yellowled** [comment]
Should be done with [additional_plugins/8c2a4a](https://github.com/s9y/additional_themes/commit/8c2a4a56050b939ae07905b17048e63175e1e10a).
