### ISSUE TITLE
2k11 - reflows due to overridden image dimensions

### ISSUE THREAD

**Issue by gnuheidix** [s9y/Serendipity#330]
I noticed that a lot of reflows had happened especially on my image heavy page http://gnuheidix.de/pages/bilder.html during page load on a slow connection. (text and page length jumps around during image retrieval)

The image dimensions on my blog are set properly as HTML attributes width and height by s9y image chooser and my external script magic.
I fixed the issue by removing img{height:auto;} from CSS. The browser now honors the image dimension set by the system, the layout is finished very early in the rendering process and stays fixed while images are being painted in.

I'm not a CSS nut and I don't know if this change is applicable to s9y in general due to the huge amount of plugins which could break. That's why I'm not sending a pull request for this. Could you please check if this performance improvement can be applied to the codebase?

**Comment by yellowled** [comment]
The `img { height: auto; } ` is part of a CSS trick to make images responsive. It makes sure that these images keep the correct aspect ratio, no matter if the `width` and `height` atrributes are kept in place or not. Granted, it is not the ideal solution for responsive image, but

* it was the only one available back in the day when 2k11 was first developed
* it still is the only one that works without any additional work necessary from blog users

I can see why this does cause performance problems on that particular page of your blog, especially with a slow connection – indeed, this CSS does trigger a reflow, and 259 images on a single page are simply a bit much. For a page with this many images, I would usually recommend adding a lazyloading script or (easier said then done, I know) not having that many `<img>` elements on a single page.

Anyway, I don't think this is applicable to s9y/2k11 in general. (It is, however, good to know that we actually have users who care about this stuff.)
