### ISSUE TITLE
Replace equal heights solution with flexbox

### ISSUE THREAD

**Issue by yellowled** [s9y/Serendipity#333]
As proposed in #332, the current equal heights solution is not always ideal since it applies the same `min-height` to a group of elements. A better solution would be to only apply equal heights to elements in the same row of said group of elements, i.e. element sitting next to each other.

This is possible (for [browsers supporting it](http://caniuse.com/#feat=flexbox) at least) with `flexbox` (see [demo](http://codepen.io/imohkay/pen/gpard)). Since there is no `flexbox` polyfill, this needs a fallback for IE < 10 which can basically be the current layout without the equal heights script. Modernizrs `flexbox` support detection should be used since it's not limited to IE < 10.

Also related: #73

**Comment by onli** [comment]
@yellowled Given the milestone I'd like to ping you here. Do you still want this for 2.1, or do you postpone pr drop this?

**Comment by yellowled** [comment]
I *can* do this for 2.1 if I get the time to implement and test it properly. But I don't think it should be a release blocker. So if 2.1 is rather close, I'd postpone it to 2.2.

**Comment by onli** [comment]
Okay. I'll just treat is as a non-blocker and we see again what is the state of this when the other issues are done.

**Comment by yellowled** [comment]
For future references, here's where this applies/is used:

- [ ] themes (`templates/2k11/admin/templates.inc.tpl`)
- [ ] plugins (for the left/hidden/right containers) (`templates/2k11/admin/show_plugins.fnc.tpl`)
- [ ] installable plugins (`templates/2k11/admin/plugins.inc.tpl`)
- [ ] dashboard (`templates/2k11/admin/overview.inc.tpl`)
- [ ] media database (`templates/2k11/admin/media_items.tpl`)
- [ ] maintenance (`templates/2k11/admin/maintenance.inc.tpl` and `plugins/serendipity_event_entryproperties/serendipity_event_entryproperties.php`)
- [ ] static pages (`serendipity_event_staticpage/backend_templates/default_staticpage_backend.tpl`)
- [ ] admin notes dashboard widget (`serendipity_event_adminnotes/serendipity_event_adminnotes.php`)
- [ ] link trimmer dashboard widget (`serendipity_event_linktrimmer/plugin_linktrimmer.tpl`)

**Comment by yellowled** [comment]
- [ ] “embedded” media db (i.e. in the entry editor)
- [ ] **Safari/Mac:** height of empty plugin containers

**Comment by yellowled** [comment]
For further reference (since I can't do IE testing at the moment): pretty sure [flex-basis doesn't account for box-sizing:border-box](https://github.com/philipwalton/flexbugs#7-flex-basis-doesnt-account-for-box-sizingborder-box) is an issue for us in IE11.

**Comment by yellowled** [comment]
This should be done, but it probably needs more testing. It would be great if someone could test this on a (current) Android tablet (I don't have access to one), but it should work there.

@garvinhicking @onli I hope it's okay that I just merged this without letting anyone but me test it first. I don't think this requires another beta *version*, but it would be good if 2.1 wasn't released on Monday. :)

Closing since it's done in my opinion. Please re-open or open seperate issues for bugs with this.
