### ISSUE TITLE
Backend JS is not working in LITE packages

### ISSUE THREAD

**Issue by yellowled** [s9y/Serendipity#334]
Related forum thread: http://board.s9y.org/viewtopic.php?p=10441561

**TL;DR:** The LITE packages are missing the bundled jQuery in `/templates/`, which leads to (most of) the backend JS not working.

I assume this is an error in the process/script generating the LITE packages (which is why I assigned it to @garvinhicking). Seems like when cleaning out themes from `/templates/` to save space, jQuery is removed as well. For all I know, this might have been for even longer, it just wasn't an issue before 2.0.

**Comment by yellowled** [comment]
Another option would of course be to drop the LITE packages altogther (while we're cleaning up the whole s9y project).

**Comment by onli** [comment]
We really should drop the lite package or fix the bug, if that isn't already done?

**Comment by yellowled** [comment]
I don't know if this is fixed. @garvinhicking?

**Comment by ophian** [comment]
Fixed by dropping the LITE package at all.
