### ISSUE TITLE
Concatenation of body and extended body breaks Markdown compilation

### ISSUE THREAD

**Issue by mattsches** [s9y/Serendipity#335]
When generating a fulltext feed of the latest entries, correct Markdown compilation of the extended body might fail because `body` and `extended_body` are concatenated using a simple whitespace: https://github.com/s9y/Serendipity/blob/master/include/functions_rss.inc.php#L71
Markdown expects a newline.

Proposal: Change this line to
```
$entry['body'] .= "\r\n" . $entry['extended'];
```
However, this might affect other plugins such as Textile. The bug could also be fixed in the Markdown plugin, but that would be a little bit more complex.

**Comment by bauigel** [comment]
Yes, this happens with textile too. Should be fixed within s9y i think.

**Comment by garvinhicking** [comment]
I'm fine with changing it to a newline; shouldn't "\n" be sufficient though?

**Comment by mattsches** [comment]
You're right, that should be enough.

**Comment by garvinhicking** [comment]
Could you also backport to 2.0 branch?
