### ISSUE TITLE
Cache header for serendipity.js gets overwritten

### ISSUE THREAD

**Issue by onli** [s9y/Serendipity#337]
http://board.s9y.org/viewtopic.php?f=10&t=20328&sid=d1e6aca093ac79803c87b4fd388a0dad&p=10442627#p10442627

Seems like changes to the header set in this part of the index.php don't get applied.

**Comment by garvinhicking** [comment]
It could be that the HTTP/1.0 header that is set later on overwrites all previous headers, and they should be emitted AFTER the HTTP/1.0 200 OK header...?

**Comment by onli** [comment]
Maybe. But I can't reproduce the bug, for me that is working fine (with just a 0 appended to the 3600):

![js-cache-header_tiny](https://cloud.githubusercontent.com/assets/900380/6998012/0a203f06-dbd3-11e4-8848-c6cb8d1e24c6.png)

I'll ask in the thread for further info.

**Comment by onli** [comment]
Seems to be not a problem anymore.
