### ISSUE TITLE
Problem with pages

### ISSUE THREAD

**Issue by ddeimeke** [s9y/Serendipity#339]
Please check, the link "Nächste Seite" (next page) refers to the last page (same with tags):

http://www.deimeke.net/dirk/blog/index.php?/categories/12-internet
http://www.deimeke.net/dirk/blog/index.php?/categories/12-internet/P40.html

(Even though I think P40 is the correct 2nd page).

Comming from
http://www.deimeke.net/dirk/blog/index.php?/categories/12-internet/P40.html
previous page is
http://www.deimeke.net/dirk/blog/index.php?/categories/12-internet/P41.html
and next page is
http://www.deimeke.net/dirk/blog/index.php?/categories/12-internet/P39.html

Serendipity 2.1-alpha1 und PHP 5.4.16

**Comment by garvinhicking** [comment]
Seems like the "Stable archive sort" feature, isn't this what it's supposed to be?

**Comment by onli** [comment]
Yes, this seems to work exactly as it should.

**Comment by ddeimeke** [comment]
Ah, ok! I see.
