### ISSUE TITLE
thoughts about fallback chaining...

### ISSUE THREAD

**Issue by ophian** [s9y/Serendipity#343]
Plugins which use a template file to parse certain things for the frontend, in some cases also accessed for the backend, will use 
```php
$tfile    = serendipity_getTemplateFile($filename, 'serendipityPath');
```
which loops template fallback chaining as
```php
Array
(
    [0] => myTheme/
    [1] => default/
    [2] => 2k11/
)
```
Now, the foreach will return the first match, or return $filename,
Plugins normally all follow this principle
```php
        $filename = basename($filename);
        $tfile    = serendipity_getTemplateFile($filename, 'serendipityPath');
        if (!$tfile || $tfile == $filename) {
            $tfile = dirname($this->pluginFile) . '/' . $filename;
        }
```
We use serendipity_getTemplateFile for real template http path fallbacks & theme file fallbacks and for plugin template file fallbacks, which have slightly different premises. The latter assumes to look into [0] only and then fall back to the plugin delivered template file. This is what a plugin author can influence: "deliver the template or let a user theme overwrite this tpl".
This is why the `default/` theme only carried two plugin template files, based to the old standard of internal core plugins (categories and calendar). These two break with the simple assumed fallback principle, since it was the only real place to store the template files.

Nowadays "2k11" is the "Standard" theme, but also used as the new "default". While it was invented to be a "generic" theme, it includes some more plugin template files. But since it is in the chaining theme directory fallback, the upper principle (user theme/plugin dir) will not match any more. Or say, will break the simple principle, delivering "all" its plugin_*.tpls it has "inbetween".

For a plugin author this means to give up this $tfile get principle, if 2k11 (better say the "Standard" theme) already includes this template file, or use this default "plugin" tpl as the plugins "default" fallback file, including possible changes. This now happens to some plugins like staticpages or includeentry (staticblock) etc. 

We have gone a long way with this, since this already started with "Bulletproof", but it got used even more with "2k11". (_There have been always good reasons to follow this approach. Sure! I don't want to discuss that, in case someone feels being meant or hit._)

Did you follow so far and did you get my concerns?

The question is: _What to do now with this little "mess"_ in these cases. (I think there is a need to have a strict guideline to not mess it up even more.)

1. Always force users which use user themes to include their own copy? (_hard to anounce_)
2. Give up the principle for these plugins to check user theme/plugin dir in another way? (_if there is no other way to proceed?_)
3. Change serendipity_getTemplateFile() or 2k11 to not include these tpls. (_probably not feasible_)
4. Do what...? (_return to a simple approach? . make it even more complicated?_)
5. Did I forget anything?

@garvinhicking 

/..._sorry if that got too long... it helps me thinking!_ ;)

**Comment by onli** [comment]
1.     Array
         (
              [0] => myTheme/
              [1] => default/
              [2] => 2k11/
         )

 That'd be wrong. It should be:

      Array
      (
           [0] => myTheme/
           [1] => 2k11/
           [2] => default/
       )

 Is that really mixed up in s9y right now?

 2. I got that right? You observe that 2k11's tpls overwrite the plugin tpls. Your question is whether this is a problem?

**Comment by yellowled** [comment]
I'm not sure if I understand correctly what the problem is, but I think there's another option. I'm not sure if it is feasible or breaks backwards compatibility in an unacceptable way, but for what it's worth: if plugins would emit “proper” frontend code, themes would not have to override their templates. (I'll spare you the details of what “proper” would mean for the time being because I'm not sure if this actually makes sense.)

**Comment by ophian** [comment]
> Is that really mixed up in s9y right now?

Yes, thats what it says: (Its frontend accessment and you are right, it is set different by 2.0+ against prior versions, (_??? I'm not sure if really by accident, since it came in with the testing "idea" themes ???_), but it does not matter regarding my opening question, if we stick keeping the `$serendipity['defaultTemplate']` (MITM) here. The funny thing is that no one has ever recognized it...) https://github.com/s9y/Serendipity/blob/2.0/include/functions_config.inc.php#L295

1. $serendipity['template']
2. $serendipity['template_engine']s
3. default/
4. $serendipity['defaultTemplate']


For the second. It is a problem, since then (if it is of this sort) a plugin tpl change will need a 2k11 plugin_*.tpl change for a plugin update, or we'll have to announce this every time to use an overwriting user theme copy tpl. Both make things more complicated and messy and leave the simple approach idea. And since this is already in the wild, so we have to make the best out of it.

**Comment by onli** [comment]
> I'm not sure if really by accident, since it came in with the testing "idea" themes

That is probably just setting the engine to default and everything is fine.

>  It is a problem, since then (if it is of this sort) a plugin tpl change will need a 2k11 plugin_*.tpl change for a plugin update.

I don't think it's that bad. If I got that right, 2k11 is not covering all the plugin, only some with old and incompatible markup. If a plugin's tpl is updated, 2k11 could consider removing the custom tpl.

The template priority is important, so user can set their custom plugin template via their theme.

**Comment by yellowled** [comment]
> If I got that right, 2k11 is not covering all the plugin, only some with old and incompatible markup. 

Not counting calendar and categories, 2k11 includes 7 `.tpl` files for 5 plugins.

> If a plugin's tpl is updated, 2k11 could consider removing the custom tpl.

While outdated markup is probably the reason to use a custom `.tpl` in most cases, there's also cases where the theme simply needs very specific markup.

Also don't forget that this is not only about markup. A lot of plugins still emit inline CSS and inline JS, also a lot of them do way too much in terms of styling.

**Comment by garvinhicking** [comment]
I agree that it is a bit of a problem for maintaining, but we can't really deal with it otherwise. A template always needs to have priority of a plugin's look/template, because there's no other way a user could override the default template (patching the file in the plugin directory would overwrite the file on updates!).

I don't see a way to actually improve this handling. In our case we need to also update our core template's plugin .tpl files when plugins are updated with an important change, there's no way around that (apart from dropping a custom .tpl file if the plugin one's "good enough").

**Comment by ophian** [comment]
The problem is that current 2k11 and old bulletproof and "?" are themes and fallback (default) Standards at the same time. For all other Smarty template and other files this fallback line is perfectly OK and a wanted behaviour, but **not** intended for plugin template files, even if they tried to do their very best (for us all) at the time they were created. For some Plugins with Smarty frontend templates this isn't a problem, but for these few it is (on change!). I don't want to discuss why they are where they are...  it a problem of maintaining.

I suggest we could use a **new** serendipity_getPluginTemplateFile(...) method to look into $serendipity['template'] dir only and return $file(name) if empty, for all Plugins tpl files which also live in prior or current standard $serendipity['defaultTemplate'] themes.
This would be the easiest method to avoid conflicts and this maintaining "mess". We could also do this via a new parameter in the old method though.


Answer to other 
> That is probably just setting the engine to default and everything is fine.

No. Its like the array I posted. It is outside of fetched template engines.

**Comment by garvinhicking** [comment]
Ah, I see. You are recommending that the serendipity_getTemplateFile() method of plugins probably should ONLY accept the actual template directory, and NOT regard engine Templates?

We could add a fourth parameter to serendipity_getTemplateFile() like $prevent_engine_fallback = false that a plugin could set to true like you mention:

````
diff --git a/include/functions_config.inc.php b/include/functions_config.inc.php
index a279cd8..d3d4e77 100644
--- a/include/functions_config.inc.php
+++ b/include/functions_config.inc.php
@@ -255,9 +255,10 @@ function serendipity_set_user_var($name, $val, $authorid, $copy_to_s9y = true) {
  * @param   string      The filename to search for in the selected template
  * @param   string      The path selector that tells whether to return a HTTP or realpath
  * @param   bool        Enable to include frontend template fallback chaining (used for wysiwyg Editor custom config files)
+ * @param   bool        By default, also template "engine" directories are checked. Plugins might want to disable this.
  * @return  string      The full path+filename to the requested file
  */
-function serendipity_getTemplateFile($file, $key = 'serendipityHTTPPath', $force_frontend_fallback = false) {
+function serendipity_getTemplateFile($file, $key = 'serendipityHTTPPath', $force_frontend_fallback = false, $prevent_engine_fallback = false) {
     global $serendipity;
 
     $directories = array();
@@ -270,7 +271,7 @@ function serendipity_getTemplateFile($file, $key = 'serendipityHTTPPath', $force
             // If enabled, even when within the admin suite it will be possible to reference files that
             // reside within a frontend-only template directory.
             $directories[] = $serendipity['template'] . '/';
-            if (isset($serendipity['template_engine']) && $serendipity['template_engine'] != null) {
+            if (isset($serendipity['template_engine']) && $serendipity['template_engine'] != null && !$prevent_engine_fallback) {
                 $p = explode(',', $serendipity['template_engine']);
                 foreach($p AS $te) {
                     $directories[] = trim($te) . '/';
@@ -278,11 +279,13 @@ function serendipity_getTemplateFile($file, $key = 'serendipityHTTPPath', $force
             }
         }
 
-        $directories[] = $serendipity['defaultTemplate'] .'/';
-        $directories[] = 'default/';
+        if (!$prevent_engine_fallback) {
+            $directories[] = $serendipity['defaultTemplate'] .'/';
+            $directories[] = 'default/';
+        }    
     } else {
         $directories[] = isset($serendipity['template']) ? $serendipity['template'] . '/' : '';
-        if (isset($serendipity['template_engine']) && $serendipity['template_engine'] != null) {
+        if (isset($serendipity['template_engine']) && $serendipity['template_engine'] != null && !$prevent_engine_fallback) {
             $p = explode(',', $serendipity['template_engine']);
             foreach($p AS $te) {
                 $directories[] = trim($te) . '/';
@@ -292,8 +295,10 @@ function serendipity_getTemplateFile($file, $key = 'serendipityHTTPPath', $force
         // Frontend templates currently need to fall back to "default" (see "idea"), so that they get the
         // output they desire. If templates are based on 2k11, the need to set "Engine: 2k11" in their info.txt
         // file.
-        $directories[] = 'default/';
-        $directories[] = $serendipity['defaultTemplate'] .'/';
+        if (!$prevent_engine_fallback) {
+            $directories[] = 'default/';
+            $directories[] = $serendipity['defaultTemplate'] .'/';
+        }    
     }
 
     foreach ($directories as $directory) {
´´´´

We could add a second function like you propose, but that would feel too redundant for me... and we'd always need to remember both lookup methods then.

(This would apply to 2.1+, not 2.0.2 where that change would IMO be to dangerous)

**Comment by ophian** [comment]
That was my goal! ( i don't even think we would actually need this in the first backend fallback part.) Yes. :+1: 

> apply to 2.1+, not 2.0.2

Do you mean the change or the new method? I don't see a change to be dangerous. It is necessary! And any possible change would have to wait for that version to be out.
I'd also suggest to not name it `$prevent_engine_fallback = false` - than to name it `$prevent_fallback = false` or `$prevent_default_fallback = false`, since `engine` is not meant.

**Comment by onli** [comment]
But then users could no longer overwrite the plugin's tpl.

**Comment by ophian** [comment]
I assume you mean this line:
```diff
+        if (isset($serendipity['template_engine']) && $serendipity['template_engine'] != null && !$prevent_engine_fallback) {
```
Yes. Right, this should NOT be changed for the new parameter. Since then $serendipity['template'] is actually $serendipity['defaultTemplate'] and is not a "fallback" than a "theme". 
We only want to prevent the fallback for the Fallback for this Plugins cases.

**Comment by garvinhicking** [comment]
@ophian I don't understand your last comment. This if-structure only applies to "template_engine" parts, which is a directory where a plugin should NOT look inside, this seems right to me?!
About 2.1+: Plugins could use this already for compatibility to 2.1+, in 2.1- cases the fourth parameter would just be ignored. IMO it could easily break things we are not thinking about, so this is definitely something not going to 2.0. I don't see this as a bugfix, but a new feature, and our commit policy mentions new features to not occur in minor releases...

@onli Yes, plugins would need to support this new fourth parameter, but I don't see this being to hard to adapt to? What's the alternative, do you have anything in mind? I do agree with Ian that a .tpl file from the plugin itself should have precedence over a customized .tpl file of an engine/fallback-theme that is actually not really used on the site. We cannot distinct between calls to serendipity_getTemplateFile() coming from the core or from a plugin within the method currently, so we can't actually force this change to applie to plugin .tpl files without it affecting core calls to it.

**Comment by ophian** [comment]
I was answering to onlis one-liner. He added something afterwards.

To clarify this up: You suggest to do this:
```diff
         $directories[] = isset($serendipity['template']) ? $serendipity['template'] . '/' : '';
-        if (isset($serendipity['template_engine']) && $serendipity['template_engine'] != null) {
+        if (isset($serendipity['template_engine']) && $serendipity['template_engine'] != null && !$prevent_engine_fallback) {
             $p = explode(',', $serendipity['template_engine']);
             foreach($p AS $te) {
                 $directories[] = trim($te) . '/';
@@ -292,8 +295,10 @@ function serendipity_getTemplateFile($file, $key = 'serendipityHTTPPath', $force
         // Frontend templates currently need to fall back to "default" (see "idea"), so that they get the
         // output they desire. If templates are based on 2k11, the need to set "Engine: 2k11" in their info.txt
         // file.
-        $directories[] = 'default/';
-        $directories[] = $serendipity['defaultTemplate'] .'/';
+        if (!$prevent_engine_fallback) {
+            $directories[] = 'default/';
+            $directories[] = $serendipity['defaultTemplate'] .'/';
+        }    
     }
```
I suggest to use this only:
```diff
         $directories[] = isset($serendipity['template']) ? $serendipity['template'] . '/' : '';
         if (isset($serendipity['template_engine']) && $serendipity['template_engine'] != null) {
            $p = explode(',', $serendipity['template_engine']);
             foreach($p AS $te) {
                 $directories[] = trim($te) . '/';
@@ -292,8 +295,10 @@ function serendipity_getTemplateFile($file, $key = 'serendipityHTTPPath', $force
         // Frontend templates currently need to fall back to "default" (see "idea"), so that they get the
         // output they desire. If templates are based on 2k11, the need to set "Engine: 2k11" in their info.txt
         // file.
-        $directories[] = 'default/';
-        $directories[] = $serendipity['defaultTemplate'] .'/';
+        if (!$prevent_engine_fallback) {
+            $directories[] = 'default/';
+            $directories[] = $serendipity['defaultTemplate'] .'/';
+        }    
     }
```
since that "search for engines fallback part" would not need that exclude. Consider "Mytheme" with some very few files is a child of "2k11", which is its engine. Then you need this fallback even for Plugin template files.

btw, could you please describe, why you changed the order of `default` and `$serendipity['defaultTemplate']` when you comitted that "idea" test theme patch?

If added to 2.1 only - all Plugin changes with frontend tpl changes (in special staticpages) are on hold.

**Comment by garvinhicking** [comment]
@ophian Well, but this could happen in the backend section as well, we do have plugins that use custom .tpl files in the backend that could be part of a 2k11 backend directory at some point. Better to think of it now.

We changed "default" to be the first one because 2k11 uses .tpl files that only apply if the framework of 2k11 is used, but other plugins that depend on "bulletproof" (which always fell back to 'default') would then use outpot of 2k11 instead of "default". "default" is really the better fallback for better compatibility than 2k11, which opted for 2k11-styling and not globally working one. It provides new HTML structures that older themes are incompatible with, so they need to get that old HTML, not the new one.

This is something that would get fixed BTW with the new parameter, because then the default of a plugin would be it's own .tpl file and not the "old fallback" one.

I don't see that plugin changes with frontend tpl would need to be on hold. A plugin could make a version check on serendipity, and if it's 2.1- it would force its own .tpl file. We'd need that even if we port the fix to 2.0.2 to make the plugins work in other s9y versions properly as well.

**Comment by onli** [comment]
> What's the alternative, do you have anything in mind?

I just wouldn't do this. 

We are talking about .tpls in 2k11 and default, nothing more. 

 * *default:* plugin_calendar.tpl, plugin_categories.tpl
 * *2k11:* plugin_calendar.tpl, plugin_categories.tpl, plugin_commentsearch_searchresults.tpl, plugin_contactform.tpl, plugin_findmore.tpl, plugin_staticblock.tpl, plugin_staticpage_searchresults.tpl, plugin_staticpage_sidebar.tpl, plugin_staticpage.tpl

It seems wrong to me to add code into the core for those few files. We should update the tpls in the plugin to 2k11's version, remove them from 2k11, and then stick to the principle that a theme should bring their own tpl if it needs custom code.

**Comment by ophian** [comment]
> Well, but this could happen in the backend section as well, we do have plugins that use custom .tpl files in the backend that could be part of a 2k11 backend directory at some point. Better to think of it now.

I can't remember we already have that. Can you give me an example? Or tell me why and how a plugin would need that in the future? (Staticpages 'backend_templates' can't be meant IMHO. It is recognized different, and/or uses the 3rd parameter, AFAIR (in dev).) I tell you why I think this to be. I came to be working on event_includenentry plugin because of a bug. This has a frontend dependency tpl in 2k11, which is accesses in both: frontend and backend framework. In the backend accessment, it seemed to still run through the frontend part of the serendipity_getTemplateFile method. 

The new guideline with this new fourth parameter would be, to not use that much plugin tpls in future `$serendipity['defaultTemplate']` themes any more, if not in real need for the theme itself. If we have this situation, like in the current, the 4th parameter patch would help a lot.

Please forgive, your answer does not seem to answer my engine questions example, regarding the patch addition for engines too, does it.... ?

> A plugin could make a version check ... and ... force its own .tpl file.

That would mean to use 
```php
if (file_exists($serendipity['serendipityPath'] . $serendipity['templatePath'] . $serendipity['template'])) {
$file = ....
```
I wanted to avoid this as much as possible. This would mean to have three different kind of fallback procedures (Current, API, Workaroud).

> We changed "default" to be the first ...

Ok. I understand. Let me rethink. It is seen as a workaround for the bulletproof fallback to `default/` theme. And it is not bad for 2k11 itself, since 2k11 can be set as the User Theme `$serendipity['template']` or be a parent engine of a User Theme. Both being set before. In mean: "That patch _degrades_ 2k11`s hidden try to be the new "default/" theme back into line." :) But in case of another  "Example" Theme, the fallback does now follow the bulletproof workaround, doesn't it? Is that what we want(ed)? (Please, again: this is a seperate issue.)

**Comment by garvinhicking** [comment]
> I can't remember we already have that. Can you give me an example?

I can't, but to me it is a lot more logical to enforce a check for this 
in both frontend and admin cases, and I can only think it will help in 
the future. Which advantage would it have leaving the check out for the 
backend?

> Please forgive, your answer does not seem to answer my engine questions
> example, regarding the patch addition for engines too, does it.... ?

Sorry, I don't understand?

>     A plugin could make a version check ... and ... force its own .tpl file.
>
> That would mean to use
>
> if  (file_exists($serendipity['serendipityPath'].  $serendipity['templatePath'].  $serendipity['template'])) {
> $file  =  ....
>
> I wanted to avoid this as much as possible. This would mean to have
> three different kind of fallback procedures (Current, API, Workaroud).

Since we should always look out for good backwards compatibility, those 
1-2 lines shouldn't really hurt, if that ensures that a plugin works in 
many installations...

Now my problem is the concerns raised by onli I can understand, we might 
want to keep it "cleaner" and think about cleaning up our fallback theme 
.tpl files and let the plugin improve on it. Both ways to deal with this 
have advantages and disadvantages.

If we implement the new parameter we'll still have version forks in the 
plugins, bloating up code, so I do wonder if we don't make things more 
complicated, where instead we could just "clean up" at another place.

Do we have someone to weigh in on this to have a tipping point towards 
one solution? @yellowled?  :-)

> Ok. I understand. Let me rethink. It is seen as a workaround for the
> bulletproof fallback to |default/| theme. And it is not bad for 2k11
> itself, since 2k11 can be set as the User Theme
> |$serendipity['template']| or be a parent engine of a User Theme. Both
> being set before. In mean: "That patch /degrades/ 2k11`s hidden try to
> be the new "default/" theme back into line." :) But in case of another
> "Example" Theme, the fallback does now follow the bulletproof
> workaround, doesn't it? Is that what we want(ed)? (Please, again: this
> is a seperate issue.)

If a theme does not want the bulletproof/default fallback, it needs to 
put the proper .tpl file into its own directory or use the 2k11 engine 
(which should force a 2k11 template instead of bp/default)...?!

Regards,
Garvin

**Comment by ophian** [comment]
> If a theme does not want the bulletproof/default fallback, it needs to put the proper .tpl file into its own directory or use the 2k11 engine (which should force a 2k11 template instead of bp/default)...?!

Yes, in case of theme TPL files and that is what you patch comment says in functions_config.inc.

if you disable or have not set the plugin_contactform.tpl in "UserTheme" (with no engine set), you get `/templates/2k11/plugin_contactform.tpl` since the Frontend "fallback" currently is 
```php
FRONTEND:plugin_contactform.tpl:Array
(
    [0] => UserTheme/
    [1] => default/
    [2] => 2k11/
)
``` 
and this should be named the "default fallback" followed by "standard fallback". This template there naturally looks "ugly" since all styles and constants owned to 2k11 are missing.
Back to my origin question, this should not happen and only use the plugin based template file instead.

If set bulletproof as the USER theme you get from /templates/bulletproof/plugin_contactform.tpl
```php
FRONTEND:plugin_contactform.tpl:Array
(
    [0] => bulletproof/
    [1] => default/
    [2] => default/
    [3] => 2k11/
)
``` 
which is caused by Bulletproof already having set `Engine: default` and is part of the fallback line already ("Idea" does not, and follows fallback 1, 3 4)

1. $serendipity['template']
2. ($serendipity['template_engine']s)
3. default/
4. $serendipity['defaultTemplate']

About the "keep it cleaner" argue. This is a valid argument, but we already have the situation that this has been in the wild for years. So we can not control in what situation we get for upgraders. (How would you want to purge existing "theme based" plugin tpl files? No way to go, even if technically possible.) Also a strict setting like this new parameter, to avoid plugin templates fallbacks searching the wrong "default/standard" theme directories, would help to avoid this messing up again one day in future. At last there is the "valid" approach of a theme like 2k11 to decide its own needs for plugin based templates too at a certain development time, even if that may need an Announcement in case the origin plugin based tpl will change. 
My goal starting this all, was to only get rid of the "theme based fallback line" for plugin template files, for 3 and 4, somehow simple and quickly "ready to use". Engines "could" hook in - this would be a "feature" in this case. (_see answer at the bottom_)

> I can't, but to me it is a lot more logical to enforce a check for this in both frontend and admin cases, and I can only think it will help in the future. Which advantage would it have leaving the check out for the backend?

Hm..., avoid possible conflicts we can't think of yet. That is why I asked. 
It is of only real need in the frontend part, as far as I can overview this issue.


> Sorry, I don't understand?

You wanted to set 
```diff
-        if (isset($serendipity['template_engine']) && $serendipity['template_engine'] != null) {
+        if (isset($serendipity['template_engine']) && $serendipity['template_engine'] != null && !$prevent_engine_fallback) {
```
to prevent the plugin template file fallback for engine based plugins too, if true. 
I know this is a clean and strict approach, which would keep theme based templates files and plugin based template files in the theme strictly apart, fallbackwise. I asked, if this couldn't be an exceptional situation, where "UserTheme" with some very few files (eg just some css) is a child of "2k11", which is its parent engine (one could say: the UserTheme would still be "2k11" then...). Then you might need this fallback even for Plugin template files, since the "2k11" plugin_*.tpls are part of the themes "need". Its a question of "definition" and on which side we keep extending possibilities or simplicity. ;-)

**Comment by garvinhicking** [comment]
I think we should talk over this in a mumble meeting, it's hard for me to favor one or the other.

I'm dragging behind on the new s9y.org structure and documentation, can't find the willpower to work on this. We might need to also discuss how this can be progressed...

**Comment by ophian** [comment]
## Prelude

I found other issues within the fallback chaining, which made me rethink this getTemplateFile() function again. I think it is **not** working as it should, doing complicated thinks to prevent issues which should not exist, etc. We have been just lucky until now that this did not fall back on us, since the usage to make use of these concepts is luckily not wide spread until now.
Let me try to simplify it. 

## Conception Thoughts

The function `getTemplateFile()` has to become much more clear (simple) in general. 
It is (almost) **always** the case that the fallback line is, or better say **has to be**:

* A. array[0] User template = `$serendipity['template']`
* B. array[1] "Engine" template = the frontend themes fallback engine info.txt value Engine: XXXX, which is `$serendipity['template_engine']`
* C. array[2] Standard default template = `$serendipity['defaultTemplate']`
* D. array[3] `'/default'` template dir, which is a real fallback

We just have two general Exceptions:

1. This is for the chosen backend Template, which per default is set to `Backend: 2k11`, or may be another selected theme with its own backend. Having 2 subs with:

  1.1. A forced fallback for custom additions to the backend in (1) without a real backend (like for the custom cke js files).
  1.2. A possible Backend "engine" concept, analog or near to the frontend engine concept. (Example: just use a (or some) backend ~~`admin/user.css`~~ file(s) without all the other backend files. [_Striked out since the admin/user.css already has an exception._])

2. The already here discussed Plugins usage of `getTemplateFile()`, to only check for `A` and `B`, which are `array[0]` and a "possible" engine in `array[1]` and return straight to the plugin template file usage.

For the second (2), that would mean to generally set `B` to `A` by default, when not overwritten by `$serendipity['template_engine']` from info.txt. 
For the first (1), we just need to check for `defined('IN_serendipity_admin') && $serendipity['smarty_preview'] == false` and `$serendipity['template_backend']`, which is what we already do.
For the sub first (1.1) this is by the third parameter `$force_frontend_fallback`.
For the second sub (1.2) we would need to think of using the third param too, or have another concept.

To now simplify this; Our general fallback order **is wrong** and **should be** by example:

2k11 as the users (Parent) template
```
$serendipity['template']: 2k11
$serendipity['template_engine']: 2k11
$serendipity['defaultTemplate']: 2k11
fallback: default 
```
or an independent (Parent) template
``` 
$serendipity['template']: testX
$serendipity['template_engine']: testX
$serendipity['defaultTemplate']: 2k11
fallback: default
```
or an engine Child template
```
$serendipity['template']: photo
$serendipity['template_engine']: 2k11
$serendipity['defaultTemplate']: 2k11
fallback: default
```
In short:

Array Chaining Ex 1 | Array Chaining Ex 2 | Array Chaining Ex 3 | 
------------ | ------------- | -------------
2k11, 2k11, 2k11, default  | testX, testX, 2k11, default | photo, 2k11, 2k11, default

The sub cases (1.1) and (1.2) are handled within (1).

Have a break!
Did I oversee or forget something? (_Before writing this, I thought it could be as simple as the famous "Bierdeckel"_ ;-) )

## Current situation

At the moment we have always this situation in the backend 

#### TEST CASE User theme is `testX` and backend is `2k11`:

BGTFRP1 = Array Output of: BackendGetTemplateFileRunPartOne
(Remember, the array does not show **what** was found, than only **where** to look for.)
Output by `echo $file` with `print($directories)` in getTemplateFile().
FFF: = echo $file in $force_frontend_fallback { }

#### Before header
```
FFF: admin/ckeditor_custom_plugin.js

BGTFRP1: admin/ckeditor_custom_plugin.js
Array
(
    [0] => 2k11/
    [1] => testX/
    [2] => 2k11/
    [3] => default/
)

FFF: admin/ckeditor_custom_config.js

BGTFRP1: admin/ckeditor_custom_config.js
Array
(
    [0] => 2k11/
    [1] => testX/
    [2] => 2k11/
    [3] => default/
)

FFF: 

BGTFRP1: admin/index.tpl
Array
(
    [0] => 2k11/
    [1] => 2k11/
    [2] => default/
)
```

#### In the header

```
FFF: 

BGTFRP1: jquery_backend.js
Array
(
    [0] => 2k11/
    [1] => 2k11/
    [2] => default/
)
etc [pp = modernizr a.s.o.]
```

#### Beneath header in the content part

```
FFF: 

BGTFRP1: admin/entries.tpl
Array
(
    [0] => 2k11/
    [1] => 2k11/
    [2] => default/
)

FFF: 

BGTFRP1: /full/path/to/templates/2k11/admin/entries.tpl
Array
(
    [0] => 2k11/
    [1] => 2k11/
    [2] => default/
)

FFF: 

BGTFRP1: admin/entries.inc.tpl
Array
(
    [0] => 2k11/
    [1] => 2k11/
    [2] => default/
)
```

#### In the posted entry saving message iframe ["framed run"]

```
FFF: admin/ckeditor_custom_plugin.js

BGTFRP1: admin/ckeditor_custom_plugin.js
Array
(
    [0] => 2k11/
    [1] => testX/
    [2] => 2k11/
    [3] => default/
)

FFF: admin/ckeditor_custom_config.js

BGTFRP1: admin/ckeditor_custom_config.js
Array
(
    [0] => 2k11/
    [1] => testX/
    [2] => 2k11/
    [3] => default/
)

FFF: preview_iframe.tpl

BGTFRP1: preview_iframe.tpl
Array
(
    [0] => 2k11/
    [1] => testX/
    [2] => 2k11/
    [3] => default/
)

FFF: 

BGTFRP1: jquery_backend.js
Array
(
    [0] => 2k11/
    [1] => 2k11/
    [2] => default/
)

FFF: emoticons.inc.php

BGTFRP1: emoticons.inc.php
Array
(
    [0] => 2k11/
    [1] => testX/
    [2] => 2k11/
    [3] => default/
)

FFF: img/emoticons/cry.png

BGTFRP1: img/emoticons/cry.png
Array
(
    [0] => 2k11/
    [1] => testX/
    [2] => 2k11/
    [3] => default/
)

FFF: img/emoticons/smile.png

BGTFRP1: img/emoticons/smile.png
Array
(
    [0] => 2k11/
    [1] => testX/
    [2] => 2k11/
    [3] => default/
)

etc [pp]
```

Which is wrong in several (I'd say all) cases! I does work, since for some files, as you can see in the "framed run" for example, the array[0] '2k11' is luckily empty, so it actually finds the next occurence in the user template. 

One of the issues which led to this written behaviour, was the `preview_iframe.tpl` file. It think it was suggested to be mainly the file markup from the `$serendipity['template_backend']` dir, to have the "style" appear styled (height, etc pp, and script indexdDB etc). After that the question of this frames `$serendipity['template']` styles and user styles came up, and so on, making us all a little dizzy.
When playing around i wondered (again), why the preview file did not be the `testX` preview_iframe file (see below) and was missing some certain styles for the green icon-ok-circled message. There my "odyssey" began, leading to this far too long documentary of chaining thoughts. (_Sorry guys!_)

(I reverted the preview_iframe file define in `serendipity_smarty_show()` with `$tplfile = ($template == 'preview_iframe.tpl') ? serendipity_getTemplateFile($template, 'serendipityPath', true) : serendipity_getTemplateFile($template, 'serendipityPath');` testwise.)

I did not touch in here the ("wrong"?) order thing we have with 
````php
        $directories[] = $serendipity['defaultTemplate'] .'/';
        $directories[] = 'default/';
````
which also was started getting discussed on top somewhere before (see Garvins answer commented on 27 May).

## Suggestion

Order by  `$serendipity['template']`, `$serendipity['template_engine']`, `$serendipity['defaultTemplate']`, `'/default'` template fallback (and make any Exceptions later, replacing the keys values, for example).

```php
.... {}
```

I need a break here..!

Now: Does this all picture the CURRENT and the GOAL, to get this finally sorted out?

**Comment by ophian** [comment]
I have some plugin updates ready for these changes, for the time being.
