### ISSUE TITLE
Update from 1.7.8 to 2.0.1 changed database host

### ISSUE THREAD

**Issue by DerNamenlose** [s9y/Serendipity#344]
I just updated my S9Y installation from 1.7.8 to 2.0.1 according to the documentation. Everything went smoothly, the update page came up, had no complaints, did it's thing and my blog greeted me with "Unable to connect to database". Turns out, that the update process had changed the $serendipity['dbHost'] entry in serendipity_config_local.inc.php from '192.168.16.5' to 'localhost'. As my database resides on another host, this obviously breaks access. Manually changing it back brings everything back to working order.

**Comment by garvinhicking** [comment]
Could it be that you changed dbHost in the serendipity_config_local.inc.php file manually at some point, not through the s9y backend?

I guess taht in your serendpity_config DB table the "old" value of "localhost" still stood there, and this was used when the upgrader rebuild the local config file. There should be no other case that s9y changes a config value, it uses the master value specified in the database...

**Comment by onli** [comment]
@garvinhicking Do you see a way to not regenerate the file? I realize we do that to set the new version, but couldn't we use the values set in the file instead looking into the database for the other fields?

**Comment by DerNamenlose** [comment]
Yes, I did indeed. AFAIK once I changed the database to another host, I couldn't reach it anymore to set the config in the backend. After changing the config file and getting everything working again, I simply forgot about it.

Now that you reminded me of that, I looked at the backend and lo and behold! there's the localhost in there. Now I did try to change this, but even though it claims success in the configuration interface, it just shows localhost as the configured database again (although the database access itself does work, so obviously it doesn't touch the config file). Should I open a new bug for this?

**Comment by onli** [comment]
> Now I did try to change this, but even though it claims success in the configuration interface, it just shows localhost as the configured database again 

That seems a bit buggy, and I can see that here as well. After saving, did you reload the page? Then the display host changed for me.

**Comment by yellowled** [comment]
Some weird browser form autofill FU maybe?

**Comment by DerNamenlose** [comment]
No, tried it with a clean browser, which has never seen that blog even from afar. Same thing.
