### ISSUE TITLE
Speedup s9y by using a cache

### ISSUE THREAD

**Issue by onli** [s9y/Serendipity#345]
See the [forum-thread](http://board.s9y.org/viewtopic.php?f=11&p=10443063&sid=610c75731adf30ecb844d04f5fa0d8fb#p10443063).

**Comment by onli** [comment]
Please test the cache by setting [$use_internal_cache](https://github.com/s9y/Serendipity/blob/0125f1539e4305d6ee0de0368672a49f40f9b3ac/serendipity_config.inc.php#L454) to true.

**Comment by garvinhicking** [comment]
Nice, I'm really excited about feedback for this. Could you also document this in docs/NEWS for testers?

**Comment by onli** [comment]
Sure, done

**Comment by onli** [comment]
@garvinhicking Based on positive first feedback, I'd like to add a real config option and then close here. Ok?

**Comment by garvinhicking** [comment]
Fine by me!
