### ISSUE TITLE
select theme - use as backend / frontend button issue

### ISSUE THREAD

**Issue by ophian** [s9y/Serendipity#347]
If a theme say "2kcopy" has a own backend, we have two buttons on the theme installer page: "Install: Frontend" and "Install Backend".
If you choose to use its backend first, you still have the option to set it also as the frontend.
But not vice versa.
If you install this theme as frontend first, you cannot set it to backend. 

This is a minor issue, but needs a solution I think.

**Comment by yellowled** [comment]
I think this does the trick, but maybe you guys should look it over because this feels as if it should have been way more complicated. :D

In terms of UI/UX: shouldn't the currently selected backend theme have a "Install: Frontend" button as well (if it is not already the selected frontend theme)?

**Comment by yellowled** [comment]
(That's also why I did not cherry-pick it to `2.0` yet.)

**Comment by ophian** [comment]
Seems OK for me.

> In terms of UI/UX: shouldn't the currently selected backend theme have a "Install: Frontend" button as well (if it is not already the selected frontend theme)?

I would say "No", since this fix only covers the "unusual" case of another backend theme being available and not already set. Its IMHO better to have the two upper current frontend and backend theme buttonless for the masses, except the frontend config button, if have. For me it is more clear to always search for a new frontend theme in the "Available themes" section - ever.

**Comment by yellowled** [comment]
> the "unusual" case of another backend theme being available and not already set

It also covers the “Hey, the theme you just chose has it's own backend which probably fits nicely with the frontend, you sure you want to keep the old one?” cases.

I'll give the other guys a day or two to chime in on this before I cherry-pick it to `2.0`
