### ISSUE TITLE
Clean up docs/*

### ISSUE THREAD

**Issue by yellowled** [s9y/Serendipity#348]
My inner Monk would like to clean up/reformat `docs/*`, especially `docs/NEWS`.

It shows that this file is now being edited by multiple people on a regular basis. Formatting is now always consistent, some release dates are missing etc. Since this is the most important docs file bundled with the core, I feel it should be nicely formatted. While I'm at it, I can do the same for the rest of them.

A few questions:

* Do these *have* to have the `#` at the beginning for some weird reason?
* Is there a specific reason to use 3 space for indentation here? We usually use 4.
* Do we have a policy as to when to move NEWS to NEWS_OLD? I think back to the last minor version (1.7.0 in this case) should be more than enough.
* Shouldn't `beta` in [RELEASE](https://github.com/s9y/Serendipity/blob/master/docs/RELEASE) be something different than 2.0.1?

**Comment by garvinhicking** [comment]
1.) No reason, I never noticed
2.) I manually indent with joe which doesn't display whitespace in my setup. We can use 4.
3.) No policy. I agree we can remove anything before 1.7.
4.) Not sure about that one, but I think only properly released releases are available, so 2.1 is not an option

**Comment by yellowled** [comment]
Thanks for the feedback. Here's another idea – we should change these to Markdown. That way, they can be displayed really nice on GitHub, but are still quite readable in terminals and text editors.

Anyone opposed?

**Comment by ophian** [comment]
Yes. I like it to be text only.

**Comment by yellowled** [comment]
Why?

**Comment by ophian** [comment]
We do not format such text, same as in changelogs. Why should we change this to Markdown?
Reading it on Github va web is just one possibility of many.

**Comment by yellowled** [comment]
Wow. My inner Monk was not aware *how* long `NEWS` and `NEWS_OLD` actually **are** …

Y'all can forget about me reformatting these to Markdown. Strike that. I never suggested it.

**Comment by yellowled** [comment]
Okay, I'm not going to reformat stuff that is going to be moved to `NEWS_OLD` soon anyway.

Everyone, in the future please make sure to

* use four spaces to indent this
* clip your lines at 72 characters

**Comment by ophian** [comment]
(2cts: Its not code, why should it rely on 4 spaces?)
Why did you remove linebreaks where they were set by purpose?

**Comment by yellowled** [comment]
> why should it rely on 4 spaces?

It's not about four spaces per se. It's about using one setting and sticking to it. There were far more instances of 4 spaces than 3 spaces, so less editing.

> Why did you remove linebreaks where they were set by purpose?

If I did, I did accidentally, probably because it wasn't clear that it was an itentional line break. I suggest to not use line breaks at all in the future. If something needs to be on a seperate line, use paragraphs. I feel that's more readable anyway.

If you want me to fix the intentional line breaks, please point them out. It would probably be quicker to just fix them yourselves, though.

**Comment by ophian** [comment]
Fixed accidently added 2.1 commits in 2.0 branch
