### ISSUE TITLE
chaining all the css into serendipity.css

### ISSUE THREAD

**Issue by ophian** [s9y/Serendipity#350]
There is another problem with these two issues (#343 and this #349) . They are somehow related to the thing mentioned here.

I am quite sure we all would say: The user.css should always be appended to the **very** end of the serendipity.css stream, to give support to change things after all data has been streamed into.
And **It actually is**, but if you append css data by plugin to the $eventData stream by `$eventData .= file_get_contents($tfile);` this is included beneath the user.css output.
One could say - don't do this then and stick to echo, which prepends it! But there is a problem if we need to access 
```php
                    if (strpos($eventData, $searchstring) !== false) {
                       // class exists in CSS by another Plugin, 
                       // or a user has customized it 
                       // and we don't need default
                       return;
                    }
```
in a plugin, to check for already existing stylesheet selectors.
And here is the issue:

1. If you **append** the css by `$eventData .=` it is found by strpos, when it exists, at the moment of check, but is added below the user.css stuff, which allows plugin css checks, but prevents user.css checks and can not be overwritten by the user.css itself easily.
2. If you **prepend** the css by `echo file_get_contents($tfile)` strpos does not work for this kind of css data at this moment, since serendipity.css eventData is currently templates/default/style_fallback.css templates/theme/style.css, the user.css and at last the prior in pluginList appended plugin css data only .

I got noted to this, when using staticpage sidebar dtree and linklist sidebar dtree, which both are to be prepended by echo. You can't check 
```php
                    $pos = strpos($eventData, $searchstr);
                    if ($pos === false) {

                        $tfile = serendipity_getTemplateFile($filename, 'serendipityPath');
                        if (!$tfile || $tfile == $filename) {
                            $tfile = dirname(__FILE__) . '/' . $filename;
                        }
                        echo file_get_contents($tfile);
                    }
```
then. And always get both dtree css files.

The question is, "what to do best"?! (I assume we can't have both.)

**Comment by yellowled** [comment]
> The user.css should always be appended to the very end of the serendipity.css stream, to give support to change things after all data has been streamed into.

Probably the only thing I can contribute to this: The `user.css` **has to** be appende to the very end of the generated CSS, otherwise it is (at least 50%) pointless because users will not be able to override plugin styles in the `user.css`. And those styles tend to be the ones that need to be overridden the most.

Yes, users *could* technically user `!important` and higher specifity through i.e. `id`s, but trust me when I say from all the experience I have with CSS: that will not work well, and it will be **very** challenging for even experienced users.

**Comment by garvinhicking** [comment]
I agree. I think we'll need to move this appending to $out below the hook_event call.

**Comment by ophian** [comment]
Yes, that is much better!

What do you think about (2) ? 
If we move the plugin css hook in front of all other `$out` includes, it does not care, if we use `echo` or `.=` in plugins and strpos() should work for all streamed css by time, naturally except user.css customized data. (Or has that got to do with the "output buffering"?)
Or should we better keep both, "prepend" and "append" plug-ins for certain "design" reasons? (That would need us to at least have a deep look into all plugins using this "check double load tweak".)

**Comment by garvinhicking** [comment]
I don't properly understand. I propose this:

```
diff --git a/serendipity.css.php b/serendipity.css.php
index a8f5f52..d1db826 100644
--- a/serendipity.css.php
+++ b/serendipity.css.php
@@ -85,13 +85,13 @@ $out .= serendipity_printStylesheet(
          serendipity_getTemplateFile($css_file, '')
 );
 
+serendipity_plugin_api::hook_event($css_hook, $out);
+
 $out .= serendipity_printStylesheet(
          serendipity_getTemplateFile($css_userfile, 'serendipityPath', true),
          serendipity_getTemplateFile($css_userfile, '', true)
 );
 
-serendipity_plugin_api::hook_event($css_hook, $out);
-
 echo $out;
 
 //
```

So just move the output of the event hook before the printStylesheet call to user.css. A plugin won't be able to check what is inside user.css, but it doesn't have to, the user.css will need to overwrite it on its own...

**Comment by ophian** [comment]
Yes. This is what I did too. But for (2) this still needs to use `$eventData .= ` which is appended to "end" for strpos() to work properly. This is a "design" question: `echo css` will be on top, `.= css`  near end. All css data echoed goes on top (afterwards). Where is the culprit of strpos not working there. Is it the buffer or the place of the hook?

**Comment by garvinhicking** [comment]
Everything passed on by echo will only be gathered later on by ob_get_contents and is not part of $eventData (it cannot be). So plugins would need to modify $eventData instead of echo CSS.

**Comment by ophian** [comment]
That is what I meant. So it is by design.
Do you want to commit the patch? And add the possible fallback chain of 2k11 to the user.css change note in NEWS?

**Comment by garvinhicking** [comment]
Just committed!
