### ISSUE TITLE
grablet issue with Chrome only

### ISSUE THREAD

**Issue by ophian** [s9y/Serendipity#351]
On my local dev setups with 2.1-dev (slightly different) I suddenly discovered the more current one to not display the pluginmanager_grablet button any more with latest Google Chrome Browser. I found the `<li> pluginmanager_place nojs-controls` active, which disables to display the button pluginmanager_grablet button and uses the fallback.
Before I grab deep into - to get an idea why this happens to Chrome only - let me please quickly ask if that is an issue happening to you too @yellowled ? Has anything changed which could influence this?

**Comment by yellowled** [comment]
* s9y `master` @ 64f32ef864157a4e90e8de96b8caac068e926975
* Google Chrome 43.0.2357.130 (64-bit) on OS X

Grablet is displayed with button, is draggable. Everything works fine.

I did, however, get a few template compilation errors after `git pull`ing and logging into the backend, but those went away as soon as I cleared the template cache. Does not seem to be a bug for me.

**Comment by ophian** [comment]
Thanks. I closed down and reopened Chrome and all was there again. Strange. I think I had played around with Chromes toogle device mode.

**Comment by yellowled** [comment]
> I think I had played around with Chromes toogle device mode.

I have experienced Chrome's device mode acting strange in recent versions. Rule of thumb: if something behaves strange while you're in device mode or having used device mode in that session in that tab, always hit reload first.

**Comment by ophian** [comment]
I did hard reload several times and even had started the browser again (I think). :)
