### ISSUE TITLE
uploadResize needs image check

### ISSUE THREAD

**Issue by ophian** [s9y/Serendipity#353]
and does not respect other object files to pass through!
See http://board.s9y.org/viewtopic.php?f=10&t=20437

**Comment by onli** [comment]
The problem seems to be that other files than images lead to a JS-error and can then not be uploaded.

**Comment by yellowled** [comment]
Xmas issue cleanup – this issue has been open, but without interaction for a while now. Is it still an issue? Has anyone tested or reproduced it? Should/can we close it?

**Comment by onli** [comment]
I work on it.
