### ISSUE TITLE
Atom feed futures and errors

### ISSUE THREAD

**Issue by ophian** [s9y/Serendipity#354]
We have an issue with the XML atom feed using and expecting XHTML, but getting delivered HTML5 simple single html tags, not closing with a xhtml slash, eg `<img >` vs `<img />`
We should either:

1. fix the atom encoding (was suggested, but seems not possible according to thread),
2. deliver xhtml style for all single tags (which might not be that easy to find them all),
3. or disable ATOM usage, which was designed when XHTML was expected to become Standard
4. fix and use xhtmlcleanup plugin for this

http://board.s9y.org/viewtopic.php?f=10&t=20429

What shall we do with it for 2.1.0 and/or 2.0.2?

**Comment by yellowled** [comment]
> single tags (which might not be that easy to find them all)

They are usually called self-closing tags, and they are:

* `<area />`
* `<br />`
* `<col />`
* `<embed />`
* `<hr />`
* `<img />`
* `<input />`
* `<keygen />`
* `<param />`
* `<source />`
* `<track />`
* `<wbr />`

That *should* be all of them. The following elements are self-closing as well, but should only be used in the `<head>` or are (`<command>`) deprecated. I think we can skip those.

* `<base />`
* `<command />`
* `<link />`
* `<meta />`

**Comment by yellowled** [comment]
I’m not saying this needs to be fixed for 2.0.2, but it is a bugfix, so it should be in a patch milestone/release.

**Comment by yellowled** [comment]
I don't think disabling Atom altogether is an option. That might break feed subscriptions.

**Comment by ophian** [comment]
I said "find", not "know" :)

**Comment by garvinhicking** [comment]
We have the xhtmlcleanup plugin to fix that? Putting it in the core is IMO not so good, just for the atom feed...?!

**Comment by yellowled** [comment]
> We have the xhtmlcleanup plugin to fix that?

If we expect people to have (and keep) that installed just for the atom feed, we might as well put it in the core.

**Comment by ophian** [comment]
> We have the xhtmlcleanup plugin to fix that?

Right, I added it to the list of possibilities.

**Comment by ophian** [comment]
Atom was always more error-prone than rss2. I simply did not use it any more for a longer time.
So I think the xhtmlcleanup plugin is way too much for this rare case and we might better go with onlis last suggestion for 2.0.1 and mark Atom as deprecated for 2.1.

**Comment by yellowled** [comment]
> go with onlis last suggestion for **2.0.2**

Fixed that for you. :)

**Comment by yellowled** [comment]
Xmas issue cleanup – this issue has been open, but without interaction for a while now. Is it still an issue? Has anyone tested or reproduced it? Should/can we close it?

**Comment by onli** [comment]
I'm not actually certain that the CDATA approach will lead to the html being rendered correctly in feed readers. But the current xhtml-approach is 100% wrong, so let's try it out and wait for feedback – but I'll close here for release management. Re-Open if issues arise.
