### ISSUE TITLE
set mysqli for upgraders

### ISSUE THREAD

**Issue by ophian** [s9y/Serendipity#355]
> For the 2.1 release we could add a upgrader routine to switch to mysqli automatically 

see https://github.com/s9y/Serendipity/commit/2f06e28f2346036ed7e9b30baf4c239996cd2ff5

**Comment by onli** [comment]
What is the right thing to do here? One of you two wants to implement the switch via the upgrader, or shall we just internally map mysql calls to to mysqli backend? mysql is dead and deprecated for so long I think that would be better than going with the more error-prone upgrader route.

**Comment by garvinhicking** [comment]
Yeah, that would probably be better. If "mysql" is configured, the db.inc.php could override that and load the mysqli layer instead. Since we require a PHP version now that should always ship mysqli, I hope there are no caveats we are forgetting about...

**Comment by onli** [comment]
Ha! I think we have this already, see https://github.com/s9y/Serendipity/blob/8da4c647a88241899f9d377eaa81c7b080406685/include/db/db.inc.php#L6. If that is what I think it is, could you close confirm (by looking at it) and close here?

**Comment by garvinhicking** [comment]
Nice. Forgot about it. Closed, Ian - if you have anything to add, feel free to reopen.

**Comment by ophian** [comment]
We should not want this! This is just a dirty workaround, which was a need when we had a requirement for low PHP versions.
What I intended to have is "Set `mysqli` for `mysql` upgraders in DB now and forever ONCE". It makes no sense to me overwriting it silently on every request for 5.5+ USERS only. AND I think we want users to notice that `mysqli` is the default, though they'll never notice the other way.

**Comment by onli** [comment]
Why would we want any of this? This small if makes no performance difference and is way more solid than an upgrader task. And to notify users we won't use that mysql extension that does not work anymore serves no purpose.

**Comment by ophian** [comment]
Any of what?
An upgrader task was Garvins idea. I would have reset that with the 2.1 release and thats it. And meant "notify" by being in configuration database, which would still point to mysql currently!

**Comment by ophian** [comment]
@garvinhicking I still think it would be good to make this possible on 2.1 upgrade for PHP < 5.5 users too!
I know time is not working for my argument, but there are still a lot of "frozen" servers out there, which still could benefit from using `mysqli`.

**Comment by onli** [comment]
They do not need us to force them – the mysql extension should work fine for them, right? And they can pick mysqli via the configuration. I do not see the need to change this via the upgrader.

**Comment by ophian** [comment]
I disagree. The workaround for 5.5+ is just a dirty workaround, performed on every request for ever. It would be so easy to set it once in real and thats it. And this or all of us!
