### ISSUE TITLE
ImageLibrary: Full Sorting filters look a bit strange

### ISSUE THREAD

**Issue by ophian** [s9y/Serendipity#356]
Is this intended to be like this? (see vertical lines, structure of blocks, and what is a bp date?, etc.)
![sortfilter](https://cloud.githubusercontent.com/assets/1105372/8679040/8a896810-2a58-11e5-901b-a715f605a626.PNG)

Can we make this a bit more strait?

**Comment by yellowled** [comment]
> Is this intended to be like this?

It may have room for improvement. As does most of the backend. Other than that it is intented to look like this, yes.

> see vertical lines

What “vertical lines”?

> what is a bp date?

Apparently, it is a variable that no one ever bothered to add a lang constant for to replace it with a more descriptive term. (Read: “I don't know, either.”)

> Can we make this a bit more strait?

I have no idea what you mean by “strait”.

**Comment by ophian** [comment]
> What “vertical lines”?

ie see `Sortieren nach (i.date)` not on line with `Dateiname` and `Autor` (are they subs of the first?)
same later on in the middle and 
the last three blocks not in this triple grid, because of being independent blocks or why...?

Sorry. Meant "straight", in mean of "structured" so you can nearly immediately imagine what happens when and what to let off.

**Comment by yellowled** [comment]
> the last three blocks not in this triple grid, because of being independent blocks or why...?

Ah. Good catch. The floats are not being cleared. I'll address that shortly.

> so you can nearly immediately imagine what happens when and what to let off

I'm sorry, but I still don't get what you mean. What do you want to achieve?

**Comment by ophian** [comment]
Maybe we should rethink the sort of these block. In example, gather all double input fields, and/or set a display like block box for the sorting fields that _may_ belong together, and so on. I am not ready with thinking about that yet... Structering.

**Comment by yellowled** [comment]
Then I suggest that I just address the layout issues and give you more time to think. (Frankly, I don't have the time or the energy to address more than that at the moment anyway.)

**Comment by ophian** [comment]
really better ...! But strange is, we now have actually "6" line, previous had "4" (not in real, but suggested). Why is that and why did it grow than shrink?

**Comment by yellowled** [comment]
I literally don't understand you.

**Comment by yellowled** [comment]
This was *always* supposed to be 3 filters per grid row. I don't know how you get to 6 or 4, but that was either a bug or an optical illusion. This is how it is and was supposed to be. If there are more than 3 `input` elements in one row, that's because some filters have 2 `input` elements because the filter is actually a range (from … to …).

I'll close this now. If and when you have thought about suggestions for restructuring this, please discuss them in the forums first. We agreed to not lead discussions on GitHub any more, remember?

**Comment by ophian** [comment]
"Optical Illusion" with real impact, though! :)
![sortfilternew](https://cloud.githubusercontent.com/assets/1105372/8680725/8aa430ea-2a63-11e5-86fa-349bc7e01a27.PNG)
Was this a discussion without bugging effect?
Thanks anyway.

**Comment by yellowled** [comment]
No, but dicussing restructuring will be.

It should ideally be two seperate things – an issue about the layout bug and a discussion which will eventually leads to an issue about restruturing the section. It is annoying for other developers (especially those that don't contribute to these issues) to have lengthy discussions on GitHub.

**Comment by ophian** [comment]
Ok. I will try to discuss the restructuring somewhere else, even if that does not help someone in need to read this, to decide to contribute himself or not.

But i need an answer for the follwing here, to continue my work. (I assign @garvinhicking to this. Maybe he can help out.)

Having a look onto this full captured filter screenshot, we have 17 items, right?
The array `$media.sort_order` delivers 15 items
```php
Array
(
    [i.date] => Array
        (
            [desc] => Upload-Datum
            [type] => date
        )

    [i.name] => Array
        (
            [desc] => Dateiname
        )

    [i.authorid] => Array
        (
            [desc] => Autor
            [type] => authors
        )

    [i.extension] => Array
        (
            [desc] => Dateiendung
        )

    [i.size] => Array
        (
            [desc] => Dateigröße
            [type] => intrange
        )

    [i.dimensions_width] => Array
        (
            [desc] => Bildbreite
            [type] => intrange
        )

    [i.dimensions_height] => Array
        (
            [desc] => Bildhöhe
            [type] => intrange
        )

    [bp.DPI] => Array
        (
            [desc] => DPI
            [type] => int
        )

    [bp.RUN_LENGTH] => Array
        (
            [desc] => Laufzeit
            [type] => intrange
        )

    [bp.DATE] => Array
        (
            [desc] => Verknüpftes Datum
            [type] => date
        )

    [bp.COPYRIGHT] => Array
        (
            [desc] => Copyright
        )

    [bp.TITLE] => Array
        (
            [desc] => Titel
        )

    [bp.COMMENT1] => Array
        (
            [desc] => Kurzer Kommentar
        )

    [bp.COMMENT2] => Array
        (
            [desc] => Langer Kommentar
        )

    [bp.ALT] => Array
        (
            [desc] => Bildinhalt (Zusammenfassung für das ALT-Attribut)
        )

)
```
Which are 7 `i.items` and 8 `bp.items`. The `i.items` are image properties (i), the `bp.items` are mediaproperties base_properties (bp).

The labels are set via `<label for="serendipity_filter_{$filter@key}">{$filter.desc}</label>`.
As you can see, there are some, which do not show up as a name + `(bp.desc)` in parenthesis.
This is, while the code only sets those as `fieldset span` information headers, if of type `date` or `intrange`.

Now to the questions. (Which are also related to the _"We will need to check this again, since some ordermode items (mostly the bp.* ones), like bp.TITLE|COMMENTx|DATE break the flow or are not set right and need some conditional tweaks."_ commit  note of some of my last commits.

If you look to the captured screenshot with a sharp eye, you'll see `Dateiname` is shown twice. The first is the i.name (see array), the second is hardcoded (not array deflated) to the tpl as 
```Smarty
                <div id="media_filter_file" class="form_field left">
                    <label for="serendipity_only_filename">{$CONST.SORT_ORDER_NAME}</label>
                    <input id="serendipity_only_filename" name="serendipity[only_filename]" type="text" value="{$media.only_filename|escape}">
                </div>
```
at the bottom of the array loop deflation.

This is followed by another hardcoded filter, which is media keywords:
```Smarty
                <div id="media_filter_keywords" class="form_field center">
                    <label for="keyword_input">{$CONST.MEDIA_KEYWORDS}</label>
                    <input id="keyword_input" name="serendipity[keywords]" type="text" value="{$media.keywords_selected|escape}">
                </div>
```

Now, 

1. Is that a rest of some old or some 2.0-dev smartifying coding state?
2. Is that perhaps meant as an approach for the simplified filter `simple filter` option? (Simple filter btw currently delivers `i.date` and `i.name` and the 2 hardcoded items)
3. Is there maybe a (plugin?) filter state where these two hardcoded items are the only items showing up?
4. Why isn't media keywords in the sort_order (bp?) array?
5. You can't distinguish between `i.items` and `bp.items` per option or per design?! (I think it would be nice to have this. To have extended filters (which is  a need to set, when you allow bulkdelete or bulkmove of media library items) being something really usefull for the user, which needs to understand the meaning, and will keep asking this in the mentioned discussion.)
6. The hardcoded `Dateiname` is based to `only_filename`, which is set and added to the `$parems` array by
```php
function serendipity_generateImageSelectorParems($format = 'url') {
    ....
    $standaloneFilterParams = array('only_path', 'only_filename');
```
and latterly added to the `$media` full array.  What are both array items for? (Originally meant and currently used?)

In follow of all this, there are other question coming up, like `are all items of $media array still a need` and so on...

Please forgive if that was a long post again. But I need to be precise to show my concerns and my questions.

Thanks for any helping contribution.

**Comment by onli** [comment]
Ian, I do not think there is anyone who really has the answers to all those questions. I remember that only_filename had a special usage, but don't have the time to dig into there properly. But well, maybe Garvin still chimes in.

Basically, the i. or bp. filters are fetched directly from the database fields. The state of those is exactly why the simple-filters-option exists. I do not want to invest work there, as UI and code is a mess and I can't imagine those being used.

If also simple-filters doubles fields, that would be a bug and should be cleaned up. And yes, I just checked, definitely looks like a bug. I'll open an issue.

**Comment by ophian** [comment]
It does not make sense to me to pick something out, before we have a funded answer on this; And that I already have declared as a bug, but sits in a larger questionary. Nobody ever even noticed this before. Since simplifying is just one site of the medal, the other is to make these other detailled views being something really usefull and understandable as much as possible. As always, Serendipity is nothing you can just simplify down. It has extended and multi level possibilities, which is the magick of this piece of software. I **do** want to keep them and **do** want to find them and **do** want to make them be clearly and easy recognisable for the users.

**Comment by onli** [comment]
Of course you can simplify it. We just did.

> I do want to keep them and do want to find them and do want to make them be clearly and easy recognisable for the users.

Well, I don't :) I don't even think it is possible to make that approach workable. Knock yourself out, but that will at least be a bunch of work.

**Comment by garvinhicking** [comment]
I'll try to answer this, can you please make a forum post with the questions from your posting that are still open? That's the best place where we can discuss it, because it's not an "issue" per definition.

(If you already posted this to the forums, I'll need a few days to get re-settled into work and then check into it!)
