### ISSUE TITLE
ImageLibrary: FR to allow bulk move

### ISSUE THREAD

**Issue by ophian** [s9y/Serendipity#357]
Do we have a bulk move to another image directory?
Can we make this possible in core via the checkbox fields and another button at bottom for a popup layer to finally move the checkmarked images to another dir?
Or shall we make this via a Plugin (if possible)?

I think this is a real feature a media library must have by default!

**Comment by yellowled** [comment]
Currently, the only way to move a *single* image is through the media properties. That is pretty well hidden as it is, but it's also the reason why there is no “bulk move”. At the part of the interface where moving a single image happens, there is no way to select multiple files.

Personally, I think

a) this is a CMS feature, I'm not sure if it's necessary in a blog environment
b) implementing the bulk move would be learning to run before learning to walk
c) this needs more discussion, which should not be done on GitHub
