### ISSUE TITLE
Auto-Upgrader not working (sourceforge -> github)

### ISSUE THREAD

**Issue by onli** [s9y/Serendipity#358]
The autoupgrader plugin is trying to download from sourceforge, where 2.0.2 is not uploaded. We need to change its download location.

**Comment by garvinhicking** [comment]
Ah damn, need to document this. I am hoping the SF.net upload facility will become available shortly, then I'll try to upload the files there, too.

**Comment by onli** [comment]
Okay. Shall we point the autoupdate to github anyway?

**Comment by ophian** [comment]
I can make a diff shortly
