### ISSUE TITLE
Dashboard grid col=2 lined autoupdate Box breaks follow-up boxes floats

### ISSUE THREAD

**Issue by ophian** [s9y/Serendipity#359]
The Autoupdate Box in the dashboard like overview file breaks the floats of the other boxes.
![autoupdbox_breaks_dashboard_floats](https://cloud.githubusercontent.com/assets/1105372/8880079/3c61f2f2-3236-11e5-9c08-67aaad85840d.png)

I suggest to add a `<hr>` to overview.inc.tpl, which avoids this behaviour.
```diff
@@ -29,10 +29,11 @@
 
                 <span class="msg_notice"><span class="icon-info-circled"></span> {$CONST.NEW_VERSION_AVAILABLE} {$curVersion}</span>
                 {$updateButton}
             </section>
         {/if}
+        <hr>
     {/if}
 
     {if $no_create !== true}
         <section id="dashboard_comments" class="equal_heights quick_list dashboard_widget">
             <h3>{if 'adminComments'|checkPermission}<a href="serendipity_admin.php?serendipity[adminModule]=comments">{/if}{$CONST.COMMENTS}{if 'adminComments'|checkPermission}</a>{/if}</h3>
```

**Comment by yellowled** [comment]
I'm not sure it actually breaks the floats. I'd like to have a look at it with a bit of time (and without having had three large beers just now, to be honest).

How do I “provoke” said message? Reset the version in serendipity_config.inc.php?

**Comment by ophian** [comment]
> Someone remind me how to “provoke” said message, please. Reset the version in serendipity_config.inc.php?

yes

**Comment by yellowled** [comment]
Thanks for the confirmation.

Fixed.
