### ISSUE TITLE
Multilingual sidebar lang overwrites backend language

### ISSUE THREAD

**Issue by ophian** [s9y/Serendipity#361]
Setting a frontend sidebars multilingual lang, logged IN or OFF, sets a global `$serendipity['lang']` (which is the one in "Configuration") for the back- and frontend, even when not logged-in.
Personal Preferences `$serendipity['default_lang']` does not overrule this setting, even when submitted again, which it normally does when global lang is something else.

Multilingual Plugin should at least have an option, to translate lingified strings only, or change the blog language (which it does now). But this all should IMO **not** overrule the backends Personal Preference language!
In the backend, I think, `$serendipity['default_lang']` should always be checked to set the desired lang, even when a user lang cookie was already set.

Did I miss something?

I am about to submit some bugfixes to multilingual plugin. This is why I need this to be clear or fixed!
@garvinhicking 

Edit: Also see http://board.s9y.org/viewtopic.php?f=4&t=19820

**Comment by ophian** [comment]
The "force full language switch" option, adding GET serendipity[user_language]=newlang to the per entries lang links, does not work anymore in 2.0x. In 1.7.8 it does work.

**Comment by ophian** [comment]
I started to play around with the language sets to debug why this language issue happened and at first wondered, why I got set to english all the time within a fresh browser session. 
If nothing is set before, `serendipity_load_configuration()` introduces the `$serendipity` array with the lang set by authorid `0` from the config table.
```
    // Store default language
    $serendipity['default_lang'] = $serendipity['lang'];
```
which is build by a query, checking for authorid = 0
```
name value authorid
array ( 'lang' 	'en' 	0, 'lang' 	'de' 	1 )
```
I'd say that is wrong, if you don't tell me I am misled here, since I could not find a way to change the authorid 0 lang to the admin chosen lang yet. Do we have this? Using Configuration or PP does not help, IMHO.

Else we would need something like this in`serendipity_load_configuration()`:
```php
    // check correct language if admin ID differs from installed, which is authorid 0
    $lang_author1_admin = serendipity_db_query("SELECT value FROM {$serendipity['dbPrefix']}config WHERE name = 'lang' AND authorid = 1", true, 'assoc');
    if ($lang_author1_admin['value'] != $serendipity['lang']) {
        $serendipity['lang'] = $lang_author1_admin['value'];
    }
    // Store default language
    $serendipity['default_lang'] = $serendipity['lang'];
``` 

Or we would need to set the preferred lang(uage) in configuration, adding the ID 1 value to the ID 0 value too, since 0 is usually meant as "all authorid" or "not set authorid", see #264.

(I need to know and clear this to dig any deeper for the issue starter.)
@garvinhicking

**Comment by garvinhicking** [comment]
Authorid 0 is the global configuration for the blog's language that is 
set on installation and within the usual global config. So this 
shouldn't be wrong.

When s9y is installed you pick the default language of the blog AND your 
admin user, but both are different settings. One applies to yourself, 
the other to a visitor that has no s9y author account.

**Comment by ophian** [comment]
Yes, that is what I have tried to describe too.
~~We should need a capability to change this in the global configuration, since the admin user can set his authors language over his personal preferences and the one in configuration ...~~ ups now I did it again and it changed, very strange. (Yeah, now I remember this and had it already described in the linked blog thread myself - oh gosh!) Well, if that does work, this is the best and we will just have to note this to be the same lang when using multilingual blogs. Now I can continue. Thanks.

**Comment by ophian** [comment]
Yepp, the first issue seems to be mainly a matter of this lang kuddelmuddel... but we should think of always force the backend language to a strict authorID = author config check to get the once set preferred language in the backend and not a cookie or session lang passed by the frontend.

But I really wonder why the "force" option with lang=de, linking to:
`index.php?archives/48-English.html&serendipity[lang_selected]=en&serendipity[user_language]=en`
does not work like the sidebars languagechooser too? GET serendipity[user_language]=en seems to have no effect everywhere in the frontend (and stick to the session or even cookie). Is it a GET vs POST issue, maybe?
I did this in a fresh browser session on 1.7.8 and it worked. This is where I thought it to be somehow broken in 2.0ups, but it seems to happen there too, when you have done it already once. So it probably is a matter of cookies, I assume. Or do I missunderstand this force option?
@garvinhicking Can you shed some light here too, please?

**Comment by garvinhicking** [comment]
I don't think so - a session/cookie needs to have preference, or else 
you couldn't change the frontend language...?!?!

I think the user_language thing is enforced by the multilingual event 
plugin?! Don't have the time to investigate right now, though. Did you 
make a full grep on the s9y source and additional plugins for 
"user_language" and check where it's used?

**Comment by ophian** [comment]
As far as I can see this is in multilingual plugin only and cores serendipity_getSessionLanguage().

They both want to access a `$_REQUEST['user_language']`, but this isn't available or disabled somewhere, but `$serendipity['GET']['user_language']` is what the request wants to be. The only time this REQUEST per se is available is, when you submit the languagechooser sidebar select.

I now added testwise a `$_REQUEST['user_language'] = $serendipity['GET']['user_language'];` before the lang headers are set into the multilingual introspect() method.

This seems to work and the entry and everything else being langified changes (except the banners entry_title issue I mentioned in the forum). A SESSION is set with [serendipityLanguage] => en and [last_lang] => en. (A search request seems to use last lang further on ...)
This holds as long as this browser session is open. 

Now, there is a question (1) and a issue (2) left: 
  1. Is that link force option expected to only live as long as the SESSION lives? (the post selection sets a cookie.)
  2. Now that the session works fine and hold the requested `en` language, a next click in the frontend widly uses this, but not the entry itself, where that link came from. (this will show up in default lang mode again). I need an idea how to tell S9y or the multilang to fetch the `en` entry.

Being a bit _hackish_, this "_seems_" to work for a first switch (not when switching again!):
```
$_REQUEST['user_language'] = $serendipity['GET']['user_language'];
if (!empty($_SESSION['serendipityLanguage'])) $this->showlang = $_SESSION['serendipityLanguage'];
```
What do you think? I'd need something further for the next switch to always get the correct lang name, but this gets messy... I need a break now.

**Comment by garvinhicking** [comment]
Thanks for the digging. I'm not so sure about 1.), but I believe yes, it 
should only be for the session. About 2 I would really need to read the 
code, which I can't right now. But your "hackish" patch looks ok to me, 
I wouldn't mind committing this at that time and we can see how that 
fixes things for people or raises other issues. But I think it should be 
fine then...!

**Comment by ophian** [comment]
Hmm, I can't make a real diff right now and am in hurry... so here is my last solution, which seems to fix every linked (and forced) lang to set and create the right language without doublecklick etc, compare with https://github.com/s9y/additional_plugins/blob/master/serendipity_event_multilingual/serendipity_event_multilingual.php#L61

```php
        // Okay, Garv. I explain this to you ONCE and ONLY.
        // $this->lang_display is the variable that FORCES translations of entries. If a translation does not exist,
        //                     an entry is NOT SHOWN.
        // $this->showlang     is the variable that indicates which language of an entry to prefer.
        if (isset($serendipity['GET']['lang_display'])) {
            $this->lang_display = serendipity_db_escape_string($serendipity['GET']['lang_display']);
            header('X-Serendipity-ML-LD-1: ' . $this->cleanheader($this->lang_display));
        }
        
+        // check for REQUESTs being sent (imagine the user in a DE blog links an EN entry version and force option is set TRUE)
+        // $_REQUEST was somehow disabled and not available, but used here and in serendipity_getSessionLanguage()
+        $_REQUEST['user_language'] = $serendipity['GET']['user_language'];
+        // normal fallback
+        if (!isset($serendipity['GET']['lang_selected']) && !isset($_REQUEST['user_language'])) {
+            if (!empty($_SESSION['serendipityLanguage'])) $this->showlang = $_SESSION['serendipityLanguage'];
+        }

        if (empty($this->showlang) && isset($serendipity['POST']['properties']['lang_selected'])) {
            $this->showlang = ($serendipity['POST']['properties']['lang_selected']);
            $_SESSION['last_lang'] = $this->showlang;
            serendipity_header('X-Serendipity-ML-SL-1: ' . $this->cleanheader($this->showlang));
        } elseif (empty($this->showlang) && isset($serendipity['GET']['lang_selected'])) {
            $this->showlang = serendipity_db_escape_string($serendipity['GET']['lang_selected']);
            $_SESSION['last_lang'] = $this->showlang;
            serendipity_header('X-Serendipity-ML-SL-2: ' . $this->cleanheader($this->showlang));
        } elseif (empty($this->showlang) && isset($_REQUEST['user_language'])) {
            $this->showlang = $_REQUEST['user_language'];
            $this->lang_display = $this->showlang;
            serendipity_header('X-Serendipity-ML-SL-3: ' . $this->cleanheader($this->showlang));
        } elseif (empty($this->showlang) && isset($_REQUEST['serendipity']['serendipityLanguage'])) {
            $this->showlang = $_REQUEST['serendipity']['serendipityLanguage'];
            serendipity_header('X-Serendipity-ML-SL-4: ' . $this->cleanheader($this->showlang));
        } elseif (empty($this->showlang) && isset($serendipity['lang']) && !isset($_SESSION['last_lang'])) {
            $this->showlang = $serendipity['lang'];
            serendipity_header('X-Serendipity-ML-SL-5: ' . $this->cleanheader($this->showlang));
        }

+        // a user has already set a forced language and now wants to return to the default language - doing such here, avoids a doublecklick need..
+        if ($this->showlang == 'default' || $_SESSION['last_lang'] == 'default') {
+            if (isset($_COOKIE['serendipityLanguage'])) $_COOKIE['serendipityLanguage'] = $serendipity['default_lang'];
+            $this->showlang = $serendipity['default_lang'];
+            $_SESSION['serendipityLanguage'] = $_REQUEST['user_language'] = $serendipity['default_lang'];
+            if ($_SESSION['last_lang'] == 'default') $_SESSION['last_lang'] = $serendipity['default_lang'];
+            $serendipity['lang'] = $serendipity['default_lang'];
+        } // the entry is shown in default language as a fallback, when another language is chosen that has no entryproperties translation

        if (!isset($serendipity['languages'][$this->showlang])) {
            $this->showlang = '';
            serendipity_header('X-Serendipity-ML-SL-RESET: ' . $this->cleanheader($serendipity['default_lang']));
        }

        if (!headers_sent()) {
            serendipity_header('X-Serendipity-ContentLang: ' . $this->cleanheader($this->showlang));
        }

        $this->setupDB();
```

**Comment by ophian** [comment]
I also added some force option checks and resets for the upper... which is doing even better.

To come back to this topic...

> I don't think so - a session/cookie needs to have preference, or else you couldn't change the frontend language...?!?!

That is not what I meant in detail. I meant the admins PP set lang having **always** preference over frontend set session/cookies langs **in the backend(!)**. So it would not matter what was the last selection in the frontend; always make the backend use the "super" lang, stored as ('lang', 'de', 1). This would have to be done in core, I think, not in the plugin. 
(It might be in question, if we have this backend lang overwrite the session/cookie stored langs, or have it only be used in the backend.)
Is that more clear?

At the moment we have the Problem that frontend selected sidebar langs by the ADMIN, influence the admins backend lang, for the ADMIN. Which is not necessary and is highly confusing for everybody trying to understand how multilingual is gona work. Reading some of the old forum posts regarding this issue make this clear.

**Comment by onli** [comment]
Is this still an issue? I think I remember some commits coming in for that?

**Comment by garvinhicking** [comment]
Closing for now, I believe that when changing the language on the frontend, it should be rather clear that this specific choice carries to the backend == the whole blog. I think we cannot really add an indicator or text at that place, because that would look ugly.

If there are specific ideas on how to improve the situation, please reopen&comment
