### ISSUE TITLE
renaming ML items page reload does not work

### ISSUE THREAD

**Issue by ophian** [s9y/Serendipity#370]
This may have been overread, since added as a commit note, I add this here as a possible issue now.

I still have the issue when renaming a file, via the ML rename on click event,  that the XHR location href POST answer does not trigger or work and reload the page. (Please only try this with a current(!) master from now or yesterday.)
But I do have the same issue with 2.0.2 (remote and local).
I first need a verification if that is an issue you have on 2.0.2 too, please.
Any ideas what causes this or further verifications are welcome.

**Comment by onli** [comment]
Confirmed. Renaming items in 2.0 does rename then, but does not show the change – there is no page reload and no naming change via js.

**Comment by ophian** [comment]
Yeah, thanks! I forgot to make clear the renaming is working well per se and it is only the reload which has an issue.

Do you have Chrome available to check up, if there is a possible js issue, which Moz does not show?

**Comment by ophian** [comment]
Ufff! That tooooook loooong! It was like digging in the dark - YES! But at last I think I got it!

Our approach getting some html content by images.inc.tpl on `rename return` is missing something essential, since we are in JS environment. It can not happen true and display itself on the page started. It could end up as a success: response in a JS dialog, but this is nonsense, since it has the JS redirect and a noscript action, which could never become true, while we already are in a JS environment at this moment.

So what I did now, is to remove these actions into the caller in serendipity_editor.js
```js
    // Rename file in media db
    serendipity.rename = function(id, fname) {
        var newname;
        var media_rename = '{$CONST.ENTER_NEW_NAME}';
        if (newname = prompt(media_rename + fname, fname)) {
            var media_token_url = $('input[name*="serendipity[token]"]').val();
            $.ajax({
                type: 'POST',
                url: '?serendipity[adminModule]=images&serendipity[adminAction]=rename&serendipity[fid]='+ escape(id) +'&serendipity[newname]='+ escape(newname) +'&serendipity[token]='+ media_token_url,
                async: true,
                cache: false,
                success: function(response) {
                    alert(response+"{$CONST.MEDIA_RENAME} {$CONST.DONE}!");
                    window.parent.parent.location.href= '?serendipity[adminModule]=images&serendipity[adminAction]=default';
                },
                error: function(XMLHttpRequest, textStatus, errorThrown) {
                    alert("Status: " + textStatus); alert("Error: " + errorThrown);
                }
            });
            //$.post('?serendipity[adminModule]=images&serendipity[adminAction]=rename&serendipity[fid]='+ escape(id) +'&serendipity[newname]='+ escape(newname) +'&serendipity[token]='+ media_token_url);
        }
    }
```
and remove every content or failing interaction from case rename in images.inc.php and not use the tpl rename output at all. This would work. (It needed a window.parent.parent too.)

See images.inc.tpl
```smarty
{if $case_do_multidelete || $case_do_delete}
    {if $showML}{$showML}{/if}
{/if}
{* $case_rename can not respond to page - serendipity.rename() ajax will reload per script *}
{if $case_add}
    {if $showML}{$showML}{/if}
{/if}
```
and images.inc.php
```php
    case 'rename':
        $data['case_rename'] = true;
        $serendipity['GET']['fid'] = (int)$serendipity['GET']['fid'];
        $file = serendipity_fetchImageFromDatabase($serendipity['GET']['fid']);
        $serendipity['GET']['newname'] = serendipity_uploadSecure($serendipity['GET']['newname'], true);

        if (!is_array($file) || !serendipity_checkFormToken() || !serendipity_checkPermission('adminImagesDelete') ||
           (!serendipity_checkPermission('adminImagesMaintainOthers') && $file['authorid'] != '0' && $file['authorid'] != $serendipity['authorid'])) {
            return;
        }
        // all event action has to go into js
        serendipity_moveMediaDirectory(null, $serendipity['GET']['newname'], 'file', $serendipity['GET']['fid'], $file);
        break;
```
What do you think? Its not that "smart" as the other approach, but it is working! :)

(I would need some confirmations on different Server and PHP environments from you guys, since I had a HTTP_RAW_POST DATA deprecation error on my way testing and investigating this issue with PHP 5.6x. This needed some changes.)

**Comment by onli** [comment]
> What do you think? Its not that "smart" as the other approach, but it is working! :)

Absolutely first impression: Removing all that should lead to issues. I'll look at it and try to disprove that impression, thanks for the infos :)

**Comment by ophian** [comment]
> Removing all that should lead to issues.

I don't know what you mean by "all that"...

**Comment by onli** [comment]
You showed code above?

**Comment by ophian** [comment]
The only problem I see, according to the working sample above, is to change the $.ajax using alert() messages. This should be a modal, to have it use already styled html messages. Even better would be, to somehow transport these messages to the reload page. Ideas welcome.
I only wanted to have a simple example shown, on how to solve the (370) issue here. This is what I do next, before I commit that. Of course only, if someones does not come up with a better solution until then.
