### ISSUE TITLE
staticpages dying with pdo_sqlite on install

### ISSUE THREAD

**Issue by onli** [s9y/Serendipity#377]
This is the message I get:

```
<b>Fatal error</b>:  Uncaught exception 'ErrorException' with message 'Warning: var_export does not handle circular references' in /var/www/include/db/pdo-sqlite.inc.php:240
Stack trace:
#0 [internal function]: errorToExceptionHandler(2, 'var_export does...', '/var/www/includ...', 240, Array)
#1 /var/www/include/db/pdo-sqlite.inc.php(240): var_export(Array, true)
#2 /var/www/include/db/pdo-sqlite.inc.php(305): serendipity_db_query('ALTER TABLE ser...')
#3 /var/www/plugins/serendipity_event_staticpage/serendipity_event_staticpage.php(900): serendipity_db_schema_import('ALTER TABLE ser...')
#4 /var/www/plugins/serendipity_event_staticpage/serendipity_event_staticpage.php(3151): serendipity_event_staticpage-&gt;setupDB()
#5 /var/www/include/plugin_api.inc.php(1139): serendipity_event_staticpage-&gt;event_hook('backend_sidebar...', Object(serendipity_property_bag), Array, NULL)
#6 /var/www/include/functions_smarty.inc.php(561): serendipity_plugin_api::hook_event('backend_sidebar...', Array, NULL)
#7 /var/www/templates_c/2k11/73/69/66/73696 in <b>/var/www/include/db/pdo-sqlite.inc.php</b> on line <b>240</b><br />
```

Happens directly after installing the plugin.

**Comment by garvinhicking** [comment]
Problem is that serendipity_event_staticpage dies with db_built=7, and then the DB exists and "ALTER TABLE" is invalid in SQLite when new columns shall be added.

Let's check that once the staticpage plugin is the latest version.

**Comment by th-h** [comment]
@onli Could you check sometime if that still happens?

**Comment by onli** [comment]
Yes, this still happens.

I'm not exactly sure why the error happens though. SQLite can add Columns in ALTER TABLE statements. When executing the statement locally I get:

```
sqlite> ALTER TABLE serendipity_staticpages ADD COLUMN shownavi int(4) default '1';
Error: duplicate column name: shownavi
```

But I do not see why only sqlite would throw an error there in this case. And indeed in https://github.com/s9y/additional_plugins/blob/e3dbcbec2996becc1415f9922e0474f8411ac35f/serendipity_event_staticpage/serendipity_event_staticpage.php#L813 the column is already defined beforehand. Is it possible the other SQL backends just don't properly throw an error here when the `ALTER TABLE` statement fails also with them?

Maybe all this needs is to set `$built`, which is set as `$built = $this->get_config('db_built', null);`, to the current version if the database did not exist before installing the plugin?

**Comment by onli** [comment]
I added ifs to not execute those alter statements when using sqlite and added IF NOT EXISTS to the SQL, so the function can be run multiple times. That helps when it dies the first time.

That means sqlite users will still get no working database upgrade for the plugin, but that's like it always has been. To do that properly we'd probably need to use a system that manages such schema updates for us. But that's its own issue, I will close here.
