### ISSUE TITLE
Feeds wrong in Serendipity 2.1 alpha3

### ISSUE THREAD

**Issue by ddeimeke** [s9y/Serendipity#381]
Please have a look, this is the comments feed

http://www.deimeke.net/dirk/blog/index.php?/feeds/comments.rss2

which is more or less identical to the "normal feed"

http://www.deimeke.net/dirk/blog/index.php?/feeds/index.rss2

See: http://board.s9y.org/viewtopic.php?p=10444435#p10444435

**Comment by onli** [comment]
Thank you for reporting this, the fix should catch some other bugs as well. Please give me a hint if the problem persists.
