### ISSUE TITLE
"Edit" link in empty HTML nugget

### ISSUE THREAD

**Issue by yellowled** [s9y/Serendipity#382]
It is possible to use HTML nuggets in the sidebar that don't emit actual content, i.e. to include Piwik or Google Analytics snippets. These nuggets usually don't have a title and don't emit anything that is visible in the frontend. Yet they still emit an 'Edit' link to the logged-in user, which looks weird.

Steps to reproduce:

– Add an HTML nugget without a title
– Add some kind of HTML to it that does not actually emit content, i.e. Piwik snippet
– View the index page while being logged in

You will likely see two "Edit" links right below each other, which is irritating.

Suggested solution: I don't think it makes sense to tie this to the plugin not having a title – there are use cases to have nuggets without a title that actually emit content. So the best solution would probably be to add some kind of switch to the HTML nugget plugin (since it is very likely the only plugin that is affected by this?). Something like “This is a hidden HTML nugget, hide the Edit link” or something?

**Comment by donchambers** [comment]
Isn't that what serendipity_event_head_nugget is used for?  Or is this content that appears within <body>, not <head>?

**Comment by yellowled** [comment]
`serendipity_event_head_nugget` is for code that goes into `<head>`. Some of these snippets specifically state that their code should *not* go into `<head>`, so some users use HTML nuggets instead.

**Comment by yellowled** [comment]
Closed because @mariohommel (as someone who actually uses this) said that this link is actually still useful for him, so … `¯\_(ツ)_/¯`
