### ISSUE TITLE
Howto mark, move or set plugins deprecated now

### ISSUE THREAD

**Issue by ophian** [s9y/Serendipity#386]
Meanwhile we have a (growing) list of outdated and known deprecated Serendipity plugins.

I am thinking of an elegant way to get rid of them, probably without moving them from Spartacus completely for the smaller getting group of users which haven't upgraded their Blog yet.

I was thinking of 
 1. just moving them to a `deprecated/` directory, just like the `alpha/` is in `additional_plugins` and then advise 2.1 serendipity_event_spartacus to exclude plugins found in there, 
 2. **OR** set them one by one into a new GROUP, eg ```
[groups] => Array
                        (
                            [0] => DEPRECATED
                        )
``` which then could stay just as is.

Anyone any other good ideas?

List 
 * g2embed
 * autosave
 * jquery
 * dashboard
 * weather (?) sidebar
 * recaptcha (?)
 * geotag (?)
 * etc

**Comment by yellowled** [comment]
Correct me if I'm wrong, but if someone has not updated their blog yet, it means that they already have the deprecated plugins installed, doesn't it? Why would it harm them to remove the plugin from spartacus? They'd still have their local copy.

**Comment by ophian** [comment]
That is another, but related question. :)
When I wrote this, I wanted to prevent users installing old deprecated plugins at all....

**Comment by onli** [comment]
Good idea. The group could work already, if we combine it with an spartacus/admin area update to properly present that. Otherwise we just introduce another plugin attribute for that.

**Comment by yellowled** [comment]
Well, if there really is no harm in deleting them from Spartacus altogether for the small group of people that refuse to update …

**Comment by ophian** [comment]
Deleting means - no further Spartacus bugfix updates possible...

**Comment by garvinhicking** [comment]
I'd go the easy route and remove such plugins that are no longer useful from the repository*; we wouldn't really provide fixes for those plugins anyways. I don't think we should clutter up a "deprecated" group.

* CVS doesn't really allow to remove directories, so we need to remove the files specifically. Not sure if the current github->cvs sync process can handle deleted files, but if removing the files from github isn't reflected on spartacus a day later, I can delete them manually from CVS.

**Comment by ophian** [comment]
Alright. That's fine for me too. I*ll start removing within the next days, if no one opposes. Maybe we can do that one by one? See list on top!

**Comment by yellowled** [comment]
What does the “etc” plugin do, BTW? ;-)

**Comment by ophian** [comment]
is there an english expression for "_hält den Platz warm!_"?

**Comment by ophian** [comment]
I am updating the list on top from time to time. If someone has a plugin missing, or does not want a plugin to be in there, or wants to discuss its further development - please add here.

**Comment by yellowled** [comment]
Prediction: someone will miss a plugin being added or removed because no one will check this issue periodically.

Maybe you could add updates to the list as a comment (but not for every single plugin)?

**Comment by ophian** [comment]
I assume with "g2embed, autosave, jquery, dashboard" we all agree.
What is with "broken and unmaintained" weather (?) sidebar, recaptcha (?), geotag (?) plugins?

I dimly remember there was more!

**Comment by yellowled** [comment]
Garvin's still looking for someone to fix geotag in the forums. :D

**Comment by ophian** [comment]
I know. That why I added the (?).

**Comment by garvinhicking** [comment]
Yeah we shouldn't remove geotag. Weather is killable, but I believe recaptcha should still work, and we shouldn't remove that one

**Comment by ophian** [comment]
I thought of this thread  http://board.s9y.org/viewtopic.php?f=4&t=20431 when adding it to the list, while missing reCAPTCHA v2...

**Comment by ophian** [comment]
Remove "g2embed, autosave, jquery, dashboard, weather" plugin: Done.

**Comment by yellowled** [comment]
If we agree to keep geotag and recaptcha … close? Or are there more?

**Comment by ophian** [comment]
I think there were more. But ATM I don't remember which. Keep.open.

**Comment by ophian** [comment]
Beside being broken or not, there are plugins like `serendipity_event_fckeditor`, which do not make sense...

**Comment by yellowled** [comment]
We should maybe at some point discuss and document, what “deprecated” means within the s9y project, if only to create guidelines for ourselves. (But not here and not now.)

**Comment by garvinhicking** [comment]
I'll close this for now. If we find a plugin we might want to remove, we can either discuss this through a new issue.

As for a guideline, we should remove plugins from Spartacus that:

* are boken and no longer work, maybe because depending on external functionality that is no longer available
* there are critical issues with a plugin and no maintainer can be found
* there are bettter plugins that provide the same functionality

By removing them from spartacus, people who have the plugin installed (and because of any reason want to keep using them) could do that, because Serendipity would not delete them. This is how CMS's like TYPO3 also work.

When we remove a plugin from spartacus, we should write a blog announcement post to inform people who have the plugin installed, so that they can remove them themselves (or maybe even volunteer to fix/improve it).

When users find plugins that no longer work, they usually report bugs here or on the forums and we can take care of it.

**Comment by yellowled** [comment]
Also, see http://docs.s9y.org/docs/contributing/versioning.html
