### ISSUE TITLE
delay with dashboard comment answer button

### ISSUE THREAD

**Issue by ophian** [s9y/Serendipity#387]
I have a strange delay with the dashboard comment answer button to open up the magnific layer, which needs a double click to start. This happens when you just came in and rests "only(?)" until having had that once (per session?). Next clicks dont have that. Is that reproducible?

Edit: It happens on each new dashboard request, so it is reproducible per session and not only related to dashboard, since also happens on comment page (on each new request to that page) too.

**Comment by onli** [comment]
Confirmed for FF 44.0. And I remember that this is a bug I already saw with magnific – but I have no idea why that is happening.

**Comment by yellowled** [comment]
Confirmed in Chrome 48/OS X, confirmed in Safari 9.0.3/OS X as well as Safari on iOS 9.2.1.

I am positive we have seen this bug before, at least something similar. But I can't find it in the issues.

**Comment by yellowled** [comment]
430d364a882ff236f8d13d3f301e6e91e0392bdd smells a bit like this – but the order of `e.preventDefault();` and toggling the popup in `$('.comments_reply').click(function(e)` is the other way around … (and in that case, I also did not find out *why* it did not trigger, I just found a way to fix it)

**Comment by yellowled** [comment]
@ophian @onli Please test. I think that fixes it, and no, I can neither explain why we didn't use `serendipity.openPopup` here in the first place (or why exactly using that fixes the issue).

**Comment by onli** [comment]
Maybe this was not the link on first click.

The patch works! I'll close here, Ian, please re-open if it is still broken for you.
