### ISSUE TITLE
Non-WYSIWYG buttons broken in static page editor

### ISSUE THREAD

**Issue by yellowled** [s9y/Serendipity#389]
[Forum thread](http://board.s9y.org/viewtopic.php?p=10444661#p10444661)

Apparently, the static pages plugin (“old” version) still uses the old function calls of functions in the onclick handlers of the buttons that have been namespaced in `serendipity_editor.js`, which is why they don't work.

Reproduceable in 2.0.3 and current `master` with static pages 4.09. The media db button works, all others fail by just inserting `undefinedundefined`.

**Comment by yellowled** [comment]
Probably needs a version check of some sorts in order to not break this for 1.x, right?

I'm inclined to assign this to @ophian because he know the static pages probably best …?

**Comment by ophian** [comment]
> I'm inclined to assign this to

**Dare** you doing this... :) I'll never touch this totally outdated plugin again!

Please just use https://github.com/ophian/serendipity_event_staticpage/releases

**Comment by yellowled** [comment]
I'll use this once it is on Spartacus.

**Comment by donchambers** [comment]
I recall having issues with the new static pages plugin, but that was a long time ago... perhaps all is well now.

I believe the new version of the plugin deserves some extensive testing before committing it to spartacus... and I am more than willing to help with testing as I have often made extensive use of static pages.

However, I also believe we need a fix for what is currently broken, if fixing it is possible.
