### ISSUE TITLE
Style new add media button

### ISSUE THREAD

**Issue by ophian** [s9y/Serendipity#395]
See example image.
![medialibrary_newbuttonstyling](https://cloud.githubusercontent.com/assets/1105372/13723891/1ddd1958-e873-11e5-923d-11f139d61ed4.PNG)

Is this in my dev only?

**Comment by yellowled** [comment]
I can not style what I do not have.

![screenshot 2016-03-12 18 37 05](https://cloud.githubusercontent.com/assets/326223/13724307/910707c8-e881-11e5-932e-041d03120ceb.png)

**Comment by ophian** [comment]
Its in the layer! :)

**Comment by yellowled** [comment]
If all our users wrote bug reports the way you do, we would all go insane. Please try to be a *bit* more verbose.

No, that is not only in “your dev”. Yes, I can reproduce it now.

**Comment by yellowled** [comment]
@ophian Please test and close.

**Comment by ophian** [comment]
> If all our users wrote bug reports the way you do, we would all go insane. Please try to be a bit more verbose.

I don't know why you get rude on this... YL.
If you had looked a bit more "precise" to the added screenshot, you would have seen the difference to yours yourself.

I'll test and close that later. Thanks.

**Comment by yellowled** [comment]
Well, if you would have taken the time (about 30 seconds, I'd guess) to point out that this happens in the overlay, which you already knew at that point, we would both have been polite. I have asked you (politely, as far as I recall) multiple times to please be more verbose in your bug reports. Nobody can read your mind.

**Comment by ophian** [comment]
Ok, lets stop that. I see you don't understand me felling you are "shooting the messenger".

**Comment by yellowled** [comment]
I understand that, I just don't get why you insist on calling other people rude just because they make a little joke. But we apparently have a different sense of humor, so sorry about that.

But seriously, *please* be more verbose in future bug reports.

**Comment by ophian** [comment]
checked OK.
