### ISSUE TITLE
configuration - database options - broken zebra

### ISSUE THREAD

**Issue by ophian** [s9y/Serendipity#396]
see image username - password
![config_zebra](https://cloud.githubusercontent.com/assets/1105372/13744163/5275f4b8-e9e6-11e5-98d4-7f51f9098ce1.png)

which is caused by the hidden ignore (password) field, added to prevent autofilling, I assume.
https://github.com/s9y/Serendipity/blob/master/templates/2k11/admin/config_template.tpl#L39

Shall we change this, or add an exception for the odd/even "staircase" if possible, or just leave it well enough alone...?
Though we might need such ignore case more than once...

**Comment by yellowled** [comment]
I remember seing this on other occasions as well, and I remember discussing it with @onli during development. If there is a *simple* solution to fix this, we can. If not, it's no biggie. (This *should* be colored using `:nth-child(odd)` anyway, but the browser support for that wasn't that good when we started all this …

**Comment by ophian** [comment]
Using selector would may be better than Smarty `{cycle}`, I think.
How about using this `:nth-child(odd of :not([hidden])) { }`?

**Comment by yellowled** [comment]
> Using selector would may be better than Smarty {cycle}, I think.

Yeah, but it would also not work in IE8, which we (technically) still support.

We need to discuss this (in the forums or a call) at some point anyway – there are quite a lot of things that could be done better if we dropped IE8 support, but I'm not sure @garvinhicking is prepared to go that route just yet …

**Comment by yellowled** [comment]
> How about using this :nth-child(odd of :not([hidden])) { }?

That, by the way, is not valid CSS.

**Comment by garvinhicking** [comment]
IF it's just about missing zebra striping in IE8, let's go for this. We 
don't need IE8 support for "good" layout, but if possible we should 
avoid making s9y unusable with IE8.

**Comment by yellowled** [comment]
Anyone, please do **not** go ahead and remove the template logic for zebra striping just yet, I need to test this first! 😊

**Comment by yellowled** [comment]
I'll make it short: unfortunately, we can **not** just replace the `.odd`/`.even` classes with `:nth-child()` or even `:nth-of-type()`. The markup structure for the backend is way more complex in most of the places where this is used – meaning the elements that `.odd` and `.even` get applied to are not always the nth child of something (sorry, I don't know how to explain it better). I stumbled across this in the very first example I decided to check out.

My suggestion would be to add some kind of exception (skip the odd/even process if element has class hidden), if that's possible.

**Comment by yellowled** [comment]
Also note that using `:nth-child` would not even fix the issue at hand here. The hidden element is still a child, so approach to add classes and skip the class for hidden elements is even better in modern browsers. (And unfortunately, `:not` does not help there, either.)

**Comment by onli** [comment]
Yes, it's possible to do that in smarty. The syntax does not work as I expected and it felt unstable because of that, but aa12313 worked in my test.

**Comment by ophian** [comment]
Excellent idea!
