### ISSUE TITLE
help request for a community (developer) project

### ISSUE THREAD

**Issue by ophian** [s9y/Serendipity#397]
I please need some (linux path) screenshots equal to the one in the book. Please for the best use browser build-in screenshot functions.

I need a linux style (png) screenshot of:
https://github.com/s9y/Book/blob/master/img/chmod.png
A somehow cut screenshot of Bulletproof options like this:
https://github.com/s9y/Book/blob/master/img/bulletproof.png

I also need these 3 install fullpage screenshots in, in a ~1400 x 1000 px browser window.
As a fullpage screenshot in firefox this is 
`screenshot install.png --fullpage` [ENTER] in the console [Shift- F2].
Please take it best with a current 2.1 alpha3. For the first install page having that error would be nice too!
https://github.com/s9y/Book/blob/master/img/install.png
https://github.com/s9y/Book/blob/master/img/install2.png
https://github.com/s9y/Book/blob/master/img/install3.png

And lastly these 4, as fullpages as before, with the 2k11 or next theme (no calendar required).
A specific version is not required as long it is 2.x
https://github.com/s9y/Book/blob/master/img/startseite.png
https://github.com/s9y/Book/blob/master/img/startseite_archiv.png
https://github.com/s9y/Book/blob/master/img/startseite_kommentar.png
https://github.com/s9y/Book/blob/master/img/startseite_leer.png

Edit:
Oh - and not to forget
https://github.com/s9y/Book/blob/master/img/backend.php (just after install or with 1 comment and/or 1 entry)
https://github.com/s9y/Book/blob/master/img/edit_entries.png (with 1 or two entries)
https://github.com/s9y/Book/blob/master/img/comments.png (with some nice comments for these first entries)
https://github.com/s9y/Book/blob/master/img/comments2.png
https://github.com/s9y/Book/blob/master/img/quicknotes.png

Thanks for helping!

PS. A current and nice looking Database ER-Modell similar to 
https://github.com/s9y/Book/blob/master/img/dbrel.png would sure be nice to have too.

**Comment by garvinhicking** [comment]
Can I ask why you would specifically need this? As for linux, there's a 
plethora of different looks, there's no unique "linux look". And it 
matters which browser you use. As for the first screenshot, if even 
matters which window manager you use (gnome, kde, enlightenent) and 
which skins, and even which file manager tool. Maybe it's easier for the 
first screenshot to use a console output of "ls -la /directory" (which 
would be 2 lines ;)).

(I don't have any linux windowmanagers, my linux is headless, so I can't 
provide those, except a console screenshot for the first variant if you 
want: 
https://www.dropbox.com/s/nttmv084zecec15/Screenshot%202016-03-19%2012.10.38.png?dl=0)

Regards,
Garvin

**Comment by ophian** [comment]
> Can I ask why you would specifically need this?

I wanted to move to some more modern look - away from such Win XP look - I could try to find this one myself, but all the others are more important to me.
Thanks anyway!

**Comment by garvinhicking** [comment]
Hi!

Ah ok, well we could use then the native look of Chrome or Safari, I 
don't think Linux would be specifically needed?

I can try to make such screenshots on my MAC, but if someone else would 
have the time that would be awesome

**Comment by ophian** [comment]
I'd like to commit this in 9 days as a Serendipity birthday present at the state it is... :-)
Please regard, I updated my initial post for more wishes.

**Comment by ophian** [comment]
If anyone can give me a temporary access to a linux server where I can install Serendipity from scratch, I will make these screenshots quickly on my own. I sadly can't use my own for this or buy a test account account for this. Thanks.

**Comment by donchambers** [comment]
I guess I can set up something for a linux server..  but DB access is an issue, but ftp access would be no problem....  could i just set up a fresh s9y and it's db, then give you s9y & ftp credentials?

**Comment by ophian** [comment]
Best would be a fresh checkout of 2.1 dev with wget, totally untouched. Since I need these first three install pages too. I don't really want to handle with ftp.... (and perm for the first install page too, to get and solve the error!)
Full path things should be something that do not matter to be published to public.
I would give back full access to it after I finished screenshooting als these images I need.
I would need to be able to use Spartacus to install the serendipity_event_adminnotes for example.
If this all is too risky for any of you I would need help with these screenshots. :smile:

**Comment by donchambers** [comment]
Ian - I sent you info via the forum.

**Comment by ophian** [comment]
I managed to find a server myself.

I only have these two help requests left.

A somehow cut screenshot of Bulletproof options like this:
https://github.com/s9y/Book/blob/master/img/bulletproof.png
A current and nice looking Database ER-Modell similar to 
https://github.com/s9y/Book/blob/master/img/dbrel.png

**Comment by yellowled** [comment]
> A somehow cut screenshot of Bulletproof options like this

![bp-options](https://cloud.githubusercontent.com/assets/326223/14015905/add8db4e-f1bc-11e5-8300-1533fc742cd9.png)

Can't do it any larger due to display restriction, but it's at least larger than the original. Can't help with the DB model, though.

**Comment by yellowled** [comment]
(Open preview in new tab to get the full size and save, just in case.)

**Comment by ophian** [comment]
Yes thanks I could do a cut screenshot or fullpage screenshot myself, but what I wanted to have is a cut in the middle snapshot... I am missing a good tool to do this myself.

![bulletproof](https://cloud.githubusercontent.com/assets/1105372/14016099/2a4e3420-f1be-11e5-99b1-e1d4ccedb1ad.png)

**Comment by yellowled** [comment]
> a cut in the middle snapshot

I don't understand what you mean by that. (Unless you mean the zigzag border at the bottom, then I say: “forget about that, it's ugly anyway”.)

**Comment by ophian** [comment]
Ops, I always remembered the bulletprof config image somehow cut and added inbetween, so you have the start and the end, but not all options... Well, in this case I'll just cut as in your example or take it all.

**Comment by ophian** [comment]
@garvinhicking 
I'd like to release the Serendipity HTML Book, Draft Revision 2.1 on tuesday, as a birhday present to Serendipity. Where shall it live via web and where shall I paste the Git repo? Perhaps as an `html`dir inside https://github.com/s9y/Book ? (Thats where it locally currently is.)

**Comment by garvinhicking** [comment]
Wow yeah, that sounds exciting! ^^

Ideally I'd like to simply put it exactly inside that repository as a 
commit, into a subdirectory like you propse, yes!

Regards,
Garvin

**Comment by ophian** [comment]
@garvinhicking 
and what about its web presence?

**Comment by garvinhicking** [comment]
What about the GitHub Pages s9y repository?

**Comment by yellowled** [comment]
Technically, you could just put the HTML (and assets required by it) in a branch `github-pages` of the [book repository](https://github.com/s9y/Book/). Then, the HTML version should be reachable via – I think – http://s9y.github.io/book/. Then again, it might be a good idea to just add it to the docs repository.

**Comment by ophian** [comment]
If I put it into our Github pages as /book/de/ for example, would it matter that it is pure html and a service on its own?

@yellowled Sounds interesting! 
Did you ever try this yourself or hear someone successfully use this /github-pages/ dir approach?

**Comment by yellowled** [comment]
> If I put it into our Github pages as /book/de/ for example, would it matter that it is pure html and a service on its own?

I assume so, but I honestly don't know. The rest of s9y.github.io is Jekyll which then generates HTML. Not sure how it would handle vanilla HTML in the same repository. Technically, you could test it locally, but it seems like quite the hassle for something with a set date.

> Did you ever try this yourself or hear someone successfully use this /github-pages/ dir approach?

I have never used it for a project-based site, but a lot of open source projects do. I do use my “GitHub user page” for the 2k11 user.css generator, though, and that's just HTML, CSS and JS.

Technically, [GitHub pages](https://pages.github.com/) allow for two kinds of pages:

* user (or organization) pages, named after the user (so yours would be http://ophian.github.io), which are generated from a repository in that user's account with a special name
* project pages, which are generated from a *branch* of the project repository with a special name (it's `gh-pages`, by the way, not `github-page`; the URLs for those are different, I think

You *can* use Jekyll for GitHub pages, but you don't *have* to – it does not make sense for the book anyway because the sources are LaTeX and the result is already HTML.

**Comment by ophian** [comment]
So this could actually be what we/I want... (?)
https://help.github.com/articles/creating-project-pages-manually/
Hmmm.... 
Create a `gh-pages` branch in https://github.com/s9y, not in a repository .... or does it mean inside the /book repo for example?
Do I have the rights to do this?

**Comment by yellowled** [comment]
You can not create a branch in https://github.com/s9y; that is not a repository, it is our organization page on GitHub.

You would create a branch `gh-pages` in the repository https://github.com/s9y/Book and add the HTML plus assets required by the HTML to that branch. The result will – as far as I know – be available on http://s9y.github.io/book.

**However**, this *might* not work as expected, because we already use http://s9y.github.io for the new docs. I'm saying “might” because I don't know; I've never done this before, either.

**Comment by yellowled** [comment]
Also, please have a look at https://pages.github.com – it explains all this way better than the GitHub help.

**Comment by ophian** [comment]
I created and pushed a `gh-pages` branch inside `book`, https://github.com/s9y/Book/tree/gh-pages, with a test index.html as first commit. 
But something seems to be wrong - since s9y.github.io/book gets re-directed to http://docs.s9y.org/book and throws a 404 not found page. 
Any ideas? May this be while it is redirected?

**Comment by yellowled** [comment]
> May this be while it is redirected?

I don't think it has to do with the docs.s9y.org being redirected to s9y.github.io, I think it would happen without the “external” domain as well. Some web server “thinks” that s9y.github.io/book should be a part of the s9y.github.io repository, not the s9y/Book repository. Can't explain it better, have no idea what to do about it.

**Comment by yellowled** [comment]
Oh, no – it *is* working, but the repository name is actually case-sensitive. The URL for this is http://s9y.github.io/Book/, not http://s9y.github.io/book/. (Still get redirected to docs.s9y.org/Book, but that's okay, I guess.)

**Comment by ophian** [comment]
This is strange since I tried different sets already...
But now it does indead work.
It may be that it takes a while (or that docs.s9y.org has a sync via cron job or so..)
**Anyway**. This is great!

**Comment by yellowled** [comment]
As far as I know, docs.s9y.org is just a redirect to s9y.github.io.

Also, the deployment of https://github.com/s9y/s9y.github.io is not controlled via cron job, but via push to the repository. That should not concern https://github.com/s9y/Book/ at all.

**Comment by ophian** [comment]
Well that may be true but I was pretty sure to have tried Book too, so perhaps its the github sync...

**Comment by garvinhicking** [comment]
(Closing for new, we should gather issues about the book either in a separate issue tracker, or as new issues here)

(THANKS again 👍 )
