### ISSUE TITLE
New entries are accidentally password-protected through autocomplete

### ISSUE THREAD

**Issue by akomakom** [s9y/Serendipity#398]
Not sure exactly when this started (coincidental with an upgrade or not, I'm leaning towards not).

- Old entries are unaffected (didn't try editing, don't want to)
- New entries are saved, and show on front page and category pages normally (body shows)
- Viewing the entry on the entry page (/archives/###-Name.html) produces a page without the entry body.

Additionally, some of the html is missing on the entry pages.  Not just the text of the entry is missing, but some of the other elements that seem to go before/after.

I've attached the html output for a good and a bad entry (I switched to a standard theme - 1024px for the purpose of submitting this issue).  
[non-working-entry.txt](https://github.com/s9y/Serendipity/files/188096/non-working-entry.txt)
[working-entry.txt](https://github.com/s9y/Serendipity/files/188097/working-entry.txt)

## Additional troubleshooting:

1. chmod -R (nginx user) /whole/install/path
1. Enabled debug logging, nothing of value in there:
[s9ylog.txt](https://github.com/s9y/Serendipity/files/188101/s9ylog.txt)
1. templates_c is 0777 and owned by nginx user.
1. Cleaned template cache using button on Maintenance page.
1. Tried different themes
1. Disabled URL Rewriting

## Steps to reproduce 
(for me)

1. Create a new entry, subject "Test", body "Test".  Any or no category.  No other changes.
1. Save
1. View entry on front page or category as appropriate (works fine)
1. View entry by clicking the hourglass in edit entries listing (no entry body).
1. View entry by clicking on the subject on front page or category listing (no entry body), same url as above.

## Versions:

PHP 5.5.9-1ubuntu4.14 (cli) (built: Oct 28 2015 01:34:46) 
Copyright (c) 1997-2014 The PHP Group
Zend Engine v2.5.0, Copyright (c) 1998-2014 Zend Technologies
    with Zend OPcache v7.0.3, Copyright (c) 1999-2014, by Zend Technologies

Nginx 1.4.6 with factcgi
s9y 2.0.3

Any help would be greatly appreciated.

**Comment by akomakom** [comment]
Upon closer inspection, the non-working entry page is asking for password to view the entry, despite the fact that on the edit page the entry is set to "Entries can be read by : Everyone" and the password field is blank.

Nonetheless, entering some password (not even sure what, browser auto-filled it) allows me to view the entry.  So, the problem is with some hyperactive anti-spam plugin.  I have two even plugins (spamblock and challenge-response), but these are supposed to only affect commenting.  The search continues.

**Comment by akomakom** [comment]
Looks like blanking out the password field on the Edit Entry page does fix the issue. I think my browser auto-fills the field on all new entries.   Not sure why it didn't work the first time I blanked the password, but it works now.   False alarm.

**Comment by yellowled** [comment]
Glad that solved itself. :D

If you have further questions on this or other matters, the [forums](http://board.s9y.org) are probably a better place to get quick help. (Also, we kinda prefer to not have lengthy discussions in GitHub issues.)

**Comment by akomakom** [comment]
Yup, sorry about that, I didn't notice forums - all I saw were old links to php dev mailing lists.

**Comment by onli** [comment]
If the browser is autofilling that, it might still something we want to workaround. We just did that for the configuration, the database password. If it is for example FF reusing the blog login password, then we could use the same workaround here.

**Comment by ophian** [comment]
> If it is for example FF reusing the blog login password, then we could use the same workaround here.

Its not doing this.

**Comment by akomakom** [comment]
For the record, I'm using Chrome with "Autocomplete=On" extension, and the autofill is using my admin password.  I've never (intentionally) used the password-protected page feature before (didn't even know about it).

**Comment by onli** [comment]
That extension was quite important for a while. I'll repoen here so we remember this – the question is whether we can reproduce the error in chrome, possibly also with that extension.

**Comment by onli** [comment]
We had no further report of that, I'll close here for now. Let's have a look at this anyway.
