### ISSUE TITLE
Spend money on uberspace

### ISSUE THREAD

**Issue by garvinhicking** [s9y/Serendipity#402]
Send money before May 23th to Uberspace to pay for the s9y-bot uberspace so that we can use spartacus there. Wait to see if CVS actually works, before we really do that. :)

**Comment by garvinhicking** [comment]
@ddeimeke @onli Sadly the CVS access still does not work. I created a ticket on https://sourceforge.net/p/forge/site-support/12736/ but I doubt they will answer.

So we might want to trash the uberspace account and will need to continue doing it from my server.

**Comment by onli** [comment]
We need the CVS as the mirroring works via that? Otherwise this might be a good moment to cut that.

**Comment by garvinhicking** [comment]
Yes, the whole SF.net default spartacus for most installations uses the CVS checkouts.

If we cut that, it would mean that users who picked that mirror will not see new updates (or might even get errors).

I can't oversee the implications of removing CVS easily, we would need to check what exactly would need changing.

**Comment by ddeimeke** [comment]
In the end it is about where Spartacus pulls the updates from, isn't it?

So, what about updating the Spartacus plugin to pull from different sources (other than Sourceforge) and let this plugin be the only one which stays on Sourceforge.

In case a user wants to install or update a plugin from Sourceforge he/she should get an error message stating that he/she should update the Spartacus plugin first.

**Comment by garvinhicking** [comment]
@ddeimeke The Problem is that Spartacus runs on the client, so we can only change things for the future and break it for everyone not using the most up to date version. Everyone would need to update to 2.1 then immediately, because even with the maintenance 2.0.x version it would no longer work.

**Comment by garvinhicking** [comment]
should work now.
