### ISSUE TITLE
[serendipity_plugin_piwik] Please show stats in the backend

### ISSUE THREAD

**Issue by ddeimeke** [s9y/Serendipity#404]
I would like to see Piwik statistics (maybe including the graphs) in the backend and not in the sidebar of the blog.

**Comment by garvinhicking** [comment]
Should be easy by making an associated event plugin, that uses the same code like the sidebar plugin, but hook into either the dashboard view of the backend or its own section

**Comment by th-h** [comment]
WONTFIX.
