### ISSUE TITLE
lsrstopper: Intermediate page without link

### ISSUE THREAD

**Issue by onli** [s9y/Serendipity#408]
The LSR stopper plugin in the beginning (and given the page self desrciption, that's still the idea) converted pointed to a page which explained the problematique but still allowed visitors to go to the original news article. That does not work anymore, the page visitors arrive is the generic description page without button. Example: In https://www.onli-blogging.de/1542/NSU-Im-Kampf-gegen-die-Elemente.html is a link to http://www.focus.de/politik/deutschland/nazi-terror/anzeige-erstattet-akten-nsu-raubueberfall-vernichtung-1_id_3503033.html which becomes http://leistungsschutzrecht-stoppen.d-64.org/blacklisted/?url=aHR0cDovL3d3dy5mb2N1cy5kZS9wb2xpdGlrL2RldXRzY2hsYW5kL25hemktdGVycm9yL2FuemVpZ2UtZXJzdGF0dGV0LWFrdGVuLW5zdS1yYXVidWViZXJmYWxsLXZlcm5pY2h0dW5nLTFfaWRfMzUwMzAzMy5odG1s.

It's possible it's not the plugin which is at fault, but that the intermediary page is broken. @mattsches, do you know more?

**Comment by mattsches** [comment]
I will take a look at this as soon as I can find the time. To me, it sounds like the intermediary page changed somehow...

**Comment by mattsches** [comment]
Ok, I tried to reacquaint myself with this plugin ;) It's a small plugin, so there isn't much that can go wrong. Can you please check a few things for me:

- is there a `lsrstopper` directory in your `PATH_SMARTY_COMPILE` dir (probably `templates_c`)? Is there a (current) cache file in there?
- if so, its contents should be the same as in http://leistungsschutzrecht-stoppen.d-64.org/blacklist.txt
- if not, has anything changed with respect to the `HTTP_Request`/`HTTP_Request2` libraries recently?

**Comment by onli** [comment]
I had the plugin set to be inactive. I now deleted and re-installed it. Checked that the situation is unchanged, i.e. the link to focus still leads to a page explaining the situation but not providing a way to reach the focus article.

Your questions:

> is there a lsrstopper directory in your PATH_SMARTY_COMPILE dir (probably templates_c)? Is there a (current) cache file in there?

The directory is in templates_c, yes.There is a cache file there dating to today.

> if so, its contents should be the same as in http://leistungsschutzrecht-stoppen.d-64.org/blacklist.txt 

Looking at it, first and last entry are the same. Also, focus is the first.

> if not, has anything changed with respect to the HTTP_Request/HTTP_Request2 libraries recently?

Actually yes. HTTP_Request is getting finally replaced, as PHP7 does not accept it anymore. See https://github.com/s9y/Serendipity/issues/399#issuecomment-215149614 and the related commits. The blog in question however is still using PHP 5.5.9.

I'm not sure it is a plugin issue. Maybe yes, maybe the links get hashed the wrong way, or mangled somewhere. But it might also be that the page broke. Their "Link erzeugen" widget does not work for me either.

**Comment by onli** [comment]
@mattsches You had no success replicating the issue?

**Comment by mattsches** [comment]
@onli No success so far, works for me, see [this example](https://blog.sperrobjekt.de/content/1000470-Erste-Fahrradstrasse-in-Wiesbaden.html#extended) ... there are a couple of links to newspaper websites that work as expected. I also revisited [your blog post](https://www.onli-blogging.de/1542/NSU-Im-Kampf-gegen-die-Elemente.html) and the link to focus.de seems to be handled correctly.

**Comment by onli** [comment]
The link to focus.de does not lead you to [this intermediary page without a way to go to the real article](http://leistungsschutzrecht-stoppen.d-64.org/blacklisted/?url=aHR0cDovL3d3dy5mb2N1cy5kZS9wb2xpdGlrL2RldXRzY2hsYW5kL25hemktdGVycm9yL2FuemVpZ2UtZXJzdGF0dGV0LWFrdGVuLW5zdS1yYXVidWViZXJmYWxsLXZlcm5pY2h0dW5nLTFfaWRfMzUwMzAzMy5odG1s) ?

**Comment by mattsches** [comment]
Ah, I misunderstood your issue, sorry! This actually seems to be a problem on their si[d|t]e. Their link generator (in the left sidebar) seems to be broken, too. My guess is that the project is somewhat abandoned and something broke.

**Comment by onli** [comment]
Yeah, I thought so. I assume there is nothing you can do directly for the project, or is there an alternative page where the project could link to? If not we should deprecate the plugin I fear, totally blocking the article is at least not what I wanted as a user of it.

**Comment by mattsches** [comment]
I don't know of any alternative, so deprecation is probably the way to go. How _do_ we actually deprecate plugins?

**Comment by yellowled** [comment]
We [move them to Siberia](https://github.com/s9y/additional_plugins/commit/ac852a36d5693e90c81a3ab5989603a36b23f2c4).

**Comment by yellowled** [comment]
After 4,5 months, I took the liberty of executing the deprecation.
