### ISSUE TITLE
Cronjob problem with Spartacus

### ISSUE THREAD

**Issue by ddeimeke** [s9y/Serendipity#410]
I updated all blogs to Serendipity 2.1-alpha3 and enabled the cronjob plugin.

Even without telling Spartacus to do daily updates I get the following error message:

```
[31.05.2016 10:04] Executing "cronjob_always"<br />
<br />
<b>Fatal error</b>:  Call to a member function add() on null in <b>/srv/www/deimeke.net/silvia/blog/plugins/serendipity_event_spartacus/serendipity_event_spartacus.php</b> on line <b>1168</b><br />
```

Exactly the same error, when enabling Spartacus cronjobs.

**Comment by onli** [comment]
I guess that is a wrongly named variable. Could you test a small patch? In serendipity_event_spartacus.php on line 1168, please change

    $propbag->add('type', 'suboption');

to

    $bag->add('type', 'suboption');

**Comment by onli** [comment]
Strike that. I think the line is nonsensical and added by mistake in a refactoring commit. It will be best to just remove it, with the else. Thanks for catching that before the beta!

**Comment by onli** [comment]
@ddeimeke With https://github.com/s9y/Serendipity/commit/e87ab8729da6c437c7b8743f9524e375f1d78e3c this should now be fixed. Can you confirm?

**Comment by ddeimeke** [comment]
I confirm that it works now.
