### ISSUE TITLE
Recent beta1 (git pull) gives feed error

### ISSUE THREAD

**Issue by ddeimeke** [s9y/Serendipity#415]
I updated my blog to the recent beta via "git pull" and now I get a feed error.

https://www.deimeke.net/dirk/blog/index.php?/feeds/index.rss2

```
    XML Parsing Error: syntax error
    Location: https://www.deimeke.net/dirk/blog/index.php?/feeds/index.rss2
    Line Number 1, Column 1:Invalid RSS version specified or RSS-template file not found
    ^
```

http://www.feedvalidator.org/check.cgi?url=https%3A%2F%2Fwww.deimeke.net%2Fdirk%2Fblog%2Findex.php%3F%2Ffeeds%2Findex.rss2

http://board.s9y.org/viewtopic.php?f=3&t=20801

**Comment by onli** [comment]
https://github.com/s9y/Serendipity/commit/3179ed7d579209ffe25f71a37b24d0e70536cc3c fixes it, confirmed in forum. I'll close here to make that visible to the others.
