### ISSUE TITLE
serendipity.css is missing fallback styles

### ISSUE THREAD

**Issue by yellowled** [s9y/Serendipity#417]
`serendipity.css.php` is supposed to combine styles emitted by plugins,  `/templates/default/style_fallback.css`, the current theme's `style.css` and `user.css`. Currently, `/templates/default/style_fallback.css` is **not** included. (I assume this is because it's fetched from the default theme's directory? See below.)

Tested in 2.1-beta1 (current `master`) on PHP 5.6.21 (fast-cgi).

Assigned this to @onli since it *seems* related to recent changes made to `serendipity_getTemplateFile()` mentioned in #416.

**Comment by onli** [comment]
Yes, that is related. 'default' is no longer checked if it is not explicitly set as the engine.

I'd like to fix that by moving the file into 2k11, the real default template since 2.0.

**Comment by yellowled** [comment]
I don't see a reason not to, although I did not really follow the changes in the template fallback chain you made. But `style_fallback.css` is lterally only referenced in `serendipity.css.php`, so it should not matter where it's located at.

**Comment by onli** [comment]
Okay. I copied it to 2k11. It added the styles in my devblog.

**Comment by yellowled** [comment]
My dev blog won't `git pull` right now, I'll try again tomorrow to confirm and close.

**Comment by yellowled** [comment]
(Fixed, confirmed.)
