### ISSUE TITLE
Adapt core and additional themes to new serendipity_getFile 

### ISSUE THREAD

**Issue by yellowled** [s9y/Serendipity#419]
See http://board.s9y.org/viewtopic.php?p=10445984#p10445984

**Comment by yellowled** [comment]
@donchambers If you have seperate development copies of Clean Blog and Timeline, you'll want to backport the changes in 0490401f3a22ce9f22ff21431838b9ec4b79b0f8.

**Comment by donchambers** [comment]
Will do.   Sorry I am a little behind.

**Comment by yellowled** [comment]
Perfectly okay, just a heads up.
