### ISSUE TITLE
Autoupdater can't install 2.1-beta2

### ISSUE THREAD

**Issue by onli** [s9y/Serendipity#425]
The issue is that the link differs from the usual schema (https://github.com/s9y/Serendipity/archive/2.1-beta2.zip vs https://github.com/s9y/Serendipity/releases/download/2.0.4/serendipity-2.0.4.zip). Either the autoupdater plugin has to be modified to use the archive link when installing a beta version (in that case I can implement that change), or the release has to be edited to use the normal scheme (for that I'll assign @garvinhicking for now).

**Comment by yellowled** [comment]
FWIW, I can not use the releases link to `wget` the (stable) zipfile on Uberspace, I need to use the archive link. For some reason (I have no clue about this), the releases link only seems to work in browsers, which most likely is something on GitHub's side. I think.
