### ISSUE TITLE
Image download not working anymore

### ISSUE THREAD

**Issue by schoos76** [s9y/Serendipity#428]
With 2.0.5, I can't download any images from other websites anymore:
PHP Fatal error:  Call to undefined method HTTP_Request::getEffectiveUrl() in $BASE/include/admin/images.inc.php on line 228,

I think it is caused by commit fbdd50a448ed87ba34ea8c56446b8f1873eadd6f, which adds the relevant line in images.inc.php and ignores that HTTP_Request doesn't have the getEffictiveUrl method -Request2 would have.

**Comment by garvinhicking** [comment]
Thanks a lot for reporting this. Indeed I broke this, I'm terribly sorry. I tried to fix this with this commit:

https://github.com/s9y/Serendipity/commit/9c7629900e8073370f824cd0ba958aabf0048284

Can you try this out and see if that works out for you?

**Comment by schoos76** [comment]
I plan to have a look into that on this weekend - hopefully the gods of time management support that idea :)

**Comment by onli** [comment]
@schoos76 Did you have a chance to test this?
