### ISSUE TITLE
[oembed] error within settings, plugin not working in frontend

### ISSUE THREAD

**Issue by bauigel** [s9y/Serendipity#429]
The following error-messages are appearing, when i go into the plugin-settings. In frontend, there is no output. Don't know since when this happens.

```
Warning: simplexml_load_file(): I/O warning : failed to load external entity ".../plugins/serendipity_event_oembed/oembed/providers.xml" in .../plugins/serendipity_event_oembed/oembed/ProviderList.php on line 5

Warning: Invalid argument supplied for foreach() in .../plugins/serendipity_event_oembed/oembed/ProviderList.php on line 6
```

**Comment by garvinhicking** [comment]
Does this providers.xml file exist in your installation? Maybe you can edit that ProviderList.php file and change this:

$xml = simplexml_load_file(PLUGIN_OEMBED_PROVIDER_XML_FILE);// PROVIDER_XML comes from config.php

to:

die("TRYING TO LOAD: " . dirname(__FILE__) . " || " . PLUGIN_OEMBED_PROVIDER_XML_FILE . "<br />\n");

to get an output of where it tries to load the file from exactly.

**Comment by bauigel** [comment]
The code gives following return:

`TRYING TO LOAD: . || /var/www/virtual/.../plugins/serendipity_event_oembed/oembed/providers.xml`

FYI: I use S9y 2.1 B3. Maybe there is something different to 2.0?

**Comment by garvinhicking** [comment]
The directory after " || ", did you check if that mentioned exact directory+file exists? Seems to me that it is missing in your install...?!

**Comment by bauigel** [comment]
Yes, directory and file exists.

I don't know why, but output in frontend is generated again. Maybe this has been an problem with embed.ly

Errors in backend-config still appears. Thats strange because of loaded content. :-/

**Comment by garvinhicking** [comment]
Fixed with a simplxml_load_string replacement
