### ISSUE TITLE
Config option 'show_mail' in rss.php should be 'feedShowMail'

### ISSUE THREAD

**Issue by fugue88** [s9y/Serendipity#430]
This causes RSS feeds to always display "nospam@example.com" as the author's name, even if the config setting to show e-mail has been set to "yes".

See use of `show_mail` here: https://github.com/s9y/Serendipity/blob/3179ed7d579209ffe25f71a37b24d0e70536cc3c/rss.php#L240

However, the name of the config variable was changed to `feedShowMail`: https://github.com/s9y/Serendipity/blob/f63d884cfe262cf6b5e402307d7aacb21d830718/include/functions_upgrader.inc.php#L428

**Comment by fugue88** [comment]
```
--- rss.php~    2015-11-13 14:13:14.000000000 -0700
+++ rss.php     2016-12-03 16:02:09.831954899 -0700
@@ -233,7 +233,7 @@
     header('Location: ' . serendipity_get_config_var('feedCustom'));
     exit;
 }
-$metadata['showMail'] = serendipity_db_bool(serendipity_get_config_var('show_mail', $metadata['showMail']));
+$metadata['showMail'] = serendipity_db_bool(serendipity_get_config_var('feedShowMail', $metadata['showMail']));
 
 $file_version  = preg_replace('@[^0-9a-z\.-_]@i', '', $version);
 $metadata['template_file'] = serendipity_getTemplateFile('feed_' . $file_version . '.tpl', 'serendipityPath');
```

**Comment by onli** [comment]
Hi @fugue88, good catch. Would you be up to open a PR, so this can be easily merged? Would also record that the fix stems from you, which would be a plus for me.
