### ISSUE TITLE
Possible HTTP Response Splitting (CRLF)

### ISSUE THREAD

**Issue by Shinkurt** [s9y/Serendipity#434]
Hello,

In Serendipity/comment.php:

`205: header('Location: ' . ('https://' : 'http://') . $_SERVER['HTTP_HOST'] . str_replace('\\', '/', dirname($_SERVER['PHP_SELF'])) . '/serendipity_admin.php'); `

Notice that dirname($_SERVER['PHP_SELF']) is actually user controllable and in older PHP versions attackers may send in CRLF (%0A or %0D) to split headers apart.

Test case: 
`echo dirname($_SERVER['PHP_SELF']);`
site.com/test.php/anything%0ANew:header/x will put CRLF character not encoded. 

Doing urlencode() on dirname($_SERVER['PHP_SELF']) will fix this specific issue.

Thanks,

**Comment by garvinhicking** [comment]
First, please to not report security related bugs publically, thank you (more on https://docs.s9y.org/docs/contributing/index.html) :-)

Second, what code are you actually referring to? In our comment.php this code is currently used:

```
$sc_url = $serendipity['baseURL'] . 'comment.php?serendipity[entry_id]=' . $id . '&success=true&url=' . urlencode($_SERVER['HTTP_REFERER']);
                if (serendipity_isResponseClean($sc_url)) {
                    header('Status: 302 Found');
                    header('Location: ' . $sc_url);
                }
```

I don't see the code you are referring to?

**Comment by Shinkurt** [comment]
Oh sorry, I was actually refering to exit.php (https://github.com/s9y/Serendipity/blob/2797bfdf02be2b415ea65d5d6536a412d196be83/exit.php) 

```
elseif (isset($_GET['url']) && !empty($_GET['url'])) {
    // No entry-link ID was submitted. Possibly a spammer tried to mis-use the script to get into the top-list.
    $url = strip_tags(str_replace('&amp;', '&', base64_decode($_GET['url'])));
}
if (serendipity_isResponseClean($url)) {
    header('HTTP/1.0 301 Moved Permanently');
    header('Status: 301 Moved Permanently');
    header('Location: ' . $url);
}
```

I think I might have older version or I meant some other file. :)

**Comment by garvinhicking** [comment]
@Shinkurt Thanks for clarification, how about this patch, that should patch our central isResponseClean for older PHP versions to reject %0D/%0A?

`````
diff --git a/include/functions.inc.php b/include/functions.inc.php
index 7b0d8ad..df9146f 100644
--- a/include/functions.inc.php
+++ b/include/functions.inc.php
@@ -1023,7 +1023,7 @@ function serendipity_discover_rss($name, $ext) {
  * @return  boolean     Return true on success, false on failure
  */
 function serendipity_isResponseClean($d) {
-    return (strpos($d, "\r") === false && strpos($d, "\n") === false);
+    return (strpos($d, "\r") === false && strpos($d, "\n") === false && stripos($d, "%0A") === false && stripos($d, "%0D") === false);
 }
 
 /**
`````

**Comment by Shinkurt** [comment]
@garvinhicking cool. I think this should be closed now. :)
