### ISSUE TITLE
Cross Site Scripting 

### ISSUE THREAD

**Issue by Shinkurt** [s9y/Serendipity#435]
In include/admin/entries.inc.php:

405: echo '<div class="msg_notice"><span class="icon-attention-circled" aria-hidden="true"></span> ' . sprintf(MULTICHECK_NO_ITEM, $_SERVER['HTTP_REFERER']) . '</div>' . "\n"; 

Notice that $_SERVER['HTTP_REFERER']) is user controllable and one can redirect from a malicious site with payload to cause this to echo out and causing XSS. use htmlentities() should solve this.

Thanks,

**Comment by garvinhicking** [comment]
First, please to not report security related bugs publically, thank you (more on https://docs.s9y.org/docs/contributing/index.html) :-)

I fixed this issue for the upcoming 2.1 release, thank you!
