### ISSUE TITLE
File Manipulation

### ISSUE THREAD

**Issue by Shinkurt** [s9y/Serendipity#436]
In tests/coverage/append.php:

14: file_put_contents($_SERVER['SCRIPT_FILENAME'] . '.phpunit_' . $_COOKIE['PHPUNIT_SELENIUM_TEST_ID'], var_export($data, TRUE)); 

Notice that $_COOKIE['PHPUNIT_SELENIUM_TEST_ID'] is user-controllabe and used to write on files. Now since xdebug_get_code_coverage(); is called I assumed the person needs to be administrator before injecting cookies that will be writable but using any XSS vulnerabilities (reported one earlier) or any CRLF issues, one can write in these cookies.

Fix: precheck, or any other way.

Thanks,

**Comment by Shinkurt** [comment]
[data://x](data://x)

**Comment by garvinhicking** [comment]
First, please to not report security related bugs publically, thank you (more on https://docs.s9y.org/docs/contributing/index.html) :-)

I have disabled those selenium testing files now. This was more than a work in progress and we never really followed up on this.

**Comment by Shinkurt** [comment]
@garvinhicking will be there a patch to prevent this for now?

**Comment by garvinhicking** [comment]
You can actually just delete the tests/ directory as it's not needed, do you mean that? We will suggest that in our blog posting when we release the 2.1 version...
