### ISSUE TITLE
media gallery can only be sorted to "upload"

### ISSUE THREAD

**Issue by bauigel** [s9y/Serendipity#437]
In current master (v 2.1) it is only possible to sort media to upload-time. Things like filename are missing.

![bildschirmfoto 2017-01-01 um 16 23 49](https://cloud.githubusercontent.com/assets/1295005/21581892/1f130abc-d044-11e6-8079-33e349b02556.png)

**Comment by garvinhicking** [comment]
Thanks for this. Maybe @onli can have a look. I see this code in include/functions_images.inc.php:

````
$order_fields = serendipity_getImageFields();
// reset filename for building template filters, since this is hardcoded as 'only_filename'
unset($order_fields['i.name']);
````

This actually prevents anyone from using the sort order "by filename" in the dropdown. I don't actually know why this was changed, it was done by @ophian and I don't know if he is willing to comment on this any further. 

Plus,  there is this empty checkbox below the sort order, referring to a missing CONST.HIDE_SUBDIR_FILES constant (which I don't really know what that would do at this point).

Any takers for this? :-)

(@bauigel - you will get more dropdown options if you disable the Simple Filter config toggle. But also not filename)

**Comment by garvinhicking** [comment]
I see that Ian committed this fix to his Fork: https://github.com/ophian/styx/commit/2d3315eb525ca513a679d4c84b21038229138e94#diff-66ba985797ad4611ca378bfb1d373140

Maybe you want to try that out, however he removed another thing for "only filenames" which I think was something useful at some point, and at this time I cannot dig further than this.

**Comment by bauigel** [comment]
This fix works for me, i can sort for filenames again. Thank you!
