### ISSUE TITLE
Support rel=trackback

### ISSUE THREAD

**Issue by onli** [s9y/Serendipity#438]
The current way to support trackbacks via RDF-tags is ugly and not reliable (see https://www.onli-blogging.de/index.php?url=1596/Zu-Sind-Trackbacks-und-Pingbacks-out.html#c7140 for a funny example of how it can fail). An alternative way to detect the trackback target URL is rel=trackback, a metatag in the header, the same way it is done for pingbacks. We should add support for it, both by searching for this tag when sending trackbacks and by modifying our themes to emit the tag.

**Comment by garvinhicking** [comment]
We have this serendipity_pingback_autodiscover which works on <link rel="pingback">, so maybe that can be utilized also for the trackback autodiscovery...?!

**Comment by yellowled** [comment]
(If it's in `<>`, it needs to be escaped using `` on GitHub.)

**Comment by onli** [comment]
18f6429f32faebc6244a9a7176d0fce08bad41c8 looks bigger than it is, basically all this needed was one line to generate the rel=trackback element, and one `if (preg_match(...))`  and one assignment to use the header. The rest is just code moved around to give priority to this check.

But some more testing of this would be great. Already from serendipity to itself. I can run this against ursprung. It does not seem like wordpress is actually using this mechanism (anymore?). Maybe someone knows of another blog engine we could test against.

**Comment by garvinhicking** [comment]
Could you document this in docs/NEWS?

**Comment by onli** [comment]
Done. Would otherwise have waited till it is tested by others.

**Comment by onli** [comment]
I'll close here for now. The header gets emitted and detected.
