### ISSUE TITLE
Security check Spartacus http fetching

### ISSUE THREAD

**Issue by ophian** [s9y/Serendipity#44]
Quest: What about checksum check for security?
Answ.: Checksum-checks could be added, but of course this is some work to implement...

Anyone?

**Comment by garvinhicking** [comment]
We can:

* add a md5 checksum to the XML for our daily build
* When a file is downloaded through Spartacus, build the MD5 of the local file and compare it to the remote XML checksum, probably return errors/alerts
* Also add a check for each plugin file to our checksum comparison tool

Probable issues with this: This enlarges the XML about 10-15% I guess, which raises the PHP memory limit. The whole check will also take longer and more memory to parse, we might hit limits much earlier with this...

Another thing: We should add https:// to www.s9y.org and add it as a https:// mirror.

**Comment by yellowled** [comment]
@garvinhicking You wanna revisit that statement after 5 months? :) Other than that, I would just close it.

**Comment by garvinhicking** [comment]
We need to leave it open, it is still an issue.

**Comment by th-h** [comment]
Closed as WONTFIX after five years.
