### ISSUE TITLE
2.1 RC1: preg_match error when deleting comments

### ISSUE THREAD

**Issue by onli** [s9y/Serendipity#442]
When deleting a comment from the frontend, I get this error:

```
Fatal error:  Uncaught ErrorException: Warning: preg_match() expects at least 2 parameters, 1 given in /var/www/html/comment.php:14
Stack trace:
#0 [internal function]: errorToExceptionHandler(2, 'preg_match() ex...', '/var/www/html/c...', 14, Array)
#1 /var/www/html/comment.php(14): preg_match('@^https?://www\\...')
#2 {main}
  thrown in /var/www/html/comment.php on line 14
```

This seems to have been introduced in https://github.com/s9y/Serendipity/commit/6285933470bab2923e4573b5d54ba9a32629b0cd, and I want to coordinate hereb efore fixing as it was security related, to not undo things. @garvinhicking, I assume, the preg_match check was supposed to run against $_SERVER['HTTP_REFERER']?

**Comment by garvinhicking** [comment]
Dang, thanks for bringing it to my attention. I messed that up, should be fixed now
