### ISSUE TITLE
Search for plugin updates broken in 2.1-RC1

### ISSUE THREAD

**Issue by smarsching** [s9y/Serendipity#443]
I just upgrade from 2.0.5 to 2.1-RC1 and I am using the 2k11 theme for both the frontend and backend.

When trying to search for plugin updates by clicking on the "Update plugins" button on the plugins page of the backend, I get the following error message:

> Your browser did not sent a valid HTTP-Referrer string. This may have either been caused by a misconfigured browser/proxy or by a Cross Site Request Forgery (XSRF) aimed at you. The action you requested could not be completed.

The error message seems to be generated by the `serendipity_checkFormToken` function because the CSRF token is missing. The link of the "Update Plugins" button is generated by `plugins/serendipity_event_spartacus/serendipity_event_spartacus.php` line 1237 and seems to be missing the code for appending the CSRF token.

I am not sure whether using the CSRF token in a GET request is a good idea (due to the danger of leaking it through the HTTP referrer), so the preferred way would probably be changing the link to a single-button form that triggers a POST request. If you think that this is the right concept for dealing with this issue, please leave a comment so that I can try to write a patch.

**Comment by smarsching** [comment]
Never mind, I just saw that this has already been fixed by d4d46855c29971c014eed33e2b8fb22f8c87b305.

**Comment by onli** [comment]
Regardless, thanks for testing the RC. It was unfortunate that bug slipped through, but it is good to see it would have been found.
