### ISSUE TITLE
Information leakage by $admin_vars.version_info

### ISSUE THREAD

**Issue by leyrer** [s9y/Serendipity#450]
$admin_vars.version_info reports back the Serendipty, PHP and OS version. So a call to a page using templates/2k11/admin/index.tpl displays        
    Powered by Serendipity 1.7.2 and PHP 5.6.29-0+deb8u1
As this makes it very easy for an attacker to find a vulnerability, ... this information should not be displayed.

Possible solutions:
a) $admin_vars.version_info returns an empty string
b) $admin_vars.version_info returns just "Serendipity"

**Comment by yellowled** [comment]
There are more possible solutions. We could make it configurable or remove it altogether.

I don't think it makes much sense to change what `$admin_vars.version_info` emits – I seem to remember that this was kept around because it makes support easier/quicker. Supporters can quicky look up the s9y/PHP version, something people often fail to mention.

**Comment by leyrer** [comment]
If possible, I would show the detailed info it on the admin pages (authenticated user) but not for anonymous users (login screen) - if you can differentiate between those.

**Comment by onli** [comment]
I don't know.

Having the versions available helps a lot in the forum, and in those cases we are not authenticated users. But to obscure the version numbers is a first line of defence against attackers, it makes it a little bit harder to select the right attack, especially against those old PHP versions that are still around a lot.

Maybe hiding it for unauthenticated users is okay. It would make support harder, but asking the user to give the information would still be easy ("which PHP version do you use? That is written in the footer of the backend").

**Comment by yellowled** [comment]
Then again, most people who don't provide their PHP/s9y version in the forums also don't mention their URL, so you have to ask anyway.

**Comment by gnuheidix** [comment]
I use the following configuration in _serendipity_config_local.inc.php_ to prevent exposing these security related pieces of information.

`$serendipity['expose_s9y'] = false;`

@leyrer could you please check if this solves your problem.

**Comment by yellowled** [comment]
Great idea, @gnuheidix. That should indeed work. It does suppress the version numbers in the footer both for anonymous as well as logged in users.

Sorry I wasn't aware of this. We should add this to the docs as a FAQ. (Usually, I request a feature like this in the forums thinking I've come up with a great idea, only for @garvinhicking to tell me it already exists and is implemented.)

**Comment by yellowled** [comment]
Also, since `serendipity_config_local.inc.php` is *not* part of the s9y core, this is safe in case of an update.

**Comment by yellowled** [comment]
(Added [to the FAQ](https://docs.s9y.org/docs/faq/index.html#docs-i-dont-want-the-login-screen-to-expose-the-s9y-and-php-version).)

**Comment by yellowled** [comment]
Considering this fixed after more than three weeks of inactivity with a viable solution.
