### ISSUE TITLE
Installation of theme is not secure with a CSRF token

### ISSUE THREAD

**Issue by We5ter** [s9y/Serendipity#452]
Hello,

payload:http://127.0.0.1/serendipity/serendipity_admin.php?serendipity[adminModule]=templates&serendipity[adminAction]=install&serendipity[theme]=bartleby&serendipity[spartacus_fetch]=bartleby

Use tag `<img>` in another html to request this payload,after serendipity's admin visits it,theme will be changed.

version:2.0.5

**Comment by garvinhicking** [comment]
@onli I cannot currently take on this. We should be able to use the same CSRF check we enabled for plugins.

**Comment by onli** [comment]
Okay, I assigned you by default since it is security related. I'll add a token check.

**Comment by onli** [comment]
I just pushed a fix for this. If you could test the fix as well, that would be greatly appreciated.

Thanks again for the report.

**Comment by We5ter** [comment]
@onli thank you for fixing it.
