### ISSUE TITLE
Multiple file manipulation in functions_installer.inc.php when first installing

### ISSUE THREAD

**Issue by We5ter** [s9y/Serendipity#453]
`Line 591: mkdir mkdir($_POST['serendipityPath'] . $_POST['uploadPath'], $umask)`
`Line 600: mkdir mkdir($_POST['serendipityPath'] . PATH_SMARTY_COMPILE, $umask) `
`Line 609: mkdir mkdir($_POST['serendipityPath'] . PATH_ARCHIVES, $umask) `

when we first install,if we set **uploadpath** to `../../../../../tmp/uploads`,then the directory will be appear in `/tmp`

<img width="1149" alt="screen shot 2017-03-03 at 3 19 18 pm" src="https://cloud.githubusercontent.com/assets/8722530/23541889/0e3ee5ce-0025-11e7-9d34-f7abf9775ce7.png">

<img width="567" alt="screen shot 2017-03-03 at 3 20 43 pm" src="https://cloud.githubusercontent.com/assets/8722530/23541907/324fb5ec-0025-11e7-97f2-6631780fdae4.png">

**Comment by garvinhicking** [comment]
My question would be: Your apache has access to that directory; why should Serendipity not allow to be configured like this (you're the admin if you can set this)? If you install s9y, you can upload arbitrary PHP to your server already...

**Comment by We5ter** [comment]
@garvinhicking yep,you are right,but I can access other directory with s9y only,so I think this is a Unauthorized access.

**Comment by garvinhicking** [comment]
@We5ter Well you could upload a PHP script where you in fact can access /tmp - every PHP script is able to do that in your environment. In fact it would be authorized access, if you ca do it in your own PHP scripts. Serendipity uses the privileges that the scripts have that you upload.

For normal operation, an editor should not have the ability to upload and execute PHP code, but administrators (also when installing) usually have the full privileges, so I think we should allow admins to configure whatever path they want for uploads that the server has privileges for.

**Comment by We5ter** [comment]
@garvinhicking  I understand what you said.I also agree with you.

I just try to suggest from a technical point...

From your code `mkdir($_POST['serendipityPath'] . $_POST['uploadPath'], $umask)`,you want the editor to mkdir under `http://127.0.0.1/serendipity/`

so if you allow admins to configure whatever path they want for uploads that the server has privileges for.your code `mkdir($_POST['serendipityPath'] . $_POST['uploadPath'], $umask)` doesn't make sence.

You only need write it like `mkdir($_POST['uploadPath'], $umask)`

**Comment by garvinhicking** [comment]
We want by default (which is the more common case) to make the user enter a relative path, but not prevent the user to add a directory outside, so I think the current mechanism would be fine for us... thanks for discussing this!

**Comment by We5ter** [comment]
@garvinhicking OK,I also agree with you now,because it just work when first installing.and I should say thanks too.
