### ISSUE TITLE
Disable comments for entry is not secure with CSRF token

### ISSUE THREAD

**Issue by We5ter** [s9y/Serendipity#455]
vul address:http://127.0.0.1/serendipity%202/comment.php?serendipity[switch]=disable&serendipity[entry]=1

<img width="916" alt="screen shot 2017-03-03 at 3 45 57 pm" src="https://cloud.githubusercontent.com/assets/8722530/23542503/7f806246-0028-11e7-99e2-da92c34ec934.png">

**Comment by garvinhicking** [comment]
@We5ter With which s9y version did you test this? Our recent 2.1 version should contain CSRF protection against this.

**Comment by We5ter** [comment]
@garvinhicking  I test it on with s9y version 2.0.5,so it has been fixed.

**Comment by yellowled** [comment]
@garvinhicking Should we close this since it seems to be fixed in 2.1.x?

**Comment by We5ter** [comment]
Alright,thanks.
