### ISSUE TITLE
stored XSS in v2.1-rc1

### ISSUE THREAD

**Issue by We5ter** [s9y/Serendipity#456]
1.create a **standard editor** named "test",
<img width="664" alt="screen shot 2017-03-04 at 4 43 36 pm" src="https://cloud.githubusercontent.com/assets/8722530/23577450/2e9c2644-00fa-11e7-9059-2f56c1a4c5cf.png">

2.write a new entry 

`<img src=1 onerror=alert(1)>`

<img width="1278" alt="screen shot 2017-03-04 at 4 44 22 pm" src="https://cloud.githubusercontent.com/assets/8722530/23577454/382632a4-00fa-11e7-8c61-a18e1b1dde30.png">

3.then post this entry,when admin view it ,XSS occur!

<img width="1280" alt="screen shot 2017-03-04 at 4 44 36 pm" src="https://cloud.githubusercontent.com/assets/8722530/23577457/4661e1c4-00fa-11e7-9daa-32d6facbf87e.png">

**Comment by onli** [comment]
Hi @We5ter 

Thanks for reporting. But there is no sound defence against that, as far as I can see. It is absolutely necessary that javascript embedded into entries gets executed, as that enables a broad range of use cases for writing better articles - think charts, for example. We could now escape the js only when an admin is logged in, but then he would no longer realize what happens on the blog.

If you are in a multi-user blog, consider installing the serendipity_event_xsstrust plugin. With it you can define which users get the ability to post html in entries.

**Comment by We5ter** [comment]
Thank you for your quickly reply.

As you said,I have installed serendipity_event_xsstrust plugin and set value to "3"(plugin say this mean banned),but from this pugin description,this plugin just shows all authors with their ethic value,but cannot stop users get the ability to post html in entries.

And,I suggest:

As a rich text editor,other cms also allow inject html/js in entries,so I think serendipity should use CSP or httponly  or filter user's input using Regular Expression

<img width="1004" alt="screen shot 2017-03-04 at 7 57 31 pm" src="https://cloud.githubusercontent.com/assets/8722530/23578559/c90b4f24-0114-11e7-920d-65f341590da6.png">

**Comment by onli** [comment]
Oh, that looks like a valid bug in htmlpurifier! I will try out whether the current version of that fixes it.

**Comment by We5ter** [comment]
@onli Thank you for your hard work!

**Comment by onli** [comment]
There is still an issue, but you installed the wrong plugin.

You installed serendipity_plugin_xsstrust, the sidebar plugin that only shows the values. You'd need the serendipity_**event**_xsstrust plugin, which comes in the archive, but is in the other plugin menu tab. Note that it is broken in current s9y versions. The fix:

Change L96 from

    function set_config($name, $value) {

to

    function set_config($name, $value, $implodekey = '^') {


That plugin allows you to filter html completely, and that is one solution. However, that means really completely, even the output from markup plugins is fixed, which maybe should be optional. 

That is supposed to be better with htmlpurifier. Enabling the htmlpurifier option in there should filter out the script options. But it does not work for me. It seems that the purifier is not being run.

@garvinhicking, sorry to ping you again, but I'm stumped here.

**Comment by We5ter** [comment]
@onli It seems that I have installed wrong plugin indeed...

**Comment by garvinhicking** [comment]
@onli That's bad :-D

I fixed it, it checked for the wrong parameter, obviously we no longer seem to propagate $eventData['authorid'] in the presave entry hook, so I now use the currently logged in user for that.

**Comment by onli** [comment]
@We5ter Does that fix it for you?

**Comment by We5ter** [comment]
@onli It seems @garvinhicking has fixed that plugin,so this issue has been fixed yet.

**Comment by We5ter** [comment]
@onli @garvinhicking Thank you for your hard work.

**Comment by onli** [comment]
Then I'll close here. Thanks for the report. It was a real bug after all.
