### ISSUE TITLE
Bundled Net/DNSBL.php depends on missing Net/DNS.php

### ISSUE THREAD

**Issue by smarsching** [s9y/Serendipity#459]
I am using Serendipity 2.1-rc1 with PHP 7.0.15-0ubuntu0.16.04.4.

In my webserver’s error log, I am finding error messages like the following (paths and URLs anonymized):
```
[Wed Mar 08 12:37:03.609101 2017] [proxy_fcgi:error] [pid 27470:tid 140017611503360] [client 46.118.153.31:51768] AH01071: Got error 'PHP message: PHP Warning:  Uncaught ErrorException: Warning: require_once(Net/DNS.php): failed to open stream: No such file or directory in /s9yroot/bundled-libs/Net/DNSBL.php:34\nStack trace:\n#0 /s9yroot/bundled-libs/Net/DNSBL.php(34): errorToExceptionHandler(2, 'require_once(Ne...', ‚/s9yroot...‘, 34, Array)\n#1 /s9yroot/bundled-libs/Net/DNSBL.php(34): require_once()\n#2 /s9yroot/plugins/serendipity_event_spamblock_rbl/serendipity_event_spamblock_rbl.php(89): require_once(‚/s9yroot...')\n#3 /s9yroot/include/plugin_api.inc.php(1139): serendipity_event_spamblock_rbl->event_hook('frontend_saveCo...', Object(serendipity_property_bag), Array, Array)\n#4 /s9yroot/include/functions_comments.inc.php(1006): serendipity_plugin_api::hook_event('frontend_saveCo...', Array, Array)\n#5 /s9yroot/include/functio...\nPHP message: PHP Fatal error:  serendipity_event_spamblock_rbl::main(): Failed opening required 'Net/DNS.php' (include_path='.:/usr/share/php:/s9yroot/bundled-libs/:/s9yroot/bundled-libs/Smarty/libs/:/s9yroot/:') in /s9yroot/bundled-libs/Net/DNSBL.php on line 34\n', referer: <anonymized>
```

I believe this happens because the bundled `Net/DNSBL.php` depends on `NET/DNS.php` which for some reason is not bundled with s9y.

I cannot tell for sure whether this error first appeared after upgrading to s9y 2.1-rc1, upgrading to PHP 7, or has already been present for a while. Anyway, the underlying problem still seems to be present in the current version from Git.

**Comment by garvinhicking** [comment]
This is actually not an issue from the core itself, but the plugin spamblock_rbl which relies on that. However, the rbl spamblock plugin is something that might not really be supported / makes sense in the future. We'll try to address this within the plugin and see how it can provide that file.

**Comment by th-h** [comment]
> This is actually not an issue from the core itself, but the plugin spamblock_rbl which relies on that. However, the rbl spamblock plugin is something that might not really be supported / makes sense in the future. We'll try to address this within the plugin and see how it can provide that file.

AFAIS Net/DNSBL.php is only needed for `spamblock_rbl` (maybe `spamblock_surbl`, too).

If Net/DNSBL.php is bundled with the core, Net/DNS.php should, too. Or we move both to the plugin(s) (if that's possible).

**Comment by garvinhicking** [comment]
Yeah, ideally I would like to simply add DNS.php to our core, that should make it easier. However I don't know if the current DNS.php is compatible to the rest of our bundled PEAR?

**Comment by th-h** [comment]
> However I don't know if the current DNS.php is compatible to the rest of our bundled PEAR?

It should be. DNSBL.php 1.3.7 is from 2012-04-20; DNS.php is from 2010-11-03 (and "has been superseded, but is still maintained for bugs and security fixes"). That should be no problem. Will try it out.

**Comment by garvinhicking** [comment]
👍

**Comment by th-h** [comment]
Works on my dev blog without problems and fixes this bug.
