### ISSUE TITLE
Plugin sidebarhider doesn't work with Serendipity 2.1-rc1

### ISSUE THREAD

**Issue by nfriese** [s9y/Serendipity#462]
The view "Extended entry only" and "All times" from a sidebarplugin in combination with the plugin **sidebarhider**  works in the overview page, not in the extend entry. See my posts in german on the board [https://board.s9y.org/viewtopic.php?f=10&t=21125](https://board.s9y.org/viewtopic.php?f=10&t=21125). In Version 2.05 the plugin works well.

**Comment by th-h** [comment]
WONTFIX.
