### ISSUE TITLE
User authentification fail

### ISSUE THREAD

**Issue by foppro** [s9y/Serendipity#463]
User authentification fail to administrate the blog. How to solve or get a new one?

**Comment by garvinhicking** [comment]
Our github issue tracker is not meant for individual support.

Please come to our forums for questions like these.

You can reset the password by creating a small script on your site like "fixpass.php":

```
<?php
$username = "your-username";
$password = "your-new-password";
include 'serendipity_config.inc.php';
echo serendipity_db_query("UPDATE {$serendipity['dbPrefix']}authors SET password = '" . serendipity_hash($password) . "', hashtype=1 WHERE username = '" . serendipity_db_escape_string($username) . "'");
echo "Password changed.";
?>
```

Then call that via http://yourblog/fixpass.php

**Comment by foppro** [comment]
Thanks
