### ISSUE TITLE
Linking to a comment sends a pingback

### ISSUE THREAD

**Issue by yellowled** [s9y/Serendipity#464]
To reproduce (also see [forum thread](https://board.s9y.org/viewtopic.php?p=10446834)):

1. Publish an entry
2. Edit said entry without changing the timestamp to link from the entry content to a comment for the same entry (“As someone mentioned in the comments …”)
3. This sends a Pingback (why not a trackback is my first question, I don't actively use Pingbacks) to the same entry, i.e. the entry is pingbacking itself.

**Comment by onli** [comment]
Trying to reproduce this, I see this result:

 1. It does indeed send a trackback to itself
 1. But the trackback does not get shown in the comment list

Maybe that's good enough?

**Comment by th-h** [comment]
I think that's good enough.
