### ISSUE TITLE
Add proper maintenance mode

### ISSUE THREAD

**Issue by yellowled** [s9y/Serendipity#467]
Create a proper maintenance mode that shows i.e. the upgrader to logged-in users, but returns a 503 for other visitors (probably needs a cookie).

Should have an option to disable the maintenance mode manually in case of failure.

**Comment by onli** [comment]
This could use some testing and some cleanup (e.g. language constansts)

**Comment by th-h** [comment]
The code is part of 2.2.1-alpha1. - Do we need to keep this issue open?

**Comment by onli** [comment]
Not really. This needs more testing, but that should come naturally over time.
