### ISSUE TITLE
Add a delete button to the entry editor

### ISSUE THREAD

**Issue by th-h** [s9y/Serendipity#472]
Currently, you can delete entries only from the entry list, but not from the entry editor form. It would be nice to add this ability, as you can get from the entry page in the frontend to the entry editor by clicking on the "edit" link, but you can't delete your post.

The `serendipity_event_deletelink` plugin, which will (presumably ...) add a delete link to the frontend view, is going to be decprecated.

**Comment by th-h** [comment]
#491 will look like this:

![screenshot 2017-04-12 23 47 01](https://cloud.githubusercontent.com/assets/365129/24981064/4349f3aa-1fdb-11e7-9a96-f3f619d4ee9b.png)

**Comment by yellowled** [comment]
Not sure if it wouldn't be better to have the order be Delete - Preview - Save. @onli?

**Comment by th-h** [comment]
Yes, perhaps that would be better; otherwise you may save the entry and get the delete button where the save button was before.

I'll wait for onli's comment and then change the PR, if necessary.

Am 13. April 2017 08:05:33 MESZ schrieb Matthias Mees <notifications@github.com>:

**Comment by onli** [comment]
@yellowled I agree. To add in a delete button at the position of the submit button would be problematic :)

Also, I know this fits to our usage, but it is not good to have a second highlighted button in that list. The primary button is save, delete is the contrary to primary here, but it takes the focus. I think the best solution to that would be to add it to the bottom of the entry editor (not 100% convinced of that idea).

If I see that right in the PR, it would only be shown if the entry really is saved? That's good!

**Comment by yellowled** [comment]
It's also about consistency in the interface. We do not really have the “Preview - Save - Delete” combo in the backend yet, but we do have “Preview - Edit - Delete” (in static pages and entries), so maybe this is fine after all. I'm not sure. It *feels* wrong in that order, though.

**Comment by yellowled** [comment]
We could move it in front of Preview, lose the red color and use an icon button.

`<a class="button_link" href="…" title="…"><span class="icon-trash" aria-hidden="true"></span><span class="visuallyhidden">…</span></a>`

**Comment by yellowled** [comment]
Does the Delete button have an “Are you sure?” safeguard? Because it most definitely should have one here either way. Too easy to hit the wrong button by accident. I'm becoming less of a fan of that button here every time I think about it …

**Comment by onli** [comment]
Seems like a good compromise to me. Won't take the focus, not in the position of the submit, and the toolbar there is the logical place to put it.

**Comment by onli** [comment]
> Does the Delete button have an “Are you sure?” safeguard? 

It does. Without having tested it right now, the delete link goes to a second page that is a form and then triggers `doDelete`. That one should be a POST, but that's a separate issue.

**Comment by th-h** [comment]
> If I see that right in the PR, it would only be shown if the entry really is saved? That's good!

Yes, it does. It will only be shown if the entry has already been saved.

> Does the Delete button have an “Are you sure?” safeguard?

Of course. I copied the logic from the delete button in the list of entries. You'll be asked if you really want to delete the entry and have to confirm that.

> That one should be a POST, but that's a separate issue.

I know. *sigh*

> We could move it in front of Preview, lose the red color and use an icon button

I started with that and didn't like it that much, but will try again and attach a screenshot so we can compare the look.

**Comment by th-h** [comment]
That's the icon button in front of preview:

![screenshot 2017-04-13 09 42 38](https://cloud.githubusercontent.com/assets/365129/24995080/b4be8364-202d-11e7-9f5f-cb1690006934.png)

Perhaps we should add nevertheless some color, so you don't accidentally click on it on that location?

![screenshot 2017-04-13 09 45 17](https://cloud.githubusercontent.com/assets/365129/24995144/fc526bb4-202d-11e7-8661-b468f679e128.png)

(Does not look very pretty, however.)

Which one would you like?

**Comment by yellowled** [comment]
Personally, I would like to not add the delete button at all. If that's not an option, I'd go with the non-colored icon button.

**Comment by th-h** [comment]
Uh, that was a bit fast ... @garvinhicking, you merged the previous version. :)

Please see #494, that's the one @yellowled and - I think - @onli will prefer.

**Comment by garvinhicking** [comment]
Uhm yeah, true. Well, we'll just overwrite it with the right version then. Sorry :-)
