### ISSUE TITLE
Internal cache breaks the blog when serendipity_event_markdown is active

### ISSUE THREAD

**Issue by th-h** [s9y/Serendipity#478]
**Steps to reproduce:**
1. Activate the new internal cache from 2.1.0
2. Active (or just install?) serendipity_event_markdown

**Expected result:**
Everything works

**Current result:**
Nothing works any more :-(

The frontend is not displayed; in the backend, `plugin/admin/serendipity_editor.js ` can't be loaded, so you can't switch off the internal cache (you'll have to unset the database entry in `s9y_config`).

Error Log:

    PHP Catchable fatal error:  Argument 1 passed to serendipity_event_markdown::setPlaintextBody() must be of the type array, null given, called in PATH/netz-rettung-recht.de/plugins/serendipity_event_markdown/serendipity_event_markdown.php on line 182 and defined in PATHnetz-rettung-recht.de/plugins/serendipity_event_markdown/serendipity_event_markdown.php on line 209, referer: URL

**Comment by th-h** [comment]
== ERROR-REPORT (BETA/ALPHA-BUILDS) ==

Catchable: Argument 1 passed to serendipity_event_markdown::setPlaintextBody() must be of the type array, null given, called in PATH/temp-url.tb/plugins/serendipity_event_markdown/serendipity_event_markdown.php on line 182 and defined in PATH/temp-url.tb/plugins/serendipity_event_markdown/serendipity_event_markdown.php on line 209.
For more details set $serendipity['production'] = 'debug' in serendipity_config_local.inc.php to receive a stack-trace.

Fatal error:  Uncaught exception 'ErrorException' with message 'Catchable: Argument 1 passed to serendipity_event_markdown::setPlaintextBody() must be of the type array, null given, called in PATH/temp-url.tb/plugins/serendipity_event_markdown/serendipity_event_markdown.php on line 182 and defined' in PATH/temp-url.tb/plugins/serendipity_event_markdown/serendipity_event_markdown.php:209
Stack trace:
~0 PATH/temp-url.tb/plugins/serendipity_event_markdown/serendipity_event_markdown.php(209): errorToExceptionHandler(4096, 'Argument 1 pass...', 'PATH/...', 209, Array)
~1 PATH/temp-url.tb/plugins/serendipity_event_markdown/serendipity_event_markdown.php(182): serendipity_event_markdown->setPlaintextBody(NULL, '2', '0')
~2 PATH/temp-url.tb/include/plugin_api.inc.php(1139): serendipity_event_markdown->event_hook('frontend_displa...', Object(serendipity_property_bag), NULL, Array)
~3 PATH/temp-url.tb/include/functions_entries.inc.php(1320): serendipity_plugin_ap in PATH/temp-url.tb/plugins/serendipity_event_markdown/serendipity_event_markdown.php on line 209

**Comment by th-h** [comment]
That may be due to an old PHP version (5.4.45). Will investigate ...

**Comment by th-h** [comment]
Can't reproduce in a fresh install (1&1 shared hosting) running PHP 7.0.

Can't reproduce in a fresh install running PHP 5.6.30-0+deb8u1.

Seems to be bound to the PHP version in Debian Wheezy.

Close as WONTFIX?

**Comment by yellowled** [comment]
I'd say leave it up for @garvinhicking to have a last look at it, then close.

**Comment by garvinhicking** [comment]
@th-h The error message mentions that the variable passed to setPlaintextBody() is not an array but null. Do you have an installation where this happens, and could you before the call to setPlaintextbody() make a 

echo serialize($eventData);

just before the $this->setPlaintextBody() call of the "frontend_display" event hook (line 182 for me)? 

It could be that the frontend_display event hook does not get $eventData properly once caching is enabled, and that would be bad and could be a bug of the caching retrieval @onli  ?

**Comment by onli** [comment]
@garvinhicking Since I saw the report that it works in other installations I did not dig deeper into it. I assume it can't be a bug in the caching code then. But maybe the debugging in the affected blog will show more.

**Comment by th-h** [comment]
> Do you have an installation where this happens, and could you before the call to setPlaintextbody() make a
> echo serialize($eventData);
> just before the $this->setPlaintextBody() call of the "frontend_display" event hook (line 182 for me)?

Yes.

The output is just `N;` after enabling the internal cache.

Without the cache, I get everything I should get, AFAIS. (And that debug output leads to collapsed configuration blocks in Settings/Configuration, see #479 ).

**Comment by th-h** [comment]
On PHP 7.0, I get no debug output on the frontend, neither with nor withouth cache. I get it in the backend when "previewing" and "saving" my entry, though. :-O

**Comment by th-h** [comment]
I don't have those issues any more after upgrading to PHP 7.0, and as there are no more reports of this bug, AFAICT, I'll close it now. We can always reopen it if it creeps up again.
