### ISSUE TITLE
include guetzli as new jpeg encoder

### ISSUE THREAD

**Issue by bauigel** [s9y/Serendipity#482]
https://github.com/google/guetzli

> Guetzli is a JPEG encoder that aims for excellent compression density at high visual quality. Guetzli-generated images are typically 20-30% smaller than images of equivalent quality generated by libjpeg. Guetzli generates only sequential (nonprogressive) JPEGs due to faster decompression speeds they offer.

**Comment by onli** [comment]
So I looked a bit more into that. I don't think it is possible. For one, I don't think we can integrate this into the things we distribute (it's a C++ program), and I doubt we can rely on hosters having it available. Assuming it is available on a hoster/server and we call it like we call imagemagick, there are still the performance issues metioned under https://github.com/google/guetzli#using:

> Note: Guetzli uses a large amount of memory. You should provide 300MB of memory per 1MPix of the input image.
>
> Note: Guetzli uses a significant amount of CPU time. You should count on using about 1 minute of CPU per 1 MPix of input image.

We'd need to raise the needed memory limit, by a lot, and integrate a worker queue to generate thumbnails in the background (which would be nice to have anyway, but overkill for some smaller thumbnails). 

I'd love to be proven wrong here :) But for now, okay if this gets closed?
