### ISSUE TITLE
“Empty” plugins in list of installable plugins

### ISSUE THREAD

**Issue by yellowled** [s9y/Serendipity#484]
**Affected versions:** 2.1.1, 2.2.0-beta1 (both on PHP 7.0.11)

**Reproduce:** log in to backend, have Spartacus active and set to pull plugins from remote, go to event plugins page and click to install new event plugins.

**Issue:** At the very top of the list, there are (currently seven) “empty” plugins listed; they don't have a name/title, the author is “Serendipity team” and the version is “1.0” (see screenshot below).

![screenshot 2017-04-11 18 52 26](https://cloud.githubusercontent.com/assets/326223/24948145/9e125d12-1f69-11e7-89d7-95d040ec02d6.png)

Clicking install for one of them gives me:

```
== ERROR-REPORT (BETA/ALPHA-BUILDS) ==
Warning: Invalid argument supplied for foreach() in /path/to/plugins/serendipity_event_spartacus/serendipity_event_spartacus.php on line 994.
For more details set $serendipity['production'] = 'debug' in serendipity_config_local.inc.php to receive a stack-trace.

Fatal error: Uncaught ErrorException: Warning: Invalid argument supplied for foreach() in /path/to/plugins/serendipity_event_spartacus/serendipity_event_spartacus.php:994
Stack trace:
#0 /path/to/plugins/serendipity_event_spartacus/serendipity_event_spartacus.php(994): errorToExceptionHandler(2, 'Invalid argumen...', '/var/www/virtua...', 994, Array)
#1 /path/to/plugins/serendipity_event_spartacus/serendipity_event_spartacus.php(1277): serendipity_event_spartacus->download(Array, 'serendipity_eve...')
#2 /path/to/include/plugin_api.inc.php(1139): serendipity_event_spartacus->event_hook('backend_plugins...', Object(serendipity_property_bag), Array, NULL)
#3 /path/to/include/admin/plugins.inc.php(374): serendipity_plugin_api::hook_event('backend_plugins...', Array)
#4 /path/to/serendipity_admin.php(127): i in /path/to/plugins/serendipity_event_spartacus/serendipity_event_spartacus.php on line 994

== ERROR-REPORT (BETA/ALPHA-BUILDS) == 
Fatal Error: Uncaught ErrorException: Warning: Invalid argument supplied for foreach() in /path/to/plugins/serendipity_event_spartacus/serendipity_event_spartacus.php:994
Stack trace:
#0 /path/to/plugins/serendipity_event_spartacus/serendipity_event_spartacus.php(994): errorToExceptionHandler(2, 'Invalid argumen...', '/var/www/virtua...', 994, Array)
#1 /path/to/plugins/serendipity_event_spartacus/serendipity_event_spartacus.php(1277): serendipity_event_spartacus->download(Array, 'serendipity_eve...')
#2 /path/to/include/plugin_api.inc.php(1139): serendipity_event_spartacus->event_hook('backend_plugins...', Object(serendipity_property_bag), Array, NULL)
#3 /path/to/include/admin/plugins.inc.php(374): serendipity_plugin_api::hook_event('backend_plugins...', Array)
#4 /path/to/serendipity_admin.php(127): i in /path/to/plugins/serendipity_event_spartacus/serendipity_event_spartacus.php on line 994.
For more details set $serendipity['production'] = 'debug' in serendipity_config_local.inc.php to receive a stack-trace.

Fatal error: Uncaught ErrorException: Fatal Error: Uncaught ErrorException: Warning: Invalid argument supplied for foreach() in /path/to/plugins/serendipity_event_spartacus/serendipity_event_spartacus.php:994
Stack trace:
#0 /path/to/plugins/serendipity_event_spartacus/serendipity_event_spartacus.php(994): errorToExceptionHandler(2, 'Invalid argumen...', '/var/www/virtua...', 994, Array)
#1 /path/to/plugins/serendipity_event_spartacus/serendipity_event_spartacus.php(1277): serendipity_event_spartacus->download(Array, 'serendipity_eve...')
#2 /path/to/include/plugin_api.inc.php(1139): serendipity_event_spartacus->event_hook('backend_plugins...', Object(serendipity_property_bag), Array, NULL)
#3 /path/to/include/admin/plugins.inc.php(374): serendipity_plugin_api::hook_event('backend_plugins...', Array)
#4 /path/to in /path/to/plugins/serendipity_event_spartacus/serendipity_event_spartacus.php on line 994
```
Obviously, the plugin is not installed. Other users have [confirmed this](https://board.s9y.org/viewtopic.php?p=10447048), it is not specific to my installation(s).

**Comment by garvinhicking** [comment]
This is due to the "alpha" plugins being moved and their directories still existing in "CVS". I have changed this and the next spartacus run should work properly.

**Comment by yellowled** [comment]
@garvinhicking I actually suspected that, but did not mention it because there seem to be more than seven plugins in `alpha`. Thanks, I'll close here.

**Comment by yellowled** [comment]
@garvinhicking Teeny, tiny thing – yes, it does now omit the plugins in `alpha`, but it still creates the “frame” for them, i.e. an empty `h3` and an empty `ul`, which results in some extra vertical whitespace in the backend page.

I can imagine that it's not that easy to fix in `emerge_spartacus.php`, so maybe we should move `alpha` to a seperate repository after all?

**Comment by yellowled** [comment]
Of course, that's an issue with `plugins.inc.tpl`, not spartacus.

The code for that is

```
{foreach $pluggroups AS $pluggroup => $groupstack}
    {if $only_group && $pluggroup != $only_group}{continue}{/if}
    // code to emit section of plugins
{/foreach}
```
So we need to add something to that to check if the group actually contains items or something …?

**Comment by garvinhicking** [comment]
Maybe a simple:

{foreach $pluggroups AS $pluggroup => $groupstack}
    {if ($only_group && $pluggroup != $only_group) || empty($pluggroup)}{continue}{/if}
    // code to emit section of plugins
{/foreach}

-> so, adding an empty check for it?

**Comment by th-h** [comment]
Please try to reload the plugin list from Spartacus, e.g. by clicking on "upgrade plugins". The empty group should disappear. (There are no empty groups in the XML now; it has to be cached somewhere.)

**Comment by th-h** [comment]
Hm, and now the “empty” plugins have returned for me. Strange.

**Comment by garvinhicking** [comment]
Check your serendipity_pluginlist database table, this holds the cached info. Maybe there's an empty group in there somewhere due to the once empty XML.

(if it is, I'm afraid we might not be able to "push" an update to clear the database for affected users)

**Comment by yellowled** [comment]
I'll check Garvins suggestion later today, busy atm.

**Comment by th-h** [comment]
`serendipity_pluginlist` does not seem to contain groups; those are in `serendipity_plugincategories`, aren't they? -- Anyway, after switching Spartacus frpm s9y.org back to github, I'm back where we started: no "ghost" plugins, but the empty `<h3>`.

**Comment by th-h** [comment]
After staring at the code for some time, I think we explicitly add an empty group in `plugins.inc.php`, line 250, to catch plugins with no group set:

    $pluggroups[''] = array();

When commenting that out, the empty group disappears. So I don't think that has anything to do with the changes in the Spartacus XML data and we'll need that check in the template.

**Comment by th-h** [comment]
Garvins code works for me.

**Comment by yellowled** [comment]
Well, in that case … let's merge and thank @th-h for spending his vacation on s9y bugs. 👍

**Comment by garvinhicking** [comment]
@yellowled @th-h Hm, I believe if we intentionally use an empty group, this could lead to plugins not getting displayed that are not associated with a group.

We should be able to test this by creating a simply Plugin and removing the $propbag attribute with the group to simulate this... our core plugins usually should all have at least one group, but if local developers do not classify their plugin, they should still see it...

**Comment by th-h** [comment]
@garvinhicking AFAICS your suggested check in the template will only suppress the display (!) of a group of plugins that doesn't contain any plugin. The empty group - in the code - will be there, and if there are plugins without any group, the empty group will be filled and thus displayed.

**Comment by th-h** [comment]
I think we can close this issue again, as it is fixed (and as we still use an empty group but do not display it as long as it stays empty, there should be not problem with plugins not getting displayed).
