### ISSUE TITLE
Merge $serendipity[‘dashboardLimit’] and $serendipity[‘dashboardDraftLimit’]

### ISSUE THREAD

**Issue by th-h** [s9y/Serendipity#488]
According to https://docs.s9y.org/docs/developers/code-primer.html#docs-initializing-the-framework-serendipity_configincphp-and-serendipity_config_localincphp, `$serendipity[‘dashboardLimit’]` and `$serendipity[‘dashboardDraftLimit’]` should work like this:

> $serendipity[‘dashboardLimit’]: How many entries to show in dashboard (default 5)
> $serendipity[‘dashboardDraftLimit’]: How many of those dashboard entries are filled up with draft entries (default 5)

The current code does not work this way. First will display up to `dashboardLimit` future entries. If this number is smaller than `dashboardDraftLimit`, we'll add drafts until we reach `dashboardDraftLimit`.

So, let's suppose we have 3 future entries and 5 drafts. With the default settings, we'll get 3 future entries and 2 drafts, 5 all in all. But if we set `dashboardLimit` to 10 (while leaving `dashboardDraftLimit` at 5), we *should* get 3 future entries and all 5 drafts (because 3+5 <= 10 and 5 drafts <= 5). In fact, we'll get 3 future entries and just 2 drafts.

We could change the code, but that would make it more complex. As we'll get the future entries first and just fill the dashboard up with drafts anyway, I don't think there is any need to offer those two variables.

I suggest to drop `$serendipity[‘dashboardDraftLimit’]` and just use  `$serendipity[‘dashboardLimit’]`.

If you're okay with that, I could supply PRs for Serendipity and the documentation website.

**Comment by th-h** [comment]
@onli What do you think?

**Comment by onli** [comment]
I'm okay with what you outline. the one thing that is important there is to control the overall elements in the box, the distinction between drafts and future entries does not have to be in the config variables. One single variable would be best.

But to be consistent with `dashboardCommentsLimit` I would call it `dashboardEntriesLimit`.

**Comment by th-h** [comment]
Very good, will do.

Am 13. April 2017 09:11:48 MESZ schrieb onli <notifications@github.com>:

**Comment by onli** [comment]
This should be done. Thanks @th-h :)
