### ISSUE TITLE
Deprecate plugins

### ISSUE THREAD

**Issue by yellowled** [s9y/Serendipity#499]
Move the deprecated [event](https://github.com/s9y/Serendipity/wiki/Reorganize-Plugins#deprecate) and [sidebar](https://github.com/s9y/Serendipity/wiki/Reorganize-Plugins#deprecate-1) plugins in https://github.com/s9y/additional_plugins to the `alpha` directory, a.k.a. Siberia.

**Comment by yellowled** [comment]
@garvinhicking I can do that later today, just wanted to make sure that I did not misunderstand you in Slack – you said to go ahead on those plugins marked for deprecation in the wiki, correct?

**Comment by yellowled** [comment]
I went ahead and moved them.

**Comment by th-h** [comment]
https://docs.s9y.org/docs/contributing/versioning.html says:

> When a plugin is removed from Spartacus, the development team will write a blog announcement post to inform users who have the plugin installed so that they can remove them themselves (or maybe even better, volunteer to fix/improve it).

Any volunteers? ;)

**Comment by yellowled** [comment]
Ugh. Yeah, I'll do it … 🙄
