### ISSUE TITLE
Thumbnail file size too big

### ISSUE THREAD

**Issue by onli** [s9y/Serendipity#505]
For #474 I'm generating a bunch of bigger than usual thumbnails, for example a 1200px version if the original image is 1600px. In my dev blog, those bigger thumbnails end up having a bigger file size than the bigger images. The image format in this case is jpg.

Imagemagick is not active, no special parameters are set. Can someone of you reproduce this?

**Comment by yellowled** [comment]
Not sure if that helps at all, but I use imagemagick to scale images – so maybe GDlib is the culprit?

**Comment by onli** [comment]
I tested this again, with gd, and this works now - thumbnails are smaller than their parent image, with jpg and png. Since no one else complained this was probably a since fixed issue with an old lib version, and I'll consider this fixed.
