### ISSUE TITLE
Auto-upgrader should check for the ZIP PHP extension

### ISSUE THREAD

**Issue by th-h** [s9y/Serendipity#508]
The auto-upgrader needs the PHP [ZIP extension](http://php.net/manual/en/book.zip.php).

It should check for the presence of this extension accordingly.

See https://board.s9y.org/viewtopic.php?f=1&t=20888 on the forums.

**Comment by onli** [comment]
It does that! :) https://github.com/s9y/additional_plugins/blob/7b8d241c4ce5c408919e4625c7f20aec70e1c95e/serendipity_event_autoupdate/serendipity_event_autoupdate.php#L120 is the check. I don't see why this shouldn't work, so I'll close here for now, the bug report is not very definitive.
