### ISSUE TITLE
Rework media library rename functionality

### ISSUE THREAD

**Issue by onli** [s9y/Serendipity#509]
That the existing code has grown a bit wild can already be seen by `serendipity_moveMediaDirectory` being the function that gets called when a *file* gets renamed. This issue covers the project to rework the code to work with the new responsive thumbnails (#474), be more reliable (see https://board.s9y.org/viewtopic.php?f=3&t=21185), easier readable, and calling functions that actually do what their name says.

- [x] Rework code to be more sound and work with responsive thumbnails
- [x] Re-add ACL functionality
- [ ] Make sure the new approach works reliable (user testing, but try  to also implement unit tests)
- [x] Also change the image link, not just the img src

**Comment by onli** [comment]
First commit for this: https://github.com/s9y/Serendipity/commit/bfeccabcdbd62ac072a410ea1439373e4a5a5ac7

**Comment by onli** [comment]
@garvinhicking Did you have some success with the ACL functionality?

**Comment by onli** [comment]
Current bug: The href attribute of links that come before the s9yimdb comment are currently not replaced. Maybe re-add logic similar to the REGEXP replacements of staticpage, or use a sqlite compatible way - or use a new regex following the current scheme.

ACLs can be re-added to the api event hook call place in the code. Garvin will look at this :)

**Comment by garvinhicking** [comment]
I have re-added the ACL replacements.

What's missing now but important for a release is the REGEXP replacement thing (see old code: "Entry REPLACEMENT AREA").

Also, I think currently renaming the mediaproperties database table is missing as well. This took care of replacing old TITLE, realname and name attributes of a media file. I think this will need to be re-added into the serendipity_updateImageInDatabase function, please have a look.

**Comment by onli** [comment]
> What's missing now but important for a release is the REGEXP replacement thing (see old code: "Entry REPLACEMENT AREA").

I added this in https://github.com/s9y/Serendipity/commit/732f1ae851d89e1ba94fbe492a47ff3fffdd5135. The approach there has one problem: We do not know whether the old link pointed to something other than the image. Maybe you have an idea how to detect that, how to get the old image link maybe?

**Comment by onli** [comment]
> Also, I think currently renaming the mediaproperties database table is missing as well. This took care of replacing old TITLE, realname and name attributes of a media file.

Is this about https://github.com/s9y/Serendipity/blob/460b416b7c885256bfd573aa4072309b33fdcbfe/include/functions_images.inc.php#L3580? In which circumstances are those values set? I do not see it in my database nor the code, and since in the UI all seems to update now properly I'm surprised there is a second layer?

**Comment by onli** [comment]
> The approach there has one problem: We do not know whether the old link pointed to something other than the image.

This is done now. In my eyes this just needs testing, which this rework would get automatically in a beta. I'll remove the blocking tag.

**Comment by th-h** [comment]
Closed, as it will get testing in the beta.
