### ISSUE TITLE
Drag'n'drop target for plugins doesn't work

### ISSUE THREAD

**Issue by yellowled** [s9y/Serendipity#510]
**Reproduce:** In either event or sidebar plugins, drag a plugin from the lower end of the list to the inactive column or other sidebar.

**Expected behaviour:** Plugin is moved to the new column.

**Actual result:** Plugin is not moved to the column *unless* it is dragged to the *top* of the new column.

The drag'n'drop script is a homegrown function `getDragdropConfiguration` which I think @onli wrote? Anyway, this seems to use `.pluginmanager_container` for height calculations, which now does not *have* a height due to equal heights now being “generated” using flexbox.

If possible, we'd need to use `.pluginmanager_side` (the parent container) for calculations, altough that also contains a heading …

**Comment by onli** [comment]
I remember making this work for 2.0 (but I don't remember anymore how much of it comes from the script that was used before). 

I can't reproduce this. In FF, when I drag an item from the right sidebar to another that works, in current git master. Also, looking at the script, height calculation is only used to set the height and width of the dragged item, and does not use the container for that.

There might be an incompatibility with yout used browser (chrome?) and the jquery.sortable.js plugin we use?

**Comment by th-h** [comment]
Ist dies *not* work for me (FF, too) in 2.1.1. Will try to test git master on weekend.
-- 
Diese Nachricht wurde von meinem Android-Mobiltelefon mit K-9 Mail gesendet.

**Comment by yellowled** [comment]
Don't have time to test this further atm, but yes, I used Chrome and did not test any other browsers so far.

**Comment by yellowled** [comment]
Just tested in

* Chrome 58/macOS
* Firefox 53/macOS
* Safari 10.1/macOS

Maybe it's not clear enough, but you have to be dragging from the end of a plugin column that is longer than the one you're dragging to – i.e. longer than the screen so that you can not see the backend header etc. any more. Then drag to the end of the new column (just drag it across without scrolling up). That used to work before, but now it does not in any of the browsers I tested.

**Comment by onli** [comment]
Ah. Okay. That I can confirm.

For the event plugin list. In the sidebar plugin list, I just have to go higher than one plugin item height. But yes, to switch columns in the event plugin list (which is a lot higher in my case) I have to scroll up all to the top.

If I see that right, we either need to make the ol.pluginmanager_container element stretch all the way down - that might work with some flexbox properties (flex-grow: 999 and stuff like that). Or we need to switch the dropzone to be the div above, div.pluginmanager_side. I don't think that would work easily, the jquery-plugin  should expect the dropzone to be the same container it stores the element in later.

But I might be wrong. Why does it work somewhat in the sidebar plugin list? .pluginmanager_container has a height of 0 there as well. Oh, and of course we might to be able to just change the height of all containers on drag start.

**Comment by yellowled** [comment]
>  In the sidebar plugin list, I just have to go higher than one plugin item height. 

Can confirm in Chrome 66/macOS.

> In current Firefox, a simple height: 100% on .pluginmanager_container fixes the issue for me.

Yes, that works in Chrome 66/macOS as well.

I don't have time to confirm the other browsers, let alone test IE or mobile browsers, but this sounds like a solution.

**Comment by onli** [comment]
Good enough. Thanks! :)
