### ISSUE TITLE
<details> for installed plugins not displayed on Firefox?

### ISSUE THREAD

**Issue by th-h** [s9y/Serendipity#515]
The plugin manager displays just the names of all installed plugins:

![screenshot 2017-05-25 09 51 23](https://cloud.githubusercontent.com/assets/365129/26441285/32c11f74-4130-11e7-9d0e-6c74ed8ad3cf.png)

It would be nice to get some more information, *at least* the current version, as it is done on the plugin installation page:

![screenshot 2017-05-25 09 51 37](https://cloud.githubusercontent.com/assets/365129/26441345/6a6c26b2-4130-11e7-9850-b48ad43e5e1d.png)

We don't need the authors, but a link to the Changelog and/or the local documentation could help.

**Comment by yellowled** [comment]
![screenshot 2017-05-25 09 58 44](https://cloud.githubusercontent.com/assets/326223/26441463/cc66f2e8-4130-11e7-9b46-ddcadb28a442.png)

What ancient, strange browser are you using that *still* does not support the `<details>` element? (The screenshot above was taken in Chrome 58/Mac.)

**Comment by yellowled** [comment]
And more importantly, why does it not fall back gracefully?

**Comment by th-h** [comment]
> What ancient, strange browser are you using that still does not support the <details> element?

FF 53.0.3 (32-Bit) on Win7 - neither ancient nor strange, I think, rather "main line". ;)

> (The screenshot above was taken in Chrome 58/Mac.)

Wow! That's cool! (And in Chrome, it works for me, too.)

It's strange - <https://developer.mozilla.org/en-US/docs/Web/HTML/Element/details#Browser_compatibility> says Firefox should support it from 49.0 on, but it doesn't seem to do that. On the other hand, it says "no support" for IE, but IE11 does support it.

**Comment by yellowled** [comment]
We are using a JS polyfill for browsers that do not support `<details>` natively, that's why it works in IE11. It might be that this is backfiring in FF53. (I can reproduce it.)

It seems to be a rather easy CSS fix.

**Comment by yellowled** [comment]
@th-h That should fix it in `master` and `2.1`.

**Comment by th-h** [comment]
It does fix it, yes. Many thanks!
