### ISSUE TITLE
Smarty include relative path with 2.0.1 behaviour changed / reopen #331

### ISSUE THREAD

**Issue by igoltz** [s9y/Serendipity#516]
Almost 2 years after #331 was closed...

I updated a s9y (symlinked) installation from 1.7.8 to 2.0.5 to 2.1.1 and hit the unresolved bug #331 in blogs using the kinetic theme.

Prefixing the tpl files included tpl files with ./ solves it. But digging deeper through enabling _$serendipity['smarty']->testInstall();_ in functions_smarty.inc.php I get

```
    [template_dir:Smarty:private] => Array
        (
            [0] => /var/www.serendipity/html/jugendkurse/templates/default/
            [1] => /var/www.serendipity/html/jugendkurse/templates/2k11/
            [2] => /var/www.serendipity/html/jugendkurse/templates/2k11/
            [3] => /var/www.serendipity/html/jugendkurse/plugins/
            [4] => /var/www.serendipity/html/jugendkurse/templates/default/
        )
```

which does not include the template path.
Looking at serendipity_smarty_class.inc.php (from version 2.1.1) shows that the path _$template_dirs[] = $serendipity['serendipityPath'] . $serendipity['templatePath'] . $serendipity['template'];_ is only included when _$template_engine_ is not definded. However it is set to "default".
If I patch serendipity_smarty_class.inc.php so that the templatePath is always included all the kintetic based blogs work again without modifying the tpl files. Non kinetic blogs work too.

As I have no knowledge of s9y interna my question is: is this patch a bad hack?
Why is the template path not included, which in my understanding would make sense.
Or, why is template_engine set to "default" and no the actual template. If it would be set to the template name, it would included in the template_dirs.
Please could you shed some light on this behaviour.
Thanlk you in advance.

```
--- serendipity_smarty_class.inc.php.org	2017-04-09 09:35:14.000000000 +0200
+++ serendipity_smarty_class.inc.php.igo	2017-06-09 15:26:09.922142184 +0200
@@ -131,6 +131,7 @@
             // this is tested without need actually, but it makes the directory setter fallback chain a little more precise
             $template_dirs[] = $serendipity['serendipityPath'] . $serendipity['templatePath'] . $serendipity['template'];
         }
+        $template_dirs[] = $serendipity['serendipityPath'] . $serendipity['templatePath'] . $serendipity['template'];
         $template_dirs[] = $serendipity['serendipityPath'] . $serendipity['templatePath'] . $serendipity['defaultTemplate'];
         $template_dirs[] = $serendipity['serendipityPath'] . $serendipity['templatePath'] . $serendipity['template_backend'];

```

```
    [template_dir:Smarty:private] => Array
        (
            [0] => /var/www.serendipity/html/jugendkurse/templates/default/
            [1] => /var/www.serendipity/html/jugendkurse/templates/kinetic_jugendkurse2/
            [2] => /var/www.serendipity/html/jugendkurse/templates/2k11/
            [3] => /var/www.serendipity/html/jugendkurse/templates/2k11/
            [4] => /var/www.serendipity/html/jugendkurse/plugins/
            [5] => /var/www.serendipity/html/jugendkurse/templates/default/
        )`

```

**Comment by onli** [comment]
That still does not look correct to me. /templates/default/ should never be evaluated anymore, it not set explicitly as engine. And then it should be at the end.

Where is this used? Why not fetch a file via serendipity_getTemplateFile?

**Comment by igoltz** [comment]
Hi onli,
with 1.7.8 the debugging output is. So I guess s9y since 2.0.x does calculate this arry differently. And forget to include the path to the used template.

```
    [template_dir:Smarty:private] => Array
        (
            [0] => /var/www.serendipity/html/jugendkurse/templates/kinetic_jugendkurse2/
            [1] => /var/www.serendipity/html/jugendkurse/templates/bulletproof/
            [2] => /var/www.serendipity/html/jugendkurse/templates/default/
            [3] => /var/www.serendipity/html/jugendkurse/templates/
            [4] => /var/www.serendipity/html/jugendkurse/plugins/
        )

```
I do not code templates or s9y only try to find out why kinetic template fail in 2.0.x/2.1.x
Here I found that if the path to the actual template is added to the array created in [S9Y]/include/serendipity_smarty_class.inc.php kinetic template works again.
In 1.7.8 s9y handled it well, now the path is missing.

Am I save to patch serendipity_smarty_class.inc.php like posted bove?

**Comment by igoltz** [comment]
NB: found in the database that in the old blogs template_engine is configured (set to default) but in fresh installed this key is not included. Without it the array contains the path.
This follows the logic how the array is calculated but should it not always include the template first then the engines as fallback?

**Comment by onli** [comment]
> but should it not always include the template first then the engines as fallback?

Yes, but that is exactly the problem I have with this now. Normally, the template fallback order is defined in https://github.com/s9y/Serendipity/blob/master/include/functions_config.inc.php#L260. And there we actually did correct the order for newer serendipity versions.

It think that the order in serendipity_smarty_class.inc.php is for the internal smarty functions, for when a theme or plugin calls smarty->fetch instead of going through serendipity. If that's the case it should imo create exactly the same order as `serendipity_getTemplateFile`: template or backend_template, template_engine, default template (if != template_engine). 

Could you test that and send a PR if it works with the corrected order both in kinetic and 2k11?

**Comment by igoltz** [comment]
Opposite to [https://github.com/s9y/Serendipity/blob/master/include/functions_config.inc.php#L260](https://github.com/s9y/Serendipity/blob/master/include/functions_config.inc.php#L260) the array creation in [https://github.com/s9y/Serendipity/blob/master/include/serendipity_smarty_class.inc.php#L125](https://github.com/s9y/Serendipity/blob/master/include/serendipity_smarty_class.inc.php#L125) looks to me not following the proposed order. Only if template_engine is not defined template is added as first entry. Else the template _engine is added as first entry. template_engine I understand as fallback if a template does not provide all files (am I right?).
To correct this I would say that each case of the if-then construct needs to be executed but the else line first.

```
        if ($template_engine) {
            $p = explode(',', $template_engine);
            foreach($p AS $te) {
                $template_dirs[] = $serendipity['serendipityPath'] . $serendipity['templatePath'] . trim($te) . '/';
            }
        } else {
            // this is tested without need actually, but it makes the directory setter fallback chain a little more precise
            $template_dirs[] = $serendipity['serendipityPath'] . $serendipity['templatePath'] . $serendipity['template'];
        }

```

**Comment by onli** [comment]
> template_engine I understand as fallback if a template does not provide all files (am I right?)

Right. There are two fallback even: The engine, and as a second fallback the default theme, which in newer versions is 2k11.

template engine should never be a comma separated list, but well, if that's already in the code it can stay in there. Otherwise yes: The template needs to be moved to the front, away from the if. Feel invited to send a PR :)
