### ISSUE TITLE
Spartacus with Request2.php backend fails with proxy defined by trackback plugin

### ISSUE THREAD

**Issue by igoltz** [s9y/Serendipity#518]
Spartacus uses now Request2.php backend (since 2.1? Version 2.0.5 still used Request.php). This does not define proxy_pass anymore but proxy_password. 
The proxy plugins still set proxy_pass causing spartacus to fail.

```
[27-Jun-2017 11:36:28 Europe/Berlin] PHP Fatal error:  Uncaught <table style="border: 1px" cellspacing="0">
<tr><td colspan="3" style="background: #ff9999"> <b>HTTP_Request2_LogicException</b>: Unknown configuration parameter 'proxy_pass' in <b>/var/www.serendipity/serendipity-2.1.1/bundled-libs/HTTP/Request2.php</b> on line <b>364</b></td></tr>
<tr><td colspan="3" style="background-color: #aaaaaa; text-align: center; font-weight: bold;">Exception trace</td></tr>
<tr><td style="text-align: center; background: #cccccc; width:20px; font-weight: bold;">#</td><td style="text-align: center; background: #cccccc; font-weight: bold;">Function</td><td style="text-align: center; background: #cccccc; font-weight: bold;">Location</td></tr>
<tr><td style="text-align: center;">0</td><td>HTTP_Request2->setConfig('proxy_pass', '')</td><td>/var/www.serendipity/serendipity-2.1.1/bundled-libs/HTTP/Request2.php:364</td></tr>
<tr><td style="text-align: center;">1</td><td>HTTP_Request2->setConfig(Array)</td><td>/var/www.serendipity/serendipity-2.1.1/bundled-libs/HTTP/Request2.php:211< in /var/www.serendipity/serendipity-2.1.1/bundled-libs/HTTP/Request2.php on line 379
```

Could fix this with 

```
--- serendipity_event_trackback.php.org	2016-04-16 22:32:28.000000000 +0200
+++ serendipity_event_trackback.php	2017-06-27 11:52:19.480865885 +0200
@@ -115,7 +115,7 @@
                         $eventData['proxy_host'] = $host;
                         $eventData['proxy_port'] = $this->get_config('port');
                         $eventData['proxy_user'] = $this->get_config('user');
-                        $eventData['proxy_pass'] = $this->get_config('password');
+                        $eventData['proxy_password'] = $this->get_config('password');
                     }
                     break;

```
but older installations must not update to this change else would fail.

**Comment by igoltz** [comment]
And this quick fix breaks all plugins which still use HTTP/Request.php.

**Comment by garvinhicking** [comment]
I would propose to:

1.) Patch the s9y core include/functions.inc.php file; in the serendipity_request_url() API function we can set $addData['request_version'] = 2 for example.

2.) Patch any other files that use the "backend_http_request" event hook of the s9y core also set that addData variable.

3.) Patch the serendipity_event_trackback.php file, and then make a check:
if (isset($addData['request_version']) && $addData['request_version'] == 2) {
    $eventData['proxy_password'] = $this->get_config('password');
} else {
    $eventData['proxy_pass'] = $this->get_config('password');
}

This should make all HTTP/Request requests that not go through our s9y API function not have that "request_version" array key set, and fall back to the old "proxy_pass" way.

Other suggestions?

**Comment by igoltz** [comment]
I would suggest migrate all plugins to use Request2. These are at least
serendipity_event_communityrating
serendipity_event_google_sitemap
serendipity_event_flickr
serendipity_plugin_flickrbadge
serendipity_event_weblogping
serendipity_plugin_twitter
serendipity_event_podcast
serendipity_plugin_flickr

Why migrate? Well, HTTP/Request does not work with proxy and https URLs
So in s9y 2.0.5 spartacus fails with some error message it could not contact google.
But it should display the error from the  code below. If however this code is commented out spartacus works.

_s9y/bundled-libs/HTTP/Request.php_
```

         // 4.3.0 supports SSL connections using OpenSSL. The function test determines
         // we running on at least 4.3.0
         if (strcasecmp($this->_url->protocol, 'https') == 0 AND function_exists('file_get_contents') AND extension_loaded('openssl')) {
             if (isset($this->_proxy_host)) {
                 return PEAR::raiseError('HTTPS proxies are not supported.');
             }
             $host = 'ssl://' . $host;
         }

```

**Comment by onli** [comment]
So, which way to go?

**Comment by igoltz** [comment]
I vote for migration of all plugins to use Request2

**Comment by th-h** [comment]
We track the migration to Request2 in #550.
