### ISSUE TITLE
Media library Move deletes instead moves

### ISSUE THREAD

**Issue by stephanbrunker** [s9y/Serendipity#519]
Inside the media library, the move command produces unexpected results. Instead of moving, the files were deleted, physically and the database entries too. The existing links inside the articles were automatically edited as intended but without the physical files, the links doesn't work. In that correction, the new path also has one / too much: href='uploads/newfolder//filename.jpg'

And: edited is only the default language with the mulitilingual plugin, the entries in other languages aren't corrected.

**Comment by garvinhicking** [comment]
Are your file permissions/privileges maybe set in a way that don't allow write access?

Which serendipity version were you using exactly? There have been changes in our most recent versions that adress this feature. @onli

**Comment by stephanbrunker** [comment]
Unfortunately, no. Version 2.1.1 and 777 access for /uploads and its sub-folders. After using the "move" command on the Media-Database Main page, it looks like the screenshot - look for the doubled "//".
![bugscreen1](https://user-images.githubusercontent.com/18150071/27810270-76b95e48-6058-11e7-9c7d-e3a0b8207b12.JPG)

**Comment by onli** [comment]
In the current git master is a complete rewrite of the code doing that media move. If it were broken in 2.1.1, then it is very unlikely that exact bug persisted - but we should test this exact scenario, with the multilanguage plugin, and checking again whether doubled / can still pose a problem.

Though in this case, also 2.1.1 should have just ignored the doubled /.

**Comment by onli** [comment]
I tested this again with the current master. It works fine, and it really is not the same code. I will close this, but it should be reopened if it happens again.
