### ISSUE TITLE
Parse error: syntax error, unexpected functions_images.inc.php on line 2255

### ISSUE THREAD

**Issue by cbruno1** [s9y/Serendipity#522]
Hi all,

I have an error before installing Serendipity.
`Parse error: syntax error, unexpected '[' in /var/www/mydomain.com/public_html/Serendipity/include/functions_images.inc.php on line 2255`

I added `AddHandler application/x-httpd-php55 .php .php5 .php4 .php3` in .htacces without success…

My php version: HP 5.5.9-1ubuntu4.21

Thanks.

**Comment by onli** [comment]
Which version of Serendipity did you try to install?

**Comment by cbruno1** [comment]
Master branch

**Comment by onli** [comment]
I see it. Okay, that's just wrong code. Could you please try again with the commit I just pushed applied?

**Comment by cbruno1** [comment]
Perfect it works!

Thank you very much!

**Comment by onli** [comment]
Thanks for testing. It is strange that I got no parse error on my dev system. 

Be aware that this part of s9y (image handling via the media library) is a brand new re-implementation, there still might be some issues there.
