### ISSUE TITLE
Comment deletion is confirmed without checking for success

### ISSUE THREAD

**Issue by th-h** [s9y/Serendipity#527]
If you delete a comment in the backend interface, s9y will delete it from the database and show a success message - without checking if the comment has indeed been deleted succesfully.

The code is in `include\admin\comments.inc.php`:

    /* We are asked to delete a comment */
    if (isset($serendipity['GET']['adminAction']) && $serendipity['GET']['adminAction'] == 'delete' && serendipity_checkFormToken()) {
        serendipity_deleteComment($serendipity['GET']['id'], $serendipity['GET']['entry_id']);
        $msg[] = DONE . ': '. sprintf(COMMENT_DELETED, (int)$serendipity['GET']['id']);
    }

s9y should display a success message for succesful deletions, but an error if the deletion fails.

(You can resubmit a request, trying to delete an already deleted comment, or - I think - even shutdown your SQL server to reproduce.)

**Comment by onli** [comment]
I added some code to the code you highlighted to show an error message when serendipity_deleteComment does not return true. It should only return true when a comment was deleted. There is at leas tone remaining issue: When deleting a comment that was already deleted, s9y does get no negative feedback from the database layer, deleting nothing and still thinking everything is fine. I don't think we can fix this.

**Comment by onli** [comment]
I think this should be good enough now.
