### ISSUE TITLE
Add SVG as supported media type for the media database

### ISSUE THREAD

**Issue by ddeimeke** [s9y/Serendipity#529]
It would be great if we support SVG as graphics format as well.

**Comment by onli** [comment]
That shouldn't even be that hard:

 1. Allow it as uploadable media type (that may already be the case)
 1. Modify thumbnail creation to skip svgs, just copy the original instead to be the thumbnail 
 1.. Allow it to be selected in the ML entry choser

svgs can be set as src of an img-element, we should not need special case there.

**Comment by onli** [comment]
Or it could be as easy as adding it to the list of mime types ;)

**Comment by onli** [comment]
This works for me, I will close for now.
