### ISSUE TITLE
XML_RPC_Client has a deprecated constructor

### ISSUE THREAD

**Issue by bauigel** [s9y/Serendipity#532]
After a few month i tried to post an new article today and got following messages about deprecated features. Is this already fixed in current builds?

I'm running "Serendipity 2.2.0-beta1" and PHP 7.0.23, but i'm quiet sure my build is from a few days after last s9ycamp.

```
Deprecated: Methods with the same name as their class will not be constructors in a future version of PHP; XML_RPC_Client has a deprecated constructor in .../bundled-libs/XML/RPC.php on line 597

Deprecated: Methods with the same name as their class will not be constructors in a future version of PHP; XML_RPC_Response has a deprecated constructor in .../bundled-libs/XML/RPC.php on line 1046

Deprecated: Methods with the same name as their class will not be constructors in a future version of PHP; XML_RPC_Message has a deprecated constructor in .../bundled-libs/XML/RPC.php on line 1138

Deprecated: Methods with the same name as their class will not be constructors in a future version of PHP; XML_RPC_Value has a deprecated constructor in .../bundled-libs/XML/RPC.php on line 1552

```

**Comment by onli** [comment]
I though they were all fixed :/. But no, https://github.com/s9y/Serendipity/blob/master/bundled-libs/XML/RPC.php still has those type of constructors. It probably got missed because it is not loaded without a specific plugin?

**Comment by onli** [comment]
@bauigel, can you debug this a bit more? Is that happening in combination with the xmlrpc-plugin only?

I assume that it could be replaced with https://github.com/gggeek/phpxmlrpc. But for that someone familiar with the functionality needs to sit down, do the port, and test it.

**Comment by onli** [comment]
Honestly, I still do not know why you see those error messages but I don't. I now replaced the constructor, as that should remove the error. Could you test it out?

**Comment by bauigel** [comment]
I close here. Seems to be fixed.
