### ISSUE TITLE
Uploading mp4 or webm to media gallery, files not recognized as videos

### ISSUE THREAD

**Issue by ddeimeke** [s9y/Serendipity#535]
I am running the recent development snapshot of serendipity.

When I upload webm or mp4 files to the media gallery they are not recognized as videos.

Maybe a php module is missing?

(Never tried that before, so I do not know if this is an old issue).

**Comment by yellowled** [comment]
I'm not sure if I'm looking in the right place, but according to `serendipity_guessMime` in `include/functions_images.php`, mp4 *should* [be supported](https://github.com/s9y/Serendipity/blob/master/include/functions_images.inc.php#L1003). webm probably wasn't a thing yet when this was updated the last time (or no one noticed until now).

**Comment by onli** [comment]
Do we have a plugin that supports embedding videos as videos? So far that is always treated like a regular non-image, right?

**Comment by th-h** [comment]
WONTFIX.

**Comment by onli** [comment]
To explain a bit: Supporting videos would actually be great, but since no one seems to be motivated to build that for now we shouldn't leave this issue open. I offer support if someone wants to build this (it certainly is doable!), but it would not be easy.
