### ISSUE TITLE
Missing output of captcha

### ISSUE THREAD

**Issue by henschi** [s9y/Serendipity#536]
The spamblock plugin does not show the captcha image in my s9y 2.1.1 installation.
 I added "return $output;" as a new line at 815 in the file "plugins/serendipity_event_spamblock/serendipity_event_spamblock.php" and it works now.
Please validate this fix and if ok take on for the next version.

**Comment by titanofold** [comment]
Had this issue with 2.1.2, and this fix worked for me.

**Comment by onli** [comment]
@titanofold Could you send this fix as a Pull request, with a version bump of the plugin?
