### ISSUE TITLE
Plugin installation/upgrade fails with 2.1.2

### ISSUE THREAD

**Issue by th-h** [s9y/Serendipity#548]
See <https://board.s9y.org/viewtopic.php?f=3&t=23821>.

> After upgrading to 2.1.2, attempting to install or upgrade a plugin yielded the error

    The URL /additional_plugins/serendipity_event_spamblock_bayesimg/spamblock_bayes.load.gif?revision=1.9999 (IP ) could not be opened.
    Maybe the Serendipity or SourceForge.net Server is down - we are sorry, you need to try again later.

> Note that server and root path are missing from the URL. I do have set github.com in the Spartacus plugin as source for both, File/Mirror location (XML metadata) and File/Mirror location (files). After going to the Spartacus setup and intuitively ;-) clicking Save these informational messages were displayed:

    Deleting file package_template.xml...
    Deleting file package_sidebar_en.xml...
    Deleting file package_event_en.xml...

> So it seems that the upgrade from 2.1.1 to 2.1.2 should had cleared those cache files. Probably manually removing templates_c/package_* should work as well.

I can reproduce that (I just get `Unknown Reason / Your browser sent a request that this server could not understand.`, but the workaround described above fixed it for me, too).

@onli: May that be due to 615591a7d97fb3716933717028a29b049a823f94?

Would adding an upgrader task (and probably releasing a 2.1.3 shortly) be the right fix?

**Comment by garvinhicking** [comment]
This is what I meant with when you removed netmirror, if you had taken 
into account that users had this mirror selected. @onli said it would 
properly fall back to the propper mirror, maybe there's a bug in that 
logic. I haven't checked it and cannot do that, but I guess the kind is 
in the brunnen gefallen and we could only create another release now.

**Comment by th-h** [comment]
>This is what I meant with when you removed netmirror, if you had taken 
>into account that users had this mirror selected. @onli said it would 
>properly fall back to the propper mirror, maybe there's a bug in that 
>logic. I haven't checked it and cannot do that, but I guess the kind is
>in the brunnen gefallen and we could only create another release now.

Must be something else as all reporters did *not* have Netmirror selected, but (all or mostly) GitHub.

**Comment by garvinhicking** [comment]
Reading through my comment again that sounds a bit offensive. Wasnt intentional. Sorry if I came up rude. Having a bad week :-D

Maybe the array index order got screwed up or sth like that, but I cant check. We might should put up a comment for that in the blog as a hotfix?

**Comment by onli** [comment]
Well, the bug is there. Sorry. The change seemed bulletproof: Spartacus just saved the array index, if that one were too big for the now smaller array it should have set `$mirror` to null by doing `$mirror = $mirrors[$indextoolarge]`, which we catch. And that was tested and seemed to work fine :/

Debugging this now (I can reproduce the error in my blog) I missed at least one place in spartacus where the mirror is set, namely when downloading updates... I will push the patch now, we should look in a second step whether there are other places where this issue persists.

**Comment by onli** [comment]
Patch in 2.1: https://github.com/s9y/Serendipity/commit/483868b2fa2bda08a34a896b659f6f1189bbb5ed

Master was out of sync: https://github.com/s9y/Serendipity/commit/b0fb8d2d126bc8c6e2745c466eb5429c18615738

**Comment by th-h** [comment]
> Well, the bug is there. Sorry.

That just happens, to all of us. :-)

> I will push the patch now, we should look in a second step whether there are other places where this issue persists.

The same code is present in lines 840/841 (tip of 2.1, after your patch), so I think that will need the same fix, too.

**Comment by th-h** [comment]
> The same code is present in lines 840/841 (tip of 2.1, after your patch), so I think that will need the same fix, too.

Added a fix in #549. Please review and possibly merge to master.

Has to be backported (cherry-picked) to 2.1 afterwards.

**Comment by onli** [comment]
Thanks. Merged and backported, if everything worked right.

**Comment by th-h** [comment]
Should be fixed by the commits above.
