### ISSUE TITLE
Finish media gallery insert

### ISSUE THREAD

**Issue by onli** [s9y/Serendipity#552]
https://github.com/s9y/Serendipity/commit/40993037b29271ff8b007c6634d9368829784cdb contains the work I started in the last reunion. It adds a way to add several images at once. It works, but it is not complete:

 - [x] Finish the gallery markup, HTML, that currently lives in https://github.com/s9y/Serendipity/blob/40993037b29271ff8b007c6634d9368829784cdb/templates/2k11/admin/media_choose.tpl#L6 and CSS
 - [x] Add/Use language constants
 - [x] Hide the insert button until more than one image is selected
 - [x] Add the highlight around selected images, similar to when they are selected for deletion

(I assigned YL for the HTML/CSS part)

**Comment by onli** [comment]
@yellowled Did you have some time to look into this?

**Comment by yellowled** [comment]
Completely forgot about it, sorry. May get a chance to look at it in the second half of the week.

**Comment by yellowled** [comment]
@onli I have added a "minimum viable product", meaning this is not perfect, but it's a good first step. I may or may not improve upon this a bit tomorrow (a.k.a. "try to fix a few thing myself"). For the time being, here's a few ideas for improvement (see next comment).

**Comment by yellowled** [comment]
## What it needs

* add a link to a larger version of the image (if applicable)
* ability to add `alt` text for images (accessibility)
* ability to (re)sort images within the gallery (drag 'n' drop would be sexy; I think currently it just adds the selected images in the order in which they are in the media db overlay?)

## Nice to have, but not urgent

* different gallery layouts; currently, the gallery will be rows of three images using 33.333% of the available width each; that might be a good compromise, but maybe people prefer
    * 50-50
    * 25-25-25-25
    * 100 on mobile, 50-50 on tablet, 33-33-33 on desktop?
* ability to add image captions (just for consistency; I actually think that could be annoying)

## Debatable, but interesting

* "cut off" images to create a gallery in which all included thumbnails have the same format regardless of the format of the original images (this *can* be done in CSS only, I think)
* ability to add images to a gallery later on (currently, users would have to re-add the whole gallery to add a single image; this could be tied with sorting)

**Comment by yellowled** [comment]
**Note:** I added the required styles to `style_fallback.css`; not sure if that's the *best* way, but it was convenient.

**Comment by onli** [comment]
Adding links is doable, I added it to `media_chose.tpl`. But adding a proper configuration step for the sorting and adding of an alt text will take some work. Just as a note for us: When inserting images normally, the markup is generated in `serendipity_editor.js.tpl`.

**Comment by onli** [comment]
I will close this for now. I'm not certain we actually need a configuration page in between selecting the images and adding them. If we do, this could get a dedicated issue.
