### ISSUE TITLE
Caching-Error

### ISSUE THREAD

**Issue by Flip1** [s9y/Serendipity#554]
This is my first Bugreport, so sorry ... ;-)
I use S9y v2.1.2

When I change the content of an article ...
... in the backend its fine
... in the article-overview and in the categories its fine
... in the single-article-page ... its unchanged.

A look in the Database ... in Table "entries", the body is correct.
But in "entryproperties" there's the old value by property "ep_cache_body"!

Hope that helps to fix this.

And, btw, if I turn "useInternalCache" in Table "config" from false to true ... then the Blog turns into a whitescreen. Without rewrite in .htaccess, PHP tells me there's a problem :-D
But I can't get more information.

**Comment by onli** [comment]
Hi @Flip1, we changed how the caching works in the current master version. I hope we can release that soon. Sorry did that you did not get feedback earlier.

I will close for now here as I assume all of this works now, please re-open if that's not the case.
