### ISSUE TITLE
Categories are not working as expected

### ISSUE THREAD

**Issue by landei16** [s9y/Serendipity#555]
Hey community,

i´m new here and just installed the software to run a blog for my Camper Travels.
Maybe i understood the categories wrong, but when i assign articles to categories and a "guest" is clicking on a specific category, still all Blogs a visible on the screen.

What i´m doing wrong?

Thanks for some help

Landei

**Comment by yellowled** [comment]
Hi @landei16,

this is an issue tracker intended for developers. For user support, please try the [Serendipity forums](https://board.s9y.org) (please make sure to provide an URL to your live blog, if possible).
