### ISSUE TITLE
Open Redirect

### ISSUE THREAD

**Issue by infosecsecurity** [s9y/Serendipity#558]
There is an open redirect on the "URL" parameter from the exit.php page. The parameter value has to be base64 encoded in other to the redirection work.
 https://example.com/exit.php?url=aHR0cHM6Ly93d3cuaW5mb3NlYy5jb20uYnI=

**Comment by th-h** [comment]
Fixed by 19513cdf143ef5659f8afbfb3b16df921060d550 in 2.1.3, AFAIS.
