### ISSUE TITLE
Webpage: Double redirect from s9y.org to http://docs.s9y.org to https://docs.s9y.org

### ISSUE THREAD

**Issue by hannob** [s9y/Serendipity#559]
When calling s9y.org or www.s9y.org (either via http or https) it redirects to:
http://docs.s9y.org/

This in turn right away redirects to
https://docs.s9y.org/

This not only causes an unnecessary double redirect and may take needlessly long, it also poses a security risk: A user who wants to safely browse https://s9y.org/ ends up on another https page, but inbetween gets redirected via http, thus allowing an attacker to forward him to another page.

Please make the redirect from [www.]s9y.org directly go to https.

**Comment by garvinhicking** [comment]
Very true. Fixed, thanks for noticing!

**Comment by hannob** [comment]
Sure?

```
$ curl https://s9y.org -I
HTTP/1.1 302 Moved Permanently
Date: Mon, 23 Jul 2018 11:46:53 GMT
Server: Apache/2.2.15 (CentOS)
X-Powered-By: PHP/5.6.37
Location: http://docs.s9y.org/

**Comment by garvinhicking** [comment]
My fault, missed a place, this was done via a index.php outside the mod_rewrite.
