### ISSUE TITLE
check for S9Y_DB_INCLUDED likely bogus

### ISSUE THREAD

**Issue by hannob** [s9y/Serendipity#563]
When installing s9y (current git) with PHP 7.2 one of the warnings I get in the log is this:

PHP Warning:  Use of undefined constant S9Y_DB_INCLUDED - assumed 'S9Y_DB_INCLUDED' (this will throw an Error in a future version of PHP) in [path]/include/functions_installer.inc.php on line 650

This is the code where this happens:
```
    // For shared installations, probe the file on include path
    //include_once(S9Y_INCLUDE_PATH . 'include/db/db.inc.php');

    if (S9Y_DB_INCLUDED) {
        serendipity_db_probe($_POST, $errs);
    }
```

I tried to fix this, but it turned out there's something weird. The natural fix would be to change the if-clause to (defined('S9Y_DB_INCLUDED') && S9Y_DB_INCLUDED). However that broke the installer completely, it was no longer possible to install s9y.

Then I looked into this. In practice this if-clause will never not match. The reason is if a constant is undefined PHP will assume it's a string, which will always be true if used in a boolean expression. There's no place in the s9y code where S9Y_DB_INCLUDED is set to false. Thus we always get true.
S9Y_DB_INCLUDED is set to true in db.inc.php, which, as you can see in the code snippet, was apparently included in the past in this file, but it's commented out.

So to the best of my judgement this if-clause simply doesn't make any sense and it should be removed. However I don't know the code and its context.

Also relevant for #556

**Comment by onli** [comment]
Yes, this just seems wrong. The usual constant check in s9y, now mostly removed, was something like 

```
if (defined('S9Y_FRAMEWORK_PERMALINKS')) {
    return;
}
```

It is absolutely possible thought that the code you question here worked at one point in time. 

But I also do not know the context of this, so I'll refer to @garvinhicking

**Comment by garvinhicking** [comment]
Yeah, I think the clause would probably just be changed to 

```
if (defined('S9Y_DB_INCLUDED') {
  serendipity_db_probe($_POST, $errs);
}
```
does that work and not break the installer for you?

**Comment by hannob** [comment]
Hi garvin,
If I do this then - as I indicated already in the original report - the installation doesn't work. I believe this is due to the fact that the code originally expected db.inc.php to be included (where S9Y_DB_INCLUDE gets defined), but that's been commented out.

I end up getting:
```
Fatal error: Uncaught Error: Call to a member function prepare() on null in /home/hanno/websites/test.q2.re/htdocs/include/db/pdo-sqlite.inc.php:232 Stack trace: #0 /home/hanno/websites/test.q2.re/htdocs/include/admin/installer.inc.php(319): serendipity_db_query('SELECT * FROM s...', false, 'both', false, false, false, true) #1 /home/hanno/websites/test.q2.re/htdocs/serendipity_admin.php(254): require('/home/hanno/web...') #2 {main} thrown in /home/hanno/websites/test.q2.re/htdocs/include/db/pdo-sqlite.inc.php on line 232

**Comment by onli** [comment]
I removed that now. Better to react to possible installer errors then to drag unspecified code along.
