### ISSUE TITLE
Remove $HTTP_RAW_POST_DATA?

### ISSUE THREAD

**Issue by mattsches** [s9y/Serendipity#574]
The reserved variable [$HTTP_RAW_POST_DATA](http://php.net/manual/en/reserved.variables.httprawpostdata.php) is used in at least [comment.php](https://github.com/s9y/Serendipity/blob/master/comment.php) and [wfwcomment.php](https://github.com/s9y/Serendipity/blob/master/wfwcomment.php), but

> This feature was DEPRECATED in PHP 5.6.0, and REMOVED as of PHP 7.0.0.

Honestly, I haven't encountered any problems with this, but maybe we should consider

> In general, php://input should be used instead of $HTTP_RAW_POST_DATA.

**Comment by onli** [comment]
Thanks for the report. I replaced that call now with `file_get_contents("php://input");`. This might need some more testing.
