### ISSUE TITLE
Installation of git version with mysql fails

### ISSUE THREAD

**Issue by hannob** [s9y/Serendipity#584]
I'm trying to create a fresh installation of s9y based on the current git code.

The installation fails with plenty of mysql errors of the form:

```
Warning: mysqli_query() expects parameter 1 to be mysqli, null given in [path]/include/db/mysqli.inc.php on line 68
Warning: mysqli_error() expects parameter 1 to be mysqli, null given in [path]/include/db/mysqli.inc.php on line 71
```

HOWEVER after that it looks like the installation finished just fine. I get a normal output ending with a button "Visit your new blog here":
```
Checking to see if the database and tables already exist
they do not
Creating default database setup... Done
Creating primary author 'John Doe' Done
Setting default theme Done
Installing default plugins Done
Attempting to write .htaccess file...
Done Serendipity has been successfully installed
Thank you for choosing Serendipity

Visit your new blog here
```

So it seems some mysql error happens during the installation, but it's not properly detected. That this can even happen probably means a whole number of error checks are missing.
Trying to visit the site you only get an error of the form "Query failed: Table '[tablename].serendipity_entries' doesn't exist". (Or - if php 7.2 is used - the error from issue #583 )

On an identical setup an installation of the latest 2.1.4 version works fine.

**Comment by onli** [comment]
`serendipity_db_connect()` will have failed, leading to `$serendipity['dbConn']` being null instead of containing the connection. Are you sure the provided mysql-data are correct?

You did run into a case here where the error detection of the sql queries failed because the connection failed completely. It would be good to detect that in the installer, if it can be reproduced.

**Comment by hannob** [comment]
I believe this is fixed due to
https://github.com/s9y/Serendipity/commit/0b259ce52fc8366393076054aa35774342a8f9e3
