### ISSUE TITLE
Introduction of simple-cache dependency in git code makes s9y unusable in secured shared environments

### ISSUE THREAD

**Issue by hannob** [s9y/Serendipity#594]
For security reasons it's common to restrict the opcache API in shared webhosting environments.

Trying to install the latest git code of s9y I get warnings like:
```
Fatal error:  Uncaught ErrorException: Warning: Zend OPcache API is restricted by "restrict_api" configuration directive in [path]/bundled-libs/voku/simple-cache/src/voku/cache/AdapterOpCache.php:32
```
(and a stack trace and a few more of the same kind)

There's usually no reason why an application should directly call into the opcache api. I reported this also upstream, it could be worked around:
https://github.com/voku/simple-cache/issues/19

I have not digged into why this dependency was introduced, but maybe given this was recently it's worthy a discussion. In any case: I wouldn't release it like that, as this will break in many shared hosting environments.

**Comment by th-h** [comment]
Der betreffende Commit ist d52f0004a47425644ff6cd4195798933a5f9bec7, und der Blogbeitrag dazu ist [Serendipity-Entwicklungswoche, Tag 4: Über die Bundled-Libs zu Smarty und nochmal zum Cache](https://www.onli-blogging.de/1794/Serendipity-Entwicklungswoche,-Tag-4-UEber-die-Bundled-Libs-zu-Smarty-und-nochmal-zum-Cache.html).

ping @onli

**Comment by hannob** [comment]
Upstream:
https://github.com/voku/simple-cache/commit/5c15b62188636f87a204ac4a7a45bfc16f0a822e

**Comment by th-h** [comment]
See #595.

**Comment by onli** [comment]
#595 is now merged!
