### ISSUE TITLE
Document PHP 7.0 as minimum

### ISSUE THREAD

**Issue by onli** [s9y/Serendipity#596]
If PHP 7.0 is the new minimum version we should document that with the next release in the docs and the release announcement. Since PHP 7.0 is already EOL in practice that means 7.1 would be the minimal sound choice and PHP 7.2 the better one.

**Comment by voku** [comment]
The problem is that some Linux distributions will still support old versions of PHP... 😑 http://phpversions.info/operating-systems/

**Comment by onli** [comment]
As long as PHP 7.0 is available that's probably okay. Annoying will be the distros stuck on PHP 5.x. But I hope that all relevant hosters have moved on by now, the push for PHP 7 was pretty strong.

Or do you feel like adding PHP 5.6 compatiblity to simple-cache? :) The only other hard requirement for PHP 7.0 I'm aware of is in our autologin cookie token. That one does not trigger errors when not being used and there is a polyfill for older PHP versions that could be added. But frankly, I doubt putting in the work to support the old PHP versions is worth it :/

**Comment by Ressy66** [comment]
We should be supporting whatever the masses are using still. 5.6 is still supported by php org so should be valid usage version.


.

**Comment by yellowled** [comment]
> End of life | A release that is no longer supported. Users of this release should upgrade as soon as possible, as they may be exposed to unpatched security vulnerabilities.

– [The PHP Group](http://php.net/supported-versions.php)

End of life of PHP 5.6 was 2019/01/01. Even PHP 7.0 has reached end of life.

**Comment by th-h** [comment]
Done in code, has yet to be added to the documentation website.

**Comment by onli** [comment]
I'll reopen here to have this in mind for the stable release :)

**Comment by th-h** [comment]
Documentation on docs.s9y.org is now updated.
