### ISSUE TITLE
sitemap plugin: google complains about noindex pages

### ISSUE THREAD

**Issue by hannob** [s9y/Serendipity#601]
While the sitemap plugin now no longer creates malformed XML after the latest fixes I got another warning from Google's search console.

It complains that pages with a noindex metadata flag are in the sitemap.

This seems like a legit complaint from google. A sitemap should inform search engines about pages to be indexed. However at the same time saying "please index this" and "please don't index this" doesn't make much sense.

The noindex flag is included in some of the overview pages. However on a page where I use a template derived from an older version I see different behavior. Needs some more looking into it, but probably some pages should be excluded from the sitemap.

**Comment by onli** [comment]
For your context, the noxindex flag is set in modern themes via the default template index.tpl from 2k11. See https://github.com/s9y/Serendipity/blob/6c699f2ce5ca06a6b03be1c70ad11db9fb65e2b2/templates/2k11/index.tpl#L12. that means there is no comfortable matcher to let the plugin now which pages are not to be indexed. It should be possible to write a function that does this though.

**Comment by onli** [comment]
I added a config option, enabled by default, to the plugin to ignore those overview pages. It's under https://github.com/s9y/additional_plugins/pull/106 (I put it into its own branch because messing up the sitemap coudl be annoying for users). Could you have a look whether this works for you?

**Comment by th-h** [comment]
Works for me.
