### ISSUE TITLE
blog.s9y.org should default to HTTPS

### ISSUE THREAD

**Issue by hannob** [s9y/Serendipity#608]
While the main s9y webpage is proper https, the blog is not. It's available through HTTPS, but http://blog.s9y.org/ does not redirect.

I'd suggest making all s9y webpages https by default (and ideally also deploy hsts).

**Comment by th-h** [comment]
I've added the necessary redirects for blog.s9y.org.

www.s9y.org and s9y.org redirect to https://docs.s9y.org/.
docs.s9y.org is HTTPS by default.
board.s9y.org already redirects to HTTPS.

spartacus.s9y.org is still hosted at sourceforge; we'll have to move the service first. This is already tracked at #592.
