### ISSUE TITLE
Config hashkey may get unintentionally updated

### ISSUE THREAD

**Issue by erAck** [s9y/Serendipity#611]
Due to some odd "race" condition it is possible that the _serendipity_config_'s **hashkey** value gets updated with a new timestamp, which leaves all stored password hashes unusable. The scenario is:

1. The database is offline and not reachable.
2. Load a (admin) page in the browser, possibly with authentication cookies remembered
2.1.  => empty $serendipity configuration array is created.
2.2. message that database is not reachable. Ok.
3. The database comes online again.
4. Reload the (admin) page, credentials are asked
4.1. => the empty $serendipity configuration leads to serendipity_hash() storing a new $serendipity['hashkey'] value with serendipity_set_config_var()
4.2. => all stored password hashes don't match anymore, never ever.

The only remedy is to take the last backup and copy the good value into the _serendipity_config_'s **hashkey** value.

Storing the hashkey value should only be done during installation (or possibly upgrade) of S9y, but not on the fly. Or if that is not feasible then for the on-the-fly case a further check must be done if the configuration is indeed a fresh configuration and a hashkey wasn't stored yet in the table.

**Comment by onli** [comment]
Hi. Did you test this with 2.3? hashkey was used in the versions before, with md5 and sha1. Now bcrypt is used, and the custom haskey not used anymore (since bcrypt manages the hash automatically).

**Comment by erAck** [comment]
No, didn't try with 2.3. But seeing that serendipity_hash() does not rely anymore on a separately saved and possibly to be overwritten hash/salt I believe this is now fixed. Unless the database went offline right before an existing user is converted from sha1 to bcrypt when logging in.. ;-)  The safe state is reached after all users are converted, i.e. have logged in once after the upgrade.

**Comment by onli** [comment]
Okay :) Then I'll close for now and we reopen if it turns out to be still an issue.
