### ISSUE TITLE
Please consider making a new release for compatibility with modern PHP

### ISSUE THREAD

**Issue by hannob** [s9y/Serendipity#613]
The current release version of s9y (2.1.5) has various compatibility issues with modern PHP versions. I'm still running my sites on PHP 7.1, which is nearing end of support by the end of the year [1].

I think it would be good to have a new version soon that ships all the fixes that made it into git head. (FWIW I also did a brief test with an installation of the current s9y git version with PHP 7.4 beta and no warnings showed up.)

[1] https://www.php.net/supported-versions.php

**Comment by th-h** [comment]
> I think it would be good to have a new version soon that ships all the fixes that made it into git head. 

Technically, 2.3-beta1 *is* a release, albeit a beta release; the changes / fixes in git after that are more or less minor.

But I see your point: it's time release a non-beta version.

**Comment by hannob** [comment]
Some further testing revealed a PHP 7.4 issue:
https://github.com/s9y/Serendipity/pull/614

**Comment by hannob** [comment]
As a next step you could make another beta release with the latest fixes and explicitly call for people to test it on modern php (7.3/7.4) and report any warnings.

**Comment by th-h** [comment]
I think we should - and could - release a Release Candidate this weekend.

I'll do that unless someone disagrees.

**Comment by th-h** [comment]
2.3-rc1 is released; the final release is planned for next weekend, unless (grave) bugs arise.

**Comment by th-h** [comment]
Done.
