### ISSUE TITLE
Very long entries partially get lost after saving

### ISSUE THREAD

**Issue by th-h** [s9y/Serendipity#616]
From the [forums](https://board.s9y.org/viewtopic.php?f=3&t=24388):

> Yesterday, I wrote a long entry, saved it and go to sleep very happy! This morning, I opened the entry to correct it and add some new ideas and… a part of my work of yesterday had disappeared.
> 
> I know that the problem is the MySql text field that has a size limited to 64KB. This is small, specially with UTF8.
> 
> Is it possible to have S9Y use MEDIUMTEXT for the body and extended fields of table "entries" in a next version? Or is it possible to have S9Y sending an alert when the text exceed the autorised size?

**Comment by fe-hicking** [comment]
Actually the DB layer replaces {TEXT} with LONGTEXT on the installation. Both mysql and mysqli layers do that. But for older s9y installations there might not have been a DB update script for that. However, the longtext change is like 3 or 4 years ago. In that case, the user could just use a mysql client and adjust the fieldtype?

**Comment by th-h** [comment]
> However, the longtext change is like 3 or 4 years ago. 

Time is passing ... It's documented in the NEWS file for Version 1.6, from 10-2011. :)
