### ISSUE TITLE
PHP 7.2+ issue in serendipity_event_linklist

### ISSUE THREAD

**Issue by th-h** [s9y/Serendipity#617]
From the [forums](https://board.s9y.org/viewtopic.php?f=10&t=24473):

*serendipity_event_linklist* will throw warnings wiht PHP 7.2. and newer:

> Fatal error: Uncaught ErrorException: Warning: Use of undefined constant linkcount - assumed 'linkcount' (this will throw an Error in a future version of PHP) in [...]

**Comment by fe-hicking** [comment]
Has been fixed already: https://github.com/s9y/additional_plugins/commit/98b6926485e0698ea38cd29af321377360fc4b2c#diff-676efc36a762c219c69f5cdf604c3799
