### ISSUE TITLE
Update from 1.5.5 to 2.3.1 (happy end)

### ISSUE THREAD

**Issue by till** [s9y/Serendipity#633]
Hey — the TL;DR: the update worked. So kudos for building software that's capable of being updated after a decade or so. 🚀 

---

On to the challenge: I took all the steps of locking Apache, etc. and then using the updater. It kept saying it's done, but then I got back to the installer. After fiddling with the logging a bit, I found the following:

```
PHP Warning:  fopen(/path/docroot/blog/serendipity_config_local.inc.php): failed to open stream:
 Permission denied in /path/docroot/blog/include/functions_installer.inc.php on line 67
```

Turns out, this was owned my `$USER` and not `www`. (Which fixed it.)

---

The other oddity is (and I don't remember), that none of the plugins were updated. Which creates lots of "noise". Not even sure — this is probably a feature request. But showing updates available when you log into s9y would go a long way.

**Comment by th-h** [comment]
> Hey — the TL;DR: the update worked. So kudos for building software that's capable of being updated after a decade or so. 🚀

Good to hear! 😃

> PHP Warning:  fopen(/path/docroot/blog/serendipity_config_local.inc.php): failed to open stream:
 Permission denied in /path/docroot/blog/include/functions_installer.inc.php on line 67
>
> Turns out, this was owned my $USER and not www. (Which fixed it.)

I'm not sure if it's possible to find out where this came from in such an old installation ...

> But showing updates available when you log into s9y would go a long way.

That's mostly done for 2.4 (you'll get a dashboard notification for pending plugin updates).

**Comment by th-h** [comment]
Thanks for your comments!

**Comment by till** [comment]
@th-h if you handle the warning, then the installer continues. Just fyi. But do as you need. :-)

**Comment by th-h** [comment]
> @th-h if you handle the warning, then the installer continues. Just fyi. But do as you need. :-)

s9y needs write access to `serendipity_config_local.inc.php` to update e.g. the current version, so continuing wouldn't work out - the permissions need to be fixed.

**Comment by till** [comment]
@th-h Yeah, I meant:

```
if (!is_writable($path)) {
  //display error
}
```

So it doesn't _die_.
