### ISSUE TITLE
Query failed: You have an error in your SQL syntax after update to 2.3.1

### ISSUE THREAD

**Issue by igoltz** [s9y/Serendipity#636]
After update from 2.0.5 to 2.3.1 two of our blogs only show

_Query failed: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '0' at line 59_

I found that if $limit is 0 the created SQL statement ends with 0 instead of LIMIT _integer_
Below patch set $limit to empty string if empty($limit) is true. Now the SQL is correct.

```
--- functions_entries.inc.php.org	2019-09-16 11:28:01.000000000 +0200
+++ functions_entries.inc.php	2019-09-17 14:48:32.643881933 +0200
@@ -425,6 +425,8 @@
         }
 
         $limit = serendipity_db_limit_sql($limit);
+    } else {
+       $limit = "";
     }
 
     $query = "SELECT $select_key
```

**Comment by th-h** [comment]
> I found that if $limit is 0 the created SQL statement ends with 0 instead of LIMIT integer

Yes, but limit shouldn't be "0", AFAICS. How does that happen in your installation?

**Comment by igoltz** [comment]
> Yes, but limit shouldn't be "0", AFAICS. How does that happen in your installation?
I don't know, but it happens in 3 out of about 100 instances.
