### ISSUE TITLE
use of GET value and spamblock plugin

### ISSUE THREAD

**Issue by stephanbrunker** [s9y/Serendipity#641]
As I am proceeding through the language settings of Serendipity, I ran into some different issues which are kind of linked. The problem was that if I opened an article like: 

http://www.example.com/index.php?archives/54-English.html&serendipity[lang_selected]=en

### First issue:
I could not get any $_GET information and thus I couldn't provide the requested language. I did a dump of $_GET directly at the beginning of index.php and this was the result:

```
### Debug session 2019-09-28 20:06:21

   21.677656 µs debug file /var/www/s9y-132/index.php at line 13
   Var dump GET: Array
    (
        [archives/36-English_html] => 
        [serendipity] => Array
            (
                [lang_selected] => en
            }
    )
    
===============================================
### Debug session 2019-09-28 20:06:21

   21.866891 µs debug file /var/www/s9y-132/index.php at line 13
   Var dump GET: Array
    (
        [/plugin/captcha_e042a307ffca4c5ea78a4aabedc79881] => 
    )
    
```
As you can see, index.php is called twice (I think by the spamblock plugin) but on the second run, the original GET is stripped so the multilingual plugin cannot easily decide which language to display without saving the information of the GET into storage. Is that double call intended? And what is happening here?

### Second issue:
By looking at GET, i found out that the use of it is somewhat inconsistent. You have the original PHP global $_GET which is (or the serendipity array part) copied to $serendipity['GET'] in compat.inc.php . So consistently, all following functions should use the information in the $serendipity array, but they don't. You find the use of the $_GET all over the code. But that copying doesn't help with issue one because it is empty in the second run, too.

### Third issue:
the structure of the GET for content is also not consistent. For the second page of the main page it is like:

http://www.example.com/index.php?/archives/P2.html

note the ?/  - and for the multilingual article footer link as in issue one it is only the question mark without the slash. Shouldn't that be the same syntax?

I am just asking because I don't know what was intended here ...

**Comment by stephanbrunker** [comment]
The third one is fixed, that was just adding a slash on the right spot in the multilingual plugin. More tricky was to determine how the static url decoding works for the footer links (if an number is given it is used as id, the rest is ignored).

And for the second one: i fixed a few where the call was to $_GET['serendipity'][xxx] where it is straightforward. I also made the language selection in the multilingual sidebar plugin consistent so that it POST in a [serendipity]['user_language'] value. But for the others, I keep my hands off. In plugins.php there is a $_GET['submit'] and in functions_routing.inc.php: there are $_GET version, type, category, viewAuthor, p . Don't know if it would be more consistent if these also are parts of a 'serendipity' arrray.

**Comment by onli** [comment]
> Shouldn't that be the same syntax?

Yes! It should be `?archives` or `?/archives` in both cases.

> Don't know if it would be more consistent if these also are parts of a 'serendipity' arrray.

Probably, but in this situation it's really just a style question.

> but on the second run, the original GET is stripped so the multilingual plugin cannot easily decide which language to display without saving the information of the GET into storage. Is that double call intended? And what is happening here?

If serendipity itself makes a request to itself, the GET parameters of the first original request by the user just won't be present anymore. That's my mental model about this situation at least.

**Comment by stephanbrunker** [comment]
I saved the spamblock plugin for last and will look into it. Perhaps after all the changes I made it will perhaps work anyway or I have to find out why this plugin makes a call on itself. Perhaps I also find out why I still get spam comments even with the plugin active. Which is perhaps because the spammers broke the captcha protection or there is a hole somewhere to circumvent the spamblock. When I get into that code as well I can add extensive logging and put it online to wait for the next spammer to appear. So far, I managed to improve and fix everything so far. As it looks now, you can make it happen that the secondary language is mostly independent of the default language with the only exception that you cannot have an entry which only exists in the secondary language.  I'll be careful to put everything in a well-documented commit.

**Comment by stephanbrunker** [comment]
That is a though nut to crack. With the spamblock active on opening an full article, the framework ist set up and the index.php runs to the end up to $serendipity['smarty']->display. Then something happens and the whole process starts again from the beginning after 0.1 second, this time with the GET variables given from the 'post comment' button (which is like /plugin/captcha_xxxx ) I don't think this is intended and it is also a performance killer because the full page is loaded twice. And it causes issues with the multilingual plugin which depends on a GET value which is stripped. But until now, I don't have an idea what causes the reload. It can be an automated submit or something else. But if all the event hooks are already run through, it could be only in the genpage hook which is not configured for the spamblock. Anyone an idea which can shorten my search for the cause?

**Comment by stephanbrunker** [comment]
Okay, I think that one solved itself. The second call to index.php is caused by the source of the captcha image which is defined like `src="http://s9y/index.php?/plugin/captcha_ef559438d6dd277536acc44565dfbfd6"`
When the browser loads the page, it gets to the image and calls to index.php for the image. But I checked the performance and it is neglible - the initialisation of the framework needs 0.01 seconds so that is not an issue, and of course at this point is the page already loaded except for the captcha image. And with the changes in the language functions, the selection is now stable. So I can call this too closed, I just want to check out how the russian spammers get past the spamblock. I don't think there is a human who is typing this in, reads the captcha and clicks on 'comment'.

**Comment by stephanbrunker** [comment]
I found one. In the CRSF check, the 'return false' was missing. So when a forged attach was detected, the request was processed further ...

**Comment by onli** [comment]
That does not sound great, a patch would be highly welcome :)

**Comment by stephanbrunker** [comment]
I made a logging version of the plugin. Unfortunately, the spammers seem to have cracked the captcha protection. I got one display of the page and one second later a comment was issued with the right session ID. That is so fast, that can't be a human and he got the captcha right on the first try. I can think of two countermeasures: Either we write in the description to write the captcha backwards, or setting a time out - only after a reasonable amount of time for a human to read the article a comment is allowed. The error message would be like: "Sorry, but we very appreciate if you read the article before commenting".

**Comment by onli** [comment]
Captchas are indeed broken by default by now, every block can crack them. We rather should remove them, they don't offer protection anymore.

We have a bunch of different spam protections mechanisms in the spambee and bayes plugin. The spamblock plugin is so full and complicated, something like the timeout should rather go into the spambee plugin. And probably is not necessary there, with the hidden captcha and the hidden form field working well.

Btw, I sent you a mail at your web.de address, hope you got it?

**Comment by stephanbrunker** [comment]
I am running a trial version of the spamblock now with a variable timeout, based on the length of the article and the length of the comment with humanly possible values. This fix is possibly not forever, but perhaps works for a time. Depending of how many connections the spambots can open at a time because they have to wait to comment.

**Comment by stephanbrunker** [comment]
The trial works for now. I'll make a PR.
