### ISSUE TITLE
Backend Entry Editor: media_choose

### ISSUE THREAD

**Issue by stephanbrunker** [s9y/Serendipity#651]
Some versions back, i think if you wanted to insert a picture in your article, you clicked on the "media database" and then you got to the media_choose template. Now, i had to try for a while until i got there. The button for media database opens a selector with checkboxes at the picture, but if you select your picture and click 'Insert all' the pictures get inserted as gallery list. To get the previous selector, you have to click on the picture … just that there is no clue you have to. Have I simply forgotten that it was like that all the time or was that changed by adding the checkboxes which obscured that you have to click on the picture? Either way, it would be better now to have two buttons in the selector: One to insert all the selected pictures as a gallery and another to insert a single picture with the media_choose options. Or a text which tells you to click on a single picture or select multiple pictures for a list.

**Comment by onli** [comment]
Hi. No, that's new. It's the gallery insert function, for which I/we added those checkboxes. 

> Ether way, it would be better now to have two buttons in the selector: One to insert all the selected pictures as a gallery and another to insert a single picture with the media_choose options.

How would this work? Show the button at the bottom and hide it when multiple images got selected?

I'd rather suggest o change the one button we have to go to the media_choose dialog when only one image is selected.

>  Or a text which tells you to click on a single picture or select multiple pictures for a list.

If we need a label to explain functionality like this the UI is wrong. It's always better to find a solution that works without such a label (those are not read, and they should not be needed if the UI is functioal).

**Comment by stephanbrunker** [comment]
As you said, the best (intuitive) solution is to go to the media_choose dialog when one picture is selected and insert gallery on a multiple selection. I don't know who did add the gallery function but for him it would be an easy fix.

**Comment by garvinhicking** [comment]
I just wanted to write the same thing. Yeah, a distinction on whether only one image or multiple ones have been checked would be logical.

**Comment by onli** [comment]
That was me ;) Wouldn't be that easy, because you'd need to change the form target depending on the amount of checked images. But it should be doable of course.

**Comment by fe-hicking** [comment]
I thought this would be quite easy.

When implementing this became actually very hard. Clicking a link within MFP with a javascript like this:

```
$('.media_file_preview a').first().click();
```

actually does not work. So I had to take the low-road and manipulate location.href instead of actually clicking the <a> element. If someone knows why exactly this is happening and how to properly execute the actual <a> element's link I'd be very happy to get this implemented in a clean way.

**Comment by onli** [comment]
Oh, my plan would have been to change the form to have the same GET parameters and target contained in the href of the one selected image. But your way looks easier, regardless of the href hack.

**Comment by th-h** [comment]
AFAIS that works (in current master, and - as it has been backported) in 2.3.4.
