### ISSUE TITLE
Links to Articles do not work anymore

### ISSUE THREAD

**Issue by ddeimeke** [s9y/Serendipity#653]
After an update from PHP 7.1 to PHP 7.3, links to articles do not work anymore.

The Link https://www.deimeke.net/dirk/blog/index.php?/archives/3948-Hiring-DevOps-....html should point to the article "Hiring DevOps", but it shows the frontpage of the blog.

Serendipity 2.4-alpha1 and PHP 7.3.10

**Comment by garvinhicking** [comment]
Hopefully fixed in master, regression from #642

**Comment by th-h** [comment]
Fixed via 5b35569e73dd54bffe9f0d7476fb71c01a82e9b0, confirmed by @ddeimeke
