### ISSUE TITLE
External plugin login

### ISSUE THREAD

**Issue by stephanbrunker** [s9y/Serendipity#657]
There is one language bug left for me to fix. The language in the backend is now plucked from the user language setting in the database, in the frontend can the user still select any language. The bug is now when this language change happens, the plugins are loaded in the frontend language. This is because of the order of events in the configuration. First, the general language is determined with `serendipity_getSessionLanguage()` , then `serendipity_login(false)` is called and when a user is logged in with `serendipity_load_configuration(authorid)` the language for the user which is reverted to the original selection for the frontend in `serendipity_getPostAuthSessionLanguage()` . Then `lang.inc.php` is called which sets the language. 

The parameter 'false' for serendipity_login should not - following the description - forward the login to external plugins. There are three event hooks called: backend_login , backend_loginfail and backend_auth. The last one is really depending on the false parameter, the others not. The issue is only that by calling any event hook at this point in the configuration process, all the plugins are loaded and by that the language constants defined, which by nature cannot be changed later. And prior to the login, the user language is not yet determined. `serendipity_login(true)` is called again later on by serendipity_admin.php.  

I have checked now which plugins use these hooks and why. backend_loginfail is only used by event_externalauth for logging purposes. backend_login is used by event_browserid and event_openid. backend_auth doesn't matter because it is issued after all the language settings because of the parameter.

My proposal would be to expand the false parameter to the other two event hooks, that these external plugins are called after the framework is set up like intended. By doing that, the first event hook is frontend_configure at the end of the configuration which is a good place to initialize the plugins. 

For event_externalauth it shouldn't matter because I think the logging of failed attempts is intended for the own attempt by backend_auth which is not called on the first run. I am not sure if both other plugins should login at backend_login or at backend_auth like the externalauth plugin, but anyway, it should not matter when that also happens on the secondary login run. Basically, this long message revolves around two small if() conditions. And to load the languages correctly for users authenticated with an external plugin, after the second run of serendipity_login the page should be reloaded in case of an login, which is simply done by sending a header. Then the login session vars and cookies are set and the user language is loaded correctly prior to plugin initialization.

**Comment by onli** [comment]
Hi @stephanbrunker! I think these hooks are not used that much. If you want to change details there the alpha cycle is the right moment, if it has unforeseen consequences we should find them. 

This change is not already in #658, right?

**Comment by stephanbrunker** [comment]
That change is already in the PR, that all the external login action happens after the first, internal attempt. But this can only affect the browserid and openid plugins. I could not check if that changes anything because I don't have any account with openid, but it should do nothing. That change only affects the functions_config.inc.php.

 I included both PRs (Serendipity and plugins) in my personal version and it works fine, especially the multilingual plugin. The spamblock is now working too, at least for a while - spam doesn't get through the timeout, but real comments are. So if you merge those two commits, everything is fixed what I wanted to fix. (The last commit was the nl2br which didn't accepted the figure tag from the new media insertion)

**Comment by onli** [comment]
Okay. I merged and we will see whether this works as expected.
