### ISSUE TITLE
freetag plugin will advertise index pages of tags only existing on draft entries

### ISSUE THREAD

**Issue by hannob** [s9y/Serendipity#659]
While looking through google's search console I noticed a curious issue. It seemed google had recorded some tag overview pages (/plugin/tag/[sometag]) that didn't exist and emitted a 404.

Digging down why this happened it seems these were tags from draft blog posts I had never published. They still generated URLs for the sitemap, but didn't generate a page.

Not sure if this is worthy of a fix (I "fixed" it by deleting a few never-finished blogposts), but I wanted to at least let you know :-)

**Comment by onli** [comment]
I'd say it would be worth a fix if we do not change the default behaviour to not include tags :)

For each tag we'd have to check whether there is at least one entry using that tag. That's a doable sql-query, but I'd be a bit wary of the performance impact :/

**Comment by th-h** [comment]
This is not a bug in the freetag plugin, but in `serendipity_event_google_sitemap`.

> For each tag we'd have to check whether there is at least one entry using that tag. That's a doable sql-query, but I'd be a bit wary of the performance impact :/

We already do that for the sidebar plugin `serendipity_plugin_freetags`. Copied the code, tested on a test blog, seems to work alright.
