### ISSUE TITLE
[serendipity_plugin_recententries] SQL syntax error in current git-checkout

### ISSUE THREAD

**Issue by bauigel** [s9y/Serendipity#661]
I tried to use current git-version on my live system (like i ever do... ;) ) and since a few days (or more?!) it seems that the recententries-plugin doesn't work anymore. I just the following sql error...

You can see it at my homepage on https://bernd.distler.ws

> You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'FROM serendipity_entries AS e LEFT JOIN serendi' at line 6
> SELECT DISTINCT id, title, timestamp, FROM serendipity_entries AS e LEFT JOIN serendipity_entrycat ec ON e.id = ec.entryid LEFT JOIN serendipity_category c ON ec.categoryid = c.categoryid LEFT JOIN serendipity_authorgroups AS acl_a ON acl_a.authorid = 1 LEFT JOIN serendipity_access AS acl_acc ON ( acl_acc.artifact_mode = 'read' AND acl_acc.artifact_type = 'category' AND acl_acc.artifact_id = c.categoryid ) WHERE isdraft = 'false' AND timestamp <= 1573155867 AND ( c.categoryid IS NULL OR ( acl_acc.groupid = acl_a.groupid OR acl_acc.groupid = 0) OR ( acl_acc.artifact_id IS NULL ) ) ORDER BY timestamp DESC LIMIT 5

**Comment by bauigel** [comment]
OK, today i searched for the problem and it seems to be in file serendipity_plugin_recententries.php at line 219. If i remove the comma after "timestamp",  it works (for me) but i don't know if there could be problems with the 'addkey' in line 220 if there is value for it. Maybe there would be an if condition needed in line 215?

```
215         $sql_condition['addkey'] = rtrim($sql_condition['addkey'],",\n") . "\n";
216 
217         $entries_query = "SELECT DISTINCT id,
218                                 title,
219                                 timestamp, 
220                                 {$sql_condition['addkey']}
221                            FROM {$serendipity['dbPrefix']}entries AS e
222                                 {$sql_condition['joins']}
223                           WHERE isdraft = 'false' {$sql_condition['and']}
224                                 $sql_order
225                                 $sql_number";

```

**Comment by bauigel** [comment]
It seems, @stephanbrunker did this changes in https://github.com/s9y/Serendipity/commit/502b837dd6b49674671ba2c7e882d52b1f0edfb4#diff-d2bb015c31c2532d6957f83ffbea79c1

@stephanbrunker Could you please have a look at this?

**Comment by stephanbrunker** [comment]
Okay, if the _addkey_ condition is empty, there is an syntax error.  Didn't recognize this because it is not empty for me, sorry for that. I am going to fix that ASAP with an if-condition.

**Comment by stephanbrunker** [comment]
That should fix it.
