### ISSUE TITLE
LifeType importer issue

### ISSUE THREAD

**Issue by acoul** [s9y/Serendipity#664]
Hello, I am trying to import a  lifetype-1.2.12 blog on a Serendipity 2.3.2 without much success. I do get the following messages:

  Starting import procedure...
  Import successfully completed

but Serendipity blog remains empty. So far, I haven't found any further information on the lifetype importing procedure.

**Comment by acoul** [comment]
until this issue gets resolved, a few pointers that may help current lifetype users:

 https://github.com/lo-windigo/lifetype-export
http://git.ozo.com/?p=lifetype/.git;a=summary

**Comment by yellowled** [comment]
@acoul I'm sorry, but I assume you are an edge case. Most of s9y's importers are very old and not very well maintained since most of them were never really used and tested. About the only suggestion I have would be trying to use the RSS import instead. :-/

**Comment by th-h** [comment]
Thanks for the pointers! - Otherwise, I concur with yellowled: I don't see a feasible way to debug the importer right now, so I'll close the issue for now.
