### ISSUE TITLE
[serendipity_plugin_comments] Weird word wrapping in the sidebar view

### ISSUE THREAD

**Issue by lotharsm** [s9y/Serendipity#669]
It looks like the sidebar comments plugin is introducing some weird (and broken) whitespaces inside some words. I tried to play around with the word wrapping settings, but I couldn't get the additional whitespaces to disappear.

This seems to be not only happening on my blog, since I could observe it on another s9y installation too.

To illustrate, I attached this screenshot:
![comment-wrapping](https://user-images.githubusercontent.com/11882577/71322099-cfb21a80-24c3-11ea-9407-464562b933bd.PNG)

The yellow marks show the whitespaces that shouldn't be there.

Any ideas?

**Comment by th-h** [comment]
Yes, I can confirm that from my blog; a long-standing problem I just mostly forgot about. :)
