### ISSUE TITLE
Entries dated in the future "lose" deactivated plugins

### ISSUE THREAD

**Issue by ddeimeke** [s9y/Serendipity#670]
Serendipity 2.4-alpha1 and PHP 7.3.13

I create some entries, date them for the following day and deactivate the NL2BR-Plugin. Once the date is over the entries appear as expected in the blog, but the plugin is not deactivated anymore.

Sounds like a bug.

**Comment by stephanbrunker** [comment]
If it is in the plugin, is has to be in these lines, but I didn't touch them (this time):

`$markup = serendipity_db_bool($this->get_config('check_markup'));

        if (isset($hooks[$event])) {

            switch($event) {

                case 'frontend_display':

                    // check single entry for temporary disabled markups
                    if ( !$eventData['properties']['ep_disable_markup_' . $this->instance] &&
                         @!in_array($this->instance, $serendipity['POST']['properties']['disable_markups']) &&
                         !$eventData['properties']['ep_no_textile'] && !isset($serendipity['POST']['properties']['ep_no_textile']) &&
                         !$eventData['properties']['ep_no_markdown'] && !isset($serendipity['POST']['properties']['ep_no_markdown'])) {
                        // yes, this markup shall be applied
                        $serendipity['nl2br']['entry_disabled_markup'] = false;
                    } else {
                        // no, do not apply markup
                        $serendipity['nl2br']['entry_disabled_markup'] = true;
                    }
                    if ($markup && $serendipity['nl2br']['entry_disabled_markup'] === false && (class_exists('serendipity_event_textile') || class_exists('serendipity_event_markdown'))) {
                        break;
                    }`

**Comment by ddeimeke** [comment]
The disabling works in principle.

**Comment by th-h** [comment]
I think I have observed the same, but with META-Description (from `serendipity_event_metadesc`) and Social-Media-Image (from `serendipity_event_social`).

Those things have one thing in common: they're saved in the `entryproperties` table.

And it's no problem with the inital save; some future entries still have that data.
(Quite an annoying bug, as #577 was - or is?)

**Comment by th-h** [comment]
It's the same problem as #577 was (and still is, as it wasn't fixed).

See #688 for a summary of the complete set of issues. Closing here.

**Comment by th-h** [comment]
@ddeimeke Should be fixed in the _entryproperties_ plugin in current master. If you could test that some day I'd appreciate it. :-)
