### ISSUE TITLE
Media manager mixes serendipity_image_left and serendipity_image_center

### ISSUE THREAD

**Issue by manitu-opensource** [s9y/Serendipity#672]
The media manager mixes

`<img ... ... class="serendipity_image_left" ... >`

and

`<img ... class="serendipity_image_center" ... >`

when selecting images.

Attached is some diff (fix):
[diff.txt](https://github.com/s9y/Serendipity/files/4196724/diff.txt)

**Comment by yellowled** [comment]
@manitu-opensource Sorry, I can't seem to reproduce the error. Where and how does this work wrong for you?

**Comment by manitu-opensource** [comment]
In Admin Panel:

* new blog post
* Button "media manager"
* select any image (one, 1)
* Select center or left image direction

If you choose enter, the image will be aligend left and vice versa.

**Comment by th-h** [comment]
I can't reproduce that.

When I choose "center" (first, leftmost selection), I get the image centered; when I choose "left" (second selection, i.e. in the middle), I get that too. Same for "right" (third, rightmost selection). That seems to match with what I can read from the code.

(It may be counterintuitive that "center" has to be selected on the left and "left" in the center, but the icons should speak for themselves. (We got perhaps add title talks?) Apart from the fact that this selection menu has always been designed this way, this also makes sense to me as "centered" also means "without surrounding text", and this is the default choice, in my opinion.)

**Comment by manitu-opensource** [comment]
Oh sorry. Now I see it. I misinterpreted the images and supposed that aligning left would be the left option, centered the centered one etc.

My mistake. Sorry!
