### ISSUE TITLE
[serendipity_plugin_entrypaging] Pagination broken

### ISSUE THREAD

**Issue by yellowled** [s9y/Serendipity#679]
See @mariohommel s [Test blog](https://vps.hommel-net.de/serendipity/archives/3-Lorem-ipsum.html)

Next post (*not* archives prev/next, but prev/next generated by the entypaging plugin) should be https://vps.hommel-net.de/serendipity/archives/4-Test-iFrame.html, but links to https://vps.hommel-net.de/serendipity/archives/6-Testing-Emojii.html instead.

I would assume that this is somehow related to stable archives, see https://github.com/s9y/Serendipity/pull/626/commits/f4d47812a5a4e30086b44e0b72758043edbf3540 or https://github.com/s9y/Serendipity/pull/628/commits/ebb852d400b3a07348cc8faeb7f4d9ab25822b14

**Comment by th-h** [comment]
I don't think so. "entrypaging" is working in 2.3.2 (with stable archives). Something in master must have changed.

**Comment by th-h** [comment]
I can't reproduce that on current master.

Just an idea: @mariohommel could you please check your plugin configuration for the entrypaging plugin? There is a switch "PLUGIN_ENTRYPAGING_USECATEGORY" ("Use category-based pagination" or "Linkauswahl auf Basis der aktuelle Kategorie", respectively). If that is set to "yes", the behaviour would be correct, as the Lorem-Ipsum entry (no 3) is in the "Testkategorie" category, as is entry no 6, but not entry no 4 (nor no 5 - an those are skipped).

**Comment by mariohommel** [comment]
@th-h You're right! Don't know who set this switch to "yes", maybe it's default. After setting it to "no" everything is fine.
