### ISSUE TITLE
Really use thumbnails when requested

### ISSUE THREAD

**Issue by onli** [s9y/Serendipity#682]
When inserting an image into an entry, in my blog at least, the selection whether to use a thumbnail or a full sized image does not work reliably. It just happened that I tried to insert a thumbnail, but it used the full sized image.

This might be a JS issue, but it might also be related to the responsive image plugin (see #474 ), I faintly remember that the flow with that lead to ignoring options. This might also be related to the issues reported by manitu in #672

**Comment by th-h** [comment]
Can't reproduce yet on 2.3.4 (stable) or current master, but will look out for that.

**Comment by onli** [comment]
This problem seems to have vanished, maybe in a plugin update or something similar.
