### ISSUE TITLE
Scheduled entries lose all entryproperty information on publish date

### ISSUE THREAD

**Issue by th-h** [s9y/Serendipity#688]
This is a long-standing issue that is quite hard to debug. It crept up before (see #577, which unfortunately was not really solved as I thought) and was observed elsewhere (see #670 which is the same problem).

It seems (!) the issue is this:

* Prepare a scheduled entry with a publication date and time set in the future.
* Add some information that is saved in the `entryproperties`  table (from `serendipity_event_entryproperties` or from `serendipity_event_metadesc` or from `serendipity_event_social`).
* When the publication time has come, all that information gets lost. That is at least true if the entry is still a draft, but I think will happen if it is set to be published, too.
* I didn't have time to look deeper, but the problems seems to be triggered by the `generateDelayed` function of `serendipity_event_trackback` that is triggering the database update routines from the other plugins mentioned before, but with empty data.

I had placed some extensive logging at the database layer of my production blog, logging all INSERT, UPDATE and DELETE queries referring to the `entryproperties` table together with the callstack. I got this result for a draft (!) entry with a publishing date of _2020-04-06_ at _06:30_ (filesystem path shortened by replacing docroot with PATH_TO_S9Y):

```
------------------------------ 2020-04-06 06:30:23
Array
(
    [0] => Array
        (
            [file] => PATH_TO_S9Y/plugins/serendipity_event_social/serendipity_event_social.php
            [line] => 272
            [function] => serendipity_db_query
        )

    [1] => Array
        (
            [file] => PATH_TO_S9Y/include/plugin_api.inc.php
            [line] => 1184
            [function] => event_hook
            [class] => serendipity_event_social
            [type] => ->
        )

    [2] => Array
        (
            [file] => PATH_TO_S9Y/include/functions_entries.inc.php
            [line] => 1482
            [function] => hook_event
            [class] => serendipity_plugin_api
            [type] => ::
        )

    [3] => Array
        (
            [file] => PATH_TO_S9Y/plugins/serendipity_event_trackback/serendipity_event_trackback.php
            [line] => 289
            [function] => serendipity_updertEntry
        )

    [4] => Array
        (
            [file] => PATH_TO_S9Y/plugins/serendipity_event_trackback/serendipity_event_trackback.php
            [line] => 222
            [function] => generateDelayed
            [class] => serendipity_event_trackback
            [type] => ->
        )

    [5] => Array
        (
            [file] => PATH_TO_S9Y/include/plugin_api.inc.php
            [line] => 1184
            [function] => event_hook
            [class] => serendipity_event_trackback
            [type] => ->
        )

    [6] => Array
        (
            [file] => PATH_TO_S9Y/include/genpage.inc.php
            [line] => 26
            [function] => hook_event
            [class] => serendipity_plugin_api
            [type] => ::
        )

    [7] => Array
        (
            [file] => PATH_TO_S9Y/include/functions_routing.inc.php
            [line] => 505
            [args] => Array
                (
                    [0] => PATH_TO_S9Y/include/genpage.inc.php
                )

            [function] => include
        )

    [8] => Array
        (
            [file] => PATH_TO_S9Y/index.php
            [line] => 70
            [function] => serveArchives
        )

)

Query:DELETE FROM serendipity_entryproperties WHERE entryid = 2235 AND property = 'entry_image'
```
There's more of the same for other fields in `entryproperties` from other plugins; I've shortened the log to the most relevant lines:

```
------------------------------ 2020-04-06 06:30:23
Array
(
    [0] => Array
        (
            [file] => PATH_TO_S9Y/plugins/serendipity_event_metadesc/serendipity_event_metadesc.php
            [line] => 252
            [function] => serendipity_db_query
        )

    [1] => Array
        (
            [file] => PATH_TO_S9Y/include/plugin_api.inc.php
            [line] => 1184
            [function] => event_hook
            [class] => serendipity_event_metadesc
            [type] => ->
        )
[...]
Query:DELETE FROM serendipity_entryproperties WHERE entryid = 2235 AND property = 'meta_description'
```

And from `serendipity_event_entryproperties` we get these (all with the same call stack):
```

Query:DELETE FROM serendipity_entryproperties WHERE entryid = 2235 AND property LIKE 'ep_disable_markup_%'
Query:DELETE FROM serendipity_entryproperties WHERE entryid = 2235 AND property = 'ep_is_sticky'
Query:DELETE FROM serendipity_entryproperties WHERE entryid = 2235 AND property = 'ep_no_frontpage'
Query:DELETE FROM serendipity_entryproperties WHERE entryid = 2235 AND property = 'ep_hiderss'
```

So somehow s9y is nuking all extended entry information when trying to `#generate trackbacks for entries which now are shown` (which doesn't work right in its own right as it is triggered even for draft entries that reach their publish date).

I don't have time to look into this now, but I think that is the culprit.

**Comment by th-h** [comment]
Yes, that's it.

* `generateDelayed()` from `serendipity_event_trackback.php` calls `serendipity_updertEntry($stored_entry)` (line 289 of current master).
* `serendipity_updertEntry()` in `include/functions_entries.inc.php` triggers the `serendipity_plugin_api::hook_event('backend_save')` (line 1284 in 2.3 branch as logged above, line 1289 in current master).
* The `backend_save` hook is catched in all plugins that update `entryproperties` information, e.g. at line 263 in current master of `serendipity_event_social.php`, deleting old information and saving new - but there **is** no new information in `$serendipity['POST']` in this case.

**Comment by onli** [comment]
Sidenote: https://github.com/s9y/additional_plugins/blob/master/serendipity_event_trackback/serendipity_event_trackback.php#L262 need a check to not go forward for drafts. Normally there should not be drafts in the table, but that can easily happen when saving an entry first as non-draft and then as draft. Didn't think that through.

So you are saying we need to populate `$serendipity['POST']` in `generateDelayed()`, or stop the plugins from deleting the old information when no new one is available?

I think that maybe just https://github.com/s9y/additional_plugins/blob/master/serendipity_event_social/serendipity_event_social.php#L271 is not correct. That should be an "INSERT OR REPLACE" for just the image, not deleting all other data.

**Comment by th-h** [comment]
> Normally there should not be drafts in the table, but that can easily happen when saving an entry first as non-draft and then as draft. Didn't think that through.

That's not the case for me; my entries are set to be drafts by default, so they're always saved as drafts only and set to "publish" only immediately before publishing. So they're not saved as non-draft before.

> So you are saying we need to populate $serendipity['POST'] in generateDelayed(), or stop the plugins from deleting the old information when no new one is available?

The former, yes.

It's correct to delete old information even no new is available, because that's what should happen if the user has deleted the information (see below).

> That should be an "INSERT OR REPLACE" for just the image, not deleting all other data.

That code just touches the image (`AND property = 'entry_image'`) (and no other data).

I think code is correct in itself; it has to cover the case that the input field is empty because the user has deleted the content before submitting the form in order to remove an image (a META description, ...). So DELETing the database row (on that item) and INSERTing the new contents only **if** there is new contents is the right thing to do.

We "just" have to make sure that all calls to `serendipity_updertEntry()` (all triggers of `backend_save` and `backend_publish`) contain data for everything that may be submitted when saving or publishing an entry. That will include at least everything that is saved in `entryproperties`; I don't know if there are other plugins that save data to other tables when an entry is submitted.

**Comment by th-h** [comment]
Interesting. I can reproduce the problem on a fresh install of a **stable** (2.3) blog:

* You get a (wrong) entry in the `delayed_trackbacks` table for draft entries (every time you save a draft with an future publication date).
* When `generateDelayed()` is triggered or you publish the entry from our dashboard, all extended properties are lost.

But until now I can reproduce **neither** on a fresh checkout of our **master** branch. There are no entries in `delayed_trackbacks`  for drafts, and you don't lose any extended properties.

**Comment by th-h** [comment]
It's not s9y version, but `serendipity_event_freetag`. With `serendipity_event_freetag` active, I can reproduce the problem in most cases on all installation. After deactivating `serendipity_event_freetag`, the problem disappears (even in the stable version).

**Comment by th-h** [comment]
Whatever it is, it should be fixed in those plugins responsible to write extended properties, i.e. *entryproperties*, *metadesc* and *social*.

**Comment by th-h** [comment]
The problem can be reproduced a bit easier by publishing a draft from the dashboard. That will have the same result as when `delayed_trackbacks` is called - it will either nuke extended properties or (correctyl) keep them.

**Comment by th-h** [comment]
Modifications tested on a current checkout from master, manually adding the fixes from additional plugins. Works for me. - It's still possible to reset the multi-select for disabled markups and the other checkboxes from the _entryproperties_ plugin, so that should fix everything.
