### ISSUE TITLE
Backend title doubleencoding

### ISSUE THREAD

**Issue by hannob** [s9y/Serendipity#691]
I noticed that in the backend "Entries" overview the titles seem to have double-encoded HTML entities.

Screenshot with a recent blogpost of mine with brackets should show this:
![s9y-doubleenc](https://user-images.githubusercontent.com/990588/78782216-ef514e00-79a1-11ea-9e47-ae7dc9957037.png)

**Comment by onli** [comment]
Hi @hannob. Is that with the current master, or a release? I think that @stephanbrunker solved this in https://github.com/s9y/Serendipity/pull/668, but we were late merging it, so it's not in a release yet.

**Comment by hannob** [comment]
Ah sorry, failed to properly check existing issues (given that this was there a while I hadn't really expected a duplicate...)
This was with the current release. If it's fixed then fine.

**Comment by th-h** [comment]
I've already marked #668 for backporting.

**Comment by onli** [comment]
Great :)
