### ISSUE TITLE
Search term with quotes leads to an ugly php error

### ISSUE THREAD

**Issue by ddeimeke** [s9y/Serendipity#704]
Please search for "sechs-Monats-Regel" (including quotes):

https://www.deimeke.net/dirk/blog/index.php?serendipity%5Baction%5D=search&serendipity%5BsearchTerm%5D=%22sechs-Monats-Regel%22&serendipity%5BsearchButton%5D=Los%21

**Comment by th-h** [comment]
Can't reproduce that on my own blog (2.3.5).

Can't reproduce on current checkout of stable branch (2.3.6-beta1 which is identical to 2.3.5 right now), see screenshot:
![Screenshot 2020-04-25 15 34 16](https://user-images.githubusercontent.com/365129/80281355-c0113f80-870a-11ea-956c-e3d2d6525adb.png)

On current checkout of master, I do get an error message, but no exception, see screenshot:
![Screenshot 2020-04-25 15 34 14](https://user-images.githubusercontent.com/365129/80281374-e800a300-870a-11ea-887e-fa0caf899597.png)

**Comment by ddeimeke** [comment]
Serendipity 2.4-alpha2 and PHP 7.3.17 on my side.

**Comment by th-h** [comment]
Yep. It's reproducible on master<sup>1</sup>, but not on stable. Problem is that I don't see (obvious) changes in the relevant code ... must be a side effect of another change somewhere,

<sup>1</sup>: Depending on the search term, one can get the same result on your blog as on the test blog running current master, so it's the same error.

**Comment by stephanbrunker** [comment]
I tried to reproduce the error, so I created a new copy of master, but using my old database. The upgrade process to utf8mb4 failed without creating an error (i have to look into that) and with an latin database, the current master files also don't create an error.

**Comment by stephanbrunker** [comment]
I can confirm: The error is directly dependent of the database collation. If it is native latin1-german2-ci, there is no error with the current master, the error occurs only after when the database is transformed to utf8mb4 by the upgrader.

**Comment by th-h** [comment]
Yep. The test database in the master checkout has all table collations as `utf8mb4_unicode_ci` (and InnoDB as engine) while the stable checkout has collations of `utf8_unicode_ci` (and MyISAM), except for `serendipity_entrytags`, `serendipity_delayed_trackbacks`, `serendipity_tagkeywords`, `serendipity_spamblocklog` and `serendipity_spamblock_htaccess` which are `utf8mb4_unicode_ci`.

So it's a problem with full text searches either on InnoDB tables or on tables with `utf8mb4_unicode_ci` as collation.

**Comment by onli** [comment]
Just a note: The search works for me in my testblog, so this might depend on the exact version of mariadb/mysql.

**Comment by onli** [comment]
Correction: Now I see the error message as well in my dev blog. No idea why it did not appear before.

**Comment by ddeimeke** [comment]
Works! Thank you!
