### ISSUE TITLE
SQL error in hCalendar

### ISSUE THREAD

**Issue by andreasscherbaum** [s9y/Serendipity#710]
Hello,

I'm running S9y on PostgreSQL, and I see the following error in my log:
```
SELECT * FROM serendipity_entryproperties WHERE property LIKE 'mf_hCalendar_%' AND entryid IN (SELECT entryid FROM serendipity_entryproperties WHERE property = 'mf_hCalendar_startdate' AND value > (1587593847 - 259200))
ERROR:  operator does not exist: text > integer
LINE 1: ...ERE property = 'mf_hCalendar_startdate' AND value > (1587593...
That error happens because the "value" field in "public.serendipity_entryproperties" is of type "TEXT", and the comparisation is for a number.
```

Probably the easiest way to fix that error is to cast "value" to an INT or BIGINT:
```
AND value::INT >
```
However I can't quite figure out where this query is generated, otherwise I would provide a patch.

**Comment by onli** [comment]
Do you have the plugin serendipity_event_microformat installed? Grepping for mf_hCalendar pointed me to that plugin, the query might come from there.

**Comment by andreasscherbaum** [comment]
Ha, good catch, thanks.

PR is open here: https://github.com/s9y/additional_plugins/pull/115

**Comment by onli** [comment]
Merged!
