### ISSUE TITLE
"Your entry has been saved" is gone

### ISSUE THREAD

**Issue by andreasscherbaum** [s9y/Serendipity#711]
Hello,

I have one blog installation where the "Publish" dialog stays empty. I attached a screenshot of the situation. Did an integrity check of the installation, but it just says that everything is alright.

The backend theme is "2k11". The "Your entry has been saved" text is stored in the translations as "ENTRY_SAVED". In the blog where this is working, I find this text in "templates/2k11/preview_iframe.tpl" and in the compiled template under "templates_c". In the blog where this is not working, I have the same file (identical checksum for preview_iframe.tpl), but the string never appears in the cached template directory. In fact, "templates/2k11/" is identical in both installations.
Did try to clean the template cache as well, with no result.

One thing I found: "templates_c/2k11" did not exist in the blog where this is not working, and creating the directory never populated it.

Has anyone an idea where I can start looking what is wrong here?
![s9y_2020-03-30_01](https://user-images.githubusercontent.com/1191463/80507790-82fdb500-8977-11ea-80e2-d7c761b9e6b6.png)
![s9y_2020-03-31_01](https://user-images.githubusercontent.com/1191463/80507794-85600f00-8977-11ea-9c1c-592110644437.png)

**Comment by onli** [comment]
Hi. Did you already check your apache error log? There might be a PHP execution error that prevents the text from being generated.

**Comment by andreasscherbaum** [comment]
Yes, did check that (and just tried again). The Apache2 error log is empty for that time.

Any other meaning of debugging this?

**Comment by andreasscherbaum** [comment]
I did change the frontend template on this specific blog, and the problem is gone.
No idea how that is related though.
