### ISSUE TITLE
W3C Feed validator does not like S9Y feeds with comments

### ISSUE THREAD

**Issue by hannob** [s9y/Serendipity#713]
I'm opening a bug here for transparency and in the hope to get feedback, though I am not sure this is a bug in S9Y or should require any action from our side.

I got complains from people that some tools don't like my blog feed. The W3C Feed Validator will complain for most S9Y feeds with an unclear error [1].

If one runs the validator code locally one will see a python attribute error (will attach file with error). Turning this into a minimal example it turns out HTML comments encoded in the <content:encode> tag are the problem. A minimal example would be this:
```
<?xml version="1.0" encoding="utf-8" ?>
<rss version="2.0" xmlns:content="http://purl.org/rss/1.0/modules/content/">
<channel>
<title>example</title>
<link>https://example.org/</link>
<description>example</description>
<item>
<title>example</title>
<content:encoded>
&lt;!-- test --&gt;
</content:encoded>
</item>
</channel>
</rss>
```

HTML comments in blogposts are common in s9y because it adds them when adding images from the media gallery.

I found no indication in the RSS spec that comments would be disallowed in <content:encoded>, but I am no XML or RSS expert. For now I am inclined to believe this is simply a bug in the W3C Feedvalidator. Still it is causing interoperability issues for S9Y users.

[1] https://validator.w3.org/feed/check.cgi?url=https%3A%2F%2Fblog.s9y.org%2Ffeeds%2Findex.rss2
[2] https://github.com/w3c/feedvalidator

**Comment by hannob** [comment]
[feedvalidator-local-error.txt](https://github.com/s9y/Serendipity/files/4563249/feedvalidator-local-error.txt)
error message

**Comment by onli** [comment]
The validator complaining on its own is no problem. But you are saying that users have problems because of this in regular feed readers?

**Comment by hannob** [comment]
Newsblur was the service mentioned to me: https://twitter.com/djco/status/1247792748968546304

(And in any case: I guess it's plausible that people will use the W3C feed validator both in their own software and - as you can see by the tweet replies - as public evidence that they can consider a feed invalid, so this should be handled somehow. But for now I'd wait for a reply on the feedvalidator issue.)

**Comment by onli** [comment]
Okay. Just in case: The best place to remove those comments if necessary is probably somewhere in https://github.com/s9y/Serendipity/blob/280a2f1c00a5b9fadb9f01c66b123290e461e634/include/functions_rss.inc.php#L30

**Comment by th-h** [comment]
We probably could just use a regexp to filter anything between `<!--`  and `-->` as there is no need to output HTML comments in our feeds.

**Comment by hannob** [comment]
The feedvalidator comment issue has been fixed, given that this was no bug on our side I think we shouldn't change anything.

However there's a bunch of recommendations and warnings how we could make our feeds more compatible. I'll check if I can resolve some of them. I'll also test newsblur and will try to reach out to them.

**Comment by onli** [comment]
@hannob, if there was a follow-up that was probably in separate issues. Can we close here, since the original issue is fixed?

**Comment by hannob** [comment]
I think we can close.
