### ISSUE TITLE
Make a link to strtime

### ISSUE THREAD

**Issue by qbi** [s9y/Serendipity#724]
The settings page of 2k11 has a mention of PHP's `strftime`:

https://github.com/s9y/Serendipity/blob/3bc302fbcfae9fd3067a5d972acb55f4e81fea11/templates/2k11/config.inc.php#L40

Is it possible to link to the config? My suggestion is:

`         'name' => GENERAL_PLUGIN_DATEFORMAT . " (<a src=\"http://php.net/strftime\">http://php.net/strftime</a>)", `

Does that work? If yes, it would be helpful to have this link to jump easily to the documentation.

**Comment by yellowled** [comment]
As far as I know, that is not possible.
