### ISSUE TITLE
[core?] should shorten IPv6 addresse more than to /64

### ISSUE THREAD

**Issue by Zugschlus** [s9y/Serendipity#728]
Hi,

![image](https://user-images.githubusercontent.com/1712376/81185429-ddb79200-8fb1-11ea-842d-7ae744d1351f.png)

with IP address shortening enabled, this cuts the IP address to /64, which is still enough to identify the user in a residential customer ISP. Please consider shortening to /56¹ or /48, or to make this configurable.

Greetings
Marc

¹ some ISPs hand out /56 networks to single customers, so /56 might still be "personenbezogen".

**Comment by onli** [comment]
Thank you for the report. Just fyi, that's in the dsgvo plugin.

I changed that plugin to remove one block more. @garvinhicking or @th-h, if it's not necessary to do so you could revert https://github.com/s9y/additional_plugins/commit/915e7e06eb7b1d22bc1a3a64c94905f9d9947525. But probably there is no real difference between having that block or not.

**Comment by onli** [comment]
I assume this was fixed with the commit, if not please re-open.
