### ISSUE TITLE
[serendipity_event_spamblock_bayes] create table statement in code is MySQL only

### ISSUE THREAD

**Issue by Zugschlus** [s9y/Serendipity#737]
Hi,

the create table statement
```
		$sql = "CREATE TABLE IF NOT EXISTS
                    {$serendipity['dbPrefix']}spamblock_bayes (
                    token VARCHAR(100) NOT NULL,
                    ham BIGINT UNSIGNED NOT NULL DEFAULT '0',
                    spam BIGINT UNSIGNED NOT NULL DEFAULT '0',
                    type VARCHAR(20) DEFAULT '{$this->type['body']}'
                    ) {UTF_8};";
```

doesn't work on PostgreSQL. Additionally, due to the absence of any error handling, the plugin installs just fine and claims successful operations while this is actually impossible due to the table not existing.

I have gotten some positive results from using

```
s9y_mh_blog=> create table if not exists s9y_spamblock_bayes (
s9y_mh_blog(> token VARCHAR(100) NOT NULL,
s9y_mh_blog(> ham BIGINT NOT NULL DEFAULT '0',
s9y_mh_blog(> spam BIGINT NOT NULL DEFAULT '0',
s9y_mh_blog(> type VARCHAR(20) DEFAULT '' ) ;
CREATE TABLE
```

But I have no idea whether the omitted "unsigned" and "{UTF_8}" will have in consequences. In addition, what is $this->type['body'] in this context?

Greetings
Marc

**Comment by onli** [comment]
Hi @Zugschlus 

> But I have no idea whether the omitted "unsigned" and "{UTF_8}" will have in consequences.

The Unsigned won't matter in practice, but the missing {UTF_8} could lead to the database using the wrong charset. But it looks like https://github.com/s9y/Serendipity/blob/master/include/db/pdo-postgres.inc.php#L272 will set it to empty anyway, so at least for now it makes no difference.

> In addition, what is $this->type['body'] in this context?

An entry of an array defined by the plugin, in https://github.com/s9y/additional_plugins/blob/master/serendipity_event_spamblock_bayes/serendipity_event_spamblock_bayes.php#L34.

https://github.com/s9y/additional_plugins/blob/12aaee2e8fdf38d15ff8e97d82286603feae4239/serendipity_event_statistics/serendipity_plugin_statistics.php#L244 shows how serendipity plugins usually create SQL files for specific database backends when the schema replacement is not enough, but here it should be enough to just leave out the `UNSIGNED` for postgresql by properly using the schema here, by replacing it with `{UNSIGNED}` in the sql statement?

**Comment by onli** [comment]
@Zugschlus Follow up question: Are you using postgres or pdo-postgres as database layer? You can check that under "Konfiguration -> Datenbankeinstellungen -> Datenbanktyp".

**Comment by onli** [comment]
This plugin does no longer create this table. It is still not compatible with Postgres, as it is missing that database backend in the plugin, but that would have to be provided by the b8 plugin or a different developer. @Zugschlus, if you are still around, that could be a great contribution. I will however close here for now, as it's not an issue that can be acted on properly anymore.
