### ISSUE TITLE
After installation: serendipity_config does not exist

### ISSUE THREAD

**Issue by onli** [s9y/Serendipity#745]
On the current uberspace, I'm trying to install serendipity-2.3.5. Everything seems to work, but in the last step of the installer I get a bunch of error messages saying `$DATABASE.serendipity_config does not exist`. And indeed: serendipity_config was not created.

PHP 7.4.1, mysql 10.3.23-MariaDB.

I will debug a bit more now, but I already checked and the error logs are empty, so this is at the very least a strange installer bug.

The issues does not occur when I select SQLite as database, so this is likely linked to the database definition or engine specific codepath.

**Comment by stevleibelt** [comment]
Any chance to debug a bit deeper already?

**Comment by onli** [comment]
Hi @stevleibelt, no progress so far. Did you run into the same issue? I secretly hoped it was an outlier.

**Comment by stevleibelt** [comment]
Hi @onli sadly not, I tried it on a fresh debian virtual machine :-\. Chance is high I've missed something since I've done it with lots of kids around.
I will give it a try as soon as possible.

**Comment by onli** [comment]
This is unlikely to still be relevant :)

**Comment by onli** [comment]
Right, time flies for s9y especially fast ;) Good thing is that I for PHP 8 the installation was now tested again quite a few time, this one really ought to be fixed.

If I can help you in any way when you want to work on s9y, pls let me know! :)
