### ISSUE TITLE
wrong charset after updating to utf8mb4

### ISSUE THREAD

**Issue by bauigel** [s9y/Serendipity#747]
I checked out the current git-master and upgraded my weblog for testing utf8mb4 at a live-instance. The upgrade worked good so far, no problems. 

But if i try to use emojis within entries or comments, they got replaced with "????".

After talking to @garvinhicking i found out, that the dbCharset in "serendipity_local_config" is set to utf8, but it has to be changed to 
`$serendipity['dbCharset'] = 'utf8mb4';`

Now the emojis seems to work in entries and comments as they should.

We should find a solution to automate this or give an advise to the user to change this manually.

**Comment by onli** [comment]
Sounds like a missed step of the utf8-upgrade that should've been covered in https://github.com/s9y/Serendipity/issues/394#issuecomment-635262452.

**Comment by surrim** [comment]
I'm using a small workaround for this probem. You can modify `include/functions_installer.inc.php`, Line 112:
`fwrite($configfp, "\t\$serendipity['dbCharset']         = 'utf8mb4';\n");`

Without this fix I have to fix my serendipity_local_config everytime after saving the server configuration.

**Comment by onli** [comment]
@surrim Can we do that conditionally always when we would also use utf8mb4 for the database? We check that with a function, `serendipity_utf8mb4_ready()`, which should only be available when the mysqli-database layer is loaded.

**Comment by surrim** [comment]
> 
> 
> @surrim Can we do that conditionally always when we would also use utf8mb4 for the database? We check that with a function, `serendipity_utf8mb4_ready()`, which should only be available when the mysqli-database layer is loaded. Maybe that can be used to create a proper patch?

Sure, you just can use
`fwrite($configfp, "\t\$serendipity['dbCharset']         = '" . (serendipity_utf8mb4_ready() ? 'utf8mb4' : addslashes(SQL_CHARSET)) . "';\n");`

**Comment by onli** [comment]
Right! But only if we use mysql. I'm not sure whether we can simply check for the existence of that function there, will the correct database layer be already loaded?

**Comment by onli** [comment]
Working on this showed a bug: `$serendipity['dbCharset']` on my dev environment was always set to `latin1`, even if the blog charset itself later was `UTF-8` - I think the installer is bugged there and always used the non-utf8 language file, which sets `SQL_CHARSET` to `latin1`. But utf8 should always work, so this is the new default.

But this is only for new installations. To solve really this issue we need to change the `$serendipity['dbCharset']` line in **serendipity_config_local.inc.php** to `utf8mb4` in the upgrader task.

**Comment by onli** [comment]
This should be fixed. Please re-open if this bug occurs again.
