### ISSUE TITLE
Spamblock CAPTCHA image is too small for old folks or visually impaired

### ISSUE THREAD

**Issue by justinacolmena** [s9y/Serendipity#752]
Just a suggestion, obviously not "the" right way of doing things, but here's a patch for those who need help with the big E on the eye chart on the wall.
```
$ diff -u serendipity/plugins/serendipity_event_spamblock/serendipity_event_spamblock.php.0 serendipity/plugins/serendipity_event_spamblock/serendipity_event_spamblock.php
```

```
--- serendipity/plugins/serendipity_event_spamblock/serendipity_event_spamblock.php.0   2021-03-26 19:04:35.196667304 +0000
+++ serendipity/plugins/serendipity_event_spamblock/serendipity_event_spamblock.php     2021-03-26 19:24:52.644197757 +0000
@@ -1320,8 +1320,11 @@
                                 }
                             }
                         }
-                        imagejpeg($image, NULL, 90); // NULL fixes https://bugs.php.net/bug.php?id=63920
+                       $image_E = imagescale($image, exp(1) * imagesx($image));
                         imagedestroy($image);
+
+                        imagejpeg($image_E, NULL, 90); // NULL fixes https://bugs.php.net/bug.php?id=63920
+                        imagedestroy($image_E);
                     } else {
                         header('Content-Type: image/png');
                         $output_char = strtolower($_SESSION['spamblock']['captcha'][$parts[1] - 1]);
```

**Comment by justinacolmena** [comment]
Like this:
![captcha-sample](https://user-images.githubusercontent.com/32494761/112685952-1d85a300-8e2a-11eb-9107-9ca62c1264ef.jpeg)

**Comment by onli** [comment]
@justinacolmena  Shall we look into merging the right way to do this?

In general the captcha should not be used, we probably should remove it entirely (the alternative: spamblock_bee + spamblock_bayes). But having it be a bit bigger could improve upon the current default.

**Comment by justinacolmena** [comment]
I don't have a opinion on the matter. I am new to Serendipity, and I just posted what worked for me. Look around at other blogs, see how it's handled.

[Schneier on Security](https://www.schneier.com/) has a very simple question for commenters:

> Fill in the blank: the name of this blog is Schneier on ___________ (required):
> [___________]

And probably other methods like "spamblock_bee + spamblock_bayes" that you mentioned are enabled as well.

**Comment by onli** [comment]
Spamblock_bee is not that different from that solution. It adds a hidden input that is to not be filled, and optionally an input with a simple math problem that is automatically filled with javascript.

If you intend to work on this, I'd invite you to send in a pull request that makes the captcha bigger, ideally with the mentioned "right way of doing things" ;) 

This issue I'll close (but we can reopen), the documentation of this approach seems to be done. Btw, you are aware of your forum at https://board.s9y.org/, right? It would have fitted there as well.
