### ISSUE TITLE
An issue of Stored XSS was discovered via "General Settings - Blog name" parameter in Serendipity 2.4-alpha2. 

### ISSUE THREAD

**Issue by my123px** [s9y/Serendipity#762]
An issue of Stored XSS was discovered in Serendipity 2.4-alpha2. 
"serendipity/serendipity_admin.php" has a Stored XSS vulnerability via the "General Settings - Blog name" parameter.
Through the constructed malicious XSS code, the attacker can obtain the information of all users who visit the front-end page of the site and perform malicious operations.
Constructed malicious XSS code：
![image](https://user-images.githubusercontent.com/33975676/118452675-f90ebe80-b728-11eb-9c8e-92645fe99ddf.png)
Front-end user access results：
![image](https://user-images.githubusercontent.com/33975676/118452942-3d01c380-b729-11eb-9a80-a3e099459129.png)

**Comment by my123px** [comment]
Hello, thank you for your reply. It is true that if only from the perspective of security impact, this vulnerability may not be harmful, but if you consider this flaw from the level of coding security specifications, then this vulnerability may not be recommended to be retained. If teh XSS mentioned in #456 is the design consideration for the support of rich text, then the two vulnerabilities mentioned this time have no relevant considerations, so I still hope that we can strengthen it, after all, not all people who login the manage panel are ethical administrators.
At the same time, thank you for your reminder, I will follow the process described in https://docs.s9y.org/docs/contributing/index.html for the subsequent submission of security vulnerabilities

**Comment by onli** [comment]
> but if you consider this flaw from the level of coding security specifications, then this vulnerability may not be recommended to be retained

That's a valid point. We should have a look at how the value of those two variables is stored and printed, and either escape it before storing it or when emitting it. 

Are you interested in working on that potential patch? :)

**Comment by my123px** [comment]
How about adding a htmlspecialchars() function when getting input? The flags parameter uses ENT_QUOTES.

**Comment by onli** [comment]
That could work. But those settings are mixed with other settings, Will all of them continue to work when HTML-encoded? It might be easier to just escape them in templates/2k11/index.tpl.

**Comment by th-h** [comment]
I don't think it makes sense to escape input from blog administrators (or authors). They should be able to configure their blog the way they want to, and they can do that anyway by other means (plugins, themes, modifying code).

**Comment by onli** [comment]
In any case there was no work on this, and we agree that it is not a critical security issue. Should we close this and its sister issue?
