### ISSUE TITLE
An issue of Stored XSS was discovered via "General Settings - Blog description" parameter in Serendipity 2.4-alpha2

### ISSUE THREAD

**Issue by my123px** [s9y/Serendipity#763]
An issue of Stored XSS was discovered in Serendipity 2.4-alpha2. 
"serendipity/serendipity_admin.php" has a Stored XSS vulnerability via the "General Settings - Blog description" parameter.
Through the constructed malicious XSS code, the attacker can obtain the information of all users who visit the front-end page of the site and perform malicious operations.
Constructed malicious XSS code：
![image](https://user-images.githubusercontent.com/33975676/118457090-08433b80-b72c-11eb-8eda-a8b46989a29b.png)
Front-end user access results：
![image](https://user-images.githubusercontent.com/33975676/118457242-2741cd80-b72c-11eb-93a2-7ded2f253f8c.png)

**Comment by onli** [comment]
My answer to the other issue, https://github.com/s9y/Serendipity/issues/762#issuecomment-842359034, is valid here as well :)
