### ISSUE TITLE
Recreate Thumbnails is broken because of missing constant THUMB

### ISSUE THREAD

**Issue by stephanbrunker** [s9y/Serendipity#771]
In include/functions_images.inc.php there is line 917:
                    $resizethumb = sprintf(RESIZE_BLAHBLAH, THUMB);

But this throws an error because an constant named THUMB doesn't exist. At line 903, THUMBNAIL_SHORT exists, but that makes no sense because it prints the same message for all the thumbnails. In both cases, this should be replaced with something like the variable $sThumb. It isn't a complete fix because the message should include the new thumbnail size which is ommitted. But at least it executes. Otherwise, the s9y installation is broken because all thumbnails are deleted an not re-created.

**Comment by onli** [comment]
Thanks! Important find short before we wanted to release a beta version. I will give it a test some time later run and try to debug where that error is coming from exactly (was this always broken?). If you would like to fix it yourself just send in a PR :)

**Comment by stephanbrunker** [comment]
I don't know when the THUMB constant vanished, it was not me this time. Unfortunately, the basement of my buisiness was flooded with all items inside so I really, really have a lot of other problems. I just ran into that bug two months ago and remembered it recently. I only did a quick fix by replacing the constant, but the string should be showing the name of the file and the new size. Atm, with only $sThumb it only shows the name and the "x" from "300 x 200" for example.

**Comment by onli** [comment]
Absolutely, I'll have a look. Please stay safe!

**Comment by onli** [comment]
I think this is fixed now. I was also able to restore the output of the image dimension. That could be be prettied up a bit if someone is motivated to do so :)

Thanks again for the report. I'll close here for now, re-open is always possible.
