### ISSUE TITLE
when could we use Serendipity 2.4-beta1

### ISSUE THREAD

**Issue by bluesky0341** [s9y/Serendipity#780]
when could we use Serendipity 2.4-beta1
because Serendipity 2.4-beta1 support php8.0,i want to use

i want to use php8.0

**Comment by bluesky0341** [comment]
is it ok to use 2.4 now

**Comment by onli** [comment]
Yes. I use 2.4-beta1 for my personal site, and so do several other users. You can use 2.4 already.

**Comment by bluesky0341** [comment]
thanks for mail
for seo,i need below

title
discription
keywords


but i do not find in the website



------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "s9y/Serendipity"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年6月2日(星期四) 晚上9:50
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [s9y/Serendipity] when could we use Serendipity 2.4-beta1 (Issue #780)





 
Yes. I use 2.4-beta1 for my personal site, and so do several other users. You can use 2.4 already.

**Comment by onli** [comment]
I think the original issue is answered. Not sure about the keyword question, I hope https://board.s9y.org/ did answer it already. If not, that's the place for it.
