### ISSUE TITLE
serendipity_plugin_comments/: Fatal error: Uncaught TypeError: mb_strrpos():

### ISSUE THREAD

**Issue by ttrueten** [s9y/Serendipity#781]
Hi there,
I got the following fatal error with Serendipity 2.4-beta1 and PHP 8.0.16 and as you can see the bootstrap4 Theme:
`Fatal error: Uncaught TypeError: mb_strrpos(): Argument #3 ($offset) must be of type int, string given in /home/www/plugins/serendipity_plugin_comments/serendipity_plugin_comments.php:252 Stack trace: #0 /home/www/plugins/serendipity_plugin_comments/serendipity_plugin_comments.php(252): mb_strrpos('Insta hab ich e...', ' ', 'UTF-8') #1 /home/www/include/plugin_api.inc.php(971): serendipity_plugin_comments->generate_content('Kommentare') #2 /home/www/include/functions_smarty.inc.php(644): serendipity_plugin_api::generate_plugins('right') #3 /home/www/templates_c/bootstrap4/51/a2/33/51a233b1bab13ccc85dd0a20c60495dff9e9e678_0.file.index.tpl.php(194): serendipity_smarty_printSidebar(Array, Object(Smarty_Internal_Template)) #4 /home/www/bundled-libs/Smarty/libs/sysplugins/smarty_template_resource_base.php(123): content_62bbfd93295829_37323917(Object(Smarty_Internal_Template)) #5 /home/www/bundled-libs/Smarty/libs/sysplugins/smarty_template_compiled.php(114): Smarty_Template_Resource_Base->getRenderedTemplateCode(Object(Smarty_Internal_Template)) #6 /home/www/bundled-libs/Smarty/libs/sysplugins/smarty_internal_template.php(216): Smarty_Template_Compiled->render(Object(Smarty_Internal_Template)) #7 /home/www/bundled-libs/Smarty/libs/sysplugins/smarty_internal_templatebase.php(232): Smarty_Internal_Template->render(false, 1) #8 /home/www/bundled-libs/Smarty/libs/sysplugins/smarty_internal_templatebase.php(134): Smarty_Internal_TemplateBase->_execute(Object(Smarty_Internal_Template), NULL, NULL, NULL, 1) #9 /home/www/index.php(124): Smarty_Internal_TemplateBase->display('/home/www/ww740...') #10 {main} thrown in /home/www/plugins/serendipity_plugin_comments/serendipity_plugin_comments.php on line 252`

What can I do?

Regards,
Thomas

**Comment by onli** [comment]
You could check that codeline to see where the problem is. If I see correctly, it should be here:

```
$spacepos = mb_strrpos(mb_substr($comment, $pos, $wordwrap, $enc), ' ', $enc);
```

https://www.php.net/manual/en/function.mb-strrpos.php explains the problem: PHP changed how the function works to fuck us over again. Solution should be to change the line like this:

```
$spacepos = mb_strrpos(mb_substr($comment, $pos, $wordwrap, $enc), ' ', 0, $enc);
```

This sets the offset parameter to its default and should fix your error message. 

Would be great if you could test this in your setup, and even better if you could provide this then as a PR :)

**Comment by ttrueten** [comment]
Hey Onli,
I'll never say again that a 0 is worth nothing... 

Good, that's it. I'm going to look at the various other problems that have come up and make a report there. Thank you first of all.

Many greetings,
T.

**Comment by onli** [comment]
Great that it worked :) @ttrueten, would you like to provide this patch to the project (after all, you discovered the problem and you did test the fix) in a pull request?
