### ISSUE TITLE
Uncaught ArgumentCountError: 4 arguments are required, 2 given in [path]/plugins/serendipity_event_spamblock/serendipity_event_spamblock.php:1070

### ISSUE THREAD

**Issue by hannob** [s9y/Serendipity#791]
I am seeing errors like this in my log file:
```
PHP Fatal error:  Uncaught ArgumentCountError: 4 arguments are required, 2 given in [path]/plugins/serendipity_event_spamblock/serendipity_event_spamblock.php:1070
Stack trace:
#0 [path]/plugins/serendipity_event_spamblock/serendipity_event_spamblock.php(1070): sprintf()
#1 [path]/include/plugin_api.inc.php(1188): serendipity_event_spamblock->event_hook()
#2 [path]/include/functions_comments.inc.php(1017): serendipity_plugin_api::hook_event()
#3 [path]/include/functions_trackbacks.inc.php(388): serendipity_saveComment()
#4 [path]/comment.php(108): add_trackback()
#5 {main}
  thrown in [path]/plugins/serendipity_event_spamblock/serendipity_event_spamblock.php on line 1070
```

This is the code around the area:
```
                                if (!is_array($parts)) { // not a valid URL
                                    $this->log($logfile, $eventData['id'], $tipval_method, sprintf(PLUGIN_EVENT_SPAMBLOCK_REASON_IPVALIDATION, $addData['url'], '', ''), $addData);
                                    if ($trackback_ipvalidation_option == 'reject') {
                                        $eventData = array('allow_comments' => false);
                                        $serendipity['messagestack']['comments'][] = sprintf(PLUGIN_EVENT_SPAMBLOCK_REASON_IPVALIDATION, $addData['url']);
                                        return false;
                                    } else {
                                        $eventData['moderate_comments'] = true;
                                        $serendipity['csuccess']        = 'moderate';
                                        $serendipity['moderate_reason'] = sprintf(PLUGIN_EVENT_SPAMBLOCK_REASON_IPVALIDATION, $addData['url']);
                                    }
                                }
```

It looks to me the issue is with the sprintf calls. PLUGIN_EVENT_SPAMBLOCK_REASON_IPVALIDATION is a constant ('IP validation: %s [%s] != sender ip [%s]') with three %s string placeholders in it, so the sprintf call needs more parameters. As you can see in this code piece, one of the sprintf calls does it right by passing empty strings.

So a possible fix (and probably better than nothing) would be to add two empty strings to the other sprintf calls. However the log message created would be nonsensical, it would end up being something like 'IP validation: https://example.com/ [] != sender ip []'. Likely the right fix would be a different log message here. Likely adding a different constant (e.g. PLUGIN_EVENT_SPAMBLOCK_REASON_INVALIDURL) with just one %s would be the right move.

Just documenting this so far, I can probably come up with a patch later.

**Comment by hannob** [comment]
Additional info: in PHP 7.4 this is a warning (though sprintf won't output a string), in 8.0/8.1 it's causing the fatal error.

**Comment by hannob** [comment]
There is also a logic bug in that code. The code below comparing the trackback uri IP with the sender IP will be executed even if the url parsing failed. Will fix that as well.

**Comment by onli** [comment]
I'll close here, as the linked PR was merged.
