### ISSUE TITLE
New directory of sub-directory is not getting showed

### ISSUE THREAD

**Issue by manitu-opensource** [s9y/Serendipity#804]
When creating a directory, e.g. 2023, and a new sub-directory of the former one, e.g. 04, the sub-directory is NOT getting shown on the directory list.

Rising on Serendipity 2.4.0 with PHP 8.1.12.

The permissions on the file system are okay, both have the same permissions. Even setting access of the parent directories in s9y (e.g. access rights for admins, commentators etc.) does not change the behaviour.

Logout+re-login does not fix it.

When restarting the webserver (!) the new sub-directory arises suddently without any other changes.

We suppose some caching, e.g. php filesystem / cache stat. See https://www.php.net/manual/en/function.clearstatcache.php

**Comment by surrim** [comment]
Thanks for reporting the bug.
I already fixed it here: https://github.com/s9y/Serendipity/commit/a34f168c74762824c4eef49aeab9001629e7462c to use it in my own blog. It's not included in 2.4.0 because this version is older.

Kind regards

**Comment by onli** [comment]
The code in the commit could just be copied over into 2.4.0, if you want to solve this problem for now. Just to be clear about this, 2.4.0 is the current version, we need to create a new one with those patches. Thanks for the report!
