### ISSUE TITLE
fatal error for strftime with comments

### ISSUE THREAD

**Issue by bauigel** [s9y/Serendipity#806]
With current master it is not possible to read an article with comments. There is a fatal error. Articles without comments can be opened as usual.

It doesn't matter if I use php 8.0, 8.1 or 8.2

> Fatal error: Uncaught Exception: DateTime::__construct(): Failed to parse time string (1682620423) at position 8 (2): Unexpected character in /var/www/virtual/bauigel/bernd.distler.ws/bundled-libs/php81_bc/strftime/src/php-8.1-strftime.php:35 Stack trace: #0 /var/www/virtual/bauigel/bernd.distler.ws/bundled-libs/php81_bc/strftime/src/php-8.1-strftime.php(35): DateTime->__construct('1682620423') #1 /var/www/virtual/bauigel/bernd.distler.ws/include/functions.inc.php(143): PHP81_BC\strftime('%d.%m.%Y %H:%M', '1682620423') #2 /var/www/virtual/bauigel/bernd.distler.ws/include/functions_comments.inc.php(325): serendipity_strftime('%d.%m.%Y %H:%M', '1682620423') #3 /var/www/virtual/bauigel/bernd.distler.ws/include/functions_comments.inc.php(198): serendipity_generateCommentList('1948', Array, 0) #4 /var/www/virtual/bauigel/bernd.distler.ws/include/functions_entries.inc.php(1325): serendipity_displayCommentForm('1948', 'https://bernd.d...', true, Array, true, false, Array) #5 /var/www/virtual/bauigel/bernd.distler.ws/include/genpage.inc.php(53): serendipity_printEntries(Array, 1) #6 /var/www/virtual/bauigel/bernd.distler.ws/include/functions_routing.inc.php(393): include('/var/www/virtua...') #7 /var/www/virtual/bauigel/bernd.distler.ws/index.php(75): serveEntry(Array) #8 {main} Next InvalidArgumentException: $timestamp argument is neither a valid UNIX timestamp, a valid date-time string or a DateTime object. in /var/www/virtual/bauigel/bernd.distler.ws/bundled-libs/php81_bc/strftime/src/php-8.1-strftime.php:37 Stack trace: #0 /var/www/virtual/bauigel/bernd.distler.ws/include/functions.inc.php(143): PHP81_BC\strftime('%d.%m.%Y %H:%M', '1682620423') #1 /var/www/virtual/bauigel/bernd.distler.ws/include/functions_comments.inc.php(325): serendipity_strftime('%d.%m.%Y %H:%M', '1682620423') #2 /var/www/virtual/bauigel/bernd.distler.ws/include/functions_comments.inc.php(198): serendipity_generateCommentList('1948', Array, 0) #3 /var/www/virtual/bauigel/bernd.distler.ws/include/functions_entries.inc.php(1325): serendipity_displayCommentForm('1948', 'https://bernd.d...', true, Array, true, false, Array) #4 /var/www/virtual/bauigel/bernd.distler.ws/include/genpage.inc.php(53): serendipity_printEntries(Array, 1) #5 /var/www/virtual/bauigel/bernd.distler.ws/include/functions_routing.inc.php(393): include('/var/www/virtua...') #6 /var/www/virtual/bauigel/bernd.distler.ws/index.php(75): serveEntry(Array) #7 {main} thrown in /var/www/virtual/bauigel/bernd.distler.ws/bundled-libs/php81_bc/strftime/src/php-8.1-strftime.php on line 37

**Comment by garvinhicking** [comment]
Thanks for reporting this. I hope to have fixed this with my recent commit. It should enforce casting the timestamp to an integer. Can you see if it works for you?

**Comment by bauigel** [comment]
Works for me like a charm. :)
Seems, this fixed another problem too, which I had with static pages. 👍
