### ISSUE TITLE
SQL error (s9y 2.4.0, php8.2)

### ISSUE THREAD

**Issue by neonknight** [s9y/Serendipity#808]
Hi, after update to php8.2 (debian 12) and s9y 2.4.0 I noticed sql errors such as:

```
PHP Fatal error:  Uncaught mysqli_sql_exception: You have an error in your SQL syntax;
 check the manual that corresponds to your MariaDB server version for the right syntax to use near 'AND isdraft = 'false'  AND timestamp <= 1688043600' at line 1 in /var/www/xxx/blog/include/db/mysqli.inc.php:68\nStack trace:\n#0 /var/www/xxx/blog/include/db/mysqli.inc.php(68): mysqli_query()\n#1 /var/www/xxx/blog/include/functions_routing.inc.php(382): serendipity_db_query()\n#2 /var/www/xxx/blog/index.php(75): serveEntry()\n#3 {main}\n  thrown in /var/www/xxx/blog/include/db/mysqli.inc.php on line 68
```

**Comment by onli** [comment]
Is the error only in the log, or is it breaking your blog? The code creating the query looks like this:

```
$title = serendipity_db_query("SELECT title FROM {$serendipity['dbPrefix']}entries WHERE id=$id AND isdraft = 'false' " . (!serendipity_db_bool($serendipity['showFutureEntries']) ? " AND timestamp <= " . serendipity_db_time() : ''), true);
```

I currently do not see what is wrong with that.

**Comment by neonknight** [comment]
It's only in the log, the blog frontend seems to work fine.

```
SELECT title FROM  serendipity_entries WHERE id=1 AND isdraft = 'false' AND timestamp <= 1688043600;
```
directly in mariadb works fine.

How could I log the value of $id (I assume PHP/mysql for some reason doesn't like what's passed in this variable)?

**Comment by onli** [comment]
Edit the **include/functions_routing.inc.php** and search this line:

https://github.com/s9y/Serendipity/blob/56d68bcf99de2524c0c259e035189057b633b2e3/include/functions_routing.inc.php#L382

Directly above it, enter something like:

```
echo "id: ";
print_r($id);
```

You should then see that output when opening a blog entry.

**Comment by neonknight** [comment]
Thanks! The echo print leads to a content encoding error when opening the site. I have added this:
`error_log("id: " . var_export($id, true));`

But I haven't been able to reproduce. I'll get back when the error occurs next time.

**Comment by neonknight** [comment]
Haven't noticed the error again. May have been a race condition during update. Closing for now.
