### ISSUE TITLE
Deprecation warnings from smarty

### ISSUE THREAD

**Issue by hannob** [s9y/Serendipity#812]
I just ran a test of the current git code on php 8.2 (likely unrelated). I'm seeing lots of warnings like this:
```
Notice: Using php-function "array_key_exists" as a modifier is deprecated and will be removed in a future release. Use Smarty::registerPlugin to explicitly register a custom modifier. in /home/hanno/websites/test.mecronome.de/htdocs/bundled-libs/smarty/smarty/libs/sysplugins/smarty_internal_compile_private_modifier.php on line 112.
```

This appears to be a deprecation warning from smarty. I belive they come from constructs like these in the 2k11 template (from entries.tpl):
```
{if 'has_extended'|array_key_exists:$entry and $entry.has_extended and not $is_single_entry and not $entry.is_extended}
```
It appears 2k11 is the only template with these types of constructs.

**Comment by onli** [comment]
These types of constructs come from the PHP 8.0 requirement to check for unset variables. I fixed the deprecation warning for some of those by following the prompt, like in https://github.com/s9y/Serendipity/commit/00596760a40c614013eda7dcaef0a7cdb1aa52bf. A properly configured serendipity and PHP environment will not show these warning in production mode though anyway

Is the only warning left you see regularly  the one for `array_key_exists`? Then we can just register it manually as well.

**Comment by hannob** [comment]
Yes, all the warnings are related to array_key_exists.

**Comment by onli** [comment]
Could you give it another try with https://github.com/s9y/Serendipity/commit/854fe1b11938d679e4306b5a668397e4fe391426 applied?

**Comment by hannob** [comment]
I can confirm the smarty warnings are gone with latest git head.

**Comment by onli** [comment]
Thanks! Then I'll close here, we can re-open if the other modifiers turn out to be equally problematic.

**Comment by hannob** [comment]
Update, I noticed in my logs there's another such warning:
```
PHP Deprecated:  Using php-function "sizeof" as a modifier is deprecated and will be removed in a future release. Use Smarty::registerPlugin to explicitly register a custom modifier. in [...]/bundled-libs/smarty/smarty/libs/sysplugins/smarty_internal_compile_private_modifier.php on line 112
```

**Comment by fe-hicking** [comment]
(Sizeof should be replaced with count(), hope/guess that should still be alllowed and is already registered?)

**Comment by onli** [comment]
I tried to fix it in https://github.com/s9y/Serendipity/commit/b4cb4f586df02791812504a3e837701991b5f51a

**Comment by hannob** [comment]
I re-did a test installation with latest git and no more smarty warnings, so I think we're done here.
