### ISSUE TITLE
Autoupdater fails on 2.5.0 because of missing rounded brackets

### ISSUE THREAD

**Issue by rtoenjes** [s9y/Serendipity#824]
The serendipity_event_autoupdate-plugin fails on 2.5.0 with „Error. Could not verify the update.“ The „Checking MD5 zip file checksum:“ is not showing a hash.

After digging a bit around I found that 
`preg_match("/\(MD5: (.*)\)/", $updatePage, $found);`
looks for rounded brackets around `MD5: *` in https://github.com/s9y/Serendipity/releases/tag/2.5.0 which are missing in this version description.

**Comment by garvinhicking** [comment]
Thanks for mentioning this. I've just updated the release notes, can you check if that works now?

**Comment by rtoenjes** [comment]
Yes, it's working now. Thanks a lot for this quick reaction and fix!

**Comment by rtoenjes** [comment]
Forgot to close this as fixed.

**Comment by garvinhicking** [comment]
The "thanks" is all yours for reporting :-)
