### ISSUE TITLE
spartacus new plugin notifier buttons

### ISSUE THREAD

**Issue by ophian** [s9y/Serendipity#94]
Since YL changed the appearance of new spartacus plugin available buttons, I would suggest to make them colorize or hint them to be added by Spartacus.
I added a suggestion per image snip
![spartacus-snip](https://f.cloud.github.com/assets/1105372/2383496/43282222-a8fe-11e3-962c-191c3d792b10.png)
What do you think? (_I like the idea of having that noted to be added by Spartacus._)

**Comment by garvinhicking** [comment]
@yellowled Would you be interested in getting assigned to this issue? :-) ;-)

**Comment by yellowled** [comment]
I would be interested in discussing how to do this first. :D

**Comment by onli** [comment]
That might actually be a bit complicated. At a specific point in the backend (dashboard? plugin page?), we'd need to let spartacus do a plugin upgrade check. If there are upgrades, we'd have to set a (setings?) variable. If that variable is set, we'd show the update buttons in the dashboard and mark the update buttons in the plugin page (design might differ).

**Comment by yellowled** [comment]
Here's an idea how to emit upgrade notifications in the plugin manager while also fitting our current UI patterns. (This would probably also work well in the dashboard.)

![screenshot 2015-02-15 12 51 01](https://cloud.githubusercontent.com/assets/326223/6203144/57dd0140-b511-11e4-8e1d-f622fa3707f6.png)

**Comment by garvinhicking** [comment]
@yellowled Looks good to me, would you assign yourself to the issue or what's the status of this? :)

**Comment by yellowled** [comment]
I think all I can do here is the markup for the notification messages. :)

This is probably something that needs discussion in a dev talk first anyway. @onli voiced some technical concern above that I don't understand. Also, this is kind of related to the whole “update all plugins at once” discussion.

**Comment by onli** [comment]
Let's discuss this here: http://board.s9y.org/viewtopic.php?f=11&t=20627

**Comment by yellowled** [comment]
Just going through old issues – given the fact that 2.1 is going to have a unified “Update plugins” button, do we still think this is useful/necessary? (I think it might be useful, but it should be part of the dashboard, not the plugins page. And for that I'd like to open a seperate issue.)

**Comment by onli** [comment]
I also think it still would be useful. I can see it on the dashboard, but if it's shown there it could be easily also be shown on the plugin page.

**Comment by yellowled** [comment]
But since we now have the unified update button, shouldn't it be just *one* message? And wouldn't that message no longer require a button? (Why add a single button to a single message if there is a single button on the same page?)

So what this comes down to would be (IMO) “add the ability to display a message in the backend – in the dashboard as well as on the plugins page – that plugin updates are available”.

**Comment by onli** [comment]
> So what this comes down to would be (IMO) “add the ability to display a message in the backend – in the dashboard as well as on the plugins page – that plugin updates are available”.

Yes, exactly. In the dashboard it could be combined with a message, in the plugin page it could be an indicator at the button (like the "x unread messages" pattern) at the update button, instead of the message.

**Comment by yellowled** [comment]
* Dashboard: Message “X plugin updates are available <link to plugins page>`"
* Plugins page: “Update plugins” button has an additional indicator showing the number of updates (like “Update plugins [5]”)

**Comment by yellowled** [comment]
This has become unreadable and diverged from the original issue a lot, so I opened #423 instead.
